Repository BLAST-WarpX/warpx, pull requests merged in 2019-05, with the labels that each got.

#98 Implement real-to-complex FFT
  Source/FieldSolver/SpectralSolver/SpectralFieldData.H
  Source/FieldSolver/SpectralSolver/SpectralFieldData.cpp
  Source/FieldSolver/SpectralSolver/SpectralKSpace.H
  Source/FieldSolver/SpectralSolver/SpectralKSpace.cpp
Labels: spectral

#103 Use virtual function to select the spectral algorithm
  Source/FieldSolver/SpectralSolver/Make.package
  Source/FieldSolver/SpectralSolver/PsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/Make.package
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralSolver.H
  Source/FieldSolver/SpectralSolver/SpectralSolver.cpp
Labels: spectral

#61 Plasma profiles
  Docs/source/running_cpp/parameters.rst
  Examples/Physics_applications/laser_acceleration/inputs.2d.boost
  Source/Initialization/Make.package
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Initialization/PlasmaProfiles.cpp
Labels: enhancement

#121 add parameter z_start for parabolic chanel profile
  Examples/Physics_applications/laser_acceleration/inputs.2d.boost
  Source/Initialization/PlasmaProfiles.cpp
Labels: enhancement

#127 Split theory into several rst files
  Docs/source/latex_theory/AMR/AMR.tex
  Docs/source/latex_theory/Boosted_frame/Boosted_frame.tex
  Docs/source/latex_theory/Makefile
  Docs/source/latex_theory/PML/PML.tex
  Docs/source/latex_theory/input_output/input_output.tex
  Docs/source/latex_theory/theory.tex
  Docs/source/theory/PML.rst
  Docs/source/theory/amr.rst
  Docs/source/theory/boosted_frame.rst
  Docs/source/theory/input_output.rst
  Docs/source/theory/picsar_theory.rst
  Docs/source/theory/theory.rst
  Docs/source/theory/warpx_theory.rst
Labels: documentation

#119 Continuous injection for laser particles
  Docs/source/running_cpp/parameters.rst
  Docs/source/visualization/inputs.2d
  Examples/Modules/RigidInjection/inputs
  Examples/Modules/boosted_diags/inputs.2d
  Examples/Modules/boosted_diags/inputs.3d
  Examples/Modules/gaussian_beam/inputs
  Examples/Physics_applications/laser_acceleration/inputs.2d
  Examples/Physics_applications/laser_acceleration/inputs.2d.boost
  Examples/Physics_applications/laser_acceleration/inputs.3d
  Examples/Physics_applications/plasma_acceleration/inputs.2d
  Examples/Physics_applications/plasma_acceleration/inputs.2d.boost
  Examples/Physics_applications/plasma_acceleration/inputs.3d.boost
  Examples/Tests/Larmor/inputs
  Examples/Tests/Larmor/inputs.ml
  Examples/Tests/PML/inputs2d
  Examples/Tests/laser_on_fine/inputs
  Examples/Tests/laser_on_fine/inputs.2d
  Examples/Tests/self_force_test/inputs
  Examples/Tests/subcycling/inputs.2d
  Python/pywarpx/picmi.py
  Source/Laser/LaserParticleContainer.H
  Source/Laser/LaserParticleContainer.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.H
  Source/WarpX.cpp
  Tools/Visualization.ipynb
  Tools/performance_tests/automated_test_4_labdiags_2ppc
Labels: bug, enhancement

#128 Document more parameters
  Docs/source/building/building.rst
  Docs/source/building/gpu_local.rst
  Docs/source/building/openpmd.rst
  Docs/source/running_cpp/parameters.rst
  Docs/source/visualization/yt.rst
Labels: documentation

#134 Convert the particle position pusher to C++
  Source/FortranInterface/WarpX_f.H
  Source/FortranInterface/WarpX_picsar.F90
  Source/Particles/WarpXParticleContainer.cpp
Labels: fortran_to_c++

#120 automatically compute max_step for LPA in boost
  Docs/source/running_cpp/parameters.rst
  Source/Evolve/WarpXEvolveEM.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: enhancement

#147 port function in lab-diags to C++ for GPU
  Source/Diagnostics/BoostedFrameDiagnostic.cpp
  Source/Diagnostics/BoostedFrame_module.F90
  Source/Diagnostics/Make.package
  Source/FortranInterface/WarpX_f.H
Labels: fortran_to_c++

#150 add doc on parallelization
  Docs/source/running_cpp/parallelization.rst
  Docs/source/running_cpp/running_cpp.rst
Labels: documentation

#156 Fix/Refactor the function PushX
  Source/Particles/Make.package
  Source/Particles/Pusher/GetAndSetPosition.H
  Source/Particles/Pusher/Make.package
  Source/Particles/Pusher/UpdatePosition.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: fortran_to_c++

#124 Move NCI Godfrey filter to C++
  Examples/Physics_applications/laser_acceleration/inputs.2d.boost
  Examples/Tests/SingleParticle/bilinear_filter_analysis.py
  Examples/Tests/SingleParticle/inputs
  Regression/WarpX-tests.ini
  Source/Filter/BilinearFilter.H
  Source/Filter/BilinearFilter.cpp
  Source/Filter/Filter.H
  Source/Filter/Filter.cpp
  Source/Filter/Make.package
  Source/Filter/NCIGodfreyFilter.H
  Source/Filter/NCIGodfreyFilter.cpp
  Source/FortranInterface/WarpX_f.H
  Source/Initialization/WarpXInitData.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Utils/Make.package
  Source/Utils/NCIGodfreyTables.H
  Source/WarpX.H
  Source/WarpX.cpp
Labels: fortran_to_c++
