Repository BLAST-WarpX/warpx, pull requests merged in 2019-11, with the labels that each got.

#507 Launch RZ tests on a separate Travis instance
  .travis.yml
  CONTRIBUTING.md
  Regression/prepare_file_travis.py
Labels: automated tests

#509 Crash if unused variables only for TravisCI tests
  Regression/WarpX-tests.ini
  Regression/prepare_file_travis.py
Labels: automated tests

#511 Fix Segfault: Create Particle Functor
  Source/Particles/ParticleCreation/ElementaryProcess.H
Labels: bug, gpu

#513 Create/Copy Particle: Class Names Upper
  Source/Particles/ParticleCreation/CopyParticle.H
  Source/Particles/ParticleCreation/ElementaryProcess.H
  Source/Particles/ParticleCreation/TransformParticle.H
Labels: cleaning

#519 Call RedistributeGPU on GPU
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
Labels: gpu

#520 Modernize function `DepositCharge` ; remove unused code
  Source/Evolve/WarpXEvolveES.cpp
  Source/FortranInterface/WarpX_f.H
  Source/Parallelization/WarpXComm.H
  Source/Parallelization/WarpXComm.cpp
  Source/Particles/Make.package
  Source/Particles/WarpXParticleContainer.cpp
  Source/Particles/deposit_cic.F90
  Source/Utils/utils_ES.F90
  Source/WarpX.H
Labels: cleaning, fortran_to_c++

#515 Refactoring of LaserParticleContainer class
  Source/Laser/LaserParticleContainer.H
  Source/Laser/LaserParticleContainer.cpp
  Source/Laser/LaserProfiles.H
  Source/Laser/LaserProfiles.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileFieldFunction.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileGaussian.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileHarris.cpp
  Source/Laser/LaserProfilesImpl/Make.package
  Source/Laser/Make.package
Labels: enhancement

#473 Copy particles in z boost slice using gpu
  Docs/source/running_cpp/parameters.rst
  Docs/source/visualization/yt.rst
  Examples/Modules/boosted_diags/inputs.3d.slice
  Source/Diagnostics/BackTransformedDiagnostic.H
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: post-processing

#465 Implement space-charge initialization (non-relativistic, single-level)
  Docs/source/running_cpp/parameters.rst
  Examples/Modules/space_charge_initialization/analysis.py
  Examples/Modules/space_charge_initialization/inputs
  Python/pywarpx/picmi.py
  Regression/WarpX-tests.ini
  Source/Evolve/WarpXEvolveES.cpp
  Source/Initialization/InitSpaceChargeField.cpp
  Source/Initialization/Make.package
  Source/Initialization/WarpXInitData.cpp
  Source/Make.WarpX
  Source/Parallelization/Make.package
  Source/Parallelization/WarpXComm.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/WarpX.H
Labels: enhancement

#526 Remove more unused fortran code
  Source/FieldSolver/Make.package
  Source/FieldSolver/openbc_poisson_solver.F90
  Source/FieldSolver/solve_E_nodal.F90
  Source/FortranInterface/WarpX_f.H
Labels: cleaning, fortran_to_c++

#533 Correct documentation for `do_not_deposit`
  Docs/source/running_cpp/parameters.rst
Labels: documentation

#527 Take into account relativistic effects in Poisson solver
  Docs/source/running_cpp/parameters.rst
  Examples/Modules/relativistic_space_charge_initialization/analysis.py
  Examples/Modules/relativistic_space_charge_initialization/inputs
  Regression/WarpX-tests.ini
  Source/Initialization/InitSpaceChargeField.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/WarpX.H
Labels: enhancement

#531 Move finestLevel() calculation outside of for loop condition statements
  Source/Diagnostics/ParticleIO.cpp
  Source/Parallelization/WarpXRegrid.cpp
  Source/Particles/WarpXParticleContainer.cpp
Labels: cleaning

#535 Create code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#482 QED: add evolution of the optical depth according to Breit-Wheeler and Quantum Synchrotron processes
  Docs/source/running_cpp/parameters.rst
  Examples/Modules/qed/breit_wheeler/analysis_2d_tau_init.py
  Examples/Modules/qed/breit_wheeler/analysis_3d_optical_depth_evolution.py
  Examples/Modules/qed/breit_wheeler/inputs.2d_test_tau_init
  Examples/Modules/qed/breit_wheeler/inputs.3d_test_optical_depth_evolution
  Examples/Modules/qed/quantum_synchrotron/analysis_2d_tau_init.py
  Examples/Modules/qed/quantum_synchrotron/inputs.2d_test_tau_init
  Regression/WarpX-tests.ini
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhotonParticleContainer.H
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/QED/BreitWheelerDummyTable.H
  Source/QED/BreitWheelerEngineWrapper.H
  Source/QED/BreitWheelerEngineWrapper.cpp
  Source/QED/Make.package
  Source/QED/QuantumSyncDummyTable.H
  Source/QED/QuantumSyncEngineWrapper.H
  Source/QED/QuantumSyncEngineWrapper.cpp
Labels: enhancement, physics:qed
