Repository BLAST-WarpX/warpx, pull requests merged in 2019-07, with the labels that each got.

#192 [WIP] Convert divE and divB to c++
  Source/FieldSolver/Make.package
  Source/FieldSolver/WarpX_FDTD.H
  Source/FortranInterface/WarpX_f.F90
  Source/WarpX.cpp
Labels: fortran_to_c++

#195 Small PR to merge current deposition inside and outside buffers
  Source/Laser/LaserParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: cleaning

#201 mini-PR to turn sub-cycling on for sub-cycling test
  Examples/Tests/subcycling/inputs.2d
Labels: bug, cleaning

#211 fix some typos in pywarpx
  Python/pywarpx/picmi.py
Labels: bug, picmi

#207 Direct current deposition in C++
  Examples/Tests/PML/analysis_pml_ckc.py
  Source/Diagnostics/WarpXIO.cpp
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/Deposition/Make.package
  Source/Particles/Make.package
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: fortran_to_c++, gpu

#99 Execute spectral solver from the regular grid, instead of the dual grid
  Regression/WarpX-tests.ini
  Source/FieldSolver/SpectralSolver/SpectralFieldData.cpp
  Source/FieldSolver/WarpXFFT.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: spectral

#226 ParticleContainer: Fix unused local var
  Source/Particles/PhysicalParticleContainer.cpp
Labels: cleaning, warning

#228 Remove dependency on FFTW, when compiling the spectral solver on GPU
  Source/FieldSolver/Make.package
  Source/FieldSolver/PicsarHybridSpectralSolver/Make.package
  Source/FieldSolver/PicsarHybridSpectralSolver/PicsarHybridFFTData.H
  Source/FieldSolver/PicsarHybridSpectralSolver/PicsarHybridSpectralSolver.cpp
  Source/FieldSolver/PicsarHybridSpectralSolver/picsar_hybrid_spectral.F90
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Make.WarpX
  Source/WarpX.H
  Source/WarpX.cpp
Labels: gpu, spectral

#227 Esirkepov to cpp
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/WarpX.cpp
Labels: fortran_to_c++

#225 EB push to cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/FieldSolver/WarpX_FDTD.H
  Source/FortranInterface/WarpX_picsar.F90
Labels: fortran_to_c++

#244 Choose fields and components in plotfiles
  Docs/source/running_cpp/parameters.rst
  Examples/Tests/Langmuir/inputs.multi.rt
  Examples/Tests/Larmor/inputs
  Examples/Tests/Larmor/inputs.ml
  Examples/Tests/laser_on_fine/inputs
  Examples/Tests/laser_on_fine/inputs.2d
  Source/Diagnostics/FieldIO.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: enhancement

#238 Use WarpX current deposition for laser particles as well
  Source/Laser/LaserParticleContainer.cpp
Labels: cleaning

#160 Implement particle pusher for momentum in C++
  Source/FortranInterface/WarpX_picsar.F90
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/Make.package
  Source/Particles/Pusher/UpdateMomentumBoris.H
  Source/Particles/Pusher/UpdateMomentumVay.H
  Source/Particles/RigidInjectedParticleContainer.H
  Source/Particles/RigidInjectedParticleContainer.cpp
Labels: fortran_to_c++

#246 fix typoe: use picmi.constants.c
  Examples/Tests/Langmuir/langmuir_PICMI_rt.py
Labels: bug, picmi

#240 Summit: Auto-Calc Nodes from Jobscript
  Docs/source/building/summit.rst
Labels: documentation

#247 Cleaning in current deposition
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/Make.package
  Source/Particles/ShapeFactors.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: cleaning

#248 Apply spectral solver to the fine and coarse patch
  Source/FieldSolver/WarpXPushFieldsEM.cpp
Labels: spectral

#223 Replace Fortran field gather with C++ version
  Examples/Tests/Langmuir/langmuir2d_analysis.py
  Source/Particles/Gather/FieldGather.H
  Source/Particles/Gather/Make.package
  Source/Particles/Make.package
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
Labels: fortran_to_c++
