Repository BLAST-WarpX/warpx, pull requests merged in 2019-09, with the labels that each got.

#303 Translate laser functions from Fortran to C++
  Source/FieldSolver/SpectralSolver/Make.package
  Source/FieldSolver/SpectralSolver/WarpX_Complex.H
  Source/FortranInterface/WarpX_f.H
  Source/Laser/LaserParticleContainer.H
  Source/Laser/LaserParticleContainer.cpp
  Source/Laser/LaserProfiles.cpp
  Source/Laser/Make.package
  Source/Laser/WarpX_laser.F90
  Source/Utils/Make.package
  Source/Utils/WarpX_Complex.H
Labels: fortran_to_c++

#306 Reactivate 2D PSATD tests
  Regression/WarpX-tests.ini
Labels: automated tests, spectral

#307 Fix Langmuir tests analysis scripts
  Examples/Tests/Langmuir/langmuir_analysis.py
Labels: automated tests, bug

#312 Add laser particles on level 0 instead of max level
  Source/Laser/LaserParticleContainer.cpp
Labels: bug

#322 [mini-PR] fix typo in CKC PML
  Source/BoundaryConditions/PML_routines.F90
Labels: bug

#323 Python update
  Python/pywarpx/PGroup.py
  Python/pywarpx/WarpInterface.py
  Python/pywarpx/_libwarpx.py
  Python/pywarpx/fields.py
  Source/Python/WarpXWrappers.cpp
  Source/Python/WarpXWrappers.h
Labels: enhancement, picmi

#328 Particles: gather_from_main_grid
  Docs/source/running_cpp/parameters.rst
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
Labels: enhancement

#330 fix laser for gpu
  Source/Laser/LaserParticleContainer.H
  Source/Laser/LaserParticleContainer.cpp
  Source/Laser/LaserProfiles.cpp
Labels: bug, fortran_to_c++, gpu

#329 Clean Up Deposit on Main
  Docs/source/running_cpp/parameters.rst
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/WarpX.H
Labels: cleaning

#331 Cleanup: Include Order
  Source/Initialization/InjectorDensity.H
  Source/Initialization/InjectorDensity.cpp
  Source/Initialization/InjectorMomentum.H
  Source/Initialization/InjectorMomentum.cpp
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Utils/IonizationEnergiesTable.H
  Source/Utils/WarpXAlgorithmSelection.cpp
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.H
  Source/WarpX.cpp
  Source/main.cpp
Labels: cleaning

#334 Docs: No EOL Whitespaces
  CONTRIBUTING.md
  Docs/Makefile
  Docs/README.md
  Docs/source/building/cori.rst
  Docs/source/building/rzgeometry.rst
  Docs/source/latex_theory/newcommands.tex
  Docs/source/running_cpp/parallelization.rst
  Docs/source/running_cpp/platforms.rst
  Docs/source/running_cpp/profiling.rst
  Docs/source/running_cpp/pwfa.rst
  Docs/source/theory/amr.rst
  Docs/source/theory/input_output.rst
  Docs/source/theory/picsar_theory.rst
  Docs/source/visualization/ascent.rst
Labels: cleaning, documentation

#336 Update README.md
  README.md
Labels: documentation

#335 Headers: No Public Scope Using Namespace
  Source/BoundaryConditions/PML_current.H
  Source/Diagnostics/FieldIO.H
  Source/FieldSolver/WarpX_FDTD.H
  Source/FieldSolver/WarpX_K.H
Labels: cleaning

#337 LaserParticleContainer: Const Correctness
  Source/Laser/LaserParticleContainer.H
  Source/Laser/LaserParticleContainer.cpp
Labels: cleaning

#339 Source: tabs2spaces
  Source/BoundaryConditions/PML.H
  Source/BoundaryConditions/WarpXEvolvePML.cpp
  Source/Diagnostics/BoostedFrameDiagnostic.H
  Source/Diagnostics/BoostedFrameDiagnostic.cpp
  Source/Diagnostics/ElectrostaticIO.cpp
  Source/Diagnostics/ParticleIO.cpp
  Source/Diagnostics/WarpXIO.cpp
  Source/Evolve/WarpXEvolveEM.cpp
  Source/Evolve/WarpXEvolveES.cpp
  Source/FieldSolver/PicsarHybridSpectralSolver/PicsarHybridSpectralSolver.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PMLPsatdAlgorithm.H
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/FortranInterface/WarpX_f.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Laser/LaserParticleContainer.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/Parallelization/WarpXRegrid.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/Python/WarpXWrappers.cpp
  Source/WarpX.H
  Source/WarpX.cpp
  Source/main.cpp
Labels: cleaning

#338 Docs: tabs2spaces
  Docs/source/building/cori.rst
  Docs/source/running_cpp/parameters.rst
  Docs/source/running_cpp/pwfa.rst
Labels: cleaning, documentation

#347 Re-Activate EOL whitespace Check
  .github/workflows/source.yml
  .github/workflows/source/hasEOLwhiteSpace
  Source/Particles/MultiParticleContainer.cpp
  Tools/performance_tests/cori.py
  Tools/performance_tests/functions_perftest.py
  Tools/performance_tests/run_automated.py
  Tools/performance_tests/summit.py
Labels: automated tests

#352 [WIP] Correct deposition buffers
  Source/Parallelization/WarpXComm.cpp
Labels: bug

#351 Removed m_giv which was being set but not used.
  Source/Laser/LaserParticleContainer.cpp
  Source/Particles/PhotonParticleContainer.H
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/UpdateMomentumBoris.H
  Source/Particles/Pusher/UpdateMomentumVay.H
  Source/Particles/RigidInjectedParticleContainer.H
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: cleaning

#360 Initialize buffer MultiFabs when gather_from_main_grid
  Source/WarpX.cpp
Labels: bug

#366 Fix typo in CKC PML solver
  Source/BoundaryConditions/WarpX_PML_kernels.H
Labels: bug

#368 Unit tests for photon pusher
  Examples/Tests/photon_pusher/check.py
  Examples/Tests/photon_pusher/inputs
  Regression/WarpX-tests.ini
Labels: automated tests, question

#377 Fix back-transformed diagnostics + subcycling
  Source/Evolve/Make.package
  Source/Evolve/WarpXDtType.H
  Source/Evolve/WarpXEvolveEM.cpp
  Source/Laser/LaserParticleContainer.H
  Source/Laser/LaserParticleContainer.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhotonParticleContainer.H
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.H
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/WarpX.H
Labels: bug

#382 [mini-PR] Replace linear ramp by cosine dam in parabolic profile
  Source/Initialization/InjectorDensity.H
Labels: enhancement

#341 Ionization Energies Script: no EOL
  Source/Utils/IonizationEnergiesTable.H
  Source/Utils/write_atomic_data_cpp.py
Labels: cleaning

#393 OSX: Tabs2Spaces sed command
  .github/workflows/source/hasTabs
Labels: automated tests, bug

#392 Allow PMLs to run on GPUs
  Source/BoundaryConditions/PML.H
  Source/BoundaryConditions/WarpXEvolvePML.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
Labels: bug, gpu

#394 Split particles only during second half-push when subcycling
  Source/Particles/PhysicalParticleContainer.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: bug

#400 print statements in analysis scripts
  Examples/Modules/nci_corrector/ncicorr_analysis.py
  Examples/Tests/Langmuir/langmuir2d_analysis.py
  Examples/Tests/Langmuir/langmuir_analysis.py
  Examples/Tests/PML/analysis_pml_ckc.py
  Examples/Tests/PML/analysis_pml_psatd.py
  Examples/Tests/PML/analysis_pml_yee.py
  Examples/Tests/SingleParticle/bilinear_filter_analysis.py
  Examples/Tests/particles_in_PML/analysis.py
  Examples/Tests/photon_pusher/check.py
  Regression/WarpX-tests.ini
Labels: automated tests

#404 Splitting spacing
  Source/Particles/PhysicalParticleContainer.cpp
Labels: enhancement

#399 [mini-PR] compute aspect ratio in post-processing script
  Tools/plot_parallel.py
Labels: post-processing

#385 update doc and cleaning in Tools
  Docs/source/running_cpp/parameters.rst
  Docs/source/visualization/visualization.rst
  Tools/parallel_postproc.py
  Tools/video_yt.py
  Tools/yt3d_mpi.py
Labels: cleaning, documentation

#403 Doxygen: Update Generator File
  Docs/Doxyfile
Labels: documentation

#408 Warning: Unused Vars in PML
  Source/BoundaryConditions/PML.cpp
Labels: cleaning, warning

#412 fix types, amrex::Real and amrex::ParticleReal
  Source/Diagnostics/BoostedFrameDiagnostic.cpp
  Source/Diagnostics/ParticleIO.cpp
  Source/FortranInterface/WarpX_f.H
  Source/Initialization/InjectorPosition.H
  Source/Initialization/PlasmaInjector.H
  Source/Laser/LaserParticleContainer.H
  Source/Laser/LaserParticleContainer.cpp
  Source/Laser/LaserProfiles.cpp
  Source/Parser/GpuParser.H
  Source/Parser/WarpXParser.H
  Source/Parser/WarpXParser.cpp
  Source/Parser/wp_parser.tab.c
  Source/Parser/wp_parser.tab.h
  Source/Parser/wp_parser.y
  Source/Parser/wp_parser_c.h
  Source/Parser/wp_parser_y.c
  Source/Parser/wp_parser_y.h
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/Gather/FieldGather.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhotonParticleContainer.H
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/GetAndSetPosition.H
  Source/Particles/Pusher/UpdateMomentumBoris.H
  Source/Particles/Pusher/UpdateMomentumVay.H
  Source/Particles/Pusher/UpdatePosition.H
  Source/Particles/Pusher/UpdatePositionPhoton.H
  Source/Particles/RigidInjectedParticleContainer.H
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/Particles/deposit_cic.F90
  Source/Particles/interpolate_cic.F90
  Source/Particles/push_particles_ES.F90
  Source/WarpX.cpp
Labels: bug

#415 Change the default gather buffer size
  Docs/source/running_cpp/parameters.rst
  Source/WarpX.cpp
Labels: mesh refinement

#407 Allow compilation of WarpX without MPI
  Regression/WarpX-tests.ini
  Source/main.cpp
Labels: cleaning

#413 Move NCI filter to separate function
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
Labels: cleaning

#402 Current Synchronize: Port to GPU
  Source/FortranInterface/WarpX_f.F90
  Source/FortranInterface/WarpX_f.H
  Source/Parallelization/InterpolateCurrentFineToCoarse.H
  Source/Parallelization/WarpXComm.cpp
  Source/WarpX.H
Labels: fortran_to_c++, gpu, mesh refinement

#416 NCI Godfrey filtered for nodal gather
  Source/Filter/NCIGodfreyFilter.H
  Source/Filter/NCIGodfreyFilter.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Utils/NCIGodfreyTables.H
  Source/WarpX.cpp
Labels: documentation, enhancement
