Repository BLAST-WarpX/warpx, pull requests merged in 2019-04, with the labels that each got.

#70 HDF5 IO for the Boosted Frame Diagnostics
  Source/Diagnostics/BoostedFrameDiagnostic.H
  Source/Diagnostics/BoostedFrameDiagnostic.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Make.WarpX
  Tools/boosted_frame_hdf5.ipynb
Labels: enhancement

#80 Add option to write the fields in openPMD format
  Docs/source/building/building.rst
  Docs/source/building/cori.rst
  Docs/source/building/openpmd.rst
  Docs/source/running_cpp/parameters.rst
  Examples/Tests/Langmuir/inputs.multi.rt
  Source/Diagnostics/FieldIO.H
  Source/Diagnostics/FieldIO.cpp
  Source/Diagnostics/WarpXIO.cpp
  Source/Make.WarpX
  Source/WarpX.H
  Source/WarpX.cpp
Labels: enhancement

#81 Reorganize the code for dumping raw data ; add `rho` and `F` output
  Source/Diagnostics/FieldIO.H
  Source/Diagnostics/FieldIO.cpp
  Source/Diagnostics/WarpXIO.cpp
Labels: enhancement

#93 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#95 Implement PSATD solver in C++
  Docs/source/running_cpp/parameters.rst
  Source/FieldSolver/Make.package
  Source/FieldSolver/SpectralSolver/Make.package
  Source/FieldSolver/SpectralSolver/PsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/PsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldData.H
  Source/FieldSolver/SpectralSolver/SpectralFieldData.cpp
  Source/FieldSolver/SpectralSolver/SpectralKSpace.H
  Source/FieldSolver/SpectralSolver/SpectralKSpace.cpp
  Source/FieldSolver/SpectralSolver/SpectralSolver.H
  Source/FieldSolver/SpectralSolver/WarpX_Complex.H
  Source/FieldSolver/WarpXFFT.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: spectral

#100 Multiple antennas
  Docs/source/running_cpp/parameters.rst
  Examples/Modules/boosted_diags/inputs.2d
  Examples/Modules/boosted_diags/inputs.3d
  Examples/Modules/laser_injection/inputs
  Examples/Modules/laser_injection/inputs.2d.rt
  Examples/Modules/laser_injection/inputs.rt
  Examples/Physics_applications/laser_acceleration/inputs.2d
  Examples/Physics_applications/laser_acceleration/inputs.2d.boost
  Examples/Physics_applications/laser_acceleration/inputs.3d
  Examples/Physics_applications/laser_acceleration/laser_acceleration_PICMI.py
  Examples/Physics_applications/plasma_mirror/inputs.2d
  Examples/Tests/Larmor/inputs
  Examples/Tests/Larmor/inputs.ml
  Examples/Tests/PML/inputs2d
  Examples/Tests/gpu_test/inputs
  Examples/Tests/laser_on_fine/inputs
  Examples/Tests/laser_on_fine/inputs.2d
  Examples/Tests/self_force_test/inputs
  Python/pywarpx/Laser.py
  Python/pywarpx/Lasers.py
  Python/pywarpx/WarpX.py
  Python/pywarpx/__init__.py
  Python/pywarpx/picmi.py
  Source/Laser/LaserParticleContainer.H
  Source/Laser/LaserParticleContainer.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: enhancement

#108 Store spectral fields in a multi-component FABArray
  Source/FieldSolver/SpectralSolver/PsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldData.H
  Source/FieldSolver/SpectralSolver/SpectralFieldData.cpp
Labels: spectral

#104 Fix bugs in the spectral solver
  Source/FieldSolver/SpectralSolver/PsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldData.cpp
  Source/FieldSolver/SpectralSolver/SpectralKSpace.cpp
  Source/FieldSolver/WarpXFFT.cpp
Labels: spectral
