Repository BLAST-WarpX/warpx, pull requests merged in 2019-08, with the labels that each got.

#253 [mini-PR] allow threshold for plasma density
  Docs/source/running_cpp/parameters.rst
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/PhysicalParticleContainer.cpp
Labels: enhancement

#239 openPMD-api: v0.9.0 provides .pc files
  Docs/source/building/cori.rst
  Docs/source/building/openpmd.rst
  Docs/source/latex_theory/allbibs.bib
  Source/Make.WarpX
Labels: documentation, enhancement, openPMD output

#261 [mini-PR] Fix current deposition in buffers
  Source/Particles/WarpXParticleContainer.cpp
Labels: bug

#266 Fix compilation flag for openPMD with nvcc
  Source/Make.WarpX
Labels: gpu, openPMD output

#263 Convert charge deposition
  Source/Evolve/WarpXEvolveEM.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/FortranInterface/WarpX_f.H
  Source/FortranInterface/WarpX_picsar.F90
  Source/Laser/LaserParticleContainer.cpp
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/Deposition/Make.package
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/Utils/WarpXAlgorithmSelection.H
  Source/Utils/WarpXAlgorithmSelection.cpp
  Source/WarpX.H
Labels: fortran_to_c++

#276 Regression Mails: Add Axel
  Regression/WarpX-tests.ini
Labels: automated tests

#277 Removed stray DS_Store file
  Source/.DS_Store
Labels: cleaning

#274 Compute step MR
  Source/Evolve/WarpXEvolveEM.cpp
Labels: enhancement

#270 [mini-PR] User can specify time interval OR distance between snapshots
  Docs/source/running_cpp/parameters.rst
  Source/WarpX.cpp
Labels: enhancement

#281 C-Arrays: No Restrict
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/Gather/FieldGather.H
Labels: bug

#273 Automated tests for rigid injection
  Examples/Modules/RigidInjection/analysis_rigid_injection_BoostedFrame.py
  Examples/Modules/RigidInjection/analysis_rigid_injection_LabFrame.py
  Examples/Modules/RigidInjection/inputs
  Examples/Modules/RigidInjection/inputs.BoostedFrame
  Examples/Modules/RigidInjection/inputs.LabFrame
  Regression/WarpX-tests.ini
  Tools/read_raw_data.py
Labels: automated tests

#284 [mini-PR] Use C++ deposition as default
  Source/WarpX.cpp
Labels: fortran_to_c++

#256 `warpx.openpmd_backend`: Expose backends
  Docs/source/building/cori.rst
  Docs/source/running_cpp/parameters.rst
  Docs/source/visualization/visualization.rst
  Source/Diagnostics/FieldIO.cpp
  Source/Diagnostics/WarpXIO.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: enhancement, openPMD output

#289 Extended PML
  Docs/source/running_cpp/parameters.rst
  Examples/Tests/particles_in_PML/analysis.py
  Examples/Tests/particles_in_PML/inputs
  Examples/Tests/particles_in_PML/inputs2d
  Regression/WarpX-tests.ini
  Source/BoundaryConditions/PML.H
  Source/BoundaryConditions/PML.cpp
  Source/BoundaryConditions/PML_current.H
  Source/BoundaryConditions/PML_routines.F90
  Source/BoundaryConditions/WarpXEvolvePML.cpp
  Source/Evolve/WarpXEvolveEM.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/FortranInterface/WarpX_f.H
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: enhancement

#285 Cleanup picsar references, algorithm choices, and unused fortran references
  Docs/source/running_cpp/parameters.rst
  Examples/Tests/Langmuir/inputs.multi.rz.rt
  Examples/Tests/particles_in_PML/inputs
  Examples/Tests/particles_in_PML/inputs2d
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/FortranInterface/Make.package
  Source/FortranInterface/WarpX_f.H
  Source/FortranInterface/WarpX_picsar.F90
  Source/Laser/LaserParticleContainer.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/Utils/WarpXAlgorithmSelection.H
  Source/Utils/WarpXAlgorithmSelection.cpp
  Source/WarpX.H
  Source/WarpX.cpp
  Tools/performance_tests/functions_perftest.py
Labels: fortran_to_c++
