Repository BLAST-WarpX/warpx, pull requests merged in 2019-10, with the labels that each got.

#419 add NCI test with MR
  Examples/Modules/nci_corrector/inputs2d
  Examples/Modules/nci_corrector/ncicorr_analysis.py
  Regression/WarpX-tests.ini
Labels: automated tests

#423 Python: Single Precision Support
  Python/pywarpx/_libwarpx.py
  Python/pywarpx/fields.py
  Source/Python/WarpXWrappers.cpp
  Source/Python/WarpXWrappers.h
Labels: enhancement

#424 gitignore: python lib
  .gitignore
Labels: cleaning

#409 Port the particle partition in buffers to GPU
  Source/Particles/Sorting/Make.package
  Source/Particles/Sorting/Partition.cpp
  Source/Particles/Sorting/SortingUtils.H
Labels: gpu, mesh refinement

#431 Fix python scripts
  Examples/Modules/gaussian_beam/gaussian_beam_PICMI.py
  Examples/Physics_applications/laser_acceleration/laser_acceleration_PICMI.py
  Examples/Physics_applications/plasma_acceleration/plasma_acceleration_PICMI.mr.py
  Examples/Physics_applications/plasma_acceleration/plasma_acceleration_PICMI.py
  Examples/Tests/Langmuir/langmuir2d_PICMI.py
  Examples/Tests/Langmuir/langmuir2d_analysis.py
  Examples/Tests/Langmuir/langmuir_PICMI.py
  Examples/Tests/Langmuir/langmuir_PICMI_rt.py
  Examples/Tests/Langmuir/langmuir_PICMI_rz.py
Labels: automated tests, bug, post-processing

#435 Added const qualifiers to certain nlevs_max variables and update relevant for loops
  Source/WarpX.cpp
Labels: cleaning

#432 Fix GPU performance, by changing host compiler from `gcc` to `gnu`
  Source/Make.WarpX
Labels: bug, gpu, install

#437 Reactivate PSATD PML test
  Regression/WarpX-tests.ini
Labels: automated tests

#438 Fixing typos in warpx_push_pml_bx_ckc()
  Source/BoundaryConditions/WarpX_PML_kernels.H
Labels: bug

#433 run_test.sh: in /tmp, fix OSX
  .gitignore
  run_test.sh
Labels: automated tests, bug

#441 fix libwarpx.so compilation for cuda
  Source/Make.WarpX
Labels: bug, gpu

#414 Charge Density Synchronize: Port to GPU
  Source/FortranInterface/WarpX_f.F90
  Source/FortranInterface/WarpX_f.H
  Source/Parallelization/InterpolateDensityFineToCoarse.H
  Source/Parallelization/WarpXComm.cpp
  Source/WarpX.H
Labels: fortran_to_c++, gpu, mesh refinement

#446 Fix the issue of 'AddParticles is slow on GPU'
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: Optimization, cleaning, gpu

#464 Mini-PR: fix pushP for photons
  Source/Particles/PhotonParticleContainer.H
Labels: bug

#462 Link: Use RPATH by Default
  Source/Make.WarpX
Labels: install

#344 QED: now particles initialize a real component (optical depth) to be used for QED modules
  .travis.yml
  Docs/source/running_cpp/parameters.rst
  Examples/Modules/qed/breit_wheeler/check_2d_tau_init.py
  Examples/Modules/qed/breit_wheeler/inputs.2d_test_tau_init
  Examples/Modules/qed/quantum_synchrotron/check_2d_tau_init.py
  Examples/Modules/qed/quantum_synchrotron/inputs.2d_test_tau_init
  Examples/Physics_applications/QED/inputs.2d
  Regression/WarpX-tests.ini
  Source/Diagnostics/ParticleIO.cpp
  Source/Make.WarpX
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhotonParticleContainer.H
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/QED/BreitWheelerEngineWrapper.H
  Source/QED/BreitWheelerEngineWrapper.cpp
  Source/QED/Make.package
  Source/QED/QedWrapperCommons.H
  Source/QED/QuantumSyncEngineWrapper.H
  Source/QED/QuantumSyncEngineWrapper.cpp
Labels: enhancement, physics:qed

#467 Fix particle partition in buffers
  Source/Particles/Sorting/Partition.cpp
  Source/Particles/Sorting/SortingUtils.H
Labels: bug

#479 Add Higuera-Cary Pusher and Automatic Test
  Docs/source/running_cpp/parameters.rst
  Examples/Tests/Langmuir/inputs.rt
  Examples/Tests/particle_pusher/analysis_pusher.py
  Examples/Tests/particle_pusher/inputs
  Regression/WarpX-tests.ini
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/Make.package
  Source/Particles/Pusher/UpdateMomentumHigueraCary.H
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Utils/WarpXAlgorithmSelection.H
  Source/Utils/WarpXAlgorithmSelection.cpp
Labels: automated tests, enhancement

#197 Slice in lab frame for boosted sim
  Docs/source/running_cpp/parameters.rst
  Docs/source/visualization/yt.rst
  Examples/Modules/RigidInjection/analysis_rigid_injection_BoostedFrame.py
  Examples/Modules/boosted_diags/analysis_3Dbacktransformed_diag.py
  Examples/Modules/boosted_diags/inputs.3d.slice
  Regression/WarpX-tests.ini
  Source/Diagnostics/BoostedFrameDiagnostic.H
  Source/Diagnostics/BoostedFrameDiagnostic.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: post-processing

#361 Classical radiation reaction
  Docs/source/running_cpp/parameters.rst
  Examples/Tests/radiation_reaction/test_const_B_analytical/check.py
  Examples/Tests/radiation_reaction/test_const_B_analytical/inputs
  Regression/WarpX-tests.ini
  Source/Particles/PhotonParticleContainer.H
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/UpdateMomentumBorisWithRadiationReaction.H
  Source/Particles/RigidInjectedParticleContainer.cpp
Labels: enhancement, physics:qed

#483 save performance h5 files, and move handling to perf_logs repo
  Tools/performance_tests/run_automated.py
Labels: automated tests

#484 Perftest2
  Tools/performance_tests/automated_test_5_loadimbalance
  Tools/performance_tests/functions_perftest.py
  Tools/performance_tests/run_automated.py
  Tools/performance_tests/summit.py
Labels: automated tests, bug, cleaning, gpu

#489 run analysis only in read mode
  Tools/performance_tests/run_automated.py
Labels: automated tests

#491 [mini-PR] fix two bugs related to QED modules and photons
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhotonParticleContainer.cpp
Labels: bug

#490 add m_ convention in CONTRIBUTING markdown
  CONTRIBUTING.md
Labels: documentation

#477 Clean Examples and make sure all are tested
  .github/workflows/source.yml
  .github/workflows/source/inputsNotTested
  .github/workflows/source/wrongFileNameInExamples
  Docs/source/running_cpp/platforms.rst
  Examples/Modules/boosted_diags/inputs.2d
  Examples/Modules/boosted_diags/inputs.3d
  Examples/Modules/charged_beam/inputs
  Examples/Modules/gaussian_beam/PICMI_inputs_gaussian_beam.py
  Examples/Modules/gaussian_beam/inputs
  Examples/Modules/ionization/analysis_ionization.py
  Examples/Modules/laser_injection/Visualization.ipynb
  Examples/Modules/laser_injection/analysis_laser.py
  Examples/Modules/nci_corrector/analysis_ncicorr.py
  Examples/Modules/nci_corrector/inputs.2d
  Examples/Modules/qed/breit_wheeler/analysis_2d_tau_init.py
  Examples/Modules/qed/breit_wheeler/inputs.2d_test_tau_init
  Examples/Modules/qed/quantum_synchrotron/analysis_2d_tau_init.py
  Examples/Modules/qed/quantum_synchrotron/inputs.2d_test_tau_init
  Examples/Modules/restart/inputs
  Examples/Physics_applications/laser_acceleration/PICMI_inputs_laser_acceleration.py
  Examples/Physics_applications/laser_acceleration/inputs.2d
  Examples/Physics_applications/laser_acceleration/inputs.2d.boost
  Examples/Physics_applications/laser_acceleration/inputs.3d
  Examples/Physics_applications/laser_acceleration/inputs.rz
  Examples/Physics_applications/plasma_acceleration/PICMI_inputs_plasma_acceleration.py
  Examples/Physics_applications/plasma_acceleration/PICMI_inputs_plasma_acceleration_mr.py
  Examples/Physics_applications/plasma_acceleration/inputs.2d.boost
  Examples/Physics_applications/plasma_acceleration/inputs.3d.boost
  Examples/Tests/Langmuir/PICMI_inputs_langmuir2d.py
  Examples/Tests/Langmuir/PICMI_inputs_langmuir_rt.py
  Examples/Tests/Langmuir/PICMI_inputs_langmuir_rz.py
  Examples/Tests/Langmuir/PICMI_inputs_langmuir_rz_multimode_analyze.py
  Examples/Tests/Langmuir/analysis_langmuir.py
  Examples/Tests/Langmuir/analysis_langmuir2d.py
  Examples/Tests/Langmuir/analysis_langmuir_multi.py
  Examples/Tests/Langmuir/analysis_langmuir_multi_2d.py
  Examples/Tests/Langmuir/analysis_langmuir_multi_rz.py
  Examples/Tests/Langmuir/inputs.2d.rz
  Examples/Tests/Langmuir/inputs.lb
  Examples/Tests/Langmuir/inputs.nolb
  Examples/Tests/Langmuir/langmuir_PICMI.py
  Examples/Tests/Larmor/inputs.ml
  Examples/Tests/Larmor/inputs.mr
  Examples/Tests/PML/inputs.2d
  Examples/Tests/SingleParticle/analysis_bilinear_filter.py
  Examples/Tests/laser_on_fine/inputs
  Examples/Tests/laser_on_fine/inputs.2d
  Examples/Tests/particles_in_PML/analysis_particles_in_pml.py
  Examples/Tests/particles_in_PML/inputs.2d
  Examples/Tests/photon_pusher/analysis_photon_pusher.py
  Examples/Tests/radiation_reaction/test_const_B_analytical/analysis_classicalRR.py
  Examples/Tests/self_force_test/inputs
  Regression/WarpX-tests.ini
  Tools/batchScripts/batch_cori.sh
  Tools/batchScripts/batch_summit.sh
  Tools/batchScripts/script_profiling_summit.sh
  Tools/plot_particle_path.py
  Tools/script_profiling_summit.sh
  run_test.sh
Labels: automated tests, cleaning

#492 [mini-PR] Using abbreviation BTD to shorten names of TravisCI tests
  Regression/WarpX-tests.ini
Labels: cleaning

#422 Consts and Real Literals
  Source/Initialization/InjectorPosition.H
  Source/Laser/LaserParticleContainer.cpp
  Source/Laser/LaserProfiles.cpp
  Source/Parallelization/InterpolateCurrentFineToCoarse.H
  Source/Parallelization/WarpXComm_K.H
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Utils/WarpXTagging.cpp
Labels: cleaning

#493 replace 'boosted frame diags' with 'back-transformed diags'
  Docs/source/running_cpp/parameters.rst
  Examples/Modules/RigidInjection/inputs.BoostedFrame
  Examples/Modules/boosted_diags/inputs.3d.slice
  Examples/Physics_applications/laser_acceleration/inputs.2d.boost
  Examples/Physics_applications/plasma_acceleration/inputs.2d.boost
  Examples/Physics_applications/plasma_acceleration/inputs.3d.boost
  Python/pywarpx/picmi.py
  Source/Diagnostics/BackTransformedDiagnostic.H
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Diagnostics/Make.package
  Source/Evolve/WarpXEvolveEM.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Laser/LaserParticleContainer.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/WarpX.H
  Source/WarpX.cpp
  Tools/performance_tests/automated_test_4_labdiags_2ppc
Labels: cleaning

#476 Add uniform initial field to the grid
  Docs/source/running_cpp/parameters.rst
  Examples/Tests/Larmor/inputs.mr
  Examples/Tests/particle_pusher/inputs
  Examples/Tests/radiation_reaction/test_const_B_analytical/analysis_classicalRR.py
  Examples/Tests/radiation_reaction/test_const_B_analytical/inputs
  Source/Initialization/WarpXInitData.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: enhancement

#463 general routines for particle creation
  Docs/source/running_cpp/parameters.rst
  Source/Particles/Make.package
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/ParticleCreation/CopyParticle.H
  Source/Particles/ParticleCreation/ElementaryProcess.H
  Source/Particles/ParticleCreation/Make.package
  Source/Particles/ParticleCreation/TransformParticle.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
Labels: cleaning, help wanted

#478 Factory class for Breit Wheeler and Synchrotron engines
  Examples/Modules/qed/breit_wheeler/inputs.2d_test_tau_init
  Examples/Modules/qed/quantum_synchrotron/inputs.2d_test_tau_init
  GNUmakefile
  Source/Diagnostics/ParticleIO.cpp
  Source/Make.WarpX
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/QED/BreitWheelerEngineInnards.H
  Source/QED/BreitWheelerEngineTableBuilder.H
  Source/QED/BreitWheelerEngineTableBuilder.cpp
  Source/QED/BreitWheelerEngineWrapper.H
  Source/QED/BreitWheelerEngineWrapper.cpp
  Source/QED/Make.package
  Source/QED/QedChiFunctions.H
  Source/QED/QedTableParserHelperFunctions.H
  Source/QED/QedWrapperCommons.H
  Source/QED/QuantumSyncEngineInnards.H
  Source/QED/QuantumSyncEngineTableBuilder.H
  Source/QED/QuantumSyncEngineTableBuilder.cpp
  Source/QED/QuantumSyncEngineWrapper.H
  Source/QED/QuantumSyncEngineWrapper.cpp
  Source/Utils/WarpXUtil.H
  Source/Utils/WarpXUtil.cpp
Labels: enhancement, physics:qed
