Repository BLAST-WarpX/warpx, pull requests merged in 2019-06, with the labels that each got.

#168 Use string instead of integer to select WarpX algorithms
  Docs/source/running_cpp/parameters.rst
  Docs/source/theory/picsar_theory.rst
  Examples/Modules/RigidInjection/inputs
  Examples/Modules/boosted_diags/inputs.2d
  Examples/Modules/boosted_diags/inputs.3d
  Examples/Modules/charged_beam/inputs
  Examples/Modules/gaussian_beam/inputs
  Examples/Modules/laser_injection/inputs
  Examples/Modules/laser_injection/inputs.2d.rt
  Examples/Modules/laser_injection/inputs.rt
  Examples/Modules/nci_corrector/inputs2d
  Examples/Physics_applications/laser_acceleration/inputs.2d
  Examples/Physics_applications/laser_acceleration/inputs.2d.boost
  Examples/Physics_applications/laser_acceleration/inputs.3d
  Examples/Physics_applications/plasma_acceleration/inputs.2d
  Examples/Physics_applications/plasma_acceleration/inputs.2d.boost
  Examples/Physics_applications/plasma_acceleration/inputs.3d.boost
  Examples/Physics_applications/plasma_mirror/inputs.2d
  Examples/Physics_applications/uniform_plasma/inputs.2d
  Examples/Physics_applications/uniform_plasma/inputs.3d
  Examples/Tests/Langmuir/inputs
  Examples/Tests/Langmuir/inputs.2d.rz
  Examples/Tests/Langmuir/inputs.lb
  Examples/Tests/Langmuir/inputs.multi.2d.rt
  Examples/Tests/Langmuir/inputs.multi.rt
  Examples/Tests/Langmuir/inputs.multi.rz.rt
  Examples/Tests/Langmuir/inputs.nolb
  Examples/Tests/Langmuir/inputs.rt
  Examples/Tests/Larmor/inputs
  Examples/Tests/Larmor/inputs.ml
  Examples/Tests/PML/inputs2d
  Examples/Tests/SingleParticle/inputs
  Examples/Tests/gpu_test/inputs
  Examples/Tests/laser_on_fine/inputs
  Examples/Tests/laser_on_fine/inputs.2d
  Examples/Tests/self_force_test/inputs
  Examples/Tests/subcycling/inputs.2d
  Source/FortranInterface/WarpX_picsar.F90
  Source/Utils/Make.package
  Source/Utils/WarpXAlgorithmSelection.H
  Source/Utils/WarpXAlgorithmSelection.cpp
  Source/WarpX.cpp
Labels: documentation

#177 Spectral cufft on gpu
  Source/Evolve/WarpXEvolveEM.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldData.H
  Source/FieldSolver/SpectralSolver/SpectralFieldData.cpp
  Source/FieldSolver/SpectralSolver/SpectralKSpace.cpp
  Source/FieldSolver/WarpXFFT.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/Particles/WarpXParticleContainer.cpp
Labels: gpu, spectral

#188 Refactor the SyncRho/SyncCurrent function
  Source/Evolve/WarpXEvolveEM.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/WarpX.H
Labels: bug
