Repository BLAST-WarpX/warpx, pull requests merged in 2019-12, with the labels that each got.

#541 Add outputFile to Python tests
  Regression/WarpX-tests.ini
Labels: automated tests

#544 Do not request python3 in radiation reaction analysis scripts
  Examples/Tests/radiation_reaction/test_const_B_analytical/analysis_classicalRR.py
Labels: automated tests

#506 Use 2 MPI rank for each Travis test
  .travis.yml
  Examples/Tests/Larmor/inputs.mr
  Regression/prepare_file_travis.py
Labels: automated tests

#548 Remove GPU_inputs test
  Examples/Tests/gpu_test/inputs
  Regression/WarpX-tests.ini
Labels: automated tests, cleaning

#549 Avoid matplotlib errors in space charge regression tests
  Examples/Modules/relativistic_space_charge_initialization/analysis.py
  Examples/Modules/space_charge_initialization/analysis.py
Labels: automated tests

#547 fix_warnings
  Source/Initialization/InjectorDensity.cpp
  Source/Initialization/InjectorMomentum.H
  Source/Particles/ParticleCreation/ElementaryProcess.H
Labels: warning

#552 [mini-PR] update path to example batch script on Summit
  Docs/source/running_cpp/platforms.rst
Labels: cleaning, documentation

#558 PICMI use with WarpX
  Docs/source/running_python/running_picmi.rst
  Docs/source/running_python/running_python.rst
Labels: documentation

#555 Makefiles: C++14
  Source/Make.WarpX
Labels: enhancement

#514 openPMD particle writer
  Source/Diagnostics/Make.package
  Source/Diagnostics/WarpXIO.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/WarpXParticleContainer.H
  Source/WarpX.H
  Source/WarpX.cpp
Labels: openPMD output

#564 LGTM: Try to Build C++
  .lgtm.yml
Labels: automated tests

#562 fix a few typos in doc on visualization of back-transformed diags
  Docs/source/visualization/backtransformed_diags.rst
  Docs/source/visualization/visualization.rst
  Docs/source/visualization/yt.rst
Labels: documentation

#565 [mini-PR] Address C++ issues found by LGTM
  Source/Evolve/WarpXEvolveEM.cpp
  Source/FortranInterface/WarpX_f.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/Python/WarpXWrappers.cpp
  Source/Utils/WarpXUtil.H
  Source/WarpX.H
Labels: cleaning

#567 Fix number of guard cells copied to the PML
  Source/BoundaryConditions/PML.cpp
Labels: bug

#556 [mini-PR] Add digit separators to PhysConst::c
  Source/Utils/WarpXConst.H
Labels: cleaning

#569 Fix Doxygen warnings
  Source/BoundaryConditions/PML.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Evolve/WarpXEvolveEM.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldData.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/Filter/Filter.cpp
  Source/Laser/LaserProfiles.H
  Source/Particles/ParticleCreation/TransformParticle.H
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/QED/QedTableParserHelperFunctions.H
  Source/WarpX.cpp
Labels: documentation

#539 Adding Collision Module into WarpX
  Docs/source/running_cpp/parameters.rst
  Examples/Tests/collision/analysis_collision.py
  Examples/Tests/collision/inputs
  Regression/WarpX-tests.ini
  Source/Evolve/WarpXEvolveEM.cpp
  Source/Particles/Collision/CollisionType.H
  Source/Particles/Collision/CollisionType.cpp
  Source/Particles/Collision/ComputeTemperature.H
  Source/Particles/Collision/ElasticCollisionPerez.H
  Source/Particles/Collision/Make.package
  Source/Particles/Collision/ShuffleFisherYates.H
  Source/Particles/Collision/UpdateMomentumPerezElastic.H
  Source/Particles/Make.package
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
Labels: enhancement

#560 Python ReadRaw: Add Header
  Tools/read_raw_data.py
Labels: bug, post-processing

#572 Developer's documentation
  Docs/requirements.txt
  Docs/source/conf.py
  Docs/source/developers/amrex_basics.rst
  Docs/source/developers/developers.rst
  Docs/source/developers/diagnostics.rst
  Docs/source/developers/documentation.rst
  Docs/source/developers/fields.rst
  Docs/source/developers/initialization.rst
  Docs/source/developers/moving_window.rst
  Docs/source/developers/particles.rst
  Docs/source/developers/portability.rst
  Docs/source/developers/profiling.rst
  Docs/source/developers/repo_organization.rst
  Docs/source/index.rst
  Source/Laser/LaserParticleContainer.H
  Source/Particles/MultiParticleContainer.H
  Source/Particles/PhotonParticleContainer.H
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/RigidInjectedParticleContainer.H
  Source/Particles/WarpXParticleContainer.H
Labels: documentation

#577 [mini-PR] splitting distance depends on ppc only if uniform per cell
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/PhysicalParticleContainer.cpp
Labels: bug

#579 Fix compilation of Doc on ReadTheDocs
  Docs/requirements.txt
Labels: bug, documentation

#578 [mini-PR] Fix typos and formatting in Diagnostics/Make.package
  Source/Diagnostics/Make.package
Labels: bug, cleaning

#582 Fix Compilation errors in electrostatic solver
  Source/Diagnostics/ElectrostaticIO.cpp
  Source/Evolve/WarpXEvolveES.cpp
  Source/Make.WarpX
Labels: electrostatic

#583 Always synchronize the value of nodal points
  Source/WarpX.H
Labels: bug
