Repository BLAST-WarpX/warpx, pull requests merged in 2020-11, with the labels that each got.

#1474 Use filter in CI tests with Galilean current correction
  Examples/Tests/galilean/analysis_2d.py
  Examples/Tests/galilean/analysis_3d.py
  Regression/Checksum/benchmarks_json/galilean_2d_psatd_current_correction.json
  Regression/Checksum/benchmarks_json/galilean_3d_psatd_current_correction.json
  Regression/Checksum/benchmarks_json/galilean_rz_psatd_current_correction.json
  Regression/WarpX-tests.ini
Labels: component: spectral, component: tests

#1480 Development branch is the default, no need to specify it
  Docs/source/building/building.rst
  Docs/source/building/cmake.rst
  Docs/source/building/juwels.rst
  Docs/source/building/summit.rst
  Docs/source/developers/performance_tests.rst
  Docs/source/visualization/sensei.rst
Labels: cleaning, component: documentation

#1488 [mini-PR ] Fix an "unused variable" warning
  Source/Parallelization/WarpXComm.cpp
Labels: cleaning, warning

#1487 Fixed calls to amrex::Random() to enable HIP compilation
  Source/Particles/ElementaryProcess/Ionization.H
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineWrapper.H
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineWrapper.H
  Source/Particles/ElementaryProcess/QEDPairGeneration.H
  Source/Particles/ElementaryProcess/QEDPhotonEmission.H
  Source/Particles/ParticleCreation/FilterCopyTransform.H
  Source/Particles/PhysicalParticleContainer.cpp
Labels: backend: hip, bug, bug: affects latest release, component: QED

#1481 Use the parser for more input parameters
  Docs/source/running_cpp/parameters.rst
  Examples/Physics_applications/plasma_mirror/inputs_2d
  Source/Initialization/PlasmaInjector.cpp
  Source/Utils/WarpXUtil.H
  Source/Utils/WarpXUtil.cpp
Labels: changes input script

#1494 Cori: RZ/FFTW issue on CORI
  Docs/source/building/cori.rst
Labels: component: RZ, component: documentation, install, machine / system

#1492 CMake: New AMReX Options
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  CMakeLists.txt
  Docs/source/building/cmake.rst
  Docs/source/building/juwels.rst
  Docs/source/building/lassen.rst
  Docs/source/building/summit.rst
  cmake/WarpXFunctions.cmake
  cmake/dependencies/AMReX.cmake
Labels: component: third party, install

#1496 Revert "Cori: RZ/FFTW issue on CORI"
  Docs/source/building/cori.rst
Labels: component: documentation

#1498 Fix includes in RhoFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/RhoFunctor.cpp
Labels: bug, bug: affects latest release, component: RZ, component: spectral

#1502 ParticleNumber reduced diag: also output total number of physical particles
  Docs/source/running_cpp/parameters.rst
  Examples/Tests/reduced_diags/analysis_reduced_diags.py
  Source/Diagnostics/ReducedDiags/ParticleNumber.H
  Source/Diagnostics/ReducedDiags/ParticleNumber.cpp
Labels: component: diagnostics

#1491 openPMD-api: lib64 on some Systems
  Docs/source/building/openpmd.rst
Labels: component: documentation, component: openPMD, install

#1505 [mini]Fix check of m_do_scale in ScaleFields
  Source/Particles/Gather/ScaleFields.H
Labels: bug, bug: affects latest release, component: core

#1503 Docs: Parser Depth Balancing
  Docs/source/running_cpp/parameters.rst
Labels: component: documentation

#1504 Change Spelling: Env AMREX_CUDA_ARCH
  Docs/source/building/juwels.rst
  Docs/source/building/lassen.rst
  Docs/source/building/summit.rst
Labels: component: documentation, component: third party, install, machine / system

#1500 sx_node_galerkin: fix access to uninitialized memory
  Source/Particles/Gather/FieldGather.H
Labels: bug, bug: affects latest release, cleaning, component: core, warning

#1509 Fix error with nested MFIter loop in Schwinger
  Source/Particles/MultiParticleContainer.cpp
Labels: bug, bug: affects latest release, component: QED

#1506 Fix Box-index staggering for Coarse-fine Interpolate
  Examples/Tests/Larmor/inputs_2d_mr
  Source/Utils/Interpolate.cpp
Labels: bug, bug: affects latest release, component: diagnostics, component: mesh refinement

#1508 Ascent: Fix SoA Real Name Order
  Source/Diagnostics/FlushFormats/FlushFormatAscent.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#1510 Fix: Typo in Extract Action
  Docs/source/visualization/ascent.rst
Labels: bug, component: diagnostics, component: documentation, component: post-processing

#1384 Use tmp particle container instead of WritePlotFile with filter
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
Labels: component: diagnostics

#1511 Simplify Python Callback
  CMakeLists.txt
  Source/BoundaryConditions/WarpXEvolvePML.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/FieldSolver/WarpX_QED_Field_Pushers.cpp
Labels: component: Python

#1515 Summit: Ascent Update
  Docs/source/building/summit.rst
Labels: component: documentation, machine / system

#1483 Update picmi constants to match the values in PhysConst
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/Python_Langmuir_rz_multimode.json
  Regression/Checksum/benchmarks_json/Python_LaserAccelerationMR.json
Labels: component: PICMI

#1513 Fix PSATD equations used with PML
  Examples/Tests/PML/analysis_pml_psatd.py
  Regression/Checksum/benchmarks_json/pml_x_psatd.json
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PMLPsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PMLPsatdAlgorithm.cpp
Labels: bug: affects latest release, component: spectral

#1517 CMake: Fix PSATD on CUDA
  Source/FieldSolver/SpectralSolver/CMakeLists.txt
Labels: backend: cuda, bug, component: spectral

#1516 use_filter now controls physical and k-space filtering
  Docs/source/running_cpp/parameters.rst
  Examples/Tests/galilean/inputs_rz
  Python/pywarpx/picmi.py
  Source/WarpX.cpp
Labels: changes input script, component: documentation

#1514 GNUmake: No Python define
  Source/Make.WarpX
Labels: cleaning, component: Python, install

#1507 WarpX compiles again on Juwels
  Docs/source/building/juwels.rst
Labels: backend: cuda, component: documentation, machine / system

#1525 LapackPP: Changed Build Flags & Build Bugs
  .azure-pipelines.yml
Labels: bug, component: RZ, component: tests, component: third party, workaround

#1521 CI: Windows
  .github/workflows/windows.yml
  CMakeLists.txt
  Source/Diagnostics/ComputeDiagFunctors/PartPerGridFunctor.cpp
  Source/Initialization/PlasmaInjector.cpp
  Source/Parser/wp_parser.l
  Source/Parser/wp_parser.lex.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
Labels: component: tests, machine / system

#1526 typo in Akturk ref in laser definition
  Docs/source/running_cpp/parameters.rst
Labels: component: documentation

#1528 Fix some double to float conversions
  Source/Particles/Gather/FieldGather.H
  Source/Utils/WarpXConst.H
Labels: cleaning, warning

#1523 Init Injector: Fix Missing cmath
  Source/Initialization/InjectorMomentum.H
Labels: bug

#1522 Call FillBoundaryAux after UpdateAuxilaryData
  Regression/Checksum/benchmarks_json/PlasmaAccelerationMR.json
  Regression/Checksum/benchmarks_json/momentum-conserving-gather.json
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Evolve/WarpXEvolve.cpp
Labels: component: parallelization

#1536 Fix bug in yt workaround for Galilean 2D/RZ tests
  Examples/Tests/averaged_galilean/inputs_avg_2d
  Examples/Tests/galilean/analysis_2d.py
  Examples/Tests/galilean/inputs_2d
  Examples/Tests/galilean/inputs_rz
  Regression/Checksum/benchmarks_json/averaged_galilean_2d_psatd.json
  Regression/Checksum/benchmarks_json/galilean_2d_psatd.json
  Regression/Checksum/benchmarks_json/galilean_2d_psatd_current_correction.json
  Regression/Checksum/benchmarks_json/galilean_rz_psatd.json
  Regression/Checksum/benchmarks_json/galilean_rz_psatd_current_correction.json
  Regression/Checksum/checksum.py
Labels: bug: affects latest release, component: tests

#1531 Electrostatic lab frame
  Docs/source/running_cpp/parameters.rst
  Docs/source/running_cpp/pwfa.rst
  Examples/Tests/ElectrostaticSphere/inputs_3d
  Regression/Checksum/benchmarks_json/ElectrostaticSphereLabFrame.json
  Regression/WarpX-tests.ini
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Evolve/WarpXComputeDt.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Utils/WarpXAlgorithmSelection.H
  Source/Utils/WarpXAlgorithmSelection.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: electrostatic, enhancement

#1456 Added Jupyter notebook to calculate and plot NCI growth rate.
  Tools/PostProcessing/plot_nci_growth_rate.ipynb
Labels: component: post-processing
