Repository BLAST-WarpX/warpx, pull requests merged in 2020-04, with the labels that each got.

#859 Read species distribution from OPMD - part 2
  Docs/source/running_cpp/parameters.rst
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Utils/WarpXConst.H
Labels: changes input script, component: openPMD, enhancement

#868 Cut gaussian beam
  Docs/source/running_cpp/parameters.rst
  Examples/Tests/initial_distribution/analysis_distribution.py
  Examples/Tests/initial_distribution/inputs
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
Labels: component: core, enhancement

#877 GitHub Action: Update to v2
  .github/workflows/source.yml
Labels: component: tests, component: third party

#878 bump test tolerances
  Regression/WarpX-tests.ini
Labels: component: tests

#874 Developer Docs: Include Guide
  Docs/source/developers/repo_organization.rst
Labels: component: documentation

#875 Update release number
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
  Tools/update_release.sh
Labels: component: documentation

#879 Fix: read_raw_data Tool for Reduced
  Tools/read_raw_data.py
Labels: bug, bug: affects latest release, component: post-processing

#881 Periodic, single-box FFT
  Docs/source/running_cpp/parameters.rst
  Examples/Tests/Langmuir/inputs_3d_multi_rt
  Source/FieldSolver/SpectralSolver/SpectralFieldData.H
  Source/FieldSolver/SpectralSolver/SpectralFieldData.cpp
  Source/FieldSolver/SpectralSolver/SpectralSolver.H
  Source/FieldSolver/SpectralSolver/SpectralSolver.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: spectral

#873 Includes: Only From `Source/`
  Source/BoundaryConditions/Make.package
  Source/Diagnostics/ComputeDiagFunctors/Make.package
  Source/Diagnostics/FieldIO.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/FlushFormats/Make.package
  Source/Diagnostics/Make.package
  Source/Diagnostics/ReducedDiags/Make.package
  Source/Evolve/Make.package
  Source/FieldSolver/FiniteDifferenceSolver/ComputeDivE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveF.cpp
  Source/FieldSolver/FiniteDifferenceSolver/Make.package
  Source/FieldSolver/Make.package
  Source/FieldSolver/PicsarHybridSpectralSolver/Make.package
  Source/FieldSolver/PicsarHybridSpectralSolver/PicsarHybridSpectralSolver.cpp
  Source/FieldSolver/SpectralSolver/Make.package
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/Make.package
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithm.cpp
  Source/Filter/Make.package
  Source/FortranInterface/Make.package
  Source/Initialization/Make.package
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Laser/LaserProfilesImpl/Make.package
  Source/Laser/Make.package
  Source/Parallelization/Make.package
  Source/Parallelization/WarpXRegrid.cpp
  Source/Parser/Make.package
  Source/Particles/Collision/Make.package
  Source/Particles/Deposition/Make.package
  Source/Particles/ElementaryProcess/Make.package
  Source/Particles/ElementaryProcess/QEDPairGeneration.H
  Source/Particles/ElementaryProcess/QEDPhotonEmission.H
  Source/Particles/Gather/Make.package
  Source/Particles/Make.package
  Source/Particles/ParticleCreation/Make.package
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/Pusher/Make.package
  Source/Particles/Sorting/Make.package
  Source/Particles/WarpXParticleContainer.H
  Source/Python/Make.package
  Source/Utils/Make.package
Labels: component: QED, component: spectral, install

#884 Badge for Travis-CI: Update Link
  README.md
Labels: component: documentation

#882 GitHub Action: Check Tests on OSX
  .github/workflows/source/hasEOLwhiteSpace
  .github/workflows/source/hasNonASCII
  .github/workflows/source/hasTabs
  .github/workflows/source/inputsNotTested
  .github/workflows/source/test_travis_matrix.sh
  .github/workflows/source/travis_matrix.py
  .github/workflows/source/wrongFileNameInExamples
Labels: component: tests, machine / system

#885 [mini] Increase tolerance for single-precision test
  Regression/WarpX-tests.ini
Labels: component: tests

#887 Load balance efficiency threshold
  Source/Parallelization/WarpXRegrid.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: load balancing

#892 Avoid i%1 in a lambda, gives compiler segfault
  Source/FieldSolver/SpectralSolver/SpectralFieldData.cpp
Labels: bug, component: spectral

#890 Lower tolerance of Langmuir_multi_single_precision
  Regression/WarpX-tests.ini
Labels: component: tests

#891 [mini-PR] fix test for QED - Breit Wheeler, optical depth evolution
  Regression/WarpX-tests.ini
Labels: bug, bug: affects latest release, component: tests

#895 Replace ixType().ixType() with ixType().toIntVect() for clarity
  Source/FieldSolver/FiniteDifferenceSolver/ComputeDivE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveB.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveF.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/FieldSolver/WarpX_QED_Field_Pushers.cpp
  Source/Utils/Average.cpp
Labels: cleaning

#886 Add space before bracket for function declaration
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
Labels: cleaning

#880 Charge in BeamRelevant Redu. Diagnostic
  Docs/source/running_cpp/parameters.rst
  Examples/Tests/initial_distribution/analysis_distribution.py
  Examples/Tests/initial_distribution/inputs
  Source/Diagnostics/ReducedDiags/BeamRelevant.cpp
Labels: component: diagnostics, component: tests, enhancement

#888 Contributing Guide: Add to Sphinx
  CONTRIBUTING.md
  CONTRIBUTING.rst
  Docs/source/developers/contributing.rst
  Docs/source/developers/developers.rst
  Docs/source/developers/repo_organization.rst
  Docs/source/running_cpp/parameters.rst
Labels: component: documentation

#898 Make sure single-precision compiles on GPU
  Regression/WarpX-GPU-tests.ini
  Source/Laser/LaserParticleContainer.cpp
Labels: backend: cuda, bug, bug: affects latest release, component: tests

#899 No OpenMP for GPU tests on Garuda
  Regression/WarpX-GPU-tests.ini
Labels: backend: cuda, bug, component: tests

#889 Loadbalance efficiency threshold documentation
  Docs/source/running_cpp/parameters.rst
  Source/WarpX.H
Labels: changes input script, component: documentation

#900 Reduced Diags: Fix 2D Emittance Label
  Source/Diagnostics/ReducedDiags/BeamRelevant.cpp
Labels: bug, component: diagnostics

#901 Breathe: <4.15.0
  Docs/requirements.txt
Labels: bug, component: documentation, component: third party

#871 [Mini] PML ncell check only along active axes
  Source/BoundaryConditions/PML.cpp
Labels: bug, bug: affects latest release, changes input script

#697 Travis: openPMD-api Compile
  .travis.yml
  Regression/prepare_file_travis.py
Labels: component: openPMD, component: tests

#905 Revert "Breathe: <4.15.0"
  Docs/requirements.txt
Labels: bug, component: documentation, component: third party

#908 Reorganize Tools/ into subfolders, in prevision of LibEnsemble scripts
  Docs/source/developers/workflow.rst
  Docs/source/running_cpp/parallelization.rst
  Docs/source/running_cpp/platforms.rst
  Docs/source/visualization/advanced.rst
  Docs/source/visualization/backtransformed_diags.rst
  Docs/source/visualization/plot_parallel.rst
  Docs/source/visualization/reduced_diags.rst
  Docs/source/visualization/visualization.rst
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  Tools/BatchScripts/batch_cori.sh
  Tools/BatchScripts/batch_summit.sh
  Tools/BatchScripts/script_profiling_summit.sh
  Tools/DevUtils/compare_wx_w_3d.ipynb
  Tools/DevUtils/compute_domain.py
  Tools/DevUtils/update_copyright.sh
  Tools/DevUtils/update_release.sh
  Tools/PerformanceTests/automated_test_1_uniform_rest_32ppc
  Tools/PerformanceTests/automated_test_2_uniform_rest_1ppc
  Tools/PerformanceTests/automated_test_3_uniform_drift_4ppc
  Tools/PerformanceTests/automated_test_4_labdiags_2ppc
  Tools/PerformanceTests/automated_test_5_loadimbalance
  Tools/PerformanceTests/automated_test_6_output_2ppc
  Tools/PerformanceTests/cori.py
  Tools/PerformanceTests/functions_perftest.py
  Tools/PerformanceTests/performance_log.txt
  Tools/PerformanceTests/run_alltests.py
  Tools/PerformanceTests/run_alltests_1node.py
  Tools/PerformanceTests/run_automated.py
  Tools/PerformanceTests/summit.py
  Tools/PostProcessing/Visualization.ipynb
  Tools/PostProcessing/boosted_frame_hdf5.ipynb
  Tools/PostProcessing/cori_postproc_script.sh
  Tools/PostProcessing/plot_parallel.py
  Tools/PostProcessing/plot_particle_path.py
  Tools/PostProcessing/read_lab_particles.py
  Tools/PostProcessing/read_raw_data.py
  Tools/PostProcessing/video_yt.py
  Tools/PostProcessing/yt3d_mpi.py
  Tools/script_profiling_summit.sh
Labels: cleaning

#906 Refactor AMReX IDs to Global ID
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Utils/WarpXUtil.H
Labels: cleaning, component: diagnostics

#853 Interpolation with coarsening for general staggering
  Source/Diagnostics/ComputeDiagFunctors/CellCenterFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/DivEFunctor.cpp
  Source/Diagnostics/FieldIO.cpp
  Source/Diagnostics/WarpXIO.cpp
  Source/Utils/Average.H
  Source/Utils/Average.cpp
Labels: component: diagnostics, component: mesh refinement, enhancement

#910 Yt release
  .travis.yml
  Docs/source/building/summit.rst
  Docs/source/visualization/yt.rst
Labels: component: documentation, component: post-processing, component: tests

#913 Increase tolerance for single-precision PSATD test
  Regression/WarpX-tests.ini
Labels: component: tests

#909 Abort code if the user attempts to use PML in RZ
  Examples/Tests/Langmuir/PICMI_inputs_langmuir_rz_multimode_analyze.py
  Examples/Tests/Langmuir/inputs_2d_multi_rz_rt
  Source/WarpX.cpp
Labels: component: RZ

#816 Implementation of the RZ spectral solver
  Docs/source/building/rzgeometry.rst
  Docs/source/building/spectral.rst
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/SpectralSolver/Make.package
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/Make.package
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithmRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.H
  Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/BesselRoots.H
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/HankelTransform.H
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/HankelTransform.cpp
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/Make.package
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/SpectralHankelTransformer.H
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/SpectralHankelTransformer.cpp
  Source/FieldSolver/SpectralSolver/SpectralKSpace.H
  Source/FieldSolver/SpectralSolver/SpectralKSpaceRZ.H
  Source/FieldSolver/SpectralSolver/SpectralKSpaceRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ.H
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/Make.WarpX
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: RZ, component: core, component: spectral, enhancement

#921 Remove Jaehong and add Yin to the Reg test mailing list
  Regression/WarpX-tests.ini
Labels: component: tests

#917 Fix link to Contributing Guide in README
  README.md
Labels: component: documentation

#912 Add section on LibEnsemble
  Docs/Doxyfile
  Docs/source/index.rst
  Docs/source/libensemble/libensemble.rst
  Tools/LibEnsemble/all_machine_specs.py
  Tools/LibEnsemble/plot_results.py
  Tools/LibEnsemble/read_sim_output.py
  Tools/LibEnsemble/requirements.txt
  Tools/LibEnsemble/run_libensemble_on_warpx.py
  Tools/LibEnsemble/sim/inputs
  Tools/LibEnsemble/summit_submit_mproc.sh
  Tools/LibEnsemble/warpx_simf.py
  Tools/LibEnsemble/write_sim_input.py
Labels: component: documentation, component: third party

#856 Diags with coarsening
  Source/Diagnostics/ComputeDiagFunctors/CellCenterFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/CellCenterFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/ComputeDiagFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/DivBFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/DivBFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/DivEFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/DivEFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/PartPerCellFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/PartPerCellFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/PartPerGridFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/PartPerGridFunctor.cpp
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
Labels: component: diagnostics

#916 Bug fix: spectral div(E) with PICSAR
  Source/Diagnostics/FieldIO.cpp
Labels: bug, changes input script, component: PICSAR, component: spectral

#911 [mini] Only particle redistribute during load balance if the level is remade
  Source/Parallelization/WarpXRegrid.cpp
Labels: component: load balancing

#894 [mini] SingleParticle Docs
  Docs/source/running_cpp/parameters.rst
Labels: component: documentation

#724 Particle Plotfile Filter
  Docs/source/running_cpp/parameters.rst
  Source/Diagnostics/ParticleIO.cpp
  Source/Particles/Filter/FilterFunctors.H
  Source/Particles/Filter/Make.package
  Source/Particles/Make.package
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
Labels: changes input script, component: diagnostics, component: documentation, enhancement

#926 [mini] remove cython from CI pip install list
  .travis.yml
Labels: cleaning, component: tests

#924 [mini] LibEnsemble Script needs sys Import
  Tools/LibEnsemble/run_libensemble_on_warpx.py
Labels: bug, component: third party

#927 Remove code for hybrid PSATD, as well as remaining Fortran interface file
  Docs/Doxyfile
  Docs/source/running_cpp/parameters.rst
  Regression/WarpX-tests.ini
  Source/Diagnostics/FieldIO.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/FieldSolver/Make.package
  Source/FieldSolver/PicsarHybridSpectralSolver/Make.package
  Source/FieldSolver/PicsarHybridSpectralSolver/PicsarHybridFFTData.H
  Source/FieldSolver/PicsarHybridSpectralSolver/PicsarHybridSpectralSolver.cpp
  Source/FieldSolver/PicsarHybridSpectralSolver/picsar_hybrid_spectral.F90
  Source/FieldSolver/SpectralSolver/SpectralKSpace.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/FortranInterface/Make.package
  Source/FortranInterface/WarpX_f.H
  Source/Initialization/WarpXInitData.cpp
  Source/Make.WarpX
  Source/Parallelization/GuardCellManager.H
  Source/Parallelization/GuardCellManager.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: Fortran to C++, cleaning, component: spectral

#923 Enable openPMD standard for new diagnostics
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FlushFormats/FlushFormat.H
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.H
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.H
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/FlushFormats/Make.package
  Source/Diagnostics/WarpXIO.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: cleaning, component: diagnostics, component: openPMD

#928 fixing bug to include Bx in CellCenterFunctor for diags
  Source/Diagnostics/Diagnostics.cpp
Labels: bug, component: diagnostics

#929 These need not be member variables
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.H
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
Labels: cleaning

#930 Increase tolerance for test PlasmaAccelerationBoost3d from 1.e-14 t2.e-14
  Regression/WarpX-tests.ini
Labels: component: tests

#932 Install Docs: Spack Env Update
  Docs/source/building/cori.rst
  Docs/source/building/openpmd.rst
  Docs/source/building/python.rst
  Docs/source/building/spack.rst
  Docs/source/building/summit.rst
Labels: component: documentation, component: third party, install

#934 Adding m_ for member variables in new diags
  Source/Diagnostics/ComputeDiagFunctors/DivBFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/DivEFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/PartPerCellFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/PartPerGridFunctor.cpp
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
Labels: cleaning, component: diagnostics

#936 Python documentation updates
  Docs/source/building/python.rst
  Docs/source/running_python/examples.rst
  Docs/source/running_python/how_to_run.rst
  Docs/source/running_python/running_picmi.rst
  Docs/source/running_python/running_python.rst
  Python/setup.py
Labels: component: Python, component: documentation

#902 Add hostname to LoadBalanceCosts reduced diagnostic
  Examples/Tests/reduced_diags/analysis_reduced_diags_loadbalancecosts.py
  Source/Diagnostics/ReducedDiags/LoadBalanceCosts.H
  Source/Diagnostics/ReducedDiags/LoadBalanceCosts.cpp
  Source/Utils/WarpXUtil.H
  Source/Utils/WarpXUtil.cpp
Labels: component: diagnostics

#941 [mini] Add contact us section to documentation
  Docs/source/contact_us.rst
  Docs/source/index.rst
Labels: component: documentation

#938 New diags also handle particle
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FlushFormats/FlushFormat.H
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.H
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.H
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/Make.package
  Source/Diagnostics/ParticleDiag/Make.package
  Source/Diagnostics/ParticleDiag/ParticleDiag.H
  Source/Diagnostics/ParticleDiag/ParticleDiag.cpp
  Source/Diagnostics/ParticleIO.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Particles/Filter/FilterFunctors.H
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
Labels: cleaning, component: diagnostics

#947 ReducedDiags: Missing virtual Destructor
  Source/Diagnostics/ReducedDiags/ReducedDiags.H
Labels: bug, component: diagnostics

#946 CI: Add macOS AppleClang Build
  .github/workflows/macos.yml
Labels: component: openPMD, component: tests, machine / system

#943 Re-initialize diag functors after LoadBalance
  Source/Diagnostics/ComputeDiagFunctors/CellCenterFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/ComputeDiagFunctor.H
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/MultiDiagnostics.H
  Source/Diagnostics/MultiDiagnostics.cpp
  Source/Parallelization/WarpXRegrid.cpp
Labels: bug, component: diagnostics

#883 Read species distribution from OPMD - part 3
  Docs/source/running_cpp/parameters.rst
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Utils/WarpXConst.H
Labels: changes input script, component: openPMD

#950 Fix warnings when compiling with DEBUG
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Diagnostics/ReducedDiags/LoadBalanceCosts.cpp
  Source/FieldSolver/WarpX_QED_Field_Pushers.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileFromTXYEFile.cpp
  Source/Parallelization/InterpolateDensityFineToCoarse.H
  Source/Particles/Collision/CollisionType.cpp
  Source/Particles/Filter/FilterFunctors.H
Labels: cleaning, warning

#857 Reduce size of test output
  Examples/Modules/laser_injection/inputs_3d_rt
  Examples/Physics_applications/uniform_plasma/inputs_3d
  Examples/Tests/Langmuir/analysis_langmuir_multi.py
  Examples/Tests/Langmuir/inputs_2d_multi_rz_rt
  Examples/Tests/Langmuir/inputs_3d_multi_rt
  Examples/Tests/TwoParticle_electrostatic/inputs_3d
  Regression/WarpX-tests.ini
Labels: component: tests

#951 Add checkpoint capability to new diags
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.H
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.H
  Source/Diagnostics/FlushFormats/Make.package
  Source/WarpX.H
Labels: component: diagnostics

#957 [mini] Style change to match the Standard
  Source/BoundaryConditions/PML.cpp
  Source/Diagnostics/ReducedDiags/FieldEnergy.cpp
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/GalileanAlgorithm.cpp
  Source/Particles/Collision/CollisionType.cpp
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineTableBuilder.cpp
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineWrapper.H
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineTableBuilder.cpp
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineWrapper.H
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/Utils/WarpXMovingWindow.cpp
  Source/Utils/WarpXUtil.cpp
Labels: cleaning

#961 [Mini]Fix Langmuir_multi_nodal test case
  Regression/WarpX-tests.ini
Labels: component: tests

#962 Use direct deposition for nodal tests also on Garuda
  Regression/WarpX-GPU-tests.ini
Labels: bug, component: tests

#964 CI: macOS Single Precision
  .github/workflows/macos.yml
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/GalileanAlgorithm.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileGaussian.cpp
  Source/Utils/WarpX_Complex.H
Labels: bug, bug: affects latest release, component: tests, machine / system

#963 Fix bug when compiling OpenPMD + 2D
  Source/Particles/PhysicalParticleContainer.cpp
Labels: bug, component: diagnostics, component: openPMD
