Repository BLAST-WarpX/warpx, pull requests merged in 2020-06, with the labels that each got.

#1064 [mini] Update release number in repo
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
Labels: component: documentation

#1069 In picmi.py, convert the diagnostics to write into a sorted list
  Python/pywarpx/picmi.py
Labels: bug: affects latest release, component: PICMI, component: Python, component: diagnostics

#1075 Change numprocs=2 for python reg tests and reset benchmarks
  Regression/Checksum/benchmarks_json/Python_Langmuir_2d.json
  Regression/Checksum/benchmarks_json/Python_Langmuir_rz_multimode.json
  Regression/Checksum/benchmarks_json/Python_LaserAccelerationMR.json
  Regression/Checksum/benchmarks_json/Python_PlasmaAcceleration.json
  Regression/Checksum/benchmarks_json/Python_PlasmaAccelerationMR.json
  Regression/Checksum/benchmarks_json/Python_gaussian_beam.json
  Regression/WarpX-tests.ini
Labels: component: tests

#1077 Updates to picmi
  Python/pywarpx/PSATD.py
  Python/pywarpx/WarpX.py
  Python/pywarpx/__init__.py
  Python/pywarpx/picmi.py
Labels: component: PICMI

#1074 [Mini]Fixed bad arguments in PICMI_inputs_laser_acceleration.py
  Examples/Physics_applications/laser_acceleration/PICMI_inputs_laser_acceleration.py
Labels: component: PICMI, component: tests

#1078 remove #line wp_parser.l because it causes issues with AMReX make system
  Source/Parser/wp_parser.lex.cpp
Labels: cleaning, component: third party, install

#1076 Doc: document time staggering in output file
  Docs/source/visualization/visualization.rst
Labels: cleaning

#1067 Cori: ADIOS2
  Docs/source/building/cori.rst
Labels: component: openPMD, install, machine / system

#1081 CI Inputs Check: Fix Silent Abort
  .github/workflows/source/inputsNotTested
Labels: component: tests

#1070 [Mini] Z Offset to loaded openPMD particles
  Docs/source/running_cpp/parameters.rst
  Docs/source/running_cpp/pwfa.rst
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
Labels: changes input script, component: openPMD, enhancement

#1079 Stop mailing errors from Battra
  Regression/WarpX-tests.ini
Labels: component: tests

#1068 [mini] Update doc on ionization
  Docs/source/running_cpp/parameters.rst
Labels: component: documentation

#1090 Docs: Summit Restructure
  Docs/source/building/building.rst
  Docs/source/building/summit.rst
  Docs/source/running_cpp/platforms.rst
Labels: component: documentation

#759 Add CMake Scripts
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  CMakeLists.txt
  Source/BoundaryConditions/CMakeLists.txt
  Source/Diagnostics/CMakeLists.txt
  Source/Diagnostics/ComputeDiagFunctors/CMakeLists.txt
  Source/Diagnostics/FlushFormats/CMakeLists.txt
  Source/Diagnostics/ParticleDiag/CMakeLists.txt
  Source/Diagnostics/ReducedDiags/CMakeLists.txt
  Source/Evolve/CMakeLists.txt
  Source/FieldSolver/CMakeLists.txt
  Source/FieldSolver/FiniteDifferenceSolver/CMakeLists.txt
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/CMakeLists.txt
  Source/FieldSolver/SpectralSolver/CMakeLists.txt
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/CMakeLists.txt
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/CMakeLists.txt
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/Make.package
  Source/Filter/CMakeLists.txt
  Source/Initialization/CMakeLists.txt
  Source/Laser/CMakeLists.txt
  Source/Laser/LaserProfilesImpl/CMakeLists.txt
  Source/Parallelization/CMakeLists.txt
  Source/Parser/CMakeLists.txt
  Source/Particles/CMakeLists.txt
  Source/Particles/Collision/CMakeLists.txt
  Source/Particles/ElementaryProcess/CMakeLists.txt
  Source/Particles/ElementaryProcess/QEDInternals/CMakeLists.txt
  Source/Particles/ParticleCreation/CMakeLists.txt
  Source/Particles/Sorting/CMakeLists.txt
  Source/Python/CMakeLists.txt
  Source/Utils/CMakeLists.txt
  Source/Utils/WarpXUtil.H
  cmake/WarpXFunctions.cmake
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  cmake/dependencies/openPMD.cmake
Labels: enhancement, install

#1093 Replace amrex namespace with amrex:: prefix in DiagFunctors
  Source/Diagnostics/ComputeDiagFunctors/CellCenterFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/DivBFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/DivEFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/PartPerCellFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/PartPerGridFunctor.cpp
Labels: cleaning, component: diagnostics

#1094 Docs: Update Ascent
  Docs/source/building/summit.rst
  Docs/source/running_cpp/parameters.rst
  Docs/source/visualization/ascent.rst
  Source/Make.WarpX
Labels: component: documentation

#1085 New BTD class layout and member functions - Part 1
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/CMakeLists.txt
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/CMakeLists.txt
  Source/Diagnostics/ComputeDiagFunctors/Make.package
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.H
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/Make.package
  Source/Diagnostics/MultiDiagnostics.H
  Source/Diagnostics/MultiDiagnostics.cpp
Labels: component: diagnostics

#1098 Travis CI: Wait Longer for Make
  .travis.yml
  run_test.sh
Labels: component: tests

#1100 CMake: Ascent
  CMakeLists.txt
  Docs/source/building/summit.rst
  cmake/WarpXFunctions.cmake
  cmake/dependencies/AMReX.cmake
Labels: component: diagnostics, component: documentation, install

#1102 Renamining: development
  CONTRIBUTING.rst
  Docs/source/building/spack.rst
  Docs/source/developers/developers.rst
  Docs/source/developers/documentation.rst
  Docs/source/developers/workflow.rst
  Docs/source/index.rst
  Docs/source/visualization/sensei.rst
  README.md
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  Source/Diagnostics/BackTransformedDiagnostic.cpp
Labels: component: documentation, component: tests

#1103 reimplementation of interpolation and removal of Fortran from gnu make
  Source/Diagnostics/FieldIO.H
  Source/Diagnostics/FieldIO.cpp
  Source/Diagnostics/SliceDiagnostic.cpp
  Source/Diagnostics/WarpXIO.cpp
  Source/Make.WarpX
  Source/Utils/Interpolate.cpp
  Source/Utils/Interpolate_K.H
Labels: Fortran to C++

#1108 CMake: No Fortran
  .github/workflows/ubuntu.yml
  CMakeLists.txt
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/WarpXFunctions.cmake
  cmake/dependencies/AMReX.cmake
Labels: install

#1109 Fix: Extra Semicolons & In-Line Doxygen
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Particles/ParticleCreation/FilterCopyTransform.H
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/ShapeFactors.H
  Source/Utils/CoarsenIO.H
  Source/Utils/CoarsenMR.H
  Source/Utils/WarpXMovingWindow.cpp
  Source/Utils/WarpXUtil.cpp
  Source/WarpX.H
Labels: warning

#1107 Style Check: Eval-uable
  .github/workflows/source/hasEOLwhiteSpace
  .github/workflows/source/hasTabs
Labels: component: tests

#1105 Fix Race condition in GetParticleSlice for BTD
  Source/Particles/PhysicalParticleContainer.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#1096 [Mini] Docs info for blocking_factor
  Docs/source/running_cpp/parallelization.rst
  Docs/source/running_cpp/parameters.rst
Labels: component: documentation, component: parallelization

#1089 AddPlasmaFromFile fix for periodic boundaries
  Docs/source/running_cpp/parameters.rst
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/PhysicalParticleContainer.cpp
Labels: bug, bug: affects latest release, component: openPMD

#1005 Added check of gridding for RZ spectral solver
  Docs/source/running_cpp/parallelization.rst
  Python/pywarpx/_libwarpx.py
  Source/Python/WarpXWrappers.cpp
  Source/Python/WarpXWrappers.h
  Source/Utils/WarpXUtil.H
  Source/Utils/WarpXUtil.cpp
  Source/main.cpp
Labels: component: RZ, component: spectral

#949 Add automated test for divE cleaning
  Examples/Modules/dive_cleaning/analysis.py
  Examples/Modules/dive_cleaning/inputs_3d
  Regression/Checksum/benchmarks_json/dive_cleaning_2d.json
  Regression/Checksum/benchmarks_json/dive_cleaning_3d.json
  Regression/WarpX-tests.ini
Labels: component: tests

#1111 Use new github picsar repo
  .github/workflows/ubuntu.yml
  .lgtm.yml
  CONTRIBUTING.rst
  Docs/source/building/building.rst
  Docs/source/building/summit.rst
  Docs/source/visualization/sensei.rst
  Regression/TestFillBoundary/compare_guard_cells.sh
  cmake/dependencies/PICSAR.cmake
  run_test.sh
Labels: component: PICSAR, component: third party

#1092 New BTD class layout and member functions - Part 2
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.cpp
Labels: component: diagnostics

#1114 Summit: no `-n` in jsrun
  Tools/BatchScripts/batch_summit.sh
Labels: component: documentation, machine / system

#1118 USE_HDF5 is now supported by AMReX make system
  Source/Make.WarpX
Labels: component: diagnostics

#1115 [mini]For RZ, added assert that periodicity is not set radially
  Source/WarpX.cpp
Labels: component: RZ

#1120 CMake: MPI, Asserts and Advanced AMReX
  .github/workflows/ubuntu.yml
  CMakeLists.txt
  Docs/source/building/cmake.rst
  cmake/WarpXFunctions.cmake
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/openPMD.cmake
Labels: install

#1113 [small] Inject Particles from openPMD in RZ
  Docs/source/running_cpp/parameters.rst
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
Labels: component: RZ

#1122 [mini]Removed references to particle E and B from Python
  Python/pywarpx/PGroup.py
  Python/pywarpx/_libwarpx.py
Labels: cleaning, component: Python

#1124 CMake: AMReX Advanced Options
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  cmake/dependencies/openPMD.cmake
Labels: component: third party, install

#1130 Fix typo
  Source/Particles/Gather/GetExternalFields.cpp
Labels: bug

#830 Add plasma refactor
  Regression/Checksum/benchmarks_json/Langmuir_2d_nompi.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_rz.json
  Regression/Checksum/benchmarks_json/LaserAcceleration.json
  Regression/Checksum/benchmarks_json/LaserAccelerationBoost.json
  Regression/Checksum/benchmarks_json/LaserAccelerationMR.json
  Regression/Checksum/benchmarks_json/LaserAccelerationRZ.json
  Regression/Checksum/benchmarks_json/PlasmaAccelerationBoost2d.json
  Regression/Checksum/benchmarks_json/PlasmaAccelerationBoost3d.json
  Regression/Checksum/benchmarks_json/PlasmaAccelerationMR.json
  Regression/Checksum/benchmarks_json/PlasmaMirror.json
  Regression/Checksum/benchmarks_json/Python_Langmuir_rz_multimode.json
  Regression/Checksum/benchmarks_json/Python_LaserAccelerationMR.json
  Regression/Checksum/benchmarks_json/Python_PlasmaAcceleration.json
  Regression/Checksum/benchmarks_json/Python_PlasmaAccelerationMR.json
  Regression/Checksum/benchmarks_json/ionization_boost.json
  Regression/Checksum/benchmarks_json/ionization_lab.json
  Regression/Checksum/benchmarks_json/momentum-conserving-gather.json
  Regression/Checksum/benchmarks_json/qed_breit_wheeler_opt_depth_evolution.json
  Regression/Checksum/benchmarks_json/qed_breit_wheeler_tau_init.json
  Regression/Checksum/benchmarks_json/qed_quantum_sync_tau_init.json
  Regression/Checksum/benchmarks_json/subcyclingMR.json
  Source/Initialization/InjectorPosition.H
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/PhysicalParticleContainer.cpp
Labels: Performance optimization, cleaning, component: core

#1129 typo in libEnsemble scripts
  Tools/LibEnsemble/run_libensemble_on_warpx.py
Labels: bug, bug: affects latest release, component: third party

#1099 Improve rho diagnostic
  Docs/source/visualization/advanced.rst
  Docs/source/visualization/inputs.2d
  Docs/source/visualization/visualization.rst
  Regression/Checksum/benchmarks_json/Langmuir_multi.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_nodal.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_psatd_single_precision.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_single_precision.json
  Regression/Checksum/benchmarks_json/Python_LaserAccelerationMR.json
  Source/Diagnostics/ComputeDiagFunctors/CMakeLists.txt
  Source/Diagnostics/ComputeDiagFunctors/Make.package
  Source/Diagnostics/ComputeDiagFunctors/RhoFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/RhoFunctor.cpp
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#1127 Docs: Ascent & Python Summit Updates
  CMakeLists.txt
  Docs/source/building/summit.rst
  Docs/source/libensemble/libensemble.rst
  Tools/LibEnsemble/requirements.txt
Labels: component: documentation, machine / system

#1134 Use PICSAR new development branch
  .lgtm.yml
  CONTRIBUTING.rst
  Regression/WarpX-GPU-tests.ini
  Tools/PerformanceTests/run_alltests.py
  Tools/PerformanceTests/run_alltests_1node.py
  cmake/dependencies/PICSAR.cmake
  run_test.sh
Labels: component: documentation, component: third party
