Repository BLAST-WarpX/warpx, pull requests merged in 2020-07, with the labels that each got.

#1137 Clarify Visualization notebook and fix path in the doc
  Docs/source/visualization/yt.rst
  Tools/PostProcessing/Visualization.ipynb
Labels: component: documentation

#1125 CMake: DPC++, OMP Def., Binary Names
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  CMakeLists.txt
  Docs/source/building/cmake.rst
  cmake/WarpXFunctions.cmake
  cmake/dependencies/AMReX.cmake
Labels: install

#1133 Doc: how to compile and run on Juwels
  Docs/source/building/building.rst
  Docs/source/building/cori.rst
  Docs/source/building/juwels.rst
  Docs/source/building/summit.rst
  Tools/BatchScripts/batch_juwels.sh
Labels: component: documentation

#1138 Update release tag in all files on the repo
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
Labels: component: documentation

#1143 CMake: Guard CMake 3.17 Feature
  CMakeLists.txt
Labels: backend: cuda, bug, install

#1142 assert the particles are positive to check for overflow
  Source/Particles/PhysicalParticleContainer.cpp
Labels: component: core

#1145 Docs: OMP new CMake default
  Docs/source/building/cmake.rst
Labels: component: documentation, install

#1128 PSATD: add option to update E without using rho
  Docs/source/running_cpp/parameters.rst
  Regression/Checksum/benchmarks_json/Langmuir_multi_2d_psatd.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_2d_psatd_momentum_conserving.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_2d_psatd_nodal.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_psatd.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_psatd_momentum_conserving.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_psatd_nodal.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_psatd_single_precision.json
  Regression/WarpX-tests.ini
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralSolver.H
  Source/FieldSolver/SpectralSolver/SpectralSolver.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: spectral, enhancement

#1148 [mini PR] At Initialization, step = -1 for diagnostics
  Source/Initialization/WarpXInitData.cpp
Labels: component: diagnostics

#1154 Raise the stack limit when running with cuda
  Source/main.cpp
Labels: backend: cuda, bug, component: tests

#869 Averaged Galilean PSATD
  Docs/source/running_cpp/parameters.rst
  Examples/Tests/averaged_galilean/analysis_avg_2d.py
  Examples/Tests/averaged_galilean/analysis_avg_3d.py
  Examples/Tests/averaged_galilean/inputs_avg_2d
  Examples/Tests/averaged_galilean/inputs_avg_3d
  Regression/Checksum/benchmarks_json/averaged_galilean_2d_psatd.json
  Regression/Checksum/benchmarks_json/averaged_galilean_3d_psatd.json
  Regression/WarpX-tests.ini
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/AvgGalileanAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/AvgGalileanAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/CMakeLists.txt
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/Make.package
  Source/FieldSolver/SpectralSolver/SpectralFieldData.H
  Source/FieldSolver/SpectralSolver/SpectralKSpace.cpp
  Source/FieldSolver/SpectralSolver/SpectralSolver.H
  Source/FieldSolver/SpectralSolver/SpectralSolver.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Laser/LaserParticleContainer.H
  Source/Laser/LaserParticleContainer.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhotonParticleContainer.H
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.H
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: spectral

#1149 openPMD: Directory Cleanup, 6 Digits
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: component: diagnostics

#1150 Fix bug with rho diagnostics in RZ geometry
  Examples/Physics_applications/laser_acceleration/inputs_2d_rz
  Regression/Checksum/benchmarks_json/LaserAccelerationRZ.json
  Source/Particles/WarpXParticleContainer.cpp
Labels: bug, bug: affects latest release, component: RZ

#1159 Fix compilation of AvgGalilean for GPU
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/AvgGalileanAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/AvgGalileanAlgorithm.cpp
Labels: backend: cuda, bug

#1162 Summit Power9 CPUs documentation
  Docs/source/running_cpp/platforms.rst
  Tools/BatchScripts/batch_summit_power9.sh
Labels: component: documentation, machine / system

#1084 Fix Profile: Parabolic Ch. Single Prec.
  Examples/Tests/initial_plasma_profile/analysis.py
  Examples/Tests/initial_plasma_profile/inputs
  Regression/Checksum/benchmarks_json/parabolic_channel_initialization_2d_single_precision.json
  Regression/WarpX-tests.ini
  Source/Initialization/InjectorDensity.H
Labels: bug, bug: affects latest release, component: core

#907 Added the electrostatic sphere test
  Examples/Tests/ElectrostaticSphere/analysis_electrostatic_sphere.py
  Examples/Tests/ElectrostaticSphere/inputs_3d
  Examples/Tests/TwoParticle_electrostatic/inputs_3d
  Regression/WarpX-tests.ini
Labels: component: electrostatic, component: tests

#1165 [mini] make fft_do_time_averaging a static member of class WarpX
  Source/FieldSolver/SpectralSolver/SpectralSolver.H
  Source/FieldSolver/SpectralSolver/SpectralSolver.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning, component: spectral

#1172 [Mini]Fix bug in RZ PSATD rho terms
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.cpp
Labels: bug: affects latest release, component: RZ, component: spectral

#1169 Add support for infinite-order PSATD
  Docs/source/running_cpp/parameters.rst
  Source/FieldSolver/SpectralSolver/SpectralKSpace.cpp
  Source/WarpX.cpp
Labels: component: spectral, enhancement

#1160 fix automated performance tests on Summit
  Tools/DevUtils/update_copyright.sh
  Tools/PerformanceTests/automated_test_1_uniform_rest_32ppc
  Tools/PerformanceTests/automated_test_2_uniform_rest_1ppc
  Tools/PerformanceTests/automated_test_3_uniform_drift_4ppc
  Tools/PerformanceTests/automated_test_4_labdiags_2ppc
  Tools/PerformanceTests/automated_test_5_loadimbalance
  Tools/PerformanceTests/automated_test_6_output_2ppc
  Tools/PerformanceTests/functions_perftest.py
  Tools/PerformanceTests/run_alltests.py
  Tools/PerformanceTests/run_alltests_1node.py
  Tools/PerformanceTests/run_automated.py
  Tools/PerformanceTests/summit.py
Labels: Performance optimization, component: tests

#1161 Add doc for performance tests
  Docs/source/developers/developers.rst
  Docs/source/developers/performance_tests.rst
Labels: Performance optimization, component: documentation

#1164 Default: abort_on_out_of_gpu_memory = 1
  Docs/source/running_cpp/parameters.rst
  Source/Initialization/CMakeLists.txt
  Source/Initialization/Make.package
  Source/Initialization/WarpXAMReXInit.H
  Source/Initialization/WarpXAMReXInit.cpp
  Source/main.cpp
Labels: backend: cuda, changes input script, component: documentation

#1174 Combine analysis scripts for Galilean and averaged PSATD automated tests in one
  Examples/Tests/averaged_galilean/analysis_avg_2d.py
  Examples/Tests/averaged_galilean/analysis_avg_3d.py
  Examples/Tests/galilean/analysis_2d.py
  Examples/Tests/galilean/analysis_3d.py
  Regression/WarpX-tests.ini
Labels: component: spectral, component: tests

#1179 Travis: Work-Around yt/matplotlib
  .travis.yml
Labels: bug, component: tests, component: third party, workaround

#1072 For RZ, fix the deposition near the axis
  Regression/Checksum/benchmarks_json/LaserAccelerationRZ.json
  Source/FieldSolver/WarpXPushFieldsEM.cpp
Labels: bug: affects latest release, component: RZ

#1180 fix documentation for external E B with constant values
  Docs/source/running_cpp/parameters.rst
Labels: component: documentation

#1181 [mini] Fix automated performance tests on Cori
  Tools/PerformanceTests/cori.py
Labels: Performance optimization, component: tests

#1178 Fixing compiler warnings
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/AvgGalileanAlgorithm.cpp
  Source/Parallelization/GuardCellManager.cpp
Labels: warning

#1048 LWFA: Diag add Charge Density
  Examples/Physics_applications/laser_acceleration/PICMI_inputs_laser_acceleration.py
  Examples/Physics_applications/laser_acceleration/inputs_2d
  Examples/Physics_applications/laser_acceleration/inputs_2d_boost
  Examples/Physics_applications/laser_acceleration/inputs_3d
  Regression/Checksum/benchmarks_json/LaserAcceleration.json
  Regression/Checksum/benchmarks_json/LaserAccelerationBoost.json
  Regression/Checksum/benchmarks_json/LaserAccelerationMR.json
Labels: component: PICMI, component: tests

#1182 Respect AMREX_MPI_THREAD_MULTIPLE when calling MPI Init.
  Source/main.cpp
Labels: component: diagnostics

#1186 Replace "" with <> for AMReX includes
  Source/Diagnostics/FlushFormats/FlushFormatSensei.H
  Source/Diagnostics/ReducedDiags/MultiReducedDiags.cpp
  Source/Diagnostics/ReducedDiags/ReducedDiags.H
  Source/Diagnostics/ReducedDiags/ReducedDiags.cpp
  Source/Particles/ParticleCreation/DefaultInitialization.H
  Source/Utils/WarpXProfilerWrapper.H
Labels: cleaning, component: third party

#1177 Overwrite AMReX Defaults: Python
  Source/Initialization/WarpXAMReXInit.H
  Source/Initialization/WarpXAMReXInit.cpp
  Source/Python/WarpXWrappers.cpp
Labels: backend: cuda, changes input script, component: Python

#1157 Average slice emittance - libEnsemble example
  Tools/LibEnsemble/plot_results.py
  Tools/LibEnsemble/read_sim_output.py
  Tools/LibEnsemble/warpx_simf.py
Labels: component: third party

#1082 Fix Evolution: Current Depos. and Shapes
  Regression/Checksum/benchmarks_json/Langmuir_2d_single_precision.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_psatd_single_precision.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_single_precision.json
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/Gather/FieldGather.H
  Source/Particles/ShapeFactors.H
Labels: bug, bug: affects latest release, component: core

#1192 define compute_shape_factor for VayDepos
  Source/Particles/Deposition/CurrentDeposition.H
Labels: bug, component: core

#1190 [tiny] Explained print when NaN in LibEnsemble
  Tools/LibEnsemble/warpx_simf.py
Labels: component: documentation, component: third party

#1196 openPMD: Fix NOMPI Particle Output
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: bug, bug: affects latest release, component: openPMD, machine / system

#1197 Fix Gatherv
  Source/Diagnostics/ReducedDiags/LoadBalanceCosts.H
Labels: component: load balancing

#1199 Fix docs and assertions for nox, noy, noz.
  Docs/source/running_cpp/parameters.rst
  Source/WarpX.cpp
Labels: bug: affects latest release, component: documentation

#1031 Cleaner calculation of the simulation timestep
  Examples/Tests/galilean/inputs_2d
  Examples/Tests/galilean/inputs_3d
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  Source/Evolve/CMakeLists.txt
  Source/Evolve/Make.package
  Source/Evolve/WarpXComputeDt.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianCKCAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianNodalAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianYeeAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CylindricalYeeAlgorithm.H
  Source/WarpX.H
Labels: cleaning, component: core

#1175 Add Travis regression test for RZ spectral solver
  .travis.yml
  Examples/Tests/Langmuir/analysis_langmuir_multi_rz.py
  Regression/Checksum/benchmarks_json/Langmuir_multi_rz_psatd.json
  Regression/WarpX-tests.ini
  Regression/prepare_file_travis.py
  Source/Make.WarpX
Labels: component: RZ, component: spectral, component: tests

#1200 Workaround to fix 2D Galilean benchmarks
  Regression/Checksum/benchmarks_json/averaged_galilean_2d_psatd.json
  Regression/Checksum/benchmarks_json/galilean_2d_psatd.json
  Regression/Checksum/checksum.py
Labels: component: tests

#1205 [tiny] Fix bug concerning a misprint in preprocessor directive
  Source/Particles/PhysicalParticleContainer.cpp
Labels: bug, bug: affects latest release, component: QED

#1202 Do PSATD+RZ in the RZ_NO_MPI travis instance
  .travis.yml
  Regression/prepare_file_travis.py
Labels: component: tests

#1203 CMake: RelWithDebInfo -O3
  cmake/WarpXFunctions.cmake
Labels: bug, bug: affects latest release, install

#1208 Particle id: access via getter & setter
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
Labels: component: core, component: openPMD, component: third party

#1207 Fix -Wextra-semi
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BackTransformedDiagnostic.H
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/ComputeDiagFunctor.H
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/FlushFormats/FlushFormat.H
  Source/Diagnostics/FlushFormats/FlushFormatAscent.H
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.H
  Source/Diagnostics/ParticleDiag/ParticleDiag.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianCKCAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianNodalAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianYeeAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.cpp
  Source/Laser/LaserProfiles.H
  Source/Particles/Filter/FilterFunctors.H
  Source/Particles/PhotonParticleContainer.H
  Source/Particles/ShapeFactors.H
  Source/Particles/Sorting/SortingUtils.H
  Source/Particles/WarpXParticleContainer.H
  Source/WarpX.H
Labels: warning

#1211 GNUmake Build: Enable Warnings
  GNUmakefile
Labels: install, warning

#1006 Added k-space filter for RZ spectral solver
  Docs/source/running_cpp/parameters.rst
  Python/pywarpx/picmi.py
  Source/FieldSolver/SpectralSolver/CMakeLists.txt
  Source/FieldSolver/SpectralSolver/Make.package
  Source/FieldSolver/SpectralSolver/SpectralBinomialFilter.H
  Source/FieldSolver/SpectralSolver/SpectralBinomialFilter.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.H
  Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/HankelTransform.H
  Source/FieldSolver/SpectralSolver/SpectralKSpace.H
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ.H
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: RZ, component: spectral

#1212 [tiny] Fix warning on LGTM
  Source/Diagnostics/ReducedDiags/LoadBalanceCosts.cpp
Labels: cleaning

#1209 Fix Diagnostics: Compiler Warnings
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/SliceDiagnostic.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: component: diagnostics, warning

#1188 Rename Input to `algo.maxwell_solver`
  Docs/source/developers/testing.rst
  Docs/source/running_cpp/parameters.rst
  Docs/source/visualization/inputs.2d
  Examples/Modules/boosted_diags/inputs_3d_slice
  Examples/Modules/ionization/inputs_2d_bf_rt
  Examples/Modules/ionization/inputs_2d_rt
  Examples/Modules/laser_injection_from_file/inputs.2d_test_txye
  Examples/Physics_applications/laser_acceleration/inputs_2d_boost
  Examples/Physics_applications/plasma_acceleration/inputs_2d
  Examples/Physics_applications/plasma_acceleration/inputs_2d_boost
  Examples/Physics_applications/plasma_acceleration/inputs_3d_boost
  Examples/Tests/averaged_galilean/inputs_avg_2d
  Examples/Tests/averaged_galilean/inputs_avg_3d
  Examples/Tests/particles_in_PML/inputs_2d
  Examples/Tests/particles_in_PML/inputs_3d
  Examples/Tests/reduced_diags/inputs
  Examples/Tests/reduced_diags/inputs_loadbalancecosts
  Examples/Tests/subcycling/inputs_2d
  Python/pywarpx/picmi.py
  Regression/TestFillBoundary/compare_guard_cells.sh
  Regression/TestFillBoundary/inputs.2d
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  Source/BoundaryConditions/PML.cpp
  Source/Evolve/WarpXComputeDt.cpp
  Source/Parallelization/GuardCellManager.H
  Source/Parallelization/GuardCellManager.cpp
  Source/Utils/WarpXAlgorithmSelection.cpp
  Source/WarpX.H
  Source/WarpX.cpp
  Tools/LibEnsemble/sim/inputs
Labels: changes input script, component: Python

#1218 Current Deposition: Fix Unused Params
  Source/Particles/Deposition/CurrentDeposition.H
Labels: warning

#1217 Input: Remove n<something> options
  Examples/Modules/RigidInjection/inputs_2d_BoostedFrame
  Examples/Modules/RigidInjection/inputs_2d_LabFrame
  Examples/Modules/boosted_diags/inputs_3d_slice
  Examples/Modules/dive_cleaning/inputs_3d
  Examples/Modules/ionization/inputs_2d_bf_rt
  Examples/Modules/ionization/inputs_2d_rt
  Examples/Modules/laser_injection/inputs_2d_rt
  Examples/Modules/laser_injection/inputs_3d_rt
  Examples/Modules/laser_injection_from_file/inputs.2d_test_txye
  Examples/Modules/nci_corrector/inputs_2d
  Examples/Modules/qed/breit_wheeler/inputs_2d_tau_init
  Examples/Modules/qed/breit_wheeler/inputs_3d_optical_depth_evolution
  Examples/Modules/qed/quantum_synchrotron/inputs_2d_tau_init
  Examples/Modules/qed/schwinger/inputs_3d_schwinger
  Examples/Modules/relativistic_space_charge_initialization/inputs_3d
  Examples/Modules/space_charge_initialization/inputs_3d
  Examples/Physics_applications/laser_acceleration/inputs_2d
  Examples/Physics_applications/laser_acceleration/inputs_2d_boost
  Examples/Physics_applications/laser_acceleration/inputs_2d_rz
  Examples/Physics_applications/laser_acceleration/inputs_3d
  Examples/Physics_applications/plasma_acceleration/inputs_2d
  Examples/Physics_applications/plasma_acceleration/inputs_2d_boost
  Examples/Physics_applications/plasma_acceleration/inputs_3d_boost
  Examples/Physics_applications/plasma_mirror/inputs_2d
  Examples/Physics_applications/uniform_plasma/inputs_2d
  Examples/Physics_applications/uniform_plasma/inputs_3d
  Examples/Tests/ElectrostaticSphere/inputs_3d
  Examples/Tests/Langmuir/inputs_2d_multi_rt
  Examples/Tests/Langmuir/inputs_2d_multi_rz_rt
  Examples/Tests/Langmuir/inputs_3d_multi_rt
  Examples/Tests/Langmuir/inputs_3d_rt
  Examples/Tests/Larmor/inputs_2d_mr
  Examples/Tests/Maxwell_Hybrid_QED/inputs_2d
  Examples/Tests/PML/inputs_2d
  Examples/Tests/SingleParticle/inputs_2d
  Examples/Tests/averaged_galilean/inputs_avg_2d
  Examples/Tests/averaged_galilean/inputs_avg_3d
  Examples/Tests/collision/inputs_2d
  Examples/Tests/collision/inputs_3d
  Examples/Tests/galilean/inputs_2d
  Examples/Tests/galilean/inputs_3d
  Examples/Tests/initial_distribution/inputs
  Examples/Tests/initial_plasma_profile/inputs
  Examples/Tests/laser_on_fine/inputs_2d
  Examples/Tests/particle_pusher/inputs_3d
  Examples/Tests/particles_in_PML/inputs_2d
  Examples/Tests/particles_in_PML/inputs_3d
  Examples/Tests/photon_pusher/analysis_photon_pusher.py
  Examples/Tests/photon_pusher/inputs_3d
  Examples/Tests/radiation_reaction/test_const_B_analytical/analysis_classicalRR.py
  Examples/Tests/radiation_reaction/test_const_B_analytical/inputs_3d
  Examples/Tests/reduced_diags/inputs
  Examples/Tests/reduced_diags/inputs_loadbalancecosts
  Examples/Tests/subcycling/inputs_2d
  Python/pywarpx/Lasers.py
  Python/pywarpx/Particles.py
  Python/pywarpx/picmi.py
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/WarpX.cpp
Labels: changes input script, component: core

#1219 CI: Fix oneAPI Activation
  .github/workflows/ubuntu.yml
Labels: backend: dpc++, component: tests

#1215 Docs: Hint FWHM_I in Gaussian Beam
  Docs/source/running_cpp/parameters.rst
Labels: component: documentation

#1222 Add job submission script of Cori Haswell in Doc
  Docs/source/running_cpp/platforms.rst
  Tools/BatchScripts/batch_cori_haswell.sh
Labels: component: documentation, machine / system

#1210 [tiny] Avoid particles with do_not_gather=1 be pushed in the last half step
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
Labels: bug, bug: affects latest release, component: core

#1194 Add some information about using async io in the docs
  Docs/source/building/building.rst
  Docs/source/running_cpp/parameters.rst
  Docs/source/visualization/visualization.rst
Labels: component: diagnostics, component: documentation

#1226 Travis CI: CCache
  .travis.yml
  Regression/WarpX-tests.ini
  Regression/prepare_file_travis.py
Labels: component: tests

#1224 openPMD: Field Names/Labels, Particle Record Names
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: component: RZ, component: openPMD

#1191 Add input parameter to control Galerkin-scheme gather
  Docs/source/running_cpp/parameters.rst
  Source/Initialization/WarpXInitData.cpp
  Source/Particles/ElementaryProcess/Ionization.H
  Source/Particles/ElementaryProcess/Ionization.cpp
  Source/Particles/ElementaryProcess/QEDPairGeneration.H
  Source/Particles/ElementaryProcess/QEDPairGeneration.cpp
  Source/Particles/ElementaryProcess/QEDPhotonEmission.H
  Source/Particles/ElementaryProcess/QEDPhotonEmission.cpp
  Source/Particles/Gather/FieldGather.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Python/WarpXWrappers.cpp
  Source/Python/WarpXWrappers.h
  Source/WarpX.H
  Source/WarpX.cpp
Labels: changes input script

#1225 openPMD: Reconstruct RZ Particles
  Source/Diagnostics/ParticleDiag/ParticleDiag.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: component: RZ, component: openPMD
