Repository BLAST-WarpX/warpx, pull requests merged in 2020-08, with the labels that each got.

#1227 Fix the source of some "unused variable" warnings
  Source/Initialization/InjectorMomentum.H
  Source/Initialization/InjectorPosition.H
  Source/Particles/PhotonParticleContainer.H
  Source/Particles/Pusher/GetAndSetPosition.H
  Source/Particles/WarpXParticleContainer.H
Labels: cleaning, warning

#1229 Fix some compilation warnings
  Source/BoundaryConditions/PML.H
  Source/BoundaryConditions/PML_current.H
  Source/BoundaryConditions/WarpX_PML_kernels.H
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BackTransformedDiagnostic.H
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Particles/Gather/FieldGather.H
  Source/Particles/MultiParticleContainer.H
  Source/Particles/ParticleCreation/SmartCreate.H
  Source/Particles/Pusher/GetAndSetPosition.H
  Source/WarpX.H
Labels: cleaning, warning

#1223 Travis CI: openPMD Slipped Out
  .travis.yml
  Regression/WarpX-tests.ini
  Source/Diagnostics/FieldIO.H
  Source/Diagnostics/FieldIO.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: component: openPMD, component: tests

#1233 Fix bug in RZ FDTD div(E) diagnostics
  Source/FieldSolver/FiniteDifferenceSolver/ComputeDivE.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#1158 Reformatted BTD fields
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/CellCenterFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/CellCenterFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/ComputeDiagFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/DivBFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/DivBFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/DivEFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/DivEFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/PartPerCellFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/PartPerCellFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/PartPerGridFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/PartPerGridFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/RhoFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/RhoFunctor.cpp
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Evolve/WarpXEvolve.cpp
Labels: component: diagnostics

#1151 Galilean PSATD: current correction and rho-free formulation
  Docs/source/running_cpp/parameters.rst
  Examples/Tests/galilean/analysis_2d.py
  Examples/Tests/galilean/analysis_3d.py
  Regression/Checksum/benchmarks_json/galilean_2d_psatd_current_correction.json
  Regression/Checksum/benchmarks_json/galilean_3d_psatd_current_correction.json
  Regression/WarpX-tests.ini
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/AvgGalileanAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/AvgGalileanAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/GalileanAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/GalileanAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PMLPsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PMLPsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralSolver.H
  Source/FieldSolver/SpectralSolver/SpectralSolver.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: spectral, enhancement

#1235 swap fieldGather and external fields
  Docs/source/running_cpp/parameters.rst
  Source/Particles/Gather/GetExternalFields.H
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.cpp
Labels: bug, component: RZ

#1237 Do not use psatd.ny_guard in 2D and RZ
  Source/Parallelization/GuardCellManager.cpp
Labels: changes input script, component: RZ, component: spectral

#1240 RZ PSATD: rho diags must be cell-centered
  Source/Particles/WarpXParticleContainer.cpp
Labels: bug, bug: affects latest release, component: RZ, component: spectral

#1243 [mini]fix typo in doc
  Docs/source/running_cpp/parameters.rst
Labels: component: documentation

#1245 [mini]Updated doc for installation of RZ PSATD
  Docs/source/building/rzgeometry.rst
Labels: component: RZ, component: documentation, component: spectral

#1135 Make collision module doable for RZ
  Source/Particles/Collision/CollisionType.cpp
Labels: component: RZ, component: core

#1246 [mini]Fix RZ PSATD backward transform for icomp > 0
  Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.cpp
Labels: bug: affects latest release, component: RZ, component: spectral

#1248 Fix IO automated performance test
  Source/Diagnostics/Diagnostics.cpp
  Tools/PerformanceTests/functions_perftest.py
Labels: Performance optimization, component: diagnostics, component: tests

#1247 [mini]Fix for RZ PSATD backwards transform for GPU
  Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.cpp
Labels: component: RZ, component: spectral

#1254 [mini]Fix normalization factor on rho for RZ higher modes
  Regression/Checksum/benchmarks_json/LaserAccelerationRZ.json
  Source/Particles/Deposition/ChargeDeposition.H
Labels: bug: affects latest release, component: RZ

#1156 Remove Recursive Function from Parser
  CMakeLists.txt
  Docs/source/building/cmake.rst
  Source/Initialization/InjectorMomentum.H
  Source/Make.WarpX
  Source/Parser/GpuParser.H
  Source/Parser/WarpXParser.H
  Source/Parser/WarpXParser.cpp
  Source/Parser/wp_parser.l
  Source/Parser/wp_parser.lex.cpp
  Source/Parser/wp_parser_c.h
  Source/Parser/wp_parser_y.cpp
  Source/Parser/wp_parser_y.h
  Source/main.cpp
  cmake/WarpXFunctions.cmake
Labels: backend: cuda, backend: dpc++, component: core, warning

#1257 Add doc about how to provide a Coulomb logarithm for the collision module
  Docs/source/running_cpp/parameters.rst
Labels: component: documentation

#1239 Fix some warnings
  Source/BoundaryConditions/PML_current.H
  Source/BoundaryConditions/WarpX_PML_kernels.H
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/ComputeDiagFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/DivEFunctor.cpp
  Source/Diagnostics/FieldIO.cpp
  Source/Diagnostics/FlushFormats/FlushFormatAscent.cpp
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp
  Source/Diagnostics/FlushFormats/FlushFormatSensei.H
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/ReducedDiags/BeamRelevant.cpp
  Source/Diagnostics/ReducedDiags/FieldEnergy.cpp
  Source/Diagnostics/ReducedDiags/LoadBalanceCosts.cpp
  Source/Diagnostics/ReducedDiags/MultiReducedDiags.cpp
  Source/Diagnostics/ReducedDiags/ReducedDiags.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianCKCAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianNodalAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianYeeAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/AvgGalileanAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PMLPsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralKSpace.H
  Source/FieldSolver/SpectralSolver/SpectralKSpace.cpp
  Source/FieldSolver/SpectralSolver/SpectralSolver.H
  Source/FieldSolver/WarpX_FDTD.H
  Source/FieldSolver/WarpX_QED_K.H
  Source/Filter/NCIGodfreyFilter.cpp
  Source/Laser/LaserParticleContainer.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileFromTXYEFile.cpp
  Source/Parallelization/GuardCellManager.cpp
  Source/Parallelization/WarpXComm_K.H
  Source/Parallelization/WarpXRegrid.cpp
  Source/Parser/WarpXParser.cpp
  Source/Particles/Collision/CollisionType.cpp
  Source/Particles/Collision/ComputeTemperature.H
  Source/Particles/Collision/ElasticCollisionPerez.H
  Source/Particles/Collision/ShuffleFisherYates.H
  Source/Particles/ElementaryProcess/Ionization.H
  Source/Particles/Filter/FilterFunctors.H
  Source/Particles/Gather/FieldGather.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/UpdatePositionPhoton.H
  Source/Particles/ShapeFactors.H
  Source/Utils/Interpolate.cpp
  Source/Utils/IntervalsParser.cpp
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.cpp
Labels: cleaning, warning

#1259 [mini]For PICMI, added more arguments for psatd solver
  Python/pywarpx/picmi.py
Labels: component: PICMI, component: spectral

#1241 Defining geom object for diags
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/FullDiagnostics.H
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/ParticleDiag/ParticleDiag.H
  Source/Particles/Filter/FilterFunctors.H
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.H
Labels: bug, component: diagnostics

#1261 Add .editorconfig file
  .editorconfig
Labels: component: documentation

#1262 Add copyright headers when missing
  Regression/Checksum/benchmark.py
  Regression/Checksum/checksum.py
  Regression/Checksum/checksumAPI.py
  Regression/Checksum/config.py
  Source/FieldSolver/SpectralSolver/AnyFFT.H
  Source/FieldSolver/SpectralSolver/WrapCuFFT.cpp
  Source/FieldSolver/SpectralSolver/WrapFFTW.cpp
Labels: component: documentation, component: third party

#1252 [mini]Bug fix in ParticleListDistribution
  Python/pywarpx/picmi.py
Labels: bug: affects latest release, component: PICMI

#1276 Only tag particles for splitting when we change levels if splitting is on.
  Source/Particles/WarpXParticleContainer.cpp
Labels: component: mesh refinement
