Repository BLAST-WarpX/warpx, pull requests merged in 2020-09, with the labels that each got.

#1278 Update benchmarks for id changes
  Regression/Checksum/benchmarks_json/LaserAccelerationMR.json
  Regression/Checksum/benchmarks_json/PlasmaAccelerationMR.json
  Regression/Checksum/benchmarks_json/Python_PlasmaAccelerationMR.json
  Regression/Checksum/benchmarks_json/momentum-conserving-gather.json
  Regression/Checksum/benchmarks_json/subcyclingMR.json
Labels: component: tests

#1272 Remove ManagedVector from laser
  Source/Laser/LaserParticleContainer.cpp
  Source/Laser/LaserProfiles.H
  Source/Laser/LaserProfilesImpl/LaserProfileFieldFunction.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileFromTXYEFile.cpp
Labels: backend: cuda, component: core

#1263 Fix 🩹 (almost) all warnings ⚠️ with default configuration (DIM=3, openMP+MPI, double precision, no advanced solvers, no QED, native output)
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianCKCAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianYeeAlgorithm.H
  Source/Parser/wp_parser_c.h
  Source/Parser/wp_parser_y.cpp
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/GetAndSetPosition.H
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
Labels: cleaning, warning

#1275 Disable ParticleIO for slices
  Docs/source/running_cpp/parameters.rst
  Source/Diagnostics/Diagnostics.cpp
Labels: component: diagnostics

#1264 Fix 🩹(almost) all warnings ⚠️ with default configuration in 2D (DIM=2, openMP+MPI, double precision, no advanced solvers, no QED, native output)
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianCKCAlgorithm.H
  Source/Laser/LaserProfilesImpl/LaserProfileFromTXYEFile.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/UpdatePosition.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: cleaning, warning

#1274 Remove ManagedVector from Utils
  Source/Utils/CoarsenIO.H
  Source/Utils/CoarsenIO.cpp
  Source/Utils/CoarsenMR.H
  Source/Utils/CoarsenMR.cpp
Labels: backend: cuda, backend: dpc++, backend: hip

#1270 Remove ManagedVector from spectral solver
  Source/FieldSolver/SpectralSolver/SpectralBinomialFilter.H
  Source/FieldSolver/SpectralSolver/SpectralBinomialFilter.cpp
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/BesselRoots.H
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/HankelTransform.H
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/HankelTransform.cpp
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/SpectralHankelTransformer.cpp
  Source/FieldSolver/SpectralSolver/SpectralKSpace.H
  Source/FieldSolver/SpectralSolver/SpectralKSpace.cpp
Labels: backend: cuda, backend: dpc++, backend: hip, component: spectral

#1280 In AddNParticles, id should be changed to Long
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: component: core, warning

#1277 Remove unused methods from WarpXParticleContainer.
  Source/Particles/WarpXParticleContainer.H
Labels: cleaning

#1268 Remove ManagedDeviceVector from BackTransformDiagnostic
  Source/Diagnostics/BackTransformedDiagnostic.H
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.cpp
Labels: backend: cuda, backend: dpc++, backend: hip, component: diagnostics

#1282 [mini-PR] fix Implicit capture of 'this' in extended lambda expression in SpectralKSpace.cpp
  Source/FieldSolver/SpectralSolver/SpectralKSpace.cpp
Labels: backend: cuda, bug, bug: affects latest release, component: spectral

#1265 Add structure for resampling algorithms
  Source/Evolve/WarpXEvolve.cpp
  Source/Particles/CMakeLists.txt
  Source/Particles/Make.package
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Resampling/CMakeLists.txt
  Source/Particles/Resampling/LevelingThinning.H
  Source/Particles/Resampling/Make.package
  Source/Particles/Resampling/Resampling.H
  Source/Particles/Resampling/Resampling.cpp
  Source/Particles/Resampling/ResamplingTrigger.H
  Source/Particles/Resampling/ResamplingTrigger.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Utils/IntervalsParser.H
Labels: component: core

#1269 Remove ManagedVector from finite-difference solver
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianCKCAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianNodalAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianYeeAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CylindricalYeeAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.cpp
Labels: backend: cuda, backend: dpc++, backend: hip, component: core

#1281 Use Long for the pid type in ParticleCreation
  Source/Particles/ParticleCreation/SmartUtils.H
Labels: bug, bug: affects latest release, component: QED, component: core, component: load balancing

#1285 CI: DPC++ Re-Enable
  .github/workflows/ubuntu.yml
Labels: backend: dpc++, component: tests, workaround

#1267 Remove ManagedVector from PML
  Source/BoundaryConditions/PML.H
  Source/BoundaryConditions/PML.cpp
Labels: backend: cuda, backend: dpc++, backend: hip, component: core, component: diagnostics

#1271 Remove ManagedVector from filters
  Source/Filter/BilinearFilter.cpp
  Source/Filter/Filter.H
  Source/Filter/NCIGodfreyFilter.cpp
Labels: backend: cuda, backend: dpc++, backend: hip, component: core

#1286 Fix some warnings in RZ spectral solver
  Source/FieldSolver/SpectralSolver/SpectralBinomialFilter.H
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ.H
Labels: cleaning, warning

#1287 Bug fix in Div E computation for RZ PSATD
  Source/Diagnostics/ComputeDiagFunctors/DivEFunctor.cpp
Labels: bug, bug: affects latest release, component: RZ, component: spectral

#1292 [mini] Fix typo in documentation
  Docs/source/running_cpp/parameters.rst
Labels: cleaning, component: documentation

#1291 openPMD Mesh: Fix grid offset/spacing
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: bug, bug: affects latest release, component: openPMD

#1288 Fix some more warnings
  Source/Diagnostics/BackTransformedDiagnostic.H
  Source/Particles/Gather/ScaleFields.H
  Source/Particles/WarpXParticleContainer.H
  Source/Utils/NCIGodfreyTables.H
Labels: cleaning, warning

#1299 CKC: Use Enum instead consequently
  Source/BoundaryConditions/PML.cpp
  Source/Parallelization/GuardCellManager.cpp
Labels: cleaning, component: spectral

#1297 Gather: Rename Galerkin Varnames
  Source/Particles/Gather/FieldGather.H
Labels: cleaning, component: core

#1302 openPMD-api: 0.12.0+
  Docs/source/building/cmake.rst
  Docs/source/building/openpmd.rst
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Diagnostics/requirements.txt
  Source/Initialization/PlasmaInjector.cpp
  Source/Make.WarpX
  cmake/dependencies/openPMD.cmake
Labels: component: openPMD, component: third party

#1183 Make BeamRelevant reduced diagnostic doable for RZ
  Source/Diagnostics/ReducedDiags/BeamRelevant.cpp
Labels: component: diagnostics, enhancement

#1296 openPMD: Generalize Mesh Position
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Utils/CMakeLists.txt
  Source/Utils/Make.package
  Source/Utils/RelativeCellPosition.H
  Source/Utils/RelativeCellPosition.cpp
Labels: component: openPMD

#1273 Remove ManagedVector from Particles/
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
Labels: backend: cuda, backend: dpc++, backend: hip, component: core

#1016 Variation of macroscopic properties for E-update
  Docs/source/running_cpp/parameters.rst
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianCKCAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianYeeAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/FieldAccessorFunctors.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicEvolveE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.H
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/Initialization/WarpXInitData.cpp
Labels: component: core, enhancement

#1290 SpectralSolverRZ.H: Move Implementations to Source File
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ.H
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ.cpp
Labels: cleaning, component: RZ, component: spectral

#1314 DPCPP Beta09: Package Broken
  .github/workflows/ubuntu.yml
Labels: backend: dpc++, bug, component: third party, workaround

#1320 Clean up profiling labels
  Source/Diagnostics/ParticleIO.cpp
  Source/Diagnostics/WarpXIO.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.cpp
  Source/Filter/Filter.cpp
  Source/Laser/LaserParticleContainer.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Sorting/Partition.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/Utils/CoarsenIO.cpp
  Source/Utils/CoarsenMR.cpp
  Source/Utils/WarpXUtil.cpp
Labels: cleaning

#1318 [Mini]picmi: use kspace filter automatically for RZ PSATD
  Python/pywarpx/picmi.py
Labels: component: PICMI, component: RZ, component: spectral

#1307 Fix error with IntervalsParser and whitespaces
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Particles/Resampling/ResamplingTrigger.cpp
  Source/Utils/IntervalsParser.H
  Source/Utils/IntervalsParser.cpp
  Source/WarpX.cpp
Labels: bug, bug: affects latest release

#1306 PICMI analytic applied fields
  Python/pywarpx/Constants.py
  Python/pywarpx/picmi.py
  Python/setup.py
Labels: component: PICMI

#1324 Fix: new AMReX AoS Syntax
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: bug, component: openPMD, component: third party

#1317 [Mini]picmi: replaced warpx_n[xyz]_guard with grid.guard_cells
  Python/pywarpx/picmi.py
Labels: component: PICMI, component: spectral

#1283 Implement leveling thinning algorithm
  Source/Particles/Collision/CollisionType.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Resampling/CMakeLists.txt
  Source/Particles/Resampling/LevelingThinning.H
  Source/Particles/Resampling/LevelingThinning.cpp
  Source/Particles/Resampling/Make.package
  Source/Particles/Resampling/Resampling.H
  Source/Particles/Resampling/Resampling.cpp
  Source/Utils/CMakeLists.txt
  Source/Utils/Make.package
  Source/Utils/ParticleUtils.H
  Source/Utils/ParticleUtils.cpp
Labels: component: core, enhancement

#1313 Remove The_Managed_Arena
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.H
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.cpp
  Source/Initialization/CustomDensityProb.H
  Source/Initialization/InjectorDensity.H
  Source/Initialization/InjectorDensity.cpp
  Source/Initialization/InjectorMomentum.H
  Source/Initialization/InjectorMomentum.cpp
  Source/Initialization/InjectorPosition.H
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileFieldFunction.cpp
  Source/Parser/GpuParser.H
  Source/Parser/WarpXParserWrapper.H
  Source/Parser/wp_parser_c.h
  Source/Particles/Filter/FilterFunctors.H
  Source/Particles/Gather/GetExternalFields.H
  Source/Particles/Gather/GetExternalFields.cpp
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.H
Labels: backend: cuda, backend: dpc++, backend: hip, component: core

#1329 Fix: new AMReX AoS syntax (RZ)
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: bug: affects latest release

#1326 For PICMI, expect length 2 args for 2D solver
  Python/pywarpx/picmi.py
Labels: changes input script, component: PICMI

#1337 Docs: Add CMake Intro
  Docs/source/building/cmake.rst
Labels: component: documentation

#1344 CI: Disable DPC++ oneAPI beta08
  .github/workflows/ubuntu.yml
Labels: backend: dpc++, bug, component: tests, component: third party

#1310 Fix few compilation warnings (shift)
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicEvolveE.cpp
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Resampling/LevelingThinning.cpp
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning, warning

#1338 [Mini]picmi - implemented rigid advance species option
  Python/pywarpx/Particles.py
  Python/pywarpx/picmi.py
Labels: component: PICMI

#1341 [Mini]picmi - convert True/False to 1/0
  Examples/Physics_applications/plasma_acceleration/PICMI_inputs_plasma_acceleration_mr.py
  Examples/Tests/Langmuir/PICMI_inputs_langmuir_rz_multimode_analyze.py
  Python/pywarpx/Bucket.py
Labels: component: PICMI

#1336 run_tests.sh: cd locations
  run_test.sh
Labels: component: documentation, component: tests

#1298 MPI: Init or Thread Multiple
  CMakeLists.txt
  Docs/source/building/cmake.rst
  Source/Make.WarpX
  Source/Utils/CMakeLists.txt
  Source/Utils/MPIInitHelpers.H
  Source/Utils/MPIInitHelpers.cpp
  Source/Utils/Make.package
  Source/main.cpp
  cmake/WarpXFunctions.cmake
  cmake/dependencies/AMReX.cmake
Labels: component: core, component: spectral

#1350 [mini-PR] Fix unused variable ⚠️warning⚠️ when compiling with openPMD
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.H
Labels: cleaning, warning

#1349 Fix compile ⚠️warnings⚠️ for DIM=RZ
  Source/FieldSolver/FiniteDifferenceSolver/ComputeDivE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveB.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveBPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveEPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveF.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveFPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CylindricalYeeAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicEvolveE.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/Deposition/CurrentDeposition.H
Labels: cleaning, warning

#1198 Coupling WarpX with an ✨improved✨ version of the QED library
  Docs/source/running_cpp/parameters.rst
  Examples/Modules/qed/breit_wheeler/analysis.py
  Examples/Modules/qed/breit_wheeler/analysis_2d_tau_init.py
  Examples/Modules/qed/breit_wheeler/analysis_3d_optical_depth_evolution.py
  Examples/Modules/qed/breit_wheeler/inputs_2d
  Examples/Modules/qed/breit_wheeler/inputs_2d_tau_init
  Examples/Modules/qed/breit_wheeler/inputs_3d
  Examples/Modules/qed/breit_wheeler/inputs_3d_optical_depth_evolution
  Examples/Modules/qed/quantum_synchrotron/analysis.py
  Examples/Modules/qed/quantum_synchrotron/analysis_2d_tau_init.py
  Examples/Modules/qed/quantum_synchrotron/inputs_2d
  Examples/Modules/qed/quantum_synchrotron/inputs_2d_tau_init
  Examples/Modules/qed/quantum_synchrotron/inputs_3d
  Examples/Modules/qed/schwinger/analysis_schwinger.py
  Regression/Checksum/benchmarks_json/qed_breit_wheeler_2d.json
  Regression/Checksum/benchmarks_json/qed_breit_wheeler_3d.json
  Regression/Checksum/benchmarks_json/qed_breit_wheeler_opt_depth_evolution.json
  Regression/Checksum/benchmarks_json/qed_breit_wheeler_tau_init.json
  Regression/Checksum/benchmarks_json/qed_quantum_sync_2d.json
  Regression/Checksum/benchmarks_json/qed_quantum_sync_3d.json
  Regression/Checksum/benchmarks_json/qed_quantum_sync_tau_init.json
  Regression/Checksum/benchmarks_json/qed_schwinger2.json
  Regression/Checksum/benchmarks_json/qed_schwinger4.json
  Regression/WarpX-tests.ini
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerDummyTable.H
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineInnards.H
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineTableBuilder.H
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineTableBuilder.cpp
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineWrapper.H
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineWrapper.cpp
  Source/Particles/ElementaryProcess/QEDInternals/CMakeLists.txt
  Source/Particles/ElementaryProcess/QEDInternals/Make.package
  Source/Particles/ElementaryProcess/QEDInternals/QedChiFunctions.H
  Source/Particles/ElementaryProcess/QEDInternals/QedTableParserHelperFunctions.H
  Source/Particles/ElementaryProcess/QEDInternals/QedWrapperCommons.H
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncDummyTable.H
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineInnards.H
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineTableBuilder.H
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineTableBuilder.cpp
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineWrapper.H
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineWrapper.cpp
  Source/Particles/ElementaryProcess/QEDInternals/SchwingerProcessWrapper.H
  Source/Particles/ElementaryProcess/QEDPairGeneration.H
  Source/Particles/ElementaryProcess/QEDPhotonEmission.H
  Source/Particles/ElementaryProcess/QEDPhotonEmission.cpp
  Source/Particles/ElementaryProcess/QEDSchwingerProcess.H
  Source/Particles/Gather/ScaleFields.H
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/ParticleCreation/SmartCreate.H
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/PushSelector.H
  run_test.sh
Labels: changes input script, component: PICSAR, component: QED

#1342 openPMD build: HDF5 Env Hint
  Docs/source/building/openpmd.rst
Labels: component: documentation, component: openPMD

#1357 Intel DPC++: Beta09
  .github/workflows/ubuntu.yml
Labels: backend: dpc++, component: tests

#1355 Disable laser when e_max = 0
  Source/Laser/LaserParticleContainer.cpp
Labels: bug, bug: affects latest release, component: core

#1354 DiagnosticsToAccountForMovingWindowRestart
  Source/Diagnostics/Diagnostics.cpp
Labels: bug, bug: affects latest release

#1353 openPMD-api 0.12.0: Iteration::close()
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: component: openPMD, enhancement

#1362 CI: New MKL Package for DPC++
  .github/workflows/ubuntu.yml
Labels: backend: dpc++, component: tests

#1363 CI BlasPP/LapackPP: New CMake Flags
  .travis.yml
Labels: component: RZ, component: tests

#1365 Create reduced diag ouput file only with IO process
  Source/Diagnostics/ReducedDiags/ReducedDiags.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#1364 CI: Travis CI -> Azure Pipelines
  .azure-pipelines.yml
  .travis.yml
Labels: component: tests

#1359 Docs: QED in PICSAR development
  Docs/source/building/juwels.rst
  Docs/source/building/summit.rst
  Docs/source/running_cpp/parameters.rst
  Regression/WarpX-tests.ini
Labels: component: QED, component: documentation, component: tests

#1348 Docs: Spack Env
  .gitignore
  Docs/spack.yaml
Labels: component: documentation

#1304 Initial version of use_damp_fields_in_z_guard option
  Docs/source/running_cpp/parameters.rst
  Python/pywarpx/picmi.py
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: RZ, component: spectral

#1370 Docs: Boost 1.66.0+
  Docs/source/running_cpp/parameters.rst
Labels: component: documentation, component: third party

#1369 Summit: Doc I/O Module(s)
  Docs/source/building/summit.rst
Labels: component: documentation, machine / system

#1374 Docs: GNUmake single precision
  Docs/source/building/building.rst
Labels: component: documentation

#1372 [mini-PR] Fix a couple of warnings
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.H
  Source/Parser/GpuParser.H
Labels: cleaning, warning

#1356 [mini-PR] Fix a couple of new warnings
  Source/Particles/ParticleCreation/FilterCreateTransformFromFAB.H
  Source/Particles/PhotonParticleContainer.cpp
Labels: cleaning, warning

#1294 Dump rho per species
  Docs/source/running_cpp/parameters.rst
  Source/Diagnostics/ComputeDiagFunctors/RhoFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/RhoFunctor.cpp
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/ParticleDiag/ParticleDiag.cpp
  Source/WarpX.cpp
Labels: component: diagnostics, enhancement

#1375 SYCL 2020/DPC++: C++17
  Source/Make.WarpX
Labels: backend: dpc++, install

#1334 Option to have absorbing BC for particles, regardless of field BC
  Docs/source/running_cpp/parameters.rst
  Source/Evolve/WarpXEvolve.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: changes input script, component: core, enhancement

#1377 Summit: Doc Modules for RZ+PSATD
  Docs/source/building/summit.rst
Labels: component: documentation, install, machine / system

#1327 Add CI test and documentation for leveling thinning algorithm
  Docs/source/running_cpp/parameters.rst
  Examples/Modules/resampling/analysis_leveling_thinning.py
  Examples/Modules/resampling/inputs_leveling_thinning
  Regression/Checksum/benchmarks_json/leveling_thinning.json
  Regression/WarpX-tests.ini
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Resampling/LevelingThinning.H
  Source/Particles/Resampling/LevelingThinning.cpp
  Source/Particles/Resampling/Resampling.H
  Source/Particles/Resampling/Resampling.cpp
  Source/Particles/Resampling/ResamplingTrigger.H
  Source/Particles/Resampling/ResamplingTrigger.cpp
  Source/Particles/WarpXParticleContainer.H
Labels: component: core, component: documentation

#1376 Doc: Cori MPI Thread Multiple
  Tools/BatchScripts/batch_cori.sh
  Tools/BatchScripts/batch_cori_haswell.sh
Labels: component: documentation, machine / system

#988 New Diagnostics: FieldMaximum
  Docs/source/running_cpp/parameters.rst
  Examples/Tests/reduced_diags/analysis_reduced_diags.py
  Examples/Tests/reduced_diags/inputs
  Regression/WarpX-tests.ini
  Source/Diagnostics/ReducedDiags/CMakeLists.txt
  Source/Diagnostics/ReducedDiags/FieldEnergy.cpp
  Source/Diagnostics/ReducedDiags/FieldMaximum.H
  Source/Diagnostics/ReducedDiags/FieldMaximum.cpp
  Source/Diagnostics/ReducedDiags/Make.package
  Source/Diagnostics/ReducedDiags/MultiReducedDiags.cpp
  Source/Particles/MultiParticleContainer.cpp
Labels: changes input script, component: diagnostics

#1204 Laser-Ion Acceleration Example
  Docs/source/running_cpp/examples.rst
  Examples/Physics_applications/laser_ion/inputs
  Regression/Checksum/benchmarks_json/LaserIonAcc2d.json
  Regression/Checksum/benchmarks_json/LaserIonAcc3d.json
  Regression/WarpX-tests.ini
Labels: component: documentation

#1385 Add option to only resample cells with high enough number of macroparticles
  Docs/source/running_cpp/parameters.rst
  Examples/Modules/resampling/inputs_leveling_thinning
  Source/Particles/Resampling/LevelingThinning.H
  Source/Particles/Resampling/LevelingThinning.cpp
Labels: changes input script, component: core, enhancement

#1386 Apply style conventions to LaserParticleContainer
  Source/Laser/LaserParticleContainer.H
  Source/Laser/LaserParticleContainer.cpp
Labels: cleaning

#1391 [mini] Fix error in FieldMaximum reduced diag in 2D
  Source/Diagnostics/ReducedDiags/FieldMaximum.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#1389 Implement intervals parser for reduced diagnostics
  Docs/source/running_cpp/parameters.rst
  Source/Diagnostics/ReducedDiags/BeamRelevant.cpp
  Source/Diagnostics/ReducedDiags/FieldEnergy.cpp
  Source/Diagnostics/ReducedDiags/FieldMaximum.cpp
  Source/Diagnostics/ReducedDiags/LoadBalanceCosts.cpp
  Source/Diagnostics/ReducedDiags/MultiReducedDiags.cpp
  Source/Diagnostics/ReducedDiags/ParticleEnergy.cpp
  Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp
  Source/Diagnostics/ReducedDiags/ReducedDiags.H
  Source/Diagnostics/ReducedDiags/ReducedDiags.cpp
Labels: changes input script, component: diagnostics

#1383 Minor modification of Visualization.ipynb
  Tools/PostProcessing/Visualization.ipynb
Labels: component: post-processing

#1397 [mini-PR] remove extra ;
  Source/Python/WarpXWrappers.cpp
Labels: cleaning, warning

#1393 CI: Output CPU Type
  .azure-pipelines.yml
Labels: component: tests

#1379 Remove instability on PML with do_nodal
  Source/BoundaryConditions/PML.cpp
Labels: bug, bug: affects latest release, component: core

#1368 Use fewer guard cells for deposition
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/Parallelization/GuardCellManager.H
  Source/Parallelization/GuardCellManager.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/WarpX.H
Labels: Performance optimization, backend: openmp, component: spectral
