Repository BLAST-WarpX/warpx, pull requests merged in 2021-10, with the labels that each got.

#2367 Docs PoP: Fix Co-Authors
  Docs/source/acknowledge_us.rst
Labels: component: documentation

#2360 Implement Checkpoint / Restart for Laser Particles
  Examples/Tests/restart/inputs
  Regression/Checksum/benchmarks_json/restart.json
  Regression/Checksum/benchmarks_json/restart_psatd.json
  Regression/Checksum/benchmarks_json/restart_psatd_time_avg.json
  Regression/WarpX-tests.ini
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/ParticleIO.cpp
  Source/Particles/LaserParticleContainer.H
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/WarpXParticleContainer.H
Labels: bug, bug: affects latest release, component: core, component: checkpoint/restart

#2370 Release 21.10
  CMakeLists.txt
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#2217 Add structure for proton-boron fusion module
  Docs/source/usage/parameters.rst
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
  Source/Particles/Collision/BinaryCollision/BinaryCollisionUtils.H
  Source/Particles/Collision/BinaryCollision/BinaryCollisionUtils.cpp
  Source/Particles/Collision/BinaryCollision/CMakeLists.txt
  Source/Particles/Collision/BinaryCollision/ComputeTemperature.H
  Source/Particles/Collision/BinaryCollision/ElasticCollisionPerez.H
  Source/Particles/Collision/BinaryCollision/Make.package
  Source/Particles/Collision/BinaryCollision/NuclearFusionFunc.H
  Source/Particles/Collision/BinaryCollision/PairWiseCoulombCollisionFunc.H
  Source/Particles/Collision/BinaryCollision/ParticleCreationFunc.H
  Source/Particles/Collision/BinaryCollision/ParticleCreationFunc.cpp
  Source/Particles/Collision/BinaryCollision/ShuffleFisherYates.H
  Source/Particles/Collision/BinaryCollision/UpdateMomentumPerezElastic.H
  Source/Particles/Collision/BinaryCollisionUtils.H
  Source/Particles/Collision/CMakeLists.txt
  Source/Particles/Collision/CollisionHandler.H
  Source/Particles/Collision/CollisionHandler.cpp
  Source/Particles/Collision/Make.package
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/SpeciesPhysicalProperties.H
  Source/Particles/WarpXParticleContainer.H
Labels: component: core, component: collisions

#2303 Electrostatic boundary condition handling refactor
  Source/FieldSolver/ElectrostaticSolver.H
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: electrostatic, changes input scripts / defaults, component: boundary

#2371 CI: NVHPC (CUDA)
  .github/workflows/cuda.yml
  .github/workflows/dependencies/nvhpc.sh
Labels: backend: cuda, component: tests

#2376 Capitalize python environment variables in CI workflows
  .github/workflows/cuda.yml
  .github/workflows/hip.yml
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  Docs/source/install/hpc/cori.rst
  Docs/source/install/hpc/summit.rst
Labels: component: tests

#2379 CI: mpi4py NVHPC work-around
  .github/workflows/cuda.yml
Labels: component: tests, component: Python, workaround

#2372 Docs: Simplify Release Log
  Docs/source/maintenance/release.rst
Labels: component: documentation

#2430 FieldProbe using Particle
  Docs/source/usage/parameters.rst
  Examples/Tests/reduced_diags/inputs
  Source/Diagnostics/ReducedDiags/CMakeLists.txt
  Source/Diagnostics/ReducedDiags/FieldProbe.H
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
  Source/Diagnostics/ReducedDiags/FieldProbeParticleContainer.H
  Source/Diagnostics/ReducedDiags/FieldProbeParticleContainer.cpp
  Source/Diagnostics/ReducedDiags/Make.package
  Source/Diagnostics/ReducedDiags/MultiReducedDiags.H
  Source/Diagnostics/ReducedDiags/MultiReducedDiags.cpp
  Source/Diagnostics/ReducedDiags/ReducedDiags.H
  Source/Diagnostics/ReducedDiags/ReducedDiags.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/WarpXRegrid.cpp
Labels: component: diagnostics, component: RZ

#2410 Add option to specificy absolute tolerance for the MLMG solver
  Docs/source/usage/parameters.rst
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/background_mcc.json
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: electrostatic
