Repository BLAST-WarpX/warpx, pull requests merged in 2021-04, with the labels that each got.

#1855 fix bx used in amrexParallelFor
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#1856 Move KernelTimer to Parallelization
  Source/Parallelization/KernelTimer.H
  Source/Particles/Deposition/CurrentDeposition.H
Labels: cleaning

#1845 More Output In `checksum.py` When Checksum Benchmarks Fail
  Regression/Checksum/checksum.py
Labels: component: tests

#1853 CMake: Move CCache Message
  cmake/WarpXFunctions.cmake
Labels: cleaning, install

#1859 Add Time-Averaged Fields To Raw Fields Output
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/WarpX.H
Labels: component: diagnostics

#1861 FlushFormatOpenPMD: Cleanup
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.H
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
Labels: cleaning, component: diagnostics, component: openPMD

#1860 paraview.pmd: write on close
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: bug, component: diagnostics, component: openPMD, component: third party

#1858 User input for buffer size
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/BackTransformedDiagnostic.H
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/ComputeDiagFunctor.H
Labels: Performance optimization, component: diagnostics

#1862 Initialize BTD buffer with 0 values
  Source/Diagnostics/BTDiagnostics.cpp
Labels: component: diagnostics

#1865 Release 21.04
  CMakeLists.txt
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#1451 PSATD: use number of guard cells from input file in PMLs
  Source/BoundaryConditions/PML.cpp
Labels: changes input script, component: spectral

#1870 Fix No-MPI Build Warning
  Source/Utils/MPIInitHelpers.cpp
Labels: cleaning, warning

#1866 zenodo.json: fix syntax
  .zenodo.json
Labels: bug, bug: affects latest release, component: documentation

#1838 Compile-time option to use `algo.load_balance_costs_update = gpuclock`
  CMakeLists.txt
  Docs/source/install/cmake.rst
  Docs/source/usage/parameters.rst
  GNUmakefile
  Source/Make.WarpX
  Source/Parallelization/KernelTimer.H
  Source/Particles/Deposition/CurrentDeposition.H
  cmake/WarpXFunctions.cmake
Labels: Performance optimization, backend: cuda, backend: hip, component: load balancing

#1854 Parser: Bessel Function (J_n)
  Source/Parser/wp_parser.l
  Source/Parser/wp_parser.lex.cpp
  Source/Parser/wp_parser_y.cpp
  Source/Parser/wp_parser_y.h
Labels: component: core

#1874 Allow expressions for my_constants
  Docs/source/usage/parameters.rst
  Examples/Tests/Langmuir/inputs_2d_multi_rt
  Examples/Tests/Langmuir/inputs_2d_multi_rz_rt
  Examples/Tests/Langmuir/inputs_3d_multi_rt
  Regression/Checksum/benchmarks_json/Langmuir_multi.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_2d_nodal.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_nodal.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_psatd.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_psatd_current_correction.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_psatd_current_correction_nodal.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_psatd_momentum_conserving.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_psatd_nodal.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_psatd_single_precision.json
  Source/Utils/WarpXUtil.cpp
Labels: enhancement

#1880 Regenerate parser with option "noinput"
  Source/Parser/wp_parser.l
  Source/Parser/wp_parser.lex.cpp
  Source/Parser/wp_parser.tab.cpp
  Source/Parser/wp_parser.tab.h
Labels: cleaning, warning

#1879 Remove ununsed private variable `m_update_with_rho` in `ComovingPsatdAlgorithm`
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/ComovingPsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/ComovingPsatdAlgorithm.cpp
Labels: cleaning, component: spectral, warning

#1877 Docs: Add Developer Dependencies
  Docs/source/install/dependencies.rst
Labels: component: documentation, component: tests, install

#1876 Jn: first arg int
  Source/Parser/wp_parser_y.h
Labels: warning

#1873 Abort If More Guard Cells Than Valid Cells
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
Labels: component: parallelization

#1872 Parser: Abort on NaN/Inf Results
  .github/workflows/dependencies/hip.sh
  Source/Parser/wp_parser_c.h
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: changes input script, component: third party, enhancement

#1878 Docs: How To Read Raw Data With Guard Cells
  Docs/source/dataanalysis/advanced.rst
  Docs/source/usage/parameters.rst
Labels: component: documentation

#1884 Sphinx: limit docutils to 0.16
  Docs/requirements.txt
Labels: bug, component: documentation, component: third party

#1882 Docs: Document CMAKE_VERBOSE_MAKEFILES
  Docs/source/install/cmake.rst
Labels: component: documentation, install

#1885 Fix Out-Of-Bound Access In Some Interpolation Functions
  Source/Parallelization/WarpXComm_K.H
Labels: bug, bug: affects latest release, component: interpolation, component: mesh refinement

#1886 Fix printf format in Parser
  Source/Parser/wp_parser_c.h
Labels: bug

#1888 Fix QED Build (CUDA 10.0.130)
  Source/Particles/ElementaryProcess/QEDSchwingerProcess.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/ParticleCreation/FilterCreateTransformFromFAB.H
Labels: backend: cuda, bug, bug: affects latest release, component: QED

#1816 Add a delay to laser profile read from "txye" file
  Docs/source/usage/parameters.rst
  Examples/Modules/laser_injection_from_file/inputs.2d_test_txye
  Source/Laser/LaserProfiles.H
  Source/Laser/LaserProfilesImpl/LaserProfileFromTXYEFile.cpp
Labels: enhancement

#1807 Add an option to skip deposition in the `Evolve` function ; use it for electrostatic
  Source/Evolve/WarpXEvolve.cpp
  Source/Particles/LaserParticleContainer.H
  Source/Particles/LaserParticleContainer.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhotonParticleContainer.H
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.H
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/WarpX.H
Labels: component: electrostatic

#1768 Boundary Condition : Interface with existing PML
  Docs/source/usage/parameters.rst
  Examples/Modules/gaussian_beam/PICMI_inputs_gaussian_beam.py
  Examples/Physics_applications/laser_ion/inputs
  Examples/Physics_applications/plasma_acceleration/PICMI_inputs_plasma_acceleration.py
  Examples/Physics_applications/plasma_mirror/inputs_2d
  Source/BoundaryConditions/PML.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Utils/WarpXAlgorithmSelection.H
  Source/Utils/WarpXAlgorithmSelection.cpp
  Source/Utils/WarpXUtil.cpp
  Source/WarpX.cpp
Labels: changes input script, component: boundary

#1887 Hybrid Galilean: Same Guard Cells in z as Nodal
  Regression/Checksum/benchmarks_json/averaged_galilean_2d_psatd_hybrid.json
  Regression/Checksum/benchmarks_json/averaged_galilean_3d_psatd_hybrid.json
  Regression/Checksum/benchmarks_json/galilean_hybrid_2d.json
  Source/Parallelization/GuardCellManager.cpp
Labels: component: parallelization, component: spectral

#1894 openPMD: fix additional real components (e.g., optical depths)
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: bug, bug: affects latest release, component: diagnostics, component: openPMD

#1600 Divergence cleaning for PSATD in PML
  Docs/source/usage/parameters.rst
  Examples/Tests/PML/inputs_3d
  Regression/Checksum/benchmarks_json/pml_psatd_dive_divb_cleaning.json
  Regression/WarpX-tests.ini
  Source/BoundaryConditions/PML.H
  Source/BoundaryConditions/PML.cpp
  Source/BoundaryConditions/WarpXEvolvePML.cpp
  Source/BoundaryConditions/WarpX_PML_kernels.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PMLPsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PMLPsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldData.H
  Source/FieldSolver/SpectralSolver/SpectralSolver.H
  Source/FieldSolver/SpectralSolver/SpectralSolver.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: boundary, component: spectral

#1897 Remove outdated abort and add LB PSATD regression test
  Regression/Checksum/benchmarks_json/reduced_diags_loadbalancecosts_timers_psatd.json
  Regression/WarpX-tests.ini
  Source/Evolve/WarpXEvolve.cpp
Labels: component: load balancing

#1889 AMReX/PICSAR: Weekly Update
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
Labels: component: third party

#1903 Fix logic error when load balancing with more than 1 level.
  Source/Parallelization/WarpXRegrid.cpp
Labels: bug: affects latest release, component: load balancing, component: mesh refinement

#1904 Fix LoadBalance + MR: Rebuild Particle Masks
  Source/Parallelization/WarpXRegrid.cpp
Labels: bug, bug: affects latest release, component: load balancing, component: mesh refinement

#1906 Add Silver-Mueller boundaries along z, for the RZ version of the code
  Examples/Tests/SilverMueller/inputs_rz_z
  Regression/Checksum/benchmarks_json/silver_mueller_rz_z.json
  Regression/WarpX-tests.ini
  Source/FieldSolver/FiniteDifferenceSolver/ApplySilverMuellerBoundary.cpp
Labels: component: RZ, component: boundary, enhancement

#1899 AMReX: CMake IntelLLVM
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: backend: dpc++, install

#1907 Fix Silver-Mueller boundary: cell ratio
  Regression/Checksum/benchmarks_json/silver_mueller_2d_x.json
  Regression/Checksum/benchmarks_json/silver_mueller_2d_z.json
  Source/FieldSolver/FiniteDifferenceSolver/ApplySilverMuellerBoundary.cpp
Labels: bug, bug: affects latest release, component: boundary

#1910 Docs: Update Release Git
  Docs/source/maintenance/release.rst
Labels: component: documentation

#1912 Nightly Setups: Spack + CUDA
  azure-pipelines.yml
Labels: backend: cuda, component: tests, install

#1881 Staircased embedded boundaries in the YEE solver
  Examples/Modules/embedded_boundary_cube/analysis_fields.py
  Examples/Modules/embedded_boundary_cube/inputs_3d
  Regression/Checksum/benchmarks_json/embedded_boundary_cube.json
  Regression/WarpX-tests.ini
  Source/EmbeddedBoundary/WarpXInitEB.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveB.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: boundary, enhancement

#1913 Improve Analysis Script To Test Reduced Diagnostics
  Examples/Tests/reduced_diags/analysis_reduced_diags.py
Labels: component: tests

#1918 Ensure the geometry.coord_sys == 1 for RZ
  Examples/Tests/ElectrostaticSphere/inputs_rz
  Source/Utils/WarpXUtil.cpp
Labels: component: RZ

#1920 Fix Two Warnings for Builds Without EB
  Source/FieldSolver/FiniteDifferenceSolver/EvolveB.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveE.cpp
Labels: cleaning

#1911 Docs: Particle Injection in MR
  Docs/source/usage/parameters.rst
Labels: component: documentation, component: mesh refinement

#1922 [mini] Fix indentation when evolving QSR optical depth
  Source/Particles/PhysicalParticleContainer.cpp
Labels: cleaning, component: QED

#1925 Fix the skip deposition option
  Source/Particles/MultiParticleContainer.cpp
Labels: bug, component: electrostatic
