Repository BLAST-WarpX/warpx, pull requests merged in 2021-08, with the labels that each got.

#2153 Remove predefined constants from example input files
  Examples/Modules/embedded_boundary_cube/inputs_3d
  Examples/Modules/resampling/inputs_leveling_thinning
  Examples/Physics_applications/plasma_acceleration/inputs_2d_boost
  Examples/Physics_applications/plasma_acceleration/inputs_3d_boost
  Examples/Tests/Maxwell_Hybrid_QED/inputs_2d
  Examples/Tests/restart/inputs
  Tools/LibEnsemble/sim/inputs
Labels: cleaning

#2152 BTD_ReducedSliceDiag: BTD Plotfiles
  Examples/Modules/boosted_diags/inputs_3d_slice
Labels: bug, bug: affects latest release, component: diagnostics, component: tests

#2115 Allow extra particle attributes (besides ux, uy, uz and w) to be set at particle creation in AddNParticles()
  Examples/Tests/ParticleDataPython/PICMI_inputs_2d.py
  Examples/Tests/ParticleDataPython/analysis.py
  Python/pywarpx/_libwarpx.py
  Regression/WarpX-tests.ini
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/Python/WarpXWrappers.cpp
  Source/Python/WarpXWrappers.h
Labels: bug, component: Python

#2155 Add predefined density profile to parameters documentation
  Docs/source/usage/parameters.rst
Labels: component: documentation

#2159 Initialize guard cells for spatially varying macroproperties
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.cpp
Labels: bug, bug: affects latest release, component: FDTD, component: core

#2160 openPMD: Style Cleaning (Dec/Def)
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: cleaning, component: openPMD

#2157 openPMD: Use Steps if != BTD
  Docs/source/developers/gnumake/openpmd.rst
  Docs/source/install/dependencies.rst
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Diagnostics/requirements.txt
  Source/Make.WarpX
  cmake/dependencies/openPMD.cmake
Labels: component: openPMD

#2162 openPMD: Missing Include
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: bug, bug: affects latest release, component: diagnostics, component: openPMD

#2165 PEC Analysis: Remove Unused Imports
  Examples/Tests/PEC/analysis_pec.py
  Examples/Tests/PEC/analysis_pec_mr.py
Labels: component: tests, cleaning

#2137 BinaryCollision: use more general particle data structure
  Source/Particles/Collision/BinaryCollision.H
  Source/Particles/Collision/ElasticCollisionPerez.H
  Source/Particles/Collision/PairWiseCoulombCollisionFunc.H
  Source/Particles/Pusher/GetAndSetPosition.H
Labels: component: collisions

#2163 Added B field to plasma lens
  Examples/Tests/plasma_lens/analysis.py
  Examples/Tests/plasma_lens/inputs_3d
  Regression/Checksum/benchmarks_json/Plasma_lens.json
  Source/Particles/Gather/GetExternalFields.H
  Source/Particles/Gather/GetExternalFields.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
Labels: enhancement

#2167 Python: write_dir ignored for particle diagnostics
  Python/pywarpx/picmi.py
Labels: bug, bug: affects latest release, component: diagnostics, component: Python

#2161 Add particle weight as an explicit argument for _libwarpx.py::add_particles()
  Python/pywarpx/_libwarpx.py
Labels: component: Python

#2141 RZ PSATD: Time Averaging for Multi-J Algorithm
  Examples/Tests/multi_J/inputs_rz
  Regression/Checksum/benchmarks_json/multi_J_rz_psatd.json
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.cpp
Labels: component: spectral, component: RZ

#2128 Shift parsing of physical/mathematical constants from hard-coding to table lookup
  Source/Utils/WarpXConst.H
  Source/Utils/WarpXUtil.cpp
Labels: cleaning

#2168 Moved some ParticleBoundaries routines to .cpp file
  Source/Particles/CMakeLists.txt
  Source/Particles/Make.package
  Source/Particles/MultiParticleContainer.H
  Source/Particles/ParticleBoundaries.H
  Source/Particles/ParticleBoundaries.cpp
Labels: cleaning

#2169 In add_particles, used None for input parameter values
  Python/pywarpx/_libwarpx.py
Labels: cleaning, component: Python

#2171 More cleanup of particle boundaries
  Source/Particles/ParticleBoundaries.H
  Source/Particles/ParticleBoundaries_K.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: cleaning

#2173 Gaussian Laser: fix issue related to single precision
  Source/Laser/LaserProfilesImpl/LaserProfileGaussian.cpp
Labels: bug, bug: affects latest release, component: core

#2174 ES Solver: Fix HIP SP Build
  Source/FieldSolver/ElectrostaticSolver.cpp
Labels: bug, component: electrostatic, bug: affects latest release, backend: hip, component: boundary

#2176 EB: RZ Warnings
  Source/EmbeddedBoundary/DistanceToEB.H
Labels: warning, component: RZ, component: boundary

#2178 Fix: Performance Tests (Boundary)
  Tools/PerformanceTests/automated_test_1_uniform_rest_32ppc
  Tools/PerformanceTests/automated_test_2_uniform_rest_1ppc
  Tools/PerformanceTests/automated_test_3_uniform_drift_4ppc
  Tools/PerformanceTests/automated_test_4_labdiags_2ppc
  Tools/PerformanceTests/automated_test_5_loadimbalance
  Tools/PerformanceTests/automated_test_6_output_2ppc
Labels: component: tests, changes input scripts / defaults

#2179 CI: Cover Performance Tests
  Examples/Tests/PerformanceTests/automated_test_1_uniform_rest_32ppc
  Examples/Tests/PerformanceTests/automated_test_2_uniform_rest_1ppc
  Examples/Tests/PerformanceTests/automated_test_3_uniform_drift_4ppc
  Examples/Tests/PerformanceTests/automated_test_4_labdiags_2ppc
  Examples/Tests/PerformanceTests/automated_test_5_loadimbalance
  Examples/Tests/PerformanceTests/automated_test_6_output_2ppc
  Regression/WarpX-tests.ini
Labels: Performance optimization, component: tests

#2184 AMReX/PICSAR: Weekly Update
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#2182 Updated documentation for the plasma lens
  Docs/source/usage/parameters.rst
Labels: component: documentation

#2186 [mini-PR] Radiation Reaction : fix issue in single precision
  Source/Particles/Pusher/UpdateMomentumBorisWithRadiationReaction.H
Labels: bug, component: QED, bug: affects latest release

#2180 Work-Around: ROCm/rocFFT <=4.3.0
  Source/FieldSolver/SpectralSolver/AnyFFT.H
  Source/main.cpp
Labels: bug, component: third party, backend: hip, workaround

#2185 Docs: Turner Example Calibration Data
  Docs/source/usage/examples.rst
Labels: component: documentation

#2189 openPMD: Fix GetIteration
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: bug, component: openPMD, bug: affects latest release, component: diagnostics

#2190 For plasma lens, mapped particle to lab frame
  Docs/source/usage/parameters.rst
  Source/Particles/Gather/GetExternalFields.H
  Source/Particles/Gather/GetExternalFields.cpp
Labels: bug, component: core

#2193 WarpX::Version: Not Empty
  Source/WarpX.cpp
Labels: bug, bug: affects latest release, component: core, component: diagnostics

#2187 Implemented new style BTD in picmi
  Python/pywarpx/picmi.py
Labels: enhancement, component: PICMI, component: diagnostics

#2194 Docs: Fix Cori URL (404)
  Docs/source/install/hpc/cori.rst
Labels: component: documentation, machine / system

#2197 Print "re-sorting particles" only in verbose
  Source/Evolve/WarpXEvolve.cpp
Labels: cleaning, component: core

#2195 Docs: Summit Ascent Moved
  Docs/source/install/hpc/summit.rst
Labels: component: documentation, component: third party, machine / system, component: diagnostics

#2199 AMReX/PICSAR: Weekly Update
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#2183 do_pml should not be parsed anymore.
  Docs/source/dataanalysis/inputs.2d
  Docs/source/usage/parameters.rst
  Examples/Physics_applications/plasma_acceleration/PICMI_inputs_plasma_acceleration_mr.py
  Examples/Tests/Langmuir/PICMI_inputs_langmuir_rz_multimode_analyze.py
  Examples/Tests/SilverMueller/inputs_2d_x
  Examples/Tests/SilverMueller/inputs_2d_z
  Examples/Tests/SilverMueller/inputs_rz_z
  Examples/Tests/boundaries/inputs_3d
  Examples/Tests/galilean/inputs_rz
  Examples/Tests/multi_J/inputs_rz
  Examples/Tests/photon_pusher/analysis_photon_pusher.py
  Examples/Tests/plasma_lens/inputs_3d
  Examples/Tests/radiation_reaction/test_const_B_analytical/analysis_classicalRR.py
  Examples/Tests/radiation_reaction/test_const_B_analytical/inputs_3d
  Python/pywarpx/picmi.py
  Source/WarpX.H
  Source/WarpX.cpp
  Tools/PerformanceTests/automated_test_1_uniform_rest_32ppc
  Tools/PerformanceTests/automated_test_2_uniform_rest_1ppc
  Tools/PerformanceTests/automated_test_3_uniform_drift_4ppc
  Tools/PerformanceTests/automated_test_4_labdiags_2ppc
  Tools/PerformanceTests/automated_test_5_loadimbalance
  Tools/PerformanceTests/automated_test_6_output_2ppc
Labels: changes input scripts / defaults, component: boundary

#2181 Multi-J (Hybrid): Fix Bug with Current Centering
  Source/Evolve/WarpXEvolve.cpp
Labels: bug, component: spectral, bug: affects latest release

#2144 Use less guard cells in ParallelCopy of refined level's UpdateAuxilaryData
  Source/Parallelization/WarpXComm.cpp
Labels: bug, component: mesh refinement, bug: affects latest release, component: parallelization

#2191 Update Scripts: .ini file
  Tools/Release/updateAMReX.py
  Tools/Release/updatePICSAR.py
Labels: component: documentation, component: tests

#2202 CI: Cancel Prev. GH Action on Push
  .github/workflows/cuda.yml
  .github/workflows/hip.yml
  .github/workflows/intel.yml
  .github/workflows/macos.yml
  .github/workflows/source.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
Labels: component: tests

#2150 openPMD-api: 0.14.2
  .azure-pipelines.yml
  .github/workflows/cuda.yml
  .github/workflows/intel.yml
  .lgtm.yml
  Docs/source/dataanalysis/paraview.rst
  Docs/source/developers/gnumake/openpmd.rst
  Docs/source/install/cmake.rst
  Docs/source/install/dependencies.rst
  Docs/source/install/hpc/summit.rst
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
  Source/Diagnostics/requirements.txt
  Source/Make.WarpX
  cmake/dependencies/openPMD.cmake
  setup.py
Labels: component: openPMD

#2192 update use-sensei flag
  CMakeLists.txt
  Docs/Doxyfile
  Docs/source/install/cmake.rst
  Source/BoundaryConditions/WarpXEvolvePML.cpp
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FlushFormats/CMakeLists.txt
  Source/Diagnostics/FlushFormats/FlushFormatSensei.H
  Source/Diagnostics/FlushFormats/FlushFormatSensei.cpp
  Source/Diagnostics/WarpXIO.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/FieldSolver/WarpX_QED_Field_Pushers.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.cpp
  cmake/WarpXFunctions.cmake
  cmake/dependencies/AMReX.cmake
Labels: component: diagnostics

#2203 Rho Diags: Do Not Allocate `rho_fp/cp`, Remove `plot_rho`, `setplot_rho`
  Regression/Checksum/benchmarks_json/LaserAccelerationBoost.json
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: Performance optimization, cleaning, component: diagnostics

#2207 Bug fixed: looping over all species now within `OneStep_multiJ`
  Source/Particles/MultiParticleContainer.cpp
Labels: bug, component: spectral, bug: affects latest release

#2138 Implemented the parsing of integer input parameters
  Docs/source/usage/parameters.rst
  Examples/Tests/Langmuir/inputs_3d_multi_rt
  Source/Utils/WarpXUtil.H
  Source/Utils/WarpXUtil.cpp
  Source/WarpX.cpp
Labels: enhancement

#2214 Ionization.H: Fix Bug (Division by Zero)
  Source/Particles/ElementaryProcess/Ionization.H
Labels: bug, bug: affects latest release, component: core

#2212 Add plot_raw_rho in parameters doc
  Docs/source/usage/parameters.rst
Labels: component: documentation

#2216 Docs: Summit with RHEL8
  Docs/source/install/hpc/summit.rst
Labels: component: documentation, machine / system

#2215 Improved error handling when the libwarpx shared object library can't be loaded
  Python/pywarpx/_libwarpx.py
Labels: component: Python

#2218 Updated the installation instructions
  Python/pywarpx/_libwarpx.py
Labels: component: documentation, component: Python

#2220 Allow Silver-Mueller boundary conditions to only be applied in certain directions
  Examples/Tests/SilverMueller/inputs_2d_x
  Regression/Checksum/benchmarks_json/silver_mueller_2d_x.json
  Source/BoundaryConditions/WarpXFieldBoundaries.cpp
  Source/FieldSolver/FiniteDifferenceSolver/ApplySilverMuellerBoundary.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/Utils/WarpXUtil.cpp
Labels: component: boundary

#2201 Plasma lens - transform fields from lab to boosted frame
  Source/Particles/Gather/GetExternalFields.H
  Source/Particles/Gather/GetExternalFields.cpp
  Source/Particles/MultiParticleContainer.cpp
Labels: enhancement

#2213 Evolve: Reorder py_afterstep and cur_time break
  Source/Evolve/WarpXEvolve.cpp
Labels: component: Python

#2219 Docs: Cori PICMI Instructions
  Docs/source/install/hpc/cori.rst
Labels: component: documentation, machine / system, component: Python

#2136 No particle resorting when no species
  Source/WarpX.cpp
Labels: component: parallelization

#2222 AMReX/PICSAR: Weekly Update
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#2208 Check for unused WarpX environment variables when compiling
  setup.py
Labels: install, component: Python

#2204 Ascent/SENSEI: Add Profiler
  Source/Diagnostics/FlushFormats/FlushFormatAscent.cpp
  Source/Diagnostics/FlushFormats/FlushFormatSensei.cpp
Labels: component: diagnostics

#1367 Enable restart with PSATD
  Examples/Tests/restart/analysis_restart.py
  Regression/Checksum/benchmarks_json/restart_psatd.json
  Regression/WarpX-tests.ini
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/WarpXIO.cpp
  Source/Initialization/WarpXInitData.cpp
Labels: component: spectral, component: checkpoint/restart

#1811 Use the function `SyncRho` and the array `rho_fp` in the Electrostatic solver
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/WarpX.cpp
Labels: component: electrostatic

#2225 Avoid an NaN in collision module
  Source/Particles/Collision/ElasticCollisionPerez.H
Labels: cleaning, component: collisions

#2227 Docs: Fix Summit Python
  Docs/source/install/hpc/summit.rst
Labels: bug, component: documentation, machine / system

#2230 WarpXComm.cpp: Fix Bug (Uninitialized MultiFabs)
  Source/Parallelization/WarpXComm.cpp
Labels: bug, component: parallelization

#2228 Alphabetize and add PR to glossary
  Docs/source/glossary.rst
Labels: component: documentation

#2226 Fix: Missing Include Guards (FWD)
  Source/BoundaryConditions/PML_fwd.H
  Source/Diagnostics/BackTransformedDiagnostic_fwd.H
  Source/Diagnostics/ComputeDiagFunctors/ComputeDiagFunctor_fwd.H
  Source/Diagnostics/FlushFormats/FlushFormat_fwd.H
  Source/Diagnostics/MultiDiagnostics_fwd.H
  Source/Diagnostics/ParticleDiag/ParticleDiag_fwd.H
  Source/Diagnostics/ReducedDiags/MultiReducedDiags_fwd.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver_fwd.H
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties_fwd.H
  Source/FieldSolver/SpectralSolver/SpectralFieldData_fwd.H
  Source/FieldSolver/SpectralSolver/SpectralKSpace_fwd.H
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ_fwd.H
  Source/FieldSolver/SpectralSolver/SpectralSolver_fwd.H
  Source/Filter/NCIGodfreyFilter_fwd.H
  Source/Initialization/InjectorPosition_fwd.H
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineWrapper_fwd.H
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineWrapper_fwd.H
  Source/Particles/MultiParticleContainer_fwd.H
  Source/Particles/ParticleBoundaryBuffer_fwd.H
Labels: bug, bug: affects latest release, component: core

#2205 CI: Trap NaNs, Divisions by Zero, Overflows
  Regression/prepare_file_travis.py
Labels: component: tests

#1923 ECT conformal solver
  Docs/source/usage/parameters.rst
  Examples/Modules/embedded_boundary_cube/analysis_fields.py
  Examples/Modules/embedded_boundary_rotated_cube/analysis_fields.py
  Examples/Modules/embedded_boundary_rotated_cube/inputs_3d
  Regression/Checksum/benchmarks_json/embedded_boundary_rotated_cube.json
  Regression/WarpX-tests.ini
  Source/EmbeddedBoundary/CMakeLists.txt
  Source/EmbeddedBoundary/Make.package
  Source/EmbeddedBoundary/WarpXFaceExtensions.H
  Source/EmbeddedBoundary/WarpXFaceExtensions.cpp
  Source/EmbeddedBoundary/WarpXFaceInfoBox.H
  Source/EmbeddedBoundary/WarpXInitEB.cpp
  Source/Evolve/WarpXComputeDt.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveB.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveBPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveEPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/GuardCellManager.cpp
  Source/Utils/WarpXAlgorithmSelection.H
  Source/Utils/WarpXAlgorithmSelection.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: enhancement, component: boundary

#2250 CI: Rename Travis -> CI
  .github/workflows/source.yml
  .github/workflows/source/ci_matrix.py
  .github/workflows/source/test_ci_matrix.sh
  .github/workflows/source/test_travis_matrix.sh
  Docs/source/developers/checksum.rst
  Docs/source/developers/testing.rst
  Docs/source/glossary.rst
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  Regression/prepare_file_ci.py
  run_test.sh
Labels: component: tests

#2249 AMReX/PICSAR: Weekly Update
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#2164 Make buffer of scraped particles available to Python code
  Docs/source/usage/parameters.rst
  Examples/Modules/ParticleBoundaryScrape/PICMI_inputs_scrape.py
  Examples/Modules/ParticleBoundaryScrape/analysis_scrape.py
  Python/pywarpx/_libwarpx.py
  Python/pywarpx/picmi.py
  Regression/WarpX-tests.ini
  Source/Particles/ParticleBoundaryBuffer.H
  Source/Particles/ParticleBoundaryBuffer.cpp
  Source/Python/WarpXWrappers.cpp
  Source/Python/WarpXWrappers.h
  Source/WarpX.H
Labels: component: Python

#2229 Docs: Perlmutter
  Docs/source/install/hpc.rst
  Docs/source/install/hpc/perlmutter.rst
  Tools/BatchScripts/batch_cori.sh
  Tools/BatchScripts/batch_cori_haswell.sh
  Tools/BatchScripts/batch_perlmutter.sh
Labels: backend: cuda, component: documentation, machine / system

#2239 Docs: ADIOS2 Fixed on Summit
  Docs/source/install/hpc/summit.rst
  Tools/BatchScripts/batch_summit.sh
Labels: install, machine / system, component: diagnostics

#2251 Glossary: OTP/2FA
  Docs/source/glossary.rst
Labels: component: documentation, machine / system

#2246 Added parsing in intervals
  Docs/source/usage/parameters.rst
  Examples/Tests/Langmuir/inputs_2d_multi_rz_rt
  Examples/Tests/Langmuir/inputs_3d_multi_rt
  Source/Utils/IntervalsParser.cpp
  Source/Utils/WarpXUtil.H
  Source/Utils/WarpXUtil.cpp
Labels: enhancement, cleaning, component: diagnostics

#2253 Add profiling for charge deposition
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/Particles/WarpXParticleContainer.cpp
Labels: enhancement

#2256 Add link to repo visual structure
  Docs/source/developers/repo_organization.rst
Labels: component: documentation

#2254 [Mini-PR] Initializing geometric data also with the CKC solver
  Source/WarpX.cpp
Labels: bug, component: boundary

#2260 Docs: Summit umask (Permissions)
  Docs/source/install/hpc/summit.rst
  Tools/BatchScripts/batch_summit.sh
  Tools/BatchScripts/batch_summit_power9.sh
  Tools/BatchScripts/script_profiling_summit.sh
Labels: component: documentation, workaround
