Repository BLAST-WarpX/warpx, pull requests merged in 2021-03, with the labels that each got.

#1749 AMReX: 21.03
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
Labels: component: third party

#1747 Fix Warning: PlasmaInjector
  Source/Initialization/PlasmaInjector.cpp
Labels: cleaning, warning

#1742 Remove coarse bounding box check from the BTD selection
  Source/Particles/PhysicalParticleContainer.cpp
Labels: bug, bug: affects latest release

#1645 Add CI coverage for the plotfile particle filters
  Examples/Modules/qed/schwinger/analysis_schwinger.py
  Examples/Modules/resampling/analysis_leveling_thinning.py
  Examples/Tests/Langmuir/analysis_langmuir_multi_rz.py
  Examples/Tests/Langmuir/inputs_2d_multi_rz_rt
  Examples/Tests/collision/analysis_collision_2d.py
  Examples/Tests/collision/analysis_collision_3d.py
  Examples/Tests/collision/inputs_2d
  Examples/Tests/collision/inputs_3d
  Regression/PostProcessingUtils/post_processing_utils.py
  Regression/WarpX-tests.ini
Labels: component: diagnostics, component: tests

#1723 Clean plotfile output for btd
  Source/Diagnostics/BTDiagnostics.cpp
Labels: component: diagnostics

#1744 RZ Poisson solver
  Examples/Tests/ElectrostaticSphere/analysis_electrostatic_sphere.py
  Examples/Tests/ElectrostaticSphere/inputs_rz
  Regression/WarpX-tests.ini
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/WarpX.H
Labels: component: RZ, component: electrostatic, enhancement

#1748 Add empty runtime_params = in WarpX-tests.ini
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
Labels: component: tests

#1587 CI: Always with FFTW/PSATD
  .azure-pipelines.yml
  .github/workflows/source/test_travis_matrix.sh
  Regression/prepare_file_travis.py
  Source/Parallelization/WarpXComm.cpp
  Source/Parallelization/WarpXComm_K.H
Labels: bug, bug: affects latest release, component: spectral, component: tests

#1406 GPU clock timer for measuring load balance costs
  Docs/source/running_cpp/parameters.rst
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/Utils/KernelTimer.H
  Source/Utils/WarpXAlgorithmSelection.H
  Source/Utils/WarpXAlgorithmSelection.cpp
Labels: component: load balancing, enhancement

#1756 ParticleContainer: Fix Unused Vars
  Source/Particles/PhysicalParticleContainer.cpp
Labels: warning

#1755 AMReX: CMake Install (if shared)
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party, install

#1753 Examples: Dynamic Scheduling
  Examples/Modules/laser_injection_from_file/inputs.2d_test_txye
  Examples/Physics_applications/laser_ion/inputs
  Examples/Physics_applications/plasma_mirror/inputs_2d
  Regression/WarpX-tests.ini
Labels: Performance optimization, component: documentation, component: tests

#1746 CMake: add option to compile with InterProcedural Optimizations (if available)
  CMakeLists.txt
  Docs/source/building/cmake.rst
  cmake/WarpXFunctions.cmake
Labels: install

#1758 Remove extra ghost cell used with momentum-conserving gathering
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/Parallelization/GuardCellManager.H
  Source/Parallelization/GuardCellManager.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning, component: parallelization

#1759 setup.py: libwarpx*.dll
  setup.py
Labels: bug, bug: affects latest release, component: Python, install, machine / system

#1544 Implement averaged algo on staggered grids & merge spectral classes
  Examples/Tests/averaged_galilean/inputs_avg_2d
  Examples/Tests/averaged_galilean/inputs_avg_3d
  Regression/Checksum/benchmarks_json/averaged_galilean_2d_psatd_hybrid.json
  Regression/Checksum/benchmarks_json/averaged_galilean_3d_psatd_hybrid.json
  Regression/WarpX-tests.ini
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/AvgGalileanAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/CMakeLists.txt
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/GalileanAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/Make.package
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralSolver.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/WarpX.cpp
Labels: cleaning, component: spectral, enhancement

#1757 Distribution mapping plotting with reduced diagnostics only 1 step
  Tools/PostProcessing/plot_distribution_mapping.py
Labels: component: diagnostics, component: post-processing

#1762 Update AMReX: Install (Regression)
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: bug, component: third party, install

#1752 RigidInjectedParticleContainer: clean duplicated code
  Source/Particles/RigidInjectedParticleContainer.cpp
Labels: cleaning, warning

#1754 Ion Acceleration Example: More Text...
  Examples/Physics_applications/laser_ion/inputs
  Regression/Checksum/benchmarks_json/LaserIonAcc2d.json
Labels: cleaning, component: documentation, component: tests

#1741 QEDInternals: replace amrex::Real with amrex::ParticleReal where appropriate
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineWrapper.H
  Source/Particles/ElementaryProcess/QEDInternals/QedChiFunctions.H
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineWrapper.H
  Source/Particles/ElementaryProcess/QEDInternals/SchwingerProcessWrapper.H
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
Labels: cleaning, component: QED

#1764 AMReX: Skip AMRLEVEL
  cmake/dependencies/AMReX.cmake
Labels: component: third party, install

#1750 Zenodo: Add meta-data
  .zenodo.json
  README.md
Labels: component: documentation

#1726 Remove Temporary Custom Output for Reformatted BTD
  Source/Diagnostics/BTD_Plotfile_Header_Impl.H
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: component: diagnostics

#1769 AMReX: Weekly Update
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#1778 Spectral Solver: Remove Unused Header Files
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/AvgGalileanAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/GalileanAlgorithm.H
Labels: cleaning, component: spectral

#1773 MultiParticleContainer: fix typo in comment & warning message
  Source/Particles/MultiParticleContainer.cpp
Labels: cleaning

#1774 Minor cleanup of RZ in collisions
  Source/Particles/Collision/PairWiseCoulombCollision.cpp
Labels: cleaning, component: RZ, component: collisions

#1779 Spectral Solver: Fix Allocation of rho_fp and rho_cp
  Source/WarpX.cpp
Labels: cleaning, component: spectral

#1772 Version: 21.03
  CMakeLists.txt
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
  setup.py
Labels: component: documentation

#1782 CMake: Update AMReX Particle Precision
  cmake/dependencies/AMReX.cmake
Labels: bug, bug: affects latest release, component: third party, install

#1783 CI: DPC++ Re-Enable
  .github/workflows/dependencies/dpcpp.sh
  .github/workflows/ubuntu.yml
Labels: backend: dpc++, component: tests

#1786 Fix few "unused variable" warnings
  Source/Particles/Collision/PairWiseCoulombCollision.cpp
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/Deposition/CurrentDeposition.H
Labels: cleaning

#1787 AddPlasma: Avoid a calculation resulting in NaN when num_ppc is 0
  Source/Particles/PhysicalParticleContainer.cpp
Labels: cleaning

#1789 Clean-up OneStep function: Move error message at initialization
  Source/Evolve/WarpXEvolve.cpp
  Source/WarpX.cpp
Labels: cleaning

#1795 AMReX: Weekly Update
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#1790 Move multi-physics module out of `OneStep` function
  Source/Evolve/WarpXEvolve.cpp
Labels: cleaning

#1771 README: License Block
  README.md
  Tools/Release/newVersion.sh
Labels: component: documentation

#1692 Add timers in routines that depend on cell-related work
  Source/BoundaryConditions/PML.H
  Source/BoundaryConditions/PML.cpp
  Source/Diagnostics/ComputeDiagFunctors/RhoFunctor.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveB.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/ComovingPsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/ComovingPsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/GalileanPsatdAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/GalileanPsatdAlgorithmRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PMLPsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PMLPsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithmRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldData.H
  Source/FieldSolver/SpectralSolver/SpectralFieldData.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.H
  Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralSolver.H
  Source/FieldSolver/SpectralSolver/SpectralSolver.cpp
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ.H
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Particles/Collision/CollisionHandler.cpp
  Source/Particles/Collision/PairWiseCoulombCollision.H
  Source/Particles/Collision/PairWiseCoulombCollision.cpp
  Source/Particles/MultiParticleContainer.cpp
  Source/WarpX.cpp
Labels: component: load balancing

#1765 FFTW: CMakeConfig Support (Windows)
  CMakeLists.txt
  cmake/WarpXFunctions.cmake
  cmake/dependencies/FFT.cmake
Labels: component: spectral, component: third party, install, machine / system

#1766 Implement Silver Mueller boundary conditions
  Docs/source/running_cpp/parameters.rst
  Examples/Tests/SilverMueller/analysis_silver_mueller.py
  Examples/Tests/SilverMueller/inputs_2d_x
  Examples/Tests/SilverMueller/inputs_2d_z
  Regression/Checksum/benchmarks_json/silver_mueller_2d_x.json
  Regression/Checksum/benchmarks_json/silver_mueller_2d_z.json
  Regression/WarpX-tests.ini
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/FiniteDifferenceSolver/ApplySilverMuellerBoundary.cpp
  Source/FieldSolver/FiniteDifferenceSolver/CMakeLists.txt
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/FieldSolver/FiniteDifferenceSolver/Make.package
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: boundary

#1792 Move laser particle container
  Source/Laser/CMakeLists.txt
  Source/Laser/Make.package
  Source/Particles/CMakeLists.txt
  Source/Particles/LaserParticleContainer.H
  Source/Particles/LaserParticleContainer.cpp
  Source/Particles/Make.package
  Source/Particles/MultiParticleContainer.H
Labels: cleaning, component: core

#1730 Boundary input - Periodic
  Docs/source/running_cpp/parameters.rst
  Source/Utils/WarpXAlgorithmSelection.H
  Source/Utils/WarpXAlgorithmSelection.cpp
  Source/Utils/WarpXUtil.H
  Source/Utils/WarpXUtil.cpp
  Source/WarpX.H
  Source/WarpX.cpp
  Source/main.cpp
Labels: component: boundary

#1796 Add reference to WarpX slides in the acknowledge us section
  Docs/source/acknowledge_us.rst
Labels: component: documentation

#1780 KernelTimer cleaning
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Utils/KernelTimer.H
Labels: cleaning, component: load balancing

#1770 Add option to specify a0 instead of e_max for the laser
  Docs/source/running_cpp/parameters.rst
  Examples/Modules/ionization/inputs_2d_bf_rt
  Examples/Modules/ionization/inputs_2d_rt
  Examples/Physics_applications/laser_ion/inputs
  Regression/Checksum/benchmarks_json/LaserIonAcc2d.json
  Regression/Checksum/benchmarks_json/ionization_boost.json
  Regression/Checksum/benchmarks_json/ionization_lab.json
  Source/Particles/LaserParticleContainer.cpp
Labels: changes input script

#1802 openPMD: Add ParaView .pmd Helper File
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: component: openPMD, component: third party

#1801 Replaced almost all nGrow with nGrowVect
  Source/Diagnostics/ComputeDiagFunctors/CellCenterFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/RhoFunctor.cpp
  Source/Diagnostics/FieldIO.H
  Source/Diagnostics/FieldIO.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/WarpXIO.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/Particles/ElementaryProcess/Ionization.H
  Source/Particles/ElementaryProcess/Ionization.cpp
  Source/Particles/ElementaryProcess/QEDPairGeneration.H
  Source/Particles/ElementaryProcess/QEDPairGeneration.cpp
  Source/Particles/ElementaryProcess/QEDPhotonEmission.H
  Source/Particles/ElementaryProcess/QEDPhotonEmission.cpp
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhotonParticleContainer.H
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.H
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/Utils/CoarsenIO.H
  Source/Utils/CoarsenIO.cpp
  Source/Utils/Interpolate.H
  Source/Utils/Interpolate.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#1798 Docs: Sorting Defaults Changed
  Docs/source/running_cpp/parameters.rst
  Examples/Physics_applications/laser_ion/inputs
Labels: bug, bug: affects latest release, component: documentation

#1808 Remove Wrong Parser Query in MultiParticleContainer.cpp
  Source/Particles/MultiParticleContainer.cpp
Labels: cleaning

#1809 Use Clear Naming Standard for ParmParse Variables
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
  Source/Diagnostics/FlushFormats/FlushFormatSensei.cpp
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/MultiDiagnostics.cpp
  Source/Diagnostics/ReducedDiags/BeamRelevant.cpp
  Source/Diagnostics/ReducedDiags/FieldEnergy.cpp
  Source/Diagnostics/ReducedDiags/FieldMaximum.cpp
  Source/Diagnostics/ReducedDiags/LoadBalanceEfficiency.cpp
  Source/Diagnostics/ReducedDiags/MultiReducedDiags.cpp
  Source/Diagnostics/ReducedDiags/ParticleExtrema.cpp
  Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp
  Source/Diagnostics/ReducedDiags/ReducedDiags.cpp
  Source/Diagnostics/ReducedDiags/RhoMaximum.cpp
  Source/EmbeddedBoundary/WarpXInitEB.cpp
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.cpp
  Source/Initialization/CustomDensityProb.H
  Source/Initialization/InjectorDensity.cpp
  Source/Initialization/PlasmaInjector.cpp
  Source/Initialization/WarpXAMReXInit.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/GuardCellManager.cpp
  Source/Particles/Collision/CollisionBase.cpp
  Source/Particles/Collision/PairWiseCoulombCollision.cpp
  Source/Particles/LaserParticleContainer.cpp
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Resampling/LevelingThinning.cpp
  Source/Particles/Resampling/Resampling.cpp
  Source/Particles/Resampling/ResamplingTrigger.cpp
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/Utils/WarpXUtil.cpp
  Source/WarpX.cpp
Labels: cleaning

#1813 DPC++: More Savings
  .github/workflows/dependencies/dpcpp.sh
  .github/workflows/ubuntu.yml
  cmake/WarpXFunctions.cmake
Labels: backend: dpc++, component: tests

#1793 Move Python Callback function
  Source/Evolve/WarpXEvolve.cpp
Labels: cleaning, component: Python

#1785 LoadBalanceCosts reduced diagnostic set spatial indices to zero depending on dims
  Source/Diagnostics/ReducedDiags/LoadBalanceCosts.cpp
Labels: bug, cleaning

#1814 Warnings: PSATD+RZ & More
  Source/BoundaryConditions/PML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveBPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CylindricalYeeAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/BesselRoots.H
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/SpectralHankelTransformer.H
  Source/Utils/KernelTimer.H
  Source/Utils/WarpXUtil.cpp
Labels: component: RZ, component: boundary, warning

#1800 Applied boost to single and multiple particle input
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
Labels: enhancement

#1823 AMReX/PICSAR: Weekly Update
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#1822 CMake: Build AMReX with IPO/LTO
  cmake/WarpXFunctions.cmake
  cmake/dependencies/AMReX.cmake
Labels: Performance optimization, install

#1820 CMake: Print Version
  CMakeLists.txt
  Source/Diagnostics/MultiDiagnostics.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/main.cpp
  cmake/WarpXFunctions.cmake
  cmake/dependencies/PICSAR.cmake
Labels: component: documentation, install

#1825 Disable charge deposition for photons
  Source/Particles/PhotonParticleContainer.H
Labels: Performance optimization, component: QED, component: core

#1831 README: More Badges, Beta
  README.md
Labels: component: documentation

#1830 Docs: HPC Updates
  Docs/source/install/cmake.rst
  Docs/source/install/hpc/cori.rst
  Docs/source/install/hpc/juwels.rst
  Docs/source/install/hpc/lassen.rst
  Docs/source/install/hpc/quartz.rst
  Docs/source/install/hpc/summit.rst
  Docs/source/install/users.rst
  Tools/BatchScripts/batch_juwels.sh
Labels: component: documentation

#1832 Documentation: warn the user not to change the default behavior for Galerkin scheme
  Docs/source/usage/parameters.rst
Labels: component: documentation

#1836 CI: HIP w/o MPI
  .github/workflows/ubuntu.yml
Labels: backend: hip, workaround

#1837 CI: HIPCC as C Compiler
  .github/workflows/ubuntu.yml
Labels: backend: hip, component: tests

#1834 More Badges: Install, ECP
  README.md
Labels: component: documentation

#1840 README: Project Dependencies & Communities
  README.md
Labels: component: documentation

#1841 CI: DPC++ apt clean
  .github/workflows/dependencies/dpcpp.sh
Labels: backend: dpc++, component: tests

#1819 Class `PsatdAlgorithm`: Simplify Initialization of Coefficients
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.cpp
Labels: cleaning, component: spectral

#1804 Silver Mueller in RZ
  Source/FieldSolver/FiniteDifferenceSolver/ApplySilverMuellerBoundary.cpp
Labels: component: RZ, component: boundary

#1763 Add option for finite-order centering of currents (nodal to staggered)
  Docs/source/usage/parameters.rst
  Examples/Tests/spectral_staggered/inputs_hybrid_2d
  Regression/Checksum/benchmarks_json/averaged_galilean_2d_psatd_hybrid.json
  Regression/Checksum/benchmarks_json/averaged_galilean_3d_psatd_hybrid.json
  Regression/WarpX-tests.ini
  Source/Evolve/WarpXEvolve.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/Parallelization/WarpXComm_K.H
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: interpolation, enhancement

#1815 Regrid spectral solver during load balance
  Source/Parallelization/WarpXRegrid.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: load balancing, component: spectral

#1777 openPMD: QED Attributes as scalars
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: bug, bug: affects latest release, component: openPMD

#1848 New BTD: no need for global field flag
  Source/Diagnostics/BTDiagnostics.cpp
Labels: component: diagnostics

#1849 Remove the avg_aux fields
  Regression/Checksum/benchmarks_json/averaged_galilean_2d_psatd.json
  Regression/Checksum/benchmarks_json/averaged_galilean_3d_psatd.json
  Source/Evolve/WarpXEvolve.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Particles/LaserParticleContainer.H
  Source/Particles/LaserParticleContainer.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhotonParticleContainer.H
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.H
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: diagnostics, component: mesh refinement

#1852 Add USE_OPENPMD=TRUE To Run Test `LaserIonAcc2d` Locally
  Regression/WarpX-tests.ini
Labels: component: tests

#1843 Weekly Update: AMReX & PICSAR
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party
