Repository BLAST-WarpX/warpx, pull requests merged in 2021-02, with the labels that each got.

#1668 requirements.txt: fix overspecification
  requirements.txt
  setup.py
Labels: bug, component: Python, install

#1670 scipy 1.5+
  requirements.txt
Labels: component: Python, install

#1667 Remove redundant "do_qed" option in inputfile
  Docs/source/running_cpp/parameters.rst
  Examples/Modules/qed/breit_wheeler/inputs_2d
  Examples/Modules/qed/breit_wheeler/inputs_3d
  Examples/Modules/qed/quantum_synchrotron/inputs_2d
  Examples/Modules/qed/quantum_synchrotron/inputs_3d
  Source/Diagnostics/ReducedDiags/ParticleExtrema.cpp
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
Labels: changes input script, cleaning, component: QED

#1662 remove unnecessary semicolons
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CylindricalYeeAlgorithm.H
Labels: cleaning, warning

#1669 Always synchronize nodal points of PML MultiFabs
  Regression/Checksum/benchmarks_json/pml_x_psatd.json
  Source/Evolve/WarpXEvolve.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/WarpX.H
Labels: bug: affects latest release, component: PML

#1653 Refactor finite-order interpolation functions for momentum-conserving field gathering
  Source/Parallelization/WarpXComm.cpp
  Source/Parallelization/WarpXComm_K.H
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning, component: interpolation

#1672 Updates to match picmi version 0.0.14
  Python/pywarpx/picmi.py
  Python/setup.py
  requirements.txt
  setup.py
Labels: component: PICMI

#1677 CI: BLAS++ from Mainline
  .azure-pipelines.yml
Labels: component: RZ, component: third party

#1673 Reduced diagnostic for load balance efficiency
  Docs/source/running_cpp/parameters.rst
  Source/Diagnostics/ReducedDiags/CMakeLists.txt
  Source/Diagnostics/ReducedDiags/LoadBalanceEfficiency.H
  Source/Diagnostics/ReducedDiags/LoadBalanceEfficiency.cpp
  Source/Diagnostics/ReducedDiags/Make.package
  Source/Diagnostics/ReducedDiags/MultiReducedDiags.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/WarpXRegrid.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: diagnostics

#1678 [mini-PR] Update intervals notation in visualization doc
  Docs/source/visualization/plot_distribution_mapping.rst
Labels: component: documentation

#1660 BilinearFilter: Fix compilation warning
  Source/Filter/BilinearFilter.H
  Source/Filter/BilinearFilter.cpp
  Source/Initialization/WarpXInitData.cpp
Labels: cleaning, warning

#1679 MSVC: '*/' found outside of comment
  Source/Particles/Resampling/Resampling.H
Labels: warning

#1529 Set QED support ON by default
  CMakeLists.txt
  Docs/Doxyfile
  Docs/source/building/cmake.rst
  Docs/source/building/lassen.rst
  Docs/source/building/quartz.rst
  Docs/source/building/summit.rst
  Source/Make.WarpX
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineWrapper.H
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineWrapper.cpp
  Source/Particles/ElementaryProcess/QEDInternals/QedChiFunctions.H
  Source/Particles/ElementaryProcess/QEDInternals/QedWrapperCommons.H
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineWrapper.H
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineWrapper.cpp
  Source/Particles/ElementaryProcess/QEDInternals/SchwingerProcessWrapper.H
  cmake/WarpXFunctions.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
Labels: cleaning, help wanted

#1681 Fix photon species error message
  Source/Particles/MultiParticleContainer.cpp
Labels: cleaning

#1685 Docs: QED is now on
  Docs/source/building/cmake.rst
  cmake/dependencies/PICSAR.cmake
  setup.py
Labels: component: Python, component: documentation, install

#1684 CI: Minimal Compile
  .github/workflows/dependencies/gcc.sh
  .github/workflows/ubuntu.yml
Labels: component: tests

#1683 Input load balance parameters as `algo.load_balance_param`
  Docs/source/running_cpp/parameters.rst
  Examples/Modules/laser_injection_from_file/inputs.2d_test_txye
  Examples/Physics_applications/laser_ion/inputs
  Examples/Physics_applications/plasma_mirror/inputs_2d
  Examples/Tests/reduced_diags/inputs_loadbalancecosts
  Python/pywarpx/picmi.py
  Source/WarpX.cpp
  Tools/LibEnsemble/sim/inputs
  Tools/PerformanceTests/automated_test_5_loadimbalance
Labels: changes input script, component: PICMI

#1687 Update yt data loading in analysis scripts for Galilean tests
  Examples/Tests/galilean/analysis_2d.py
  Examples/Tests/galilean/analysis_3d.py
Labels: cleaning, component: tests

#1680 openPMD-api: 0.13.2 (internal)
  cmake/dependencies/openPMD.cmake
Labels: component: openPMD

#1623 Add a automated test for testing restart
  Examples/Tests/restart/analysis_restart.py
  Examples/Tests/restart/inputs
  Regression/Checksum/benchmarks_json/restart.json
  Regression/WarpX-tests.ini
Labels: component: tests

#1689 GNUmake: QED on (TRUE) by default
  Docs/source/building/cmake.rst
  GNUmakefile
Labels: component: QED, install

#1690 Fix: Missing Geometry Includes
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/WarpX.H
Labels: bug, bug: affects latest release, component: core, install

#1695 Reset benchmarks of boosted frame tests
  Regression/Checksum/benchmarks_json/LaserAccelerationBoost.json
  Regression/Checksum/benchmarks_json/PlasmaAccelerationBoost2d.json
  Regression/Checksum/benchmarks_json/PlasmaAccelerationBoost3d.json
  Regression/Checksum/benchmarks_json/comoving_hybrid_2d.json
  Regression/Checksum/benchmarks_json/galilean_hybrid_2d.json
  Regression/Checksum/benchmarks_json/ionization_boost.json
  Regression/Checksum/benchmarks_json/restart.json
Labels: bug, component: tests, component: third party

#1686 Tool: newVersion.sh
  CMakeLists.txt
  Docs/source/conf.py
  LICENSE.txt
  Tools/Release/newVersion.sh
  cmake/dependencies/AMReX.cmake
Labels: enhancement, install

#1694 setup.py: Build Dir Path Clash
  setup.py
Labels: bug, component: Python, install

#1698 new setup.py: PYWARPX_LIB_DIR support
  .github/workflows/dependencies/pyfull.sh
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  Docs/source/building/cmake.rst
  Examples/Physics_applications/laser_acceleration/PICMI_inputs_laser_acceleration.py
  setup.py
Labels: component: Python, install

#1697 Reduced diagnostics load balance cleaning
  Source/Diagnostics/ReducedDiags/LoadBalanceCosts.H
  Source/Diagnostics/ReducedDiags/LoadBalanceEfficiency.H
Labels: cleaning

#1701 Docs: Update openPMD-viewer include
  Docs/source/visualization/openpmdviewer.rst
  Tools/DevUtils/compare_wx_w_3d.ipynb
Labels: component: documentation

#1699 CMake: Quick, Local Dependencies
  Docs/source/building/cmake.rst
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  cmake/dependencies/openPMD.cmake
  setup.py
Labels: component: third party, install

#1700 Close #1688 : Transform the moving window velocity to its boosted-frame value.
  Source/Utils/WarpXMovingWindow.cpp
Labels: component: core

#1705 Initialize aux MultiFabs on level 0
  Source/Initialization/WarpXInitData.cpp
Labels: cleaning, component: mesh refinement

#1709 Spectral Solver: Remove extra semicolons
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/AvgGalileanAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/ComovingPsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/GalileanAlgorithm.H
Labels: cleaning, component: spectral, warning

#1691 Fix bug in loop over boxes in WarpX::UpdateAuxilaryDataStagToNodal
  Source/Parallelization/WarpXComm.cpp
  Source/Parallelization/WarpXComm_K.H
Labels: bug, bug: affects latest release, cleaning, component: parallelization

#1708 CMake: Mark Some PICSAR options as "advanced"
  cmake/dependencies/PICSAR.cmake
Labels: cleaning, component: PICSAR, install

#1711 Fix warnings in docs
  Docs/Doxyfile
  Docs/source/running_cpp/pwfa.rst
  Docs/source/running_python/how_to_run.rst
  Docs/source/theory/amr.rst
  Docs/source/visualization/advanced.rst
  Docs/source/visualization/backtransformed_diags.rst
  Docs/source/visualization/openpmdviewer.rst
  Docs/source/visualization/yt.rst
Labels: component: documentation, warning

#1707 CMake: Cosmetic Clean-Up (Messages)
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  cmake/dependencies/openPMD.cmake
Labels: cleaning, install

#1703 CMake: Search rocFFT
  .github/workflows/dependencies/hip.sh
  .github/workflows/ubuntu.yml
  CMakeLists.txt
  Source/FieldSolver/SpectralSolver/CMakeLists.txt
Labels: backend: hip, bug, bug: affects latest release, component: spectral, install

#1713 MultiFabs Tags: WarpX Basics
  Source/WarpX.cpp
Labels: component: core

#1576 Plotfile capability for BTD
  Source/Diagnostics/BTD_Plotfile_Header_Impl.H
  Source/Diagnostics/BTD_Plotfile_Header_Impl.cpp
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/CMakeLists.txt
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.H
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/Make.package
Labels: component: diagnostics

#1720 Add "." to libwarpx Aliases
  CMakeLists.txt
  Python/pywarpx/_libwarpx.py
  Python/setup.py
  Source/Make.WarpX
  cmake/WarpXFunctions.cmake
  setup.py
Labels: cleaning, component: Python, install

#1715 Fix spelling typos
  Docs/source/building/juwels.rst
  Docs/source/developers/checksum.rst
  Docs/source/developers/dimensionality.rst
  Docs/source/developers/repo_organization.rst
  Docs/source/latex_theory/AMR/AMR.tex
  Docs/source/running_cpp/parallelization.rst
  Docs/source/running_cpp/parameters.rst
  Docs/source/running_cpp/profiling.rst
  Docs/source/running_cpp/pwfa.rst
  Docs/source/theory/amr.rst
  Docs/source/visualization/visit.rst
  Docs/source/visualization/visualization.rst
Labels: cleaning, component: documentation

#1710 Tool: update AMReX dependency
  Docs/source/developers/developers.rst
  Docs/source/developers/release.rst
  Docs/source/developers/workflow.rst
  Tools/DevUtils/update_release.sh
  Tools/Release/newVersion.sh
  Tools/Release/requirements.txt
  Tools/Release/updateAMReX.py
  Tools/Release/updatePICSAR.py
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
Labels: component: tests, component: third party, install

#1721 Fix: CMake Library Alias (Install)
  CMakeLists.txt
  cmake/WarpXFunctions.cmake
Labels: bug, install

#1722 pyproject.toml: build-backend
  pyproject.toml
Labels: component: Python, install

#1717 Backtransformed Diags with openPMD
  Source/Diagnostics/BTD_Plotfile_Header_Impl.cpp
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/FlushFormats/FlushFormat.H
  Source/Diagnostics/FlushFormats/FlushFormatAscent.H
  Source/Diagnostics/FlushFormats/FlushFormatAscent.cpp
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.H
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.H
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.H
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/FlushFormats/FlushFormatSensei.H
  Source/Diagnostics/FlushFormats/FlushFormatSensei.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: component: diagnostics, component: openPMD

#1696 ParticleHistogram: Fix Performance Regression
  Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp
Labels: Performance optimization, bug, bug: affects latest release, component: diagnostics

#1729 Fix: run_test.sh - fail on error & fix clone
  .azure-pipelines.yml
  Docs/source/developers/testing.rst
  Tools/Release/updateAMReX.py
  Tools/Release/updatePICSAR.py
  run_test.sh
Labels: bug, component: tests

#1727 Fix: Histogram w/o Filter
  Examples/Physics_applications/laser_ion/inputs
  Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp
Labels: bug, component: diagnostics

#1704 Summit & Cori: Update openPMD & ADIOS2
  Docs/source/building/cori.rst
  Docs/source/building/summit.rst
Labels: component: documentation, component: openPMD, install, machine / system

#1737 CI (Azure): Reorder As Jobs
  .azure-pipelines.yml
Labels: component: tests

#1739 CI: ICC use openPMD@0.13.2
  .github/workflows/ubuntu.yml
Labels: component: openPMD, component: tests

#1725 AMReX: Weekly Update
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#1740 CI (Nightly): Spack py-warpx
  azure-pipelines.yml
Labels: component: tests, install

#1714 Finite-order field centering: few small optimizations
  Source/Parallelization/WarpXComm_K.H
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning, component: interpolation

#1732 CI: openPMD-api w/o CLI Tools
  .azure-pipelines.yml
  .github/workflows/ubuntu.yml
Labels: component: openPMD, component: tests

#1736 Fix libEnsemble: optimizer selection
  Tools/LibEnsemble/run_libensemble_on_warpx.py
Labels: bug, bug: affects latest release, component: post-processing, component: third party

#1718 Add multiple particles source
  Docs/source/running_cpp/parameters.rst
  Python/pywarpx/picmi.py
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/PhysicalParticleContainer.cpp
Labels: enhancement

#1745 For picmi, fix MultiSpecies
  Python/pywarpx/picmi.py
Labels: bug, component: PICMI
