Repository BLAST-WarpX/warpx, pull requests merged in 2021-01, with the labels that each got.

#1599 Cori: Newer CMake
  Docs/source/building/cori.rst
Labels: component: documentation, install, machine / system

#1589 Docs: MR Ratio
  Docs/source/running_cpp/parameters.rst
Labels: component: documentation, component: mesh refinement

#1583 Reconfigured the collision classes to allow for generalization
  Source/Evolve/WarpXEvolve.cpp
  Source/Particles/Collision/CMakeLists.txt
  Source/Particles/Collision/CollisionBase.H
  Source/Particles/Collision/CollisionBase.cpp
  Source/Particles/Collision/CollisionHandler.H
  Source/Particles/Collision/CollisionHandler.cpp
  Source/Particles/Collision/CollisionType.H
  Source/Particles/Collision/Make.package
  Source/Particles/Collision/PairWiseCoulombCollision.H
  Source/Particles/Collision/PairWiseCoulombCollision.cpp
  Source/Particles/Collision/README.md
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
Labels: component: collisions

#1603 LGTM: Fix & Modernize C++ Build
  .lgtm.yml
Labels: component: tests

#1601 openPMD-api: 0.13.0
  CMakeLists.txt
  Docs/source/building/cmake.rst
  cmake/dependencies/openPMD.cmake
Labels: component: documentation, component: openPMD, install

#1609 Cleaned calculation of current time in analysis scripts
  Examples/Tests/Langmuir/analysis_langmuir_multi.py
  Examples/Tests/Langmuir/analysis_langmuir_multi_2d.py
  Examples/Tests/Langmuir/analysis_langmuir_multi_rz.py
Labels: cleaning, component: tests

#1608 CI: Intel ICX/ICPX
  .github/workflows/ubuntu.yml
Labels: component: tests

#1606 [mini-PR] Fix some unused variable warnings
  Source/BoundaryConditions/PML.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
Labels: cleaning, warning

#1569 Implemented update without rho in RZ spectral solver
  Docs/source/running_cpp/parameters.rst
  Regression/WarpX-tests.ini
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/GalileanPsatdAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/GalileanPsatdAlgorithmRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ.H
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ.cpp
  Source/WarpX.cpp
Labels: component: RZ, component: spectral

#1550 Set laser initiation in RZ to be 3D
  Regression/Checksum/benchmarks_json/LaserAccelerationRZ.json
  Source/Laser/LaserProfilesImpl/LaserProfileFromTXYEFile.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileGaussian.cpp
Labels: bug, bug: affects latest release, component: RZ, component: core

#1597 Avoid stringent assert statement on GPU
  Source/Particles/WarpXParticleContainer.cpp
Labels: backend: cuda, backend: dpc++, backend: hip, bug, bug: affects latest release

#1612 Fix some warnings
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/ReducedDiags/BeamRelevant.cpp
  Source/Diagnostics/ReducedDiags/ParticleExtrema.cpp
  Source/Diagnostics/SliceDiagnostic.cpp
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveF.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/FieldSolver/WarpX_QED_Field_Pushers.cpp
  Source/FieldSolver/WarpX_QED_K.H
  Source/Filter/BilinearFilter.cpp
  Source/Filter/NCIGodfreyFilter.cpp
  Source/Parallelization/WarpXComm_K.H
Labels: cleaning, warning

#1548 Add electrostatic to picmi
  Python/pywarpx/picmi.py
  Python/setup.py
Labels: component: PICMI, component: electrostatic

#1611 For python regression tests, fix the setup step
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
Labels: component: Python, component: tests

#1535 New reduced diag: maximum charge densities
  Docs/source/running_cpp/parameters.rst
  Examples/Tests/reduced_diags/analysis_reduced_diags.py
  Examples/Tests/reduced_diags/inputs
  Regression/Checksum/benchmarks_json/reduced_diags.json
  Source/Diagnostics/ReducedDiags/BeamRelevant.cpp
  Source/Diagnostics/ReducedDiags/CMakeLists.txt
  Source/Diagnostics/ReducedDiags/FieldEnergy.cpp
  Source/Diagnostics/ReducedDiags/FieldMaximum.cpp
  Source/Diagnostics/ReducedDiags/LoadBalanceCosts.cpp
  Source/Diagnostics/ReducedDiags/Make.package
  Source/Diagnostics/ReducedDiags/MultiReducedDiags.cpp
  Source/Diagnostics/ReducedDiags/ParticleEnergy.cpp
  Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp
  Source/Diagnostics/ReducedDiags/ParticleNumber.cpp
  Source/Diagnostics/ReducedDiags/RhoMaximum.H
  Source/Diagnostics/ReducedDiags/RhoMaximum.cpp
Labels: component: diagnostics

#1610 Fix some double-->float warnings in NCIGodfrey table
  Source/Filter/NCIGodfreyFilter.cpp
  Source/Utils/NCIGodfreyTables.H
Labels: cleaning, warning

#1615 Parser: Flex Prefix
  Source/Parser/wp_parser.l
  Source/Parser/wp_parser.lex.cpp
  Source/Parser/wp_parser.lex.h
  Source/Parser/wp_parser.tab.cpp
  Source/Parser/wp_parser.tab.h
  Source/Parser/wp_parser.y
  Source/Parser/wp_parser_c.cpp
  Source/Parser/wp_parser_y.cpp
  Source/Parser/wp_parser_y.h
Labels: component: core, enhancement

#1618 Fix some other warnings
  Source/Evolve/WarpXEvolve.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Laser/LaserParticleContainer.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileGaussian.cpp
  Source/Parallelization/WarpXComm_K.H
  Source/Particles/Collision/UpdateMomentumPerezElastic.H
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/ElementaryProcess/Ionization.H
  Source/Particles/PhysicalParticleContainer.cpp
Labels: cleaning, warning

#1616 Remove unused functions "ExchangeWithPml..."
  Source/Parallelization/WarpXComm.cpp
  Source/WarpX.H
Labels: cleaning, component: PML

#1617 Update docs with new CoriGPU build instructions
  Docs/source/building/cori.rst
Labels: backend: cuda, component: documentation, machine / system

#1626 [mini-PR] Fix a variable initialization warning
  Source/Filter/BilinearFilter.cpp
Labels: cleaning, warning

#1628 fix typo in Juwels doc
  Docs/source/building/juwels.rst
Labels: component: documentation, machine / system

#1627 [mini-PR] Replace some naked "new" with "unique_ptr"
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
Labels: cleaning

#1625 LLNL: Newer CMake
  Docs/source/building/lassen.rst
  Docs/source/building/quartz.rst
Labels: component: documentation, machine / system

#1629 Lassen (LLNL): HDF5
  Docs/source/building/lassen.rst
Labels: component: diagnostics, component: documentation, machine / system

#1620 openPMD-api: 0.13.1
  cmake/dependencies/openPMD.cmake
Labels: component: diagnostics, component: openPMD

#1598 Handle units properly in the particle filter function.
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Particles/Filter/FilterFunctors.H
Labels: bug, bug: affects latest release, changes input script, component: core

#1624 Fix bug in momentum-conserving interpolation function with MR
  Regression/Checksum/benchmarks_json/momentum-conserving-gather.json
  Source/Parallelization/WarpXComm_K.H
Labels: bug: affects latest release, component: mesh refinement

#1596 Unused Params: Check after Step 1
  Source/Evolve/WarpXEvolve.cpp
Labels: changes input script, component: core, enhancement

#1640 Add Superparticle version of getParticlePosition.
  Source/Particles/Pusher/GetAndSetPosition.H
Labels: enhancement

#1444 Distribution mapping and cost plotting
  Docs/source/visualization/distribution_mapping_3D.png
  Docs/source/visualization/knapsack_sfc_costs_2D.png
  Docs/source/visualization/knapsack_sfc_distribution_mapping_2D.png
  Docs/source/visualization/plot_distribution_mapping.rst
  Docs/source/visualization/reduced_diags.rst
  Docs/source/visualization/visualization.rst
  Tools/PostProcessing/plot_distribution_mapping.py
Labels: component: post-processing

#1638 SpeciesProperties: C, N, O, Cu
  Source/Particles/SpeciesPhysicalProperties.H
  Source/Utils/IonizationEnergiesTable.H
  Source/Utils/atomic_data.txt
  Source/Utils/write_atomic_data_cpp.py
Labels: component: core

#1635 Fix 2D/RZ: ParticleHistogram
  Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp
Labels: bug, bug: affects latest release, component: RZ, component: diagnostics

#1633 Fix 2D/RZ: FilterFunctor
  Source/Particles/Filter/FilterFunctors.H
Labels: bug, bug: affects latest release, component: RZ, component: core, component: diagnostics

#1622 openPMD: ionizationLevel
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: component: diagnostics, component: openPMD

#1520 Define: _OPENMP -> AMREX_USE_OMP
  Source/BoundaryConditions/PML.cpp
  Source/BoundaryConditions/WarpXEvolvePML.cpp
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/PartPerGridFunctor.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/ParticleIO.cpp
  Source/Diagnostics/ReducedDiags/FieldMaximum.cpp
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/FieldSolver/FiniteDifferenceSolver/ComputeDivE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveB.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveBPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveEPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveF.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveFPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicEvolveE.cpp
  Source/FieldSolver/WarpX_QED_Field_Pushers.cpp
  Source/Filter/BilinearFilter.cpp
  Source/Filter/Filter.cpp
  Source/Filter/NCIGodfreyFilter.cpp
  Source/Laser/LaserParticleContainer.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/Parser/GpuParser.H
  Source/Parser/WarpXParser.H
  Source/Parser/WarpXParser.cpp
  Source/Particles/Collision/PairWiseCoulombCollision.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/ParticleCreation/SmartUtils.H
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/Python/WarpXWrappers.cpp
  Source/Utils/CoarsenIO.cpp
  Source/Utils/CoarsenMR.cpp
  Source/Utils/Interpolate.cpp
  Source/Utils/WarpXMovingWindow.cpp
  Source/Utils/WarpXTagging.cpp
  Source/Utils/WarpXUtil.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: backend: openmp

#1630 Start: PerformanceHints After Init
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
Labels: Performance optimization

#1646 Remove unused lines about particle filters
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
Labels: cleaning

#1097 Add parameter for default galilean velocity
  Examples/Tests/galilean/inputs_3d
  Regression/WarpX-tests.ini
  Source/Particles/PhysicalParticleContainer.cpp
  Source/WarpX.cpp
Labels: component: spectral

#1649 Cleaned up field diagnostic in picmi interface
  Python/pywarpx/picmi.py
Labels: component: PICMI

#1644 Use pinned memory for tmp particles in diags.
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: Performance optimization, component: diagnostics

#1655 Replace an always false test with an abort
  Source/Utils/WarpXUtil.cpp
Labels: cleaning

#1651 Docs: Broken link to scripts
  Docs/source/building/quartz.rst
Labels: component: documentation, machine / system

#1654 CI: Ubuntu-latest -> 20.04
  .github/workflows/source.yml
  .github/workflows/ubuntu.yml
Labels: component: tests, component: third party, warning

#1641 Start Embedded Boundary development
  CMakeLists.txt
  Docs/source/building/cmake.rst
  GNUmakefile
  Source/EmbeddedBoundary/CMakeLists.txt
  Source/EmbeddedBoundary/Make.package
  Source/EmbeddedBoundary/WarpXInitEB.cpp
  Source/Make.WarpX
  Source/Parallelization/WarpXRegrid.cpp
  Source/WarpX.H
  Source/WarpX.cpp
  cmake/WarpXFunctions.cmake
  cmake/dependencies/AMReX.cmake
Labels: component: core, enhancement

#1643 Add filter for particle histogram
  Docs/source/running_cpp/parameters.rst
  Examples/Physics_applications/laser_ion/inputs
  Examples/Tests/initial_distribution/analysis_distribution.py
  Examples/Tests/initial_distribution/inputs
  Regression/Checksum/benchmarks_json/initial_distribution.json
  Regression/WarpX-tests.ini
  Source/Diagnostics/ReducedDiags/ParticleHistogram.H
  Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp
Labels: component: diagnostics

#1607 Take time step into account to compute guard cells for J and rho
  Regression/Checksum/benchmarks_json/Langmuir_multi_psatd_single_precision.json
  Regression/Checksum/benchmarks_json/LaserAccelerationBoost.json
  Regression/Checksum/benchmarks_json/ionization_boost.json
  Regression/Checksum/benchmarks_json/ionization_lab.json
  Regression/Checksum/benchmarks_json/particles_in_pml_3d_MR.json
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/Parallelization/GuardCellManager.H
  Source/Parallelization/GuardCellManager.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/WarpX.cpp
Labels: bug: affects latest release

#1647 Modern setup.py: CMake-Driven, Multi-Dimensional
  .github/workflows/source/hasNonASCII
  Docs/source/building/cmake.rst
  MANIFEST.in
  pyproject.toml
  requirements.txt
  setup.py
Labels: component: Python, install

#1604 Updates for electrostatic solver
  Examples/Tests/ElectrostaticSphere/analysis_electrostatic_sphere.py
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/ElectrostaticSolver.cpp
Labels: bug, component: electrostatic

#1661 Reset broken CI benchmark after collision between PRs
  Regression/Checksum/benchmarks_json/initial_distribution.json
Labels: bug, component: tests
