Repository BLAST-WarpX/warpx, pull requests merged in 2021-12, with the labels that each got.

#2612 Added parallel pragma to ApplyBoundaryConditions
  Source/Particles/WarpXParticleContainer.cpp
Labels: component: parallelization, component: boundary

#2606 Note that CCache 4.2 introduced large CUDA improvements
  Docs/source/install/dependencies.rst
Labels: component: documentation

#2609 Dimensionality Docs: Default
  Docs/source/developers/dimensionality.rst
Labels: component: documentation

#2613 AMReX/PICSAR: Weekly Update
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#2608 MergeBuffersForPlotfile: Barrier
  Source/Diagnostics/BTDiagnostics.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#2583 Fix installation location for libraries
  CMakeLists.txt
Labels: bug, install, bug: affects latest release

#2614 Release 21.12
  CMakeLists.txt
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#2403 div(E,B) Cleaning Options for PSATD
  Examples/Tests/Langmuir/analysis_langmuir_multi.py
  Examples/Tests/PML/inputs_3d
  Regression/Checksum/benchmarks_json/Langmuir_multi_psatd_div_cleaning.json
  Regression/Checksum/benchmarks_json/pml_psatd_dive_divb_cleaning.json
  Regression/WarpX-tests.ini
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldData.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/WarpX.cpp
Labels: enhancement, component: spectral

#2605 Add 2D Langmuir Test w/ MR & PSATD
  Regression/Checksum/benchmarks_json/Langmuir_multi_2d_MR_psatd.json
  Regression/WarpX-tests.ini
Labels: component: spectral, component: tests, component: mesh refinement

#2619 Fix out-of-bound in Inverse FFT of F,G
  Source/WarpX.cpp
Labels: bug, component: spectral, bug: affects latest release

#2618 Mention that the potentail should be constant inside EB
  Docs/source/usage/parameters.rst
Labels: component: documentation, component: boundary

#2620 Replace AMREX_SPACEDIM: Boundary & Parallelization
  Source/BoundaryConditions/PML.cpp
  Source/BoundaryConditions/PML_current.H
  Source/BoundaryConditions/WarpXEvolvePML.cpp
  Source/BoundaryConditions/WarpX_PML_kernels.H
  Source/Parallelization/GuardCellManager.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/Parallelization/WarpXComm_K.H
Labels: cleaning

#2607 Fix out-of-bound in the initialization of EB
  Source/EmbeddedBoundary/WarpXInitEB.cpp
Labels: bug, bug: affects latest release, component: boundary

#2624 extern 'C': Only in Headers
  Source/Python/WarpXWrappers.H
  Source/Python/WarpXWrappers.cpp
  Source/Python/WarpX_py.cpp
Labels: bug, bug: affects latest release, component: Python

#2626 Fix: Installed Symlink LIB
  CMakeLists.txt
Labels: bug, install, bug: affects latest release

#2627 AMReX/PICSAR: Weekly Update
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#2623 3D performance tests: CI smaller
  Regression/WarpX-tests.ini
Labels: component: tests

#2615 Azure CI: Cache
  .azure-pipelines.yml
  run_test.sh
Labels: component: tests

#2510 Correct collision algorithm in RZ.
  Docs/source/usage/parameters.rst
  Examples/Tests/collision/analysis_collision_rz.py
  Examples/Tests/collision/inputs_rz
  Regression/Checksum/benchmarks_json/collisionRZ.json
  Regression/WarpX-tests.ini
  Source/Particles/Collision/BinaryCollision/ElasticCollisionPerez.H
  Source/Particles/Collision/BinaryCollision/UpdateMomentumPerezElastic.H
  Source/Particles/Collision/CollisionHandler.cpp
Labels: component: RZ, component: collisions

#2622 Define WARPX_ZINDEX to denote the index for the Z dimension regardless of the build's dimensionality
  CMakeLists.txt
  Docs/source/developers/dimensionality.rst
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Initialization/InjectorMomentum.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Make.WarpX
  Source/Parallelization/GuardCellManager.cpp
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/Gather/FieldGather.H
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/WarpX.cpp
Labels: cleaning

#2621 Docs: Archiving Workflows
  Docs/source/usage/workflows.rst
  Docs/source/usage/workflows/archiving.rst
Labels: component: documentation

#2628 AMREX_SPACEDIM : Initialization and Particles
  Source/Initialization/WarpXInitData.cpp
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/ElementaryProcess/QEDSchwingerProcess.H
  Source/Particles/Gather/FieldGather.H
  Source/Particles/LaserParticleContainer.cpp
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/ParticleBoundaryBuffer.cpp
  Source/Particles/ParticleCreation/SmartCreate.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/GetAndSetPosition.H
  Source/Particles/Pusher/UpdatePosition.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: cleaning

#2576 Add CI Test for Python Wrappers w/ PML
  Docs/source/usage/examples.rst
  Examples/Tests/PythonWrappers/PICMI_inputs_2d.py
  Regression/Checksum/benchmarks_json/Python_wrappers.json
  Regression/WarpX-tests.ini
Labels: component: documentation, component: tests, component: Python

#2629 `apt` & `conda`: Update Instructions for Deps
  Docs/source/install/dependencies.rst
Labels: component: documentation, install, machine / system

#2432 PSATD: Implement Scalar Damping for F,G
  Regression/Checksum/benchmarks_json/multi_J_2d_psatd.json
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/WarpX.H
Labels: component: spectral

#2638 CI: Reduce Runtime of Test `multi_J_2d_psatd`
  Examples/Tests/multi_J/inputs_2d
  Regression/Checksum/benchmarks_json/multi_J_2d_psatd.json
Labels: component: tests

#2634 Added 1D support to fields.py
  Python/pywarpx/fields.py
Labels: component: Python

#2632 CI: Reduce Runtime of Test `subcyclingMR`
  Examples/Tests/subcycling/inputs_2d
  Regression/Checksum/benchmarks_json/subcyclingMR.json
Labels: component: tests

#2300 C++17, CMake 3.17+
  .azure-pipelines.yml
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/install/dependencies.rst
  Docs/source/install/hpc/cori.rst
  Docs/source/install/hpc/quartz.rst
  Docs/source/install/hpc/summit.rst
  README.md
  Source/Make.WarpX
  cmake/WarpXFunctions.cmake
  pyproject.toml
  setup.py
Labels: enhancement, install

#2642 Replace AMREX_SPACEDIM: Evolve & FieldSolver
  Source/Evolve/WarpXComputeDt.cpp
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveEPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/ComovingPsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/ComovingPsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PMLPsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldData.H
  Source/FieldSolver/SpectralSolver/SpectralFieldData.cpp
  Source/FieldSolver/WarpX_QED_K.H
Labels: cleaning

#2644 C++17: structured bindings to replace "std::tie(x,y,z) = f()"
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileFromTXYEFile.cpp
  Source/Utils/MsgLogger/MsgLogger.cpp
Labels: cleaning

#2645 Perlmutter: December Update
  Docs/source/install/hpc/perlmutter.rst
Labels: component: documentation, machine / system

#2593 1D tests for plasma acceleration
  Examples/Physics_applications/laser_acceleration/PICMI_inputs_laser_acceleration.py
  Examples/Physics_applications/laser_acceleration/inputs_1d
  Examples/Physics_applications/plasma_acceleration/PICMI_inputs_plasma_acceleration_1d.py
  Python/pywarpx/picmi.py
  Regression/WarpX-tests.ini
  requirements.txt
Labels: component: tests, component: Python

#2648 CMake 3.22+: Policy CMP0127
  CMakeLists.txt
Labels: warning, install, component: third party

#2653 run_test.sh: Own virtual env
  .azure-pipelines.yml
  run_test.sh
Labels: bug, component: tests, bug: affects latest release, component: Python

#2655 GNUmake: Fix Python Install (force)
  Source/Make.WarpX
Labels: bug, install, bug: affects latest release, component: Python

#2657 Fix missing checksums1d
  Docs/source/developers/testing.rst
  Regression/Checksum/benchmarks_json/LaserAcceleration_1d.json
  Regression/Checksum/benchmarks_json/Python_PlasmaAcceleration_1d.json
Labels: bug, component: documentation, component: tests

#2656 Docs: `python3 -m pip` & Virtual Env
  Docs/README.md
  Docs/source/dataanalysis/openpmdviewer.rst
  Docs/source/dataanalysis/picviewer.rst
  Docs/source/dataanalysis/yt.rst
  Docs/source/developers/documentation.rst
  Docs/source/developers/testing.rst
  Docs/source/install/dependencies.rst
Labels: component: documentation

#2651 CMake: 3.18+
  CMakeLists.txt
  Docs/source/install/dependencies.rst
  pyproject.toml
  setup.py
Labels: bug, backend: cuda, install, component: third party

#2646 fix check for absolute library install path
  CMakeLists.txt
Labels: bug, install, bug: affects latest release

#2660 C++17: if constexpr for templates in MsgLoggerSerialization
  Source/Utils/MsgLogger/MsgLoggerSerialization.H
Labels: cleaning

#2649 fixed bug in setting the boundary potentials in 1D ES simulations
  Source/FieldSolver/ElectrostaticSolver.cpp
Labels: bug, component: electrostatic, component: boundary

#2654 `use_default_v_<galilean,comoving>` Only w/ Boosted Frame
  Source/WarpX.cpp
Labels: component: spectral

#2663 ICC CI: Unbound Vars (`setvars.sh`)
  .github/workflows/dependencies/icc.sh
  .github/workflows/intel.yml
Labels: bug, component: tests, component: third party, backend: openmp, backend: dpc++, workaround

#2661 QED openPMD Tests: Specify H5 Backend
  Regression/WarpX-tests.ini
Labels: bug, component: openPMD, component: tests, component: QED, bug: affects latest release

#2659 C++17: if constexpr for templates in ShapeFactors
  Source/Particles/ShapeFactors.H
Labels: cleaning

#2263 ABLASTR Library
  .github/workflows/ubuntu.yml
  CMakeLists.txt
  Source/FieldSolver/SpectralSolver/CMakeLists.txt
  Source/Utils/CMakeLists.txt
  cmake/WarpXFunctions.cmake
  cmake/dependencies/FFT.cmake
Labels: install

#2667 Docs: Fix Warning Logger Typo
  Docs/source/developers/warning_logger.rst
Labels: component: documentation

#2664 Python: Add 3.10, Relax upper bound
  setup.py
Labels: install, component: Python

#2635 Fixing the initialization of the EB data in ghost cells
  Source/EmbeddedBoundary/WarpXInitEB.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/WarpXRegrid.cpp
  Source/WarpX.cpp
Labels: bug: affects latest release, component: boundary

#2603 Add PML Support for multi-J Algorithm
  Examples/Tests/multi_J/inputs_2d_pml
  Regression/Checksum/benchmarks_json/multi_J_2d_psatd_pml.json
  Regression/WarpX-tests.ini
  Source/Evolve/WarpXEvolve.cpp
  Source/WarpX.cpp
Labels: component: spectral, component: boundary

#2668 Fix the scope of profiler for SYCL
  Source/main.cpp
Labels: bug, backend: dpc++

#2408 Add high energy asymptotic fit for Proton-Boron total cross section
  Source/Particles/Collision/BinaryCollision/ProtonBoronFusionCrossSection.H
Labels: component: collisions

#2650 Add anisotropic mesh refinement example
  Regression/Checksum/benchmarks_json/Langmuir_multi_2d_MR_anisotropic.json
  Regression/WarpX-tests.ini
Labels: component: tests, component: mesh refinement

#2666 AMReX/PICSAR: Weekly Update
  Regression/Checksum/benchmarks_json/PEC_particle.json
  Regression/Checksum/benchmarks_json/RepellingParticles.json
  Regression/Checksum/benchmarks_json/subcyclingMR.json
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#2561 Add load balancing test
  Examples/Tests/embedded_circle/analysis.py
  Examples/Tests/embedded_circle/inputs_2d
  Regression/Checksum/benchmarks_json/embedded_circle.json
  Regression/WarpX-tests.ini
Labels: component: tests, component: load balancing, component: boundary

#2647 Adding EB multifabs to the Python interface
  Examples/Modules/embedded_boundary_python_API/PICMI_inputs_EB_API.py
  Examples/Modules/embedded_boundary_python_API/analysis.py
  Python/pywarpx/_libwarpx.py
  Python/pywarpx/fields.py
  Regression/WarpX-tests.ini
  Source/Python/WarpXWrappers.H
  Source/Python/WarpXWrappers.cpp
  Source/WarpX.H
Labels: component: Python, component: boundary

#2652 Refactor DepositCharge so it can be called from ImpactX.
  CMakeLists.txt
  Docs/source/usage/parameters.rst
  Source/ABLASTR/DepositCharge.H
  Source/ABLASTR/Make.package
  Source/ABLASTR/ProfilerWrapper.H
  Source/Make.WarpX
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/Utils/WarpXProfilerWrapper.H
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning, component: core

#2671 Fix: `pre-commit run -a`
  Examples/Modules/embedded_boundary_python_API/PICMI_inputs_EB_API.py
  Examples/Physics_applications/laser_acceleration/3d_ascent_actions.yaml
  Regression/WarpX-tests.ini
  Source/ABLASTR/DepositCharge.H
Labels: cleaning

#2672 Fix: Missing EB `analysis.py` Permissions
  Examples/Modules/embedded_boundary_python_API/analysis.py
Labels: bug, component: tests, component: Python

#2670 pre-commit: check json
  .pre-commit-config.yaml
Labels: component: tests

#2669 CI: Remove (`particle_`)`tolerance`
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
Labels: component: tests

#2636 Cori: c-blosc Support
  Docs/source/install/hpc/cori.rst
Labels: component: documentation, component: openPMD, machine / system, component: diagnostics

#2674 Docs: Perlmutter Early Science
  Tools/BatchScripts/batch_perlmutter.sh
Labels: component: documentation, machine / system

#2625 CI: Reduce Runtime of Some Galilean Tests
  Examples/Tests/averaged_galilean/inputs_avg_3d
  Examples/Tests/comoving/inputs_2d_hybrid
  Examples/Tests/galilean/analysis_3d.py
  Examples/Tests/galilean/inputs_2d_hybrid
  Regression/Checksum/benchmarks_json/averaged_galilean_3d_psatd.json
  Regression/Checksum/benchmarks_json/averaged_galilean_3d_psatd_hybrid.json
  Regression/Checksum/benchmarks_json/comoving_2d_psatd_hybrid.json
  Regression/Checksum/benchmarks_json/galilean_2d_psatd_hybrid.json
Labels: component: spectral, component: tests

#2678 CI: Azure Cache Ignore Errors
  .azure-pipelines.yml
Labels: component: tests

#2675 ABLASTR: Cleanups & Particle Moments
  CMakeLists.txt
  Source/ABLASTR/Make.package
  Source/ABLASTR/ProfilerWrapper.H
  Source/Make.WarpX
  Source/Particles/WarpXParticleContainer.cpp
  Source/Utils/WarpXProfilerWrapper.H
  Source/ablastr/Make.package
  Source/ablastr/particles/DepositCharge.H
  Source/ablastr/particles/Make.package
  Source/ablastr/particles/ParticleMoments.H
  Source/ablastr/profiler/Make.package
  Source/ablastr/profiler/ProfilerWrapper.H
Labels: component: ABLASTR

#2662 Doxygen: Fix Diags, FieldSolver, Parallelization & Particles
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/CellCenterFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/ComputeDiagFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/DivEFunctor.H
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/FlushFormats/FlushFormatSensei.H
  Source/Diagnostics/FullDiagnostics.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/ComovingPsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/GalileanPsatdAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PMLPsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralSolver.H
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ.H
  Source/Parallelization/GuardCellManager.H
  Source/Parallelization/KernelTimer.H
  Source/Particles/Collision/BackgroundMCCCollision.H
  Source/Particles/Collision/BinaryCollision/NuclearFusionFunc.H
  Source/Particles/Collision/BinaryCollision/PairWiseCoulombCollisionFunc.H
  Source/Particles/Collision/MCCScattering.H
  Source/Particles/ElementaryProcess/QEDPairGeneration.H
  Source/Particles/ElementaryProcess/QEDPhotonEmission.H
  Source/Particles/ElementaryProcess/QEDSchwingerProcess.H
  Source/Particles/Filter/FilterFunctors.H
  Source/Particles/Gather/FieldGather.H
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/Pusher/CopyParticleAttribs.H
Labels: component: documentation, cleaning, component: core, component: diagnostics, component: load balancing

#2676 Adding inputs related to pml_in_domain to picmi.ElectromagneticSolver
  Python/pywarpx/picmi.py
Labels: component: Python, component: boundary

#2677 AMREX_SPACEDIM : EB, Filter, Laser, Utils, and Diagnostics
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.cpp
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/ReducedDiags/FieldEnergy.cpp
  Source/Diagnostics/ReducedDiags/FieldMomentum.cpp
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
  Source/Diagnostics/ReducedDiags/FieldProbeParticleContainer.cpp
  Source/Diagnostics/ReducedDiags/FieldReduction.H
  Source/Diagnostics/ReducedDiags/LoadBalanceCosts.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/EmbeddedBoundary/WarpXInitEB.cpp
  Source/Filter/BilinearFilter.cpp
  Source/Filter/Filter.cpp
  Source/Filter/NCIGodfreyFilter.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileFromTXYEFile.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileGaussian.cpp
  Source/Utils/CoarsenIO.cpp
  Source/Utils/CoarsenMR.cpp
  Source/Utils/Interpolate_K.H
  Source/Utils/WarpXMovingWindow.cpp
  Source/Utils/WarpXUtil.H
  Source/Utils/WarpXUtil.cpp
  Source/WarpX.cpp
Labels: cleaning

#2637 Wrap shared object in a class to control its loading
  Docs/source/usage/parameters.rst
  Examples/Modules/ParticleBoundaryProcess/PICMI_inputs_reflection.py
  Examples/Modules/ParticleBoundaryScrape/PICMI_inputs_scrape.py
  Examples/Modules/embedded_boundary_python_API/PICMI_inputs_EB_API.py
  Examples/Physics_applications/capacitive_discharge/PICMI_inputs_2d.py
  Examples/Tests/Langmuir/PICMI_inputs_langmuir_rz_multimode_analyze.py
  Examples/Tests/ParticleDataPython/PICMI_inputs_2d.py
  Examples/Tests/ParticleDataPython/PICMI_inputs_prev_pos_2d.py
  Examples/Tests/pass_mpi_communicator/PICMI_inputs_2d.py
  Examples/Tests/restart/PICMI_inputs_runtime_component_analyze.py
  Python/pywarpx/WarpX.py
  Python/pywarpx/WarpXPIC.py
  Python/pywarpx/__init__.py
  Python/pywarpx/_libwarpx.py
  Python/pywarpx/callbacks.py
  Python/pywarpx/fields.py
  Python/pywarpx/timestepper.py
  Python/pywarpx/wx.py
  Regression/WarpX-tests.ini
Labels: component: Python

#2680 Add RZ support in libwarpx function _get_boundary_number
  Python/pywarpx/_libwarpx.py
Labels: component: RZ, component: Python, component: boundary

#2683 Generalize Analysis Scripts: Number of Digits (plt)
  Examples/Modules/RigidInjection/analysis_rigid_injection_LabFrame.py
  Examples/Modules/ionization/analysis_ionization.py
  Examples/Modules/laser_injection/analysis_2d.py
  Examples/Modules/laser_injection/analysis_laser.py
  Examples/Modules/qed/breit_wheeler/analysis_opmd.py
  Examples/Modules/qed/breit_wheeler/analysis_yt.py
  Examples/Modules/qed/quantum_synchrotron/analysis.py
  Examples/Modules/qed/schwinger/analysis_schwinger.py
  Examples/Modules/relativistic_space_charge_initialization/analysis.py
  Examples/Modules/resampling/analysis_leveling_thinning.py
  Examples/Modules/space_charge_initialization/analysis.py
  Examples/Tests/Langmuir/analysis_langmuir_multi.py
  Examples/Tests/Langmuir/analysis_langmuir_multi_2d.py
  Examples/Tests/Langmuir/analysis_langmuir_multi_rz.py
  Examples/Tests/PEC/analysis_pec.py
  Examples/Tests/PEC/analysis_pec_mr.py
  Examples/Tests/PML/analysis_pml_ckc.py
  Examples/Tests/PML/analysis_pml_psatd.py
  Examples/Tests/PML/analysis_pml_yee.py
  Examples/Tests/RepellingParticles/analysis_repelling.py
  Examples/Tests/SilverMueller/analysis_silver_mueller.py
  Examples/Tests/SingleParticle/analysis_bilinear_filter.py
  Examples/Tests/boundaries/analysis.py
  Examples/Tests/collision/analysis_collision_2d.py
  Examples/Tests/collision/analysis_collision_3d.py
  Examples/Tests/divb_cleaning/analysis.py
  Examples/Tests/galilean/analysis_2d.py
  Examples/Tests/galilean/analysis_3d.py
  Examples/Tests/initial_distribution/analysis_distribution.py
  Examples/Tests/initial_plasma_profile/analysis.py
  Examples/Tests/particle_pusher/analysis_pusher.py
  Examples/Tests/particles_in_PML/analysis_particles_in_pml.py
  Examples/Tests/photon_pusher/analysis_photon_pusher.py
  Examples/Tests/radiation_reaction/test_const_B_analytical/analysis_classicalRR.py
  Examples/Tests/reduced_diags/analysis_reduced_diags_impl.py
  Examples/Tests/reduced_diags/analysis_reduced_diags_loadbalancecosts.py
  Examples/Tests/restart/analysis_restart.py
  Regression/Checksum/checksumAPI.py
Labels: component: tests, component: diagnostics

#2690 For Python inputs, values with temporary variables are wrapped in quotes
  Python/pywarpx/Bucket.py
Labels: bug, bug: affects latest release, component: Python

#2688 AMREX_ALWAYS_ASSERT -> AMREX_ASSERT for deposition bounds checks
  Source/Particles/WarpXParticleContainer.cpp
  Source/ablastr/particles/DepositCharge.H
Labels: Performance optimization

#2694 AMReX/PICSAR: Weekly Update
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#2697 RZ correction in 2d RZ Poisson slver
  Source/FieldSolver/ElectrostaticSolver.cpp
Labels: cleaning, component: electrostatic, component: RZ

#2698 CMake: openPMD on by default
  CMakeLists.txt
  Docs/source/developers/gnumake/openpmd.rst
  Docs/source/install/cmake.rst
  Docs/source/install/hpc/cori.rst
  Docs/source/install/hpc/juwels.rst
  Docs/source/install/hpc/lassen.rst
  Docs/source/install/hpc/ookami.rst
  Docs/source/install/hpc/perlmutter.rst
  Docs/source/install/hpc/quartz.rst
  Docs/source/install/hpc/spock.rst
  Docs/source/install/hpc/summit.rst
  setup.py
Labels: component: openPMD, install

#2699 Update AMReX (RZ Poisson)
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: electrostatic, component: third party, component: RZ

#2665 Add runtime option to use DM that is 'similar' to the mother grids in the PML.
  Docs/source/usage/parameters.rst
  Examples/Tests/PythonWrappers/PICMI_inputs_2d.py
  Regression/WarpX-tests.ini
  Source/BoundaryConditions/PML.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: Performance optimization, component: parallelization, component: boundary

#2701 Doxygen: include `static` functions
  Docs/Doxyfile
Labels: bug, component: documentation

#2705 ParticleMoments: Deduct Lambda Ret Type
  Source/ablastr/particles/ParticleMoments.H
Labels: cleaning

#2602 Add embedded BC in RZ.
  Examples/Tests/ElectrostaticSphereEB/analysis_rz.py
  Examples/Tests/ElectrostaticSphereEB/inputs_rz
  Regression/Checksum/benchmarks_json/ElectrostaticSphereEB_RZ.json
  Regression/WarpX-tests.ini
  Regression/prepare_file_ci.py
  Source/EmbeddedBoundary/WarpXFaceExtensions.cpp
  Source/EmbeddedBoundary/WarpXInitEB.cpp
  Source/FieldSolver/ElectrostaticSolver.H
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: enhancement, component: boundary

#2696 Change _libwarpx.py functions to LibWarpX class methods
  Docs/source/usage/parameters.rst
  Examples/Modules/ParticleBoundaryProcess/PICMI_inputs_reflection.py
  Examples/Modules/ParticleBoundaryScrape/PICMI_inputs_scrape.py
  Examples/Modules/embedded_boundary_python_API/PICMI_inputs_EB_API.py
  Examples/Physics_applications/capacitive_discharge/PICMI_inputs_2d.py
  Examples/Tests/Langmuir/PICMI_inputs_langmuir_rz_multimode_analyze.py
  Examples/Tests/ParticleDataPython/PICMI_inputs_2d.py
  Examples/Tests/ParticleDataPython/PICMI_inputs_prev_pos_2d.py
  Examples/Tests/pass_mpi_communicator/PICMI_inputs_2d.py
  Examples/Tests/restart/PICMI_inputs_runtime_component_analyze.py
  Python/pywarpx/PGroup.py
  Python/pywarpx/WarpX.py
  Python/pywarpx/__init__.py
  Python/pywarpx/_libwarpx.py
  Python/pywarpx/fields.py
  Python/pywarpx/picmi.py
Labels: component: Python

#2709 Clean-up in ElectrostaticSolver.cpp
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/WarpX.H
Labels: cleaning, component: electrostatic

#2706 Docs: Add Missing Default for warpx.serialize_ics
  Docs/source/usage/parameters.rst
Labels: component: documentation

#2691 Test particle scraping for EB in RZ.
  Examples/Tests/scraping/analysis_rz.py
  Examples/Tests/scraping/inputs_rz
  Regression/Checksum/benchmarks_json/scraping.json
  Regression/WarpX-tests.ini
  Source/EmbeddedBoundary/DistanceToEB.H
  Source/EmbeddedBoundary/ParticleScraper.H
  Source/Particles/Gather/ScalarFieldGather.H
Labels: component: RZ, component: boundary

#2713 CI: mpi4py breaking setuptools API
  .github/workflows/cuda.yml
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  run_test.sh
Labels: component: tests, component: third party, workaround

#2556 Regression Testing: Use Mainline & CMake
  .azure-pipelines.yml
  CMakeLists.txt
  Docs/source/developers/testing.rst
  Examples/Modules/laser_injection_from_file/analysis.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  Tools/Release/updatePICSAR.py
  run_test.sh
Labels: component: tests
