Repository BLAST-WarpX/warpx, pull requests merged in 2022-06, with the labels that each got.

#3064 Boundary scraping diagnostic
  Docs/source/usage/parameters.rst
  Examples/Tests/scraping/analysis_rz.py
  Examples/Tests/scraping/inputs_rz
  Regression/WarpX-tests.ini
  Regression/requirements.txt
  Source/Diagnostics/BoundaryScrapingDiagnostics.H
  Source/Diagnostics/BoundaryScrapingDiagnostics.cpp
  Source/Diagnostics/CMakeLists.txt
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Make.package
  Source/Diagnostics/MultiDiagnostics.H
  Source/Diagnostics/MultiDiagnostics.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Particles/ParticleBoundaryBuffer.H
  Source/Particles/ParticleBoundaryBuffer.cpp
Labels: component: openPMD, component: boundary

#3152 Crusher: Update Modules
  Tools/machines/crusher-olcf/crusher_warpx.profile.example
Labels: backend: hip, machine / system

#2531 Clean-up in python wrappers to access particle data
  Source/Python/WarpXWrappers.cpp
Labels: bug, cleaning, component: third party, bug: affects latest release

#3092 Change Default for `psatd.current_correction`
  Docs/source/usage/parameters.rst
  Regression/WarpX-tests.ini
  Source/Evolve/WarpXEvolve.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: bug, component: spectral, changes input scripts / defaults, bug: affects latest release

#3154 Move warning logger in ablastr
  Docs/source/developers/warning_logger.rst
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
  Source/Diagnostics/SliceDiagnostic.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/EmbeddedBoundary/WarpXFaceExtensions.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.cpp
  Source/Initialization/PlasmaInjector.cpp
  Source/Initialization/TemperatureProperties.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileFromTXYEFile.cpp
  Source/Particles/LaserParticleContainer.cpp
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Resampling/LevelingThinning.cpp
  Source/Python/WarpXWrappers.cpp
  Source/Utils/CMakeLists.txt
  Source/Utils/MPIInitHelpers.cpp
  Source/Utils/Make.package
  Source/Utils/WarnManager_fwd.H
  Source/WarpX.H
  Source/WarpX.cpp
  Source/ablastr/CMakeLists.txt
  Source/ablastr/Make.package
  Source/ablastr/warn_manager/CMakeLists.txt
  Source/ablastr/warn_manager/Make.package
  Source/ablastr/warn_manager/WarnManager.H
  Source/ablastr/warn_manager/WarnManager.cpp
  Source/main.cpp
Labels: component: ABLASTR

#3159 Fix: WarnManager
  Source/WarpX.cpp
Labels: bug

#3158 Doc: adding few more references on numerical algorithms
  Docs/source/acknowledge_us.rst
Labels: component: documentation

#2958 Vay Deposition: Add Cumulative Sums
  Examples/Tests/VayDeposition/analysis.py
  Examples/Tests/VayDeposition/inputs_2d
  Examples/Tests/VayDeposition/inputs_3d
  Regression/Checksum/benchmarks_json/VayDeposition2D.json
  Regression/Checksum/benchmarks_json/VayDeposition3D.json
  Regression/WarpX-tests.ini
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/WarpX.H
Labels: component: spectral

#3161 Release 22.06
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#3162 Fix for 1D CUDA builds
  Source/Laser/LaserProfilesImpl/LaserProfileFromTXYEFile.cpp
Labels: bug, backend: cuda, bug: affects latest release

#3013 Merge `FillBoundary` and `NodalSync` (`OneStep_nosub`, `OneStep_sub1`)
  Examples/Tests/PythonWrappers/PICMI_inputs_2d.py
  Regression/Checksum/benchmarks_json/Python_wrappers.json
  Regression/Checksum/benchmarks_json/divb_cleaning_3d.json
  Regression/Checksum/benchmarks_json/reduced_diags_single_precision.json
  Source/Evolve/WarpXEvolve.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/Parallelization/WarpXCommUtil.H
  Source/Parallelization/WarpXCommUtil.cpp
  Source/WarpX.H
Labels: Performance optimization, component: parallelization

#3167 ABLASTR: Move Communication Utilities
  Source/BoundaryConditions/PML.cpp
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.cpp
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/SliceDiagnostic.cpp
  Source/Diagnostics/WarpXIO.cpp
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/CMakeLists.txt
  Source/Parallelization/Make.package
  Source/Parallelization/WarpXComm.cpp
  Source/Parallelization/WarpXCommUtil.H
  Source/Parallelization/WarpXSumGuardCells.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/Utils/WarpXMovingWindow.cpp
  Source/ablastr/utils/CMakeLists.txt
  Source/ablastr/utils/Communication.H
  Source/ablastr/utils/Communication.cpp
  Source/ablastr/utils/Make.package
Labels: component: parallelization, component: ABLASTR

#3170 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3173 Fix: ABLASTR CMake Build (macOS)
  Source/ablastr/utils/msg_logger/CMakeLists.txt
Labels: bug, install, component: ABLASTR

#3172 Summit: Fix BLAS++/LAPACK++ Modules
  Tools/machines/summit-olcf/summit_warpx.profile.example
Labels: bug, backend: cuda, component: spectral, component: third party, bug: affects latest release, machine / system, component: RZ

#3174 Update glossary.rst
  Docs/source/glossary.rst
Labels: component: documentation

#3171 openPMD-api: 0.14.5
  cmake/dependencies/openPMD.cmake
Labels: component: openPMD, install, component: third party

#3181 CMake: AMReX_PIC (`-fPIC`) for ABLASTR
  cmake/dependencies/AMReX.cmake
Labels: bug, install, bug: affects latest release

#3177 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3180 CMake: Generalize `CMAKE_INSTALL_CMAKEDIR`
  CMakeLists.txt
  cmake/WarpXFunctions.cmake
Labels: install, component: ABLASTR

#2994 ABLASTR: Compute Phi
  Source/FieldSolver/ElectrostaticSolver.H
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/WarpX.H
  Source/WarpX.cpp
  Source/ablastr/CMakeLists.txt
  Source/ablastr/fields/PoissonSolver.H
Labels: component: electrostatic, component: ABLASTR

#3175 Extract function for two-particle fusion reaction
  Source/Particles/Collision/BinaryCollision/NuclearFusion/ProtonBoronFusionInitializeMomentum.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/TwoProductFusionUtil.H
Labels: cleaning

#3187 Docs: Move LPI Experiment
  Docs/source/highlights.rst
Labels: component: documentation

#3190 Remove temporary copy of MultiFab
  Source/ablastr/utils/Communication.cpp
Labels: Performance optimization, component: parallelization, component: ABLASTR

#3193 Fix missing newline in documentation
  Docs/source/usage/parameters.rst
Labels: component: documentation

#3192 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/Checksum/benchmarks_json/background_mcc_dp_psp.json
  Regression/Checksum/benchmarks_json/reduced_diags_single_precision.json
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3197 Remove Unused Function `getcurrent`
  Source/WarpX.H
Labels: cleaning

#2419 Added `none` as an option for fields_to_plot
  Docs/source/usage/parameters.rst
  Examples/Modules/gaussian_beam/PICMI_inputs_gaussian_beam.py
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/LaserIonAcc2d_no_field_diag.json
  Regression/WarpX-tests.ini
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/FullDiagnostics.cpp
Labels: component: diagnostics
