Repository BLAST-WarpX/warpx, pull requests merged in 2022-08, with the labels that each got.

#3276 Release 22.08
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#3275 [mini] Remove duplicated parameter in QED inputs
  Examples/Modules/qed/breit_wheeler/inputs_2d
  Examples/Modules/qed/breit_wheeler/inputs_3d
  Examples/Modules/qed/quantum_synchrotron/inputs_2d
  Examples/Modules/qed/quantum_synchrotron/inputs_3d
Labels: component: tests, cleaning, component: QED

#3277 `SyncCurrent`: Pass References To Current MultiFabs
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/Python/WarpXWrappers.H
  Source/Python/WarpXWrappers.cpp
  Source/WarpX.H
Labels: component: parallelization

#3274 Implement output of scraped particles at domain boundaries
  Docs/source/usage/parameters.rst
  Examples/Tests/embedded_circle/inputs_2d
  Examples/Tests/scraping/analysis_rz.py
  Regression/WarpX-tests.ini
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/BoundaryScrapingDiagnostics.H
  Source/Diagnostics/BoundaryScrapingDiagnostics.cpp
  Source/Diagnostics/FlushFormats/FlushFormat.H
  Source/Diagnostics/FlushFormats/FlushFormatAscent.H
  Source/Diagnostics/FlushFormats/FlushFormatAscent.cpp
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.H
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.H
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.H
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/FlushFormats/FlushFormatSensei.H
  Source/Diagnostics/FlushFormats/FlushFormatSensei.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Particles/ParticleBoundaryBuffer.H
  Source/Particles/ParticleBoundaryBuffer.cpp
Labels: enhancement, component: openPMD, component: diagnostics, component: boundary

#3264 Docs: Lassen HDF5 Perf. Hints
  Tools/machines/lassen-llnl/lassen.bsub
  Tools/machines/summit-olcf/summit_v100.bsub
Labels: component: documentation, component: openPMD

#3284 Docs: Update Intro PFS OLCF
  Docs/source/install/hpc/cori.rst
  Docs/source/install/hpc/crusher.rst
  Docs/source/install/hpc/frontier.rst
  Docs/source/install/hpc/juwels.rst
  Docs/source/install/hpc/lassen.rst
  Docs/source/install/hpc/lawrencium.rst
  Docs/source/install/hpc/lxplus.rst
  Docs/source/install/hpc/ookami.rst
  Docs/source/install/hpc/perlmutter.rst
  Docs/source/install/hpc/quartz.rst
  Docs/source/install/hpc/spock.rst
  Docs/source/install/hpc/summit.rst
Labels: component: documentation

#3287 Regressions: remove tolerance
  Regression/WarpX-tests.ini
Labels: Performance optimization, component: tests, component: third party, machine / system

#3218 Species variables in diagnostics: deal with runtime components
  Examples/Modules/qed/breit_wheeler/inputs_2d
  Examples/Modules/qed/breit_wheeler/inputs_3d
  Examples/Modules/qed/quantum_synchrotron/inputs_2d
  Examples/Modules/qed/quantum_synchrotron/inputs_3d
  Examples/Physics_applications/laser_acceleration/inputs_rz
  Examples/Physics_applications/laser_ion/inputs
  Regression/Checksum/benchmarks_json/LaserIonAcc2d.json
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/ParticleDiag/ParticleDiag.H
  Source/Diagnostics/ParticleDiag/ParticleDiag.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
Labels: changes input scripts / defaults, component: diagnostics

#3288 Coarsen IO : tmp mf to be constructed with ngrowvect
  Source/Utils/CoarsenIO.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#3285 Use extended box array in setting par GDB for BTD
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformParticleFunctor.cpp
Labels: bug, bug: affects latest release, component: diagnostics, component: boosted frame

#3291 Doc: PICMI Parameters
  Docs/requirements.txt
  Docs/source/usage/python.rst
  requirements.txt
Labels: component: documentation, component: PICMI, component: Python

#3294 Fix out of bounds array access with Particle Scraping + Continuous Injection
  Source/EmbeddedBoundary/ParticleScraper.H
Labels: bug, bug: affects latest release

#3286 PICMI: Fix Bug in Class `Species` Init
  Python/pywarpx/picmi.py
Labels: bug, component: PICMI, bug: affects latest release

#3272 Initialize particle runtime attributes inside AddNParticles
  Examples/Modules/RigidInjection/analysis_rigid_injection_LabFrame.py
  Examples/Modules/RigidInjection/inputs_2d_LabFrame
  Python/pywarpx/_libwarpx.py
  Regression/Checksum/benchmarks_json/RigidInjection_lab.json
  Source/Particles/LaserParticleContainer.H
  Source/Particles/LaserParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/Python/WarpXWrappers.H
  Source/Python/WarpXWrappers.cpp
Labels: bug, component: QED, bug: affects latest release, component: Python

#3307 `isort`: AMReX, WarpX, etc. as First Party
  .editorconfig
  Examples/Modules/embedded_boundary_python_API/PICMI_inputs_EB_API.py
  Examples/Physics_applications/capacitive_discharge/PICMI_inputs_1d.py
  Examples/Physics_applications/capacitive_discharge/PICMI_inputs_2d.py
  Examples/Tests/Langmuir/PICMI_inputs_langmuir_rz_multimode_analyze.py
  Examples/Tests/ParticleDataPython/PICMI_inputs_2d.py
  Examples/Tests/ParticleDataPython/PICMI_inputs_prev_pos_2d.py
  Examples/Tests/PythonWrappers/PICMI_inputs_2d.py
  Examples/Tests/pass_mpi_communicator/PICMI_inputs_2d.py
  Examples/Tests/restart/PICMI_inputs_runtime_component_analyze.py
  Python/pywarpx/WarpInterface.py
  Python/pywarpx/picmi.py
Labels: component: tests, component: Python

#3304 Docs: Add Input Parameter `psatd.use_default_v_galilean`
  Docs/source/usage/parameters.rst
Labels: component: spectral, component: documentation

#3309 Enable Particle RZ BackTransformed Diagnostics
  Source/Diagnostics/ComputeDiagFunctors/BackTransformParticleFunctor.H
  Source/Diagnostics/MultiDiagnostics.cpp
Labels: enhancement, component: openPMD, component: diagnostics, component: RZ

#3302 Fill Guard Cells of Fields and Currents Independently
  Source/BoundaryConditions/PML.H
  Source/BoundaryConditions/PML.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmComoving.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmComoving.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmJLinearInTime.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmJLinearInTime.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPml.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPml.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldData.H
  Source/FieldSolver/SpectralSolver/SpectralFieldData.cpp
  Source/FieldSolver/SpectralSolver/SpectralSolver.H
  Source/FieldSolver/SpectralSolver/SpectralSolver.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: spectral, component: parallelization

#3315 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3225 Move handling of do_not_deposit to physics callers
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/Particles/LaserParticleContainer.cpp
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/Python/WarpXWrappers.cpp
Labels: component: electrostatic, component: Python

#3312 Windows CI: Abort on First Error
  .github/workflows/windows.yml
Labels: bug, component: tests, bug: affects latest release, machine / system

#3313 ABLASTR: Fix Missing Include utils::communication
  Source/ablastr/utils/Communication.H
  Source/ablastr/utils/Communication.cpp
Labels: bug, cleaning, component: ABLASTR

#3314 Docs: Add NAPAC'22 Paper
  Docs/source/acknowledge_us.rst
Labels: component: documentation

#3281 Allow filtering in z with RZ FDTD
  Examples/Physics_applications/laser_acceleration/inputs_rz
  Regression/Checksum/benchmarks_json/LaserAccelerationRZ.json
  Source/WarpX.cpp
Labels: component: RZ, component: FDTD

#3303 Docs: Lassen Disable MPI-I/O file lock
  Tools/machines/lassen-llnl/lassen.bsub
Labels: component: documentation, component: openPMD, component: third party, machine / system

#3320 Wheel: Separate Directory
  .github/workflows/windows.yml
  CMakeLists.txt
  MANIFEST.in
Labels: bug, install, bug: affects latest release, machine / system

#3325 Fix Docs for `psatd.update_with_rho`
  Docs/source/usage/parameters.rst
  Source/WarpX.cpp
Labels: component: documentation

#3316 ABLASTR: Profile OverrideSync
  Source/ablastr/utils/Communication.cpp
Labels: component: parallelization

#3330 shift BTD lab frame bounds by half a cell to prevent round off errors
  Source/Diagnostics/BTDiagnostics.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#3328 Updates to Docs/README.md
  Docs/README.md
Labels: component: documentation

#3332 Remove outdated comments from example inputfiles
  Examples/Physics_applications/laser_acceleration/inputs_1d
  Examples/Physics_applications/laser_acceleration/inputs_2d
  Examples/Physics_applications/laser_acceleration/inputs_3d
  Examples/Physics_applications/laser_acceleration/inputs_rz
  Regression/TestFillBoundary/inputs.2d
Labels: cleaning

#3322 CI: Clean up Analysis of Galilean Tests
  Examples/Tests/galilean/analysis.py
  Examples/Tests/galilean/analysis_2d.py
  Examples/Tests/galilean/analysis_3d.py
  Regression/WarpX-tests.ini
Labels: component: tests

#3333 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3326 Docs: Spack Desktop Environment
  Docs/source/install/dependencies.rst
  Tools/machines/desktop/spack-macos-openmp.yaml
  Tools/machines/desktop/spack-ubuntu-cuda.yaml
  Tools/machines/desktop/spack-ubuntu-openmp.yaml
  Tools/machines/desktop/spack-ubuntu-rocm.yaml
Labels: component: documentation, install, machine / system

#3269 Performance Hint: Too Many Boxes / GPU
  Source/Initialization/WarpXInitData.cpp
Labels: backend: cuda, Performance optimization, backend: hip, backend: dpc++

#3266 MultiParticleContainer: Prevent Bugs in Some `setVal` Calls
  Source/Particles/MultiParticleContainer.cpp
Labels: bug, cleaning

#3102 Docs: Improve Nsight Systems Section
  Docs/source/developers/profiling.rst
Labels: component: documentation

#3338 order-independent rho_<species> in RZ + openPMD
  Examples/Tests/openpmd_rz/analysis_openpmd_rz.py
  Regression/WarpX-tests.ini
  Source/Diagnostics/FullDiagnostics.cpp
Labels: bug, component: openPMD, bug: affects latest release, component: diagnostics, component: RZ

#3318 Fixed plasma lens residence correction to allow a short lens
  Examples/Tests/plasma_lens/analysis.py
  Examples/Tests/plasma_lens/inputs_short_3d
  Regression/Checksum/benchmarks_json/Plasma_lens_short.json
  Regression/WarpX-tests.ini
  Source/Particles/Gather/GetExternalFields.H
Labels: bug

#3290 Fix Bugs w/ Current Correction and Vay Deposition
  Examples/Tests/galilean/analysis.py
  Regression/Checksum/benchmarks_json/galilean_2d_psatd_current_correction.json
  Regression/Checksum/benchmarks_json/galilean_2d_psatd_current_correction_psb.json
  Regression/Checksum/benchmarks_json/galilean_3d_psatd_current_correction.json
  Regression/Checksum/benchmarks_json/galilean_3d_psatd_current_correction_psb.json
  Regression/Checksum/benchmarks_json/galilean_rz_psatd_current_correction.json
  Regression/Checksum/benchmarks_json/galilean_rz_psatd_current_correction_psb.json
  Regression/WarpX-tests.ini
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: bug, component: spectral, bug: affects latest release

#3310 Docs: Add description of Python APIs in `libwarpx`
  Docs/source/usage/python.rst
  Python/pywarpx/_libwarpx.py
  Python/pywarpx/callbacks.py
Labels: component: documentation

#3342 Python: 3.7+
  .github/workflows/cuda.yml
  Docs/source/dataanalysis/plot_parallel.rst
  Docs/source/developers/gnumake/python.rst
  Docs/source/install/dependencies.rst
  Docs/source/usage/python.rst
  Python/setup.py
  setup.py
Labels: component: documentation, install, component: Python

#3348 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3346 Fix few "magic constants" & undefined variables found with clang-tidy
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Diagnostics/ReducedDiags/ReducedDiags.cpp
  Source/Diagnostics/SliceDiagnostic.cpp
Labels: cleaning, component: boosted frame

#3349 Perlmutter: Work-Around CUDA-Aware MPI & Slurm
  Tools/machines/perlmutter-nersc/perlmutter.sbatch
Labels: backend: cuda, component: documentation, machine / system, component: parallelization, workaround

#3354 Make permission_flag_rwxrxrx a constexpr variable
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Diagnostics/ReducedDiags/ReducedDiags.cpp
Labels: cleaning
