Repository BLAST-WarpX/warpx, pull requests merged in 2022-05, with the labels that each got.

#3079 Doc: Update Perlmutter Python/HDF5
  Tools/machines/perlmutter-nersc/perlmutter_warpx.profile.example
Labels: component: documentation, install, machine / system

#3074 abort if BTD selected for RZ, and unsupported field/particle varnames
  Docs/source/usage/parameters.rst
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Diagnostics/MultiDiagnostics.cpp
Labels: bug, bug: affects latest release, component: diagnostics, component: RZ

#3076 Release 22.05
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  Source/FieldSolver/ElectrostaticSolver.cpp
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#3070 Add velocity in pml as an input in function alpha
  Source/BoundaryConditions/PML.H
  Source/BoundaryConditions/PML.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: changes input scripts / defaults, component: boundary

#3081 ABLASTR: `-fPIC` Control
  CMakeLists.txt
Labels: bug, install, bug: affects latest release, component: ABLASTR

#3082 Close #3077 Fix RZ openPMD output with MR
  Examples/Tests/scraping/inputs_rz
  Source/Diagnostics/FullDiagnostics.cpp
Labels: bug, component: openPMD, component: mesh refinement, bug: affects latest release, component: RZ

#3058 Nuclear fusion: remove underflow warning in single precision
  Source/Particles/Collision/BinaryCollision/NuclearFusion/ProtonBoronFusionInitializeMomentum.H
Labels: warning, component: collisions

#3084 Fix openPMD RZ with load-balancing
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.cpp
Labels: bug, component: openPMD, bug: affects latest release, component: load balancing, component: RZ

#3083 Fix miscellaneous issues found with clang tidy
  Source/BoundaryConditions/WarpXFieldBoundaries.cpp
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/ReducedDiags/LoadBalanceCosts.cpp
  Source/FieldSolver/WarpX_QED_Field_Pushers.cpp
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Parallelization/WarpXRegrid.cpp
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
Labels: cleaning

#3036 Add a python script to generate timestep duration plots
  Docs/source/usage/workflows.rst
  Docs/source/usage/workflows/plot_timestep_duration.rst
  Tools/PostProcessing/plot_timestep_duration.py
Labels: component: post-processing

#3094 Apply shift for zmax>0 in old BTD
  Source/Diagnostics/BackTransformedDiagnostic.cpp
Labels: bug, bug: affects latest release, component: diagnostics, component: boosted frame

#2952 Use uniform error message formatting for all the amrex::Abort() calls in WarpX.cpp
  Source/WarpX.cpp
Labels: cleaning

#3096 Use queryWithParser to Parse v_particle_pml
  Docs/source/usage/parameters.rst
  Source/WarpX.cpp
Labels: changes input scripts / defaults

#3098 Fix Wrong Abort Message for PSATD w/ Time Averaging
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.cpp
Labels: bug, component: spectral, bug: affects latest release

#3099 Doc: Improve Doxygen Links
  .gitignore
  Docs/Doxyfile
  Docs/source/conf.py
  Docs/source/developers/doxygen.rst
Labels: component: documentation, component: third party

#3101 Fix mirrors for RZ
  Source/Utils/WarpXUtil.cpp
Labels: bug, bug: affects latest release, component: RZ

#3106 Fix Breaking Pip 22.1 Logic
  .github/workflows/windows.yml
  CMakeLists.txt
  Docs/source/install/cmake.rst
  Docs/source/install/hpc/lxplus.rst
  run_test.sh
Labels: install, component: third party, component: Python, workaround

#3104 Fix Laser Injection in RZ
  Source/Particles/LaserParticleContainer.cpp
Labels: bug, bug: affects latest release, component: RZ

#3089 Add STL files support in pywarpx
  Python/pywarpx/EB2.py
  Python/pywarpx/WarpX.py
  Python/pywarpx/__init__.py
  Python/pywarpx/picmi.py
Labels: enhancement, component: Python, component: boundary

#3097 Stricter Tolerance for 3D Langmuir Tests
  Examples/Tests/Langmuir/analysis_langmuir_multi.py
Labels: component: tests

#3111 CI: HIP with https
  .github/workflows/dependencies/hip.sh
Labels: component: tests, backend: hip

#3093 Add Headers to Input File Written by PICMI
  Python/pywarpx/WarpX.py
Labels: cleaning, component: Python

#3112 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
Labels: component: third party

#2964 Use uniform error message formatting in more source files
  Source/BoundaryConditions/PML.cpp
  Source/Diagnostics/BTD_Plotfile_Header_Impl.cpp
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FieldIO.cpp
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp
  Source/Diagnostics/FlushFormats/FlushFormatSensei.cpp
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/MultiDiagnostics.cpp
  Source/Diagnostics/ParticleIO.cpp
  Source/Diagnostics/ReducedDiags/FieldMomentum.cpp
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
  Source/Diagnostics/ReducedDiags/LoadBalanceCosts.cpp
  Source/Diagnostics/ReducedDiags/MultiReducedDiags.cpp
  Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp
  Source/Diagnostics/ReducedDiags/ReducedDiags.cpp
  Source/Diagnostics/SliceDiagnostic.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/EmbeddedBoundary/WarpXInitEB.cpp
  Source/Evolve/WarpXComputeDt.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/FiniteDifferenceSolver/ApplySilverMuellerBoundary.cpp
  Source/FieldSolver/FiniteDifferenceSolver/ComputeDivE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveB.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveBPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveECTRho.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveEPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveF.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveFPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveG.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.cpp
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicEvolveE.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmComoving.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmGalileanRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmJLinearInTime.cpp
  Source/FieldSolver/SpectralSolver/WrapCuFFT.cpp
  Source/FieldSolver/SpectralSolver/WrapFFTW.cpp
  Source/FieldSolver/SpectralSolver/WrapRocFFT.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/FieldSolver/WarpX_QED_Field_Pushers.cpp
  Source/Utils/WarpXUtil.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#3068 Avoid resizing ParticleBoundaryBuffer allocation to total particle count
  Source/Particles/ParticleBoundaryBuffer.cpp
Labels: Performance optimization, component: core, component: boundary

#3071 Lassen (LLNL): ADIOS2, BLAS++ & LAPACK++
  Docs/source/install/hpc/lassen.rst
  Tools/machines/lassen-llnl/lassen_warpx.profile.example
Labels: component: documentation, install, machine / system

#3115 ABLASTR: localIDtoGlobal
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Utils/WarpXUtil.H
  Source/ablastr/particles/IndexHandling.H
Labels: component: diagnostics, component: parallelization, component: ABLASTR

#3122 Clarify error messages when parsing diagnostics input
  Source/Diagnostics/Diagnostics.cpp
Labels: component: diagnostics

#3067 Add do_average option to the particle fields diagnostic
  Docs/source/usage/parameters.rst
  Examples/Tests/particle_fields_diags/analysis_particle_diags_impl.py
  Examples/Tests/particle_fields_diags/inputs
  Regression/Checksum/benchmarks_json/particle_fields_diags.json
  Regression/Checksum/benchmarks_json/particle_fields_diags_single_precision.json
  Source/Diagnostics/ComputeDiagFunctors/ParticleReductionFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/ParticleReductionFunctor.cpp
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.cpp
Labels: changes input scripts / defaults, component: diagnostics

#3120 Fix unnecessary float to double promotions
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/SliceDiagnostic.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileFromTXYEFile.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: Performance optimization, cleaning

#3125 Use forward declaration for WarpXFaceInfoBox
  Source/EmbeddedBoundary/WarpXFaceExtensions.cpp
  Source/EmbeddedBoundary/WarpXFaceInfoBox.H
  Source/EmbeddedBoundary/WarpXFaceInfoBox_fwd.H
  Source/FieldSolver/FiniteDifferenceSolver/EvolveB.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/Parallelization/WarpXRegrid.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning, component: boundary

#3124 Remove unused enum from PhysicalParticleContainer
  Source/Particles/PhysicalParticleContainer.H
Labels: cleaning

#3126 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
Labels: component: third party

#3107 Fold Python tests into their corresponding base configurations, to better exploit ccache
  .azure-pipelines.yml
  .github/workflows/source/test_ci_matrix.sh
  Regression/WarpX-tests.ini
  Regression/prepare_file_ci.py
Labels: Performance optimization, component: tests

#3127 Docs: New Perlmutter Default Env, Microarch
  Tools/machines/perlmutter-nersc/perlmutter_warpx.profile.example
Labels: Performance optimization, component: documentation, machine / system

#3116 CMake Pip: Unique Custom Targets
  CMakeLists.txt
Labels: enhancement, install, component: Python

#3026 Simplify the function computePhi
  Source/FieldSolver/ElectrostaticSolver.cpp
Labels: cleaning, component: electrostatic

#3065 Specify particle precision
  CMakeLists.txt
  Docs/source/install/cmake.rst
  Python/pywarpx/_libwarpx.py
  Regression/Checksum/benchmarks_json/background_mcc_dp_psp.json
  Regression/WarpX-tests.ini
  Source/Diagnostics/ComputeDiagFunctors/ParticleReductionFunctor.cpp
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
  Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Particles/Collision/BinaryCollision/Coulomb/PairWiseCoulombCollisionFunc.H
  Source/Particles/Collision/BinaryCollision/Coulomb/UpdateMomentumPerezElastic.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/SingleNuclearFusionEvent.H
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineWrapper.H
  Source/Particles/Filter/FilterFunctors.H
  Source/Particles/Gather/GetExternalFields.H
  Source/Particles/LaserParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Utils/WarpXUtil.H
  Source/Utils/WarpXUtil.cpp
  cmake/WarpXFunctions.cmake
  cmake/dependencies/AMReX.cmake
  setup.py
Labels: install, component: core

#3129 Test Filter: Include Python Langmuir
  Regression/Checksum/benchmarks_json/Python_Langmuir.json
  Regression/prepare_file_ci.py
Labels: bug, component: tests, bug: affects latest release, component: Python

#3138 PML.cpp: missing util include
  Source/BoundaryConditions/PML.cpp
Labels: bug, bug: affects latest release

#3134 Fix: Field Probe no-MPI Gather
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
Labels: bug, component: third party, bug: affects latest release, component: parallelization

#3140 SpectralFieldDataRZ: Missing Utils Include
  Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.cpp
Labels: bug, bug: affects latest release

#3141 Fix: Install ABLASTR
  CMakeLists.txt
Labels: bug, install, bug: affects latest release

#3132 Write Inputs to `warpx_used_inputs`
  Docs/source/usage/how_to_run.rst
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
Labels: changes input scripts / defaults, component: core, component: diagnostics

#3143 Docs: Improve `collision_name>.species`
  Docs/source/usage/parameters.rst
Labels: component: documentation

#3144 remove extraneous WARPX_DIM_RZ
  Source/Laser/LaserProfilesImpl/LaserProfileGaussian.cpp
Labels: bug, bug: affects latest release, component: RZ

#3145 Move serialization to ablastr
  Source/Utils/MsgLogger/MsgLogger.cpp
  Source/ablastr/utils/Serialization.H
Labels: component: ABLASTR

#3117 Use Utils::TextMsg::Err and WARPX_ALWAYS_ASSERT_WITH_MESSAGE in more files
  Source/Diagnostics/FullDiagnostics.cpp
  Source/EmbeddedBoundary/WarpXFaceExtensions.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmJLinearInTime.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPml.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPmlRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.cpp
  Source/Filter/Filter.cpp
  Source/Filter/NCIGodfreyFilter.cpp
  Source/Initialization/PlasmaInjector.cpp
  Source/Initialization/TemperatureProperties.cpp
  Source/Initialization/VelocityProperties.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileFieldFunction.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileFromTXYEFile.cpp
  Source/WarpX.cpp
Labels: cleaning

#3148 Move MsgLogger to ablastr
  Source/Utils/CMakeLists.txt
  Source/Utils/Make.package
  Source/Utils/MsgLogger/Make.package
  Source/Utils/WarnManager.H
  Source/Utils/WarnManager.cpp
  Source/WarpX.cpp
  Source/ablastr/utils/CMakeLists.txt
  Source/ablastr/utils/Make.package
  Source/ablastr/utils/msg_logger/CMakeLists.txt
  Source/ablastr/utils/msg_logger/Make.package
  Source/ablastr/utils/msg_logger/MsgLogger.H
  Source/ablastr/utils/msg_logger/MsgLogger.cpp
  Source/ablastr/utils/msg_logger/MsgLogger_fwd.H
Labels: component: ABLASTR

#3147 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3139 Docs: Science Highlights
  Docs/source/acknowledge_us.rst
  Docs/source/highlights.rst
  Docs/source/index.rst
Labels: help wanted, component: documentation

#2450 Add 3D tests for proton boron fusion
  Examples/Modules/nuclear_fusion/analysis_proton_boron_fusion.py
  Examples/Modules/nuclear_fusion/inputs_3d
  Regression/Checksum/benchmarks_json/Proton_Boron_Fusion_3D.json
  Regression/WarpX-tests.ini
Labels: component: tests

#3149 AMReX no-MPI Gather Fixed
  .github/workflows/ubuntu.yml
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
Labels: component: tests, component: third party, component: diagnostics, workaround
