Repository BLAST-WarpX/warpx, pull requests merged in 2022-11, with the labels that each got.

#3493 Perlmutter (NERSC): Update Modules & Jobscript
  Docs/source/install/hpc/perlmutter.rst
  Tools/machines/perlmutter-nersc/perlmutter.sbatch
  Tools/machines/perlmutter-nersc/perlmutter_warpx.profile.example
Labels: component: documentation, machine / system

#3496 CUDA CI: Ubuntu 20.04+
  .github/workflows/cuda.yml
  .github/workflows/dependencies/nvcc11-0.sh
  .github/workflows/dependencies/nvcc11-8.sh
Labels: backend: cuda, component: tests

#3499 Release 22.11
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#3477 Allow arbitrary laser antenna normal in picmi
  Python/pywarpx/picmi.py
Labels: component: PICMI

#3495 Perlmutter (NERSC): Finish Affinity Control
  Tools/machines/perlmutter-nersc/perlmutter.sbatch
  Tools/machines/perlmutter-nersc/perlmutter_warpx.profile.example
Labels: backend: cuda, component: documentation, machine / system

#3498 Summit (OLCF): Jupyter GPFS HDF5 Issues
  Docs/source/install/hpc/summit.rst
Labels: component: documentation, component: openPMD, machine / system, workaround

#3502 Docs: Dependencies w/ Ascent & SENSEI
  Docs/source/install/dependencies.rst
Labels: component: documentation, component: diagnostics

#3503 CMake: AMReX_INSTALL Update (Shared)
  cmake/dependencies/AMReX.cmake
Labels: install

#3456 Add SymPy Notebook to Derive PSATD Equations
  Tools/Algorithms/psatd.ipynb
Labels: component: spectral

#3505 Clean Species Physical Properties
  Docs/source/usage/parameters.rst
  Source/Particles/SpeciesPhysicalProperties.cpp
Labels: bug, cleaning, bug: affects latest release

#3508 Load balancing bug fix: remake MultiFabs for Vay deposition, current centering, time averaging
  Source/Parallelization/WarpXRegrid.cpp
Labels: bug, bug: affects latest release, component: load balancing

#3504 Allow `None` for Maxwell solver
  Examples/Tests/collision/inputs_2d
  Examples/Tests/collision/inputs_3d
  Examples/Tests/collision/inputs_rz
  Examples/Tests/scraping/inputs_rz
  Source/BoundaryConditions/PML.cpp
  Source/Diagnostics/ComputeDiagFunctors/DivEFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/RhoFunctor.cpp
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Evolve/WarpXComputeDt.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/FieldSolver/FiniteDifferenceSolver/ApplySilverMuellerBoundary.cpp
  Source/FieldSolver/FiniteDifferenceSolver/ComputeDivE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveB.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveBPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveECTRho.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveEPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveF.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveFPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveG.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.cpp
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicEvolveE.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/GuardCellManager.H
  Source/Parallelization/GuardCellManager.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/Parallelization/WarpXRegrid.cpp
  Source/Parallelization/WarpXSumGuardCells.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/Utils/WarpXAlgorithmSelection.H
  Source/Utils/WarpXAlgorithmSelection.cpp
  Source/Utils/WarpXUtil.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: core

#3501 Docs: Improve MPI Threading User FAQ
  Docs/source/usage/faq.rst
Labels: component: documentation

#3485 BTD: remove old/legacy back-transformed diagnostics
  Docs/source/usage/parameters.rst
  Examples/Modules/RigidInjection/analysis_rigid_injection_BoostedFrame.py
  Examples/Modules/RigidInjection/inputs_2d_BoostedFrame
  Examples/Modules/boosted_diags/analysis.py
  Examples/Modules/boosted_diags/inputs_3d
  Examples/Physics_applications/plasma_acceleration/inputs_2d_boost
  Examples/Physics_applications/plasma_acceleration/inputs_3d_boost
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/LaserAcceleration_BTD.json
  Regression/WarpX-tests.ini
  Source/Diagnostics/BackTransformedDiagnostic.H
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Diagnostics/BackTransformedDiagnostic_fwd.H
  Source/Diagnostics/CMakeLists.txt
  Source/Diagnostics/Make.package
  Source/Diagnostics/WarpXIO.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Particles/LaserParticleContainer.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/WarpX.H
  Source/WarpX.cpp
  Tools/LibEnsemble/sim/inputs
  Tools/PerformanceTests/automated_test_4_labdiags_2ppc
Labels: changes input scripts / defaults, component: diagnostics, component: boosted frame

#3510 2D/RZ Embedded Boundaries Bug Fix
  Source/Initialization/WarpXInitData.cpp
Labels: bug, bug: affects latest release, component: boundary

#3388 Vay Deposition: Filter D, Exchange Guard Cells of J
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
Labels: bug, component: spectral, bug: affects latest release

#3517 Use makeParser function for laser field parsing option
  Source/Laser/LaserProfiles.H
  Source/Laser/LaserProfilesImpl/LaserProfileFieldFunction.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileFromTXYEFile.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileGaussian.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileHarris.cpp
  Source/Particles/LaserParticleContainer.cpp
Labels: bug, cleaning, bug: affects latest release

#3518 Fix warnings with ceil in BTD code
  Source/Diagnostics/BTDiagnostics.cpp
Labels: cleaning, component: diagnostics

#3521 CI: unbreak macOS
  .github/workflows/macos.yml
Labels: bug, component: tests, component: third party

#3484 Centralize the multi fab allocation
  Source/BoundaryConditions/PML.cpp
  Source/BoundaryConditions/PML_RZ.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/WarpXRegrid.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: core, component: Python

#3522 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  CMakeLists.txt
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3482 BTD-RZ Add multiple modes
  Examples/Tests/BTD_rz/analysis_BTD_laser_antenna.py
  Examples/Tests/BTD_rz/inputs_rz_z_boosted_BTD
  Regression/WarpX-tests.ini
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.cpp
  Source/Diagnostics/MultiDiagnostics.cpp
Labels: enhancement, component: diagnostics, component: RZ

#3486 Add Python interface for flux injection
  Docs/requirements.txt
  Python/pywarpx/picmi.py
  Python/setup.py
  requirements.txt
Labels: component: Python

#3436 Adding an if statement for the last step diagnostic
  Python/pywarpx/WarpX.py
  Python/pywarpx/picmi.py
  Source/Evolve/WarpXEvolve.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
Labels: component: diagnostics, component: Python

#3402 PushPX: GPU kernel optimization
  Source/Particles/Gather/GetExternalFields.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/PushSelector.H
Labels: backend: cuda, Performance optimization, hackathon, backend: hip, component: core, component: interpolation

#3497 Bugfix for "particle coordinates" with plane field probe reduced diagnostic
  Source/Diagnostics/ReducedDiags/FieldProbe.H
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#3530 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  Source/BoundaryConditions/PML.H
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3532 Assert for Diag Type
  Source/Diagnostics/MultiDiagnostics.cpp
Labels: component: diagnostics

#3529 Speed up Vay current deposition
  Source/Particles/Deposition/CurrentDeposition.H
Labels: Performance optimization

#3536 Allow initial analytic fields to be set through the `picmi` interface
  Python/pywarpx/picmi.py
Labels: component: PICMI

#3538 Enable the use of `FieldProbe` default parameter values
  Python/pywarpx/picmi.py
  Source/Diagnostics/ReducedDiags/FieldProbe.H
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
Labels: changes input scripts / defaults, component: diagnostics

#3535 Bug fix with reduced diagnostic FieldProbe in 1d
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
  Source/Diagnostics/ReducedDiags/FieldProbeParticleContainer.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#3537 Fix Esirkepov deposition in 1D
  Regression/Checksum/benchmarks_json/LaserAcceleration_1d.json
  Regression/Checksum/benchmarks_json/Python_LaserAcceleration_1d.json
  Source/Particles/Deposition/CurrentDeposition.H
Labels: bug, bug: affects latest release, component: core

#3343 PSATD: Rewrite Equations with/without Rho
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmJConstantInTime.cpp
Labels: component: spectral
