Repository BLAST-WarpX/warpx, pull requests merged in 2022-02, with the labels that each got.

#2807 Summit: Fix Batch Template
  Tools/machines/summit-olcf/summit_v100.bsub
Labels: bug, component: documentation, machine / system

#2751 Add abort on warning threshold
  Docs/source/usage/parameters.rst
  Regression/WarpX-tests.ini
  Regression/prepare_file_ci.py
  Source/WarpX.H
  Source/WarpX.cpp
Labels: enhancement

#2810 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#2808 Allow `_libwarpx.add_particles` to be called with empty numpy arrays
  Python/pywarpx/_libwarpx.py
Labels: bug, component: Python

#2814 Prepare for CI: Remove PGI
  Regression/prepare_file_ci.py
Labels: component: tests, cleaning

#2812 Doc: Document `run_test.sh` manipulation
  Docs/source/developers/testing.rst
  Docs/source/install/cmake.rst
Labels: component: documentation, component: tests

#2811 CI: Do Not Set `diag1.file_prefix` in `runtime_params`
  Regression/WarpX-tests.ini
Labels: component: tests, cleaning

#2809 Fix Bug with Damped BCs & MR
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/WarpX.H
Labels: bug, component: mesh refinement, bug: affects latest release, component: boundary

#2799 Read species size correctly
  Examples/Tests/FieldProbe/inputs_2d
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#2780 Docs: Improve Provisioning Perf Tests
  Docs/source/maintenance/performance_tests.rst
Labels: component: documentation, component: tests, machine / system

#2817 Add myself to .zenodo.json
  .zenodo.json
Labels: component: documentation

#2815 Docs: NERSC `ipympl` Work-Around
  Docs/source/install/hpc/cori.rst
  Docs/source/install/hpc/perlmutter.rst
Labels: component: documentation, component: post-processing, machine / system

#2816 QED example inputs: simplify initialization of product species
  Examples/Modules/qed/breit_wheeler/inputs_2d
  Examples/Modules/qed/breit_wheeler/inputs_3d
  Examples/Modules/qed/quantum_synchrotron/inputs_2d
  Examples/Modules/qed/quantum_synchrotron/inputs_3d
  Examples/Modules/qed/schwinger/inputs_3d_schwinger
  Regression/Checksum/benchmarks_json/qed_breit_wheeler_2d.json
Labels: cleaning, component: QED

#2813 Docs: Glossary (ECP, LDRD, BLAST & ABLASTR)
  Docs/source/acknowledgements.rst
  Docs/source/glossary.rst
Labels: component: documentation

#2723 3D LWFA PICMI Test: Add Electron Beam
  Examples/Physics_applications/laser_acceleration/PICMI_inputs_3d.py
  Regression/Checksum/benchmarks_json/Python_LaserAcceleration.json
Labels: component: tests, component: PICMI

#2820 Release 22.02
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#2805 Rename PSATD Classes
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/CMakeLists.txt
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/Make.package
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmComoving.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmComoving.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmGalileanRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmGalileanRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmJLinearInTime.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmJLinearInTime.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPml.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPml.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPmlRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPmlRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralSolver.H
  Source/FieldSolver/SpectralSolver/SpectralSolver.cpp
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ.cpp
Labels: component: spectral, cleaning

#2711 Fixing the computation of ECT Rho Field
  Source/FieldSolver/FiniteDifferenceSolver/CMakeLists.txt
  Source/FieldSolver/FiniteDifferenceSolver/EvolveB.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveECTRho.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/FieldSolver/FiniteDifferenceSolver/Make.package
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/Initialization/WarpXInitData.cpp
Labels: bug, bug: affects latest release, component: boundary

#2825 Docs: NERSC Jupyter ipympl==0.8.6
  Docs/source/install/hpc/cori.rst
Labels: component: documentation, component: post-processing, machine / system, workaround

#2822 CMake: Add More Pip Helpers
  .gitignore
  CMakeLists.txt
  Docs/source/install/cmake.rst
  Docs/source/usage/how_to_run.rst
  Regression/WarpX-tests.ini
Labels: component: documentation, install, component: Python

#2823 Apply clang-tidy suggestions to MsgLogger and WarnManager
  Source/Utils/MsgLogger/MsgLogger.H
  Source/Utils/MsgLogger/MsgLogger.cpp
  Source/Utils/WarnManager.H
  Source/Utils/WarnManager.cpp
Labels: cleaning

#2827 Updated documentation regarding MCC collisions
  Docs/source/usage/parameters.rst
Labels: component: documentation, component: collisions

#2828 Add `local` flag to `warpx_getNumParticles`
  Python/pywarpx/_libwarpx.py
  Source/Python/WarpXWrappers.H
  Source/Python/WarpXWrappers.cpp
Labels: component: Python

#2687 Fixes removing implicit double to float conversions
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
  Source/EmbeddedBoundary/WarpXFaceExtensions.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/ElectrostaticSolver.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CylindricalYeeAlgorithm.H
  Source/Particles/Collision/BackgroundMCCCollision.cpp
  Source/Particles/Collision/BinaryCollision/NuclearFusion/ProtonBoronFusionCrossSection.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/ProtonBoronFusionInitializeMomentum.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/SingleNuclearFusionEvent.H
  Source/Particles/Collision/MCCProcess.cpp
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/Gather/ScalarFieldGather.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/Utils/WarpXMovingWindow.cpp
  Source/Utils/WarpXUtil.H
  Source/Utils/WarpXUtil.cpp
Labels: cleaning, warning

#2834 Simplify WarpXUtil::is_in implementation
  Source/Utils/WarpXUtil.cpp
Labels: cleaning

#2833 Add const auto to for range loops whenever possible
  Source/Particles/Collision/BackgroundMCCCollision.cpp
  Source/Utils/MsgLogger/MsgLogger.cpp
Labels: cleaning

#2831 Replace deprecated header <ctype.h> with <cctype>
  Source/Particles/LaserParticleContainer.cpp
  Source/Utils/WarpXAlgorithmSelection.cpp
Labels: cleaning

#2829 Binary Collisions: Const & Restrict
  Source/Particles/Collision/BinaryCollision/Coulomb/ComputeTemperature.H
  Source/Particles/Collision/BinaryCollision/Coulomb/ElasticCollisionPerez.H
  Source/Particles/Collision/BinaryCollision/Coulomb/PairWiseCoulombCollisionFunc.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/NuclearFusionFunc.H
Labels: Performance optimization, component: collisions

#2826 Implement some clang-tidy suggestions
  Source/Diagnostics/ReducedDiags/BeamRelevant.cpp
  Source/Diagnostics/ReducedDiags/ReducedDiags.cpp
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineWrapper.H
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineWrapper.cpp
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineWrapper.H
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineWrapper.cpp
  Source/Utils/IntervalsParser.cpp
  Source/Utils/WarpXUtil.cpp
Labels: cleaning

#2835 Crusher: CMake 3.22.1
  Tools/machines/crusher-olcf/crusher_warpx.profile.example
Labels: install, backend: hip, machine / system

#2837 NCIGodfreyFilter: Fix Int Division
  Regression/Checksum/benchmarks_json/LaserAccelerationBoost.json
  Regression/Checksum/benchmarks_json/PlasmaAccelerationBoost2d.json
  Regression/Checksum/benchmarks_json/PlasmaAccelerationBoost3d.json
  Regression/Checksum/benchmarks_json/restart.json
  Source/Filter/NCIGodfreyFilter.cpp
Labels: bug, changes input scripts / defaults, bug: affects latest release, component: core

#2756 Adding documentation for lxplus
  Docs/source/install/hpc.rst
  Docs/source/install/hpc/lxplus.rst
  Tools/machines/lxplus-cern/lxplus_warpx.profile.example
  Tools/machines/lxplus-cern/spack.yaml
Labels: component: documentation, machine / system

#2840 BackTransformParticleFunctor: Unused Counter
  Source/Diagnostics/ComputeDiagFunctors/BackTransformParticleFunctor.cpp
Labels: warning, component: diagnostics

#2838 ABLASTR: particle weights `const`
  Source/Particles/PhotonParticleContainer.H
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/ablastr/particles/DepositCharge.H
Labels: cleaning, component: ABLASTR

#2841 Rename ngE as ngEB (used for E,B)
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/ReducedDiags/ParticleExtrema.cpp
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.cpp
  Source/Parallelization/WarpXRegrid.cpp
  Source/Particles/ElementaryProcess/Ionization.H
  Source/Particles/ElementaryProcess/Ionization.cpp
  Source/Particles/ElementaryProcess/QEDPairGeneration.H
  Source/Particles/ElementaryProcess/QEDPairGeneration.cpp
  Source/Particles/ElementaryProcess/QEDPhotonEmission.H
  Source/Particles/ElementaryProcess/QEDPhotonEmission.cpp
  Source/Particles/PhotonParticleContainer.H
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.H
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Python/WarpXWrappers.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#2847 Fix some offsets with the gather buffers
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.cpp
Labels: bug, component: QED, component: mesh refinement, bug: affects latest release

#2845 Add amrex REPO and BRANCH flags for python builds
  Docs/source/install/cmake.rst
  setup.py
Labels: install, component: Python

#2735 User-defined integer and real particle attributes
  Docs/source/developers/particles.rst
  Docs/source/usage/examples.rst
  Docs/source/usage/parameters.rst
  Examples/Physics_applications/laser_acceleration/inputs_1d
  Examples/Physics_applications/laser_acceleration/inputs_3d
  Examples/Physics_applications/laser_acceleration/inputs_rz
  Examples/Physics_applications/laser_ion/inputs
  Regression/Checksum/benchmarks_json/LaserAcceleration.json
  Regression/Checksum/benchmarks_json/LaserAccelerationRZ.json
  Regression/Checksum/benchmarks_json/LaserAcceleration_1d.json
  Regression/Checksum/benchmarks_json/LaserAcceleration_single_precision_comms.json
  Regression/Checksum/benchmarks_json/LaserIonAcc2d.json
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
Labels: changes input scripts / defaults, component: core

#2843 [mini] Use parser to read laser spatio-temporal couplings direction
  Source/Laser/LaserProfilesImpl/LaserProfileGaussian.cpp
Labels: component: core

#2852 Only set modified k to 0 for even number of points
  Source/FieldSolver/SpectralSolver/SpectralKSpace.cpp
Labels: bug, component: spectral, bug: affects latest release

#2788 Allow flux injection in the out-of-plane direction for RZ/2D geometry
  Examples/Tests/FluxInjection/analysis_flux_injection_rz.py
  Examples/Tests/FluxInjection/inputs_rz
  Regression/Checksum/benchmarks_json/FluxInjection.json
  Regression/WarpX-tests.ini
  Source/Initialization/InjectorMomentum.H
  Source/Initialization/InjectorPosition.H
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/PhysicalParticleContainer.cpp
Labels: component: core

#2849 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#2858 update CI to use ascent 0.8.0 release container
  .github/workflows/insitu.yml
Labels: component: tests, component: third party, component: diagnostics

#2860 ParticleBuffer: Generalize & Move
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/ParticleIO.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Particles/ParticleBoundaryBuffer.H
  Source/Particles/ParticleBoundaryBuffer.cpp
  Source/Particles/ParticleBuffer.H
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: documentation, cleaning, component: ABLASTR

#2856 ABLASTR: Refactor `deposit_charge` API
  Source/Particles/WarpXParticleContainer.cpp
  Source/ablastr/particles/DepositCharge.H
Labels: cleaning, component: ABLASTR

#2842 Provide `t_min` and `t_max` for flux injection
  Docs/source/usage/parameters.rst
  Regression/Checksum/benchmarks_json/FluxInjection.json
  Source/Evolve/WarpXEvolve.cpp
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
Labels: enhancement

#2863 Lassen: Fix Chunked HDF5 with MPI
  Tools/machines/lassen-llnl/lassen.bsub
Labels: component: openPMD, machine / system, workaround

#2839 Refactor Current Correction Functions
  Regression/Checksum/benchmarks_json/galilean_rz_psatd_current_correction.json
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmComoving.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmComoving.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmGalileanRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmGalileanRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmJLinearInTime.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmJLinearInTime.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPml.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPml.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPmlRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPmlRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralSolver.H
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ.H
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/WarpX.H
Labels: component: spectral

#2868 Add warning to FieldProbe re: Boosted Frame
  Docs/source/usage/parameters.rst
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
Labels: component: documentation, component: diagnostics

#2818 Update parsing of FieldProbe in 2D and 1D
  Docs/source/usage/parameters.rst
  Examples/Tests/FieldProbe/inputs_2d
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
Labels: component: diagnostics

#2854 Do Not Fill PML Guard Cells w/ Inverse FFTs
  Source/BoundaryConditions/PML.cpp
Labels: bug, component: spectral, bug: affects latest release, component: boundary

#2869 Fix number of guard cell for coarse patch (for relativistic Poisson solver)
  Source/Particles/WarpXParticleContainer.cpp
Labels: bug, component: mesh refinement, component: electrostatic, bug: affects latest release

#2872 openPMD: Add ADIOS2 Engine Parameter Control
  Docs/source/usage/parameters.rst
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: enhancement, component: openPMD, component: diagnostics

#2857 NVCC 11.0-11.4.1: Silence Warning in ShapeFactors
  Source/Particles/ShapeFactors.H
Labels: warning, workaround

#2887 Properly initialize timestep, for electrostatic solver with mesh refinement
  Source/Evolve/WarpXComputeDt.cpp
Labels: bug, component: mesh refinement, component: electrostatic, bug: affects latest release

#2888 Re-order all particle quantities when doing MR partition
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Sorting/Partition.cpp
Labels: bug, component: mesh refinement, bug: affects latest release

#2728 Add mesh refinement for electrostatic solver and scraping
  Examples/Tests/ElectrostaticSphereEB/inputs_rz_mr
  Examples/Tests/scraping/inputs_rz
  Regression/Checksum/benchmarks_json/ElectrostaticSphereEB_RZ_MR.json
  Regression/Checksum/benchmarks_json/scraping.json
  Regression/WarpX-tests.ini
  Source/EmbeddedBoundary/WarpXInitEB.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/Particles/ParticleBoundaryBuffer.cpp
  Source/WarpX.cpp
Labels: component: mesh refinement, component: electrostatic

#2880 Updated documentation for predefined_profile_params for parabolic_channel
  Docs/source/usage/parameters.rst
Labels: component: documentation

#2889 Remove (almost) all residual "dangerous" c-style casts in WarpX
  Source/Python/WarpXWrappers.cpp
Labels: cleaning, warning, component: Python

#2874 Lassen: Work-Around MPI Allgatherv
  Docs/source/install/hpc/lassen.rst
  Tools/machines/lassen-llnl/lassen.bsub
Labels: component: openPMD, machine / system, workaround

#2859 openPMD: Avoid Managed Memory (Fields)
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: backend: cuda, Performance optimization, component: openPMD, backend: hip, backend: dpc++, workaround

#2846 Doc: Perlmutter Python & PSATD+RZ Environment
  Docs/source/install/hpc/cori.rst
  Docs/source/install/hpc/perlmutter.rst
  Docs/source/install/hpc/summit.rst
  Tools/machines/perlmutter-nersc/perlmutter_warpx.profile.example
Labels: backend: cuda, component: documentation, install, machine / system, component: Python

#2725 Modified EM field initialization in XZ/RZ with EB
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
Labels: component: boundary

#2879 Conda: Add `pkg-config`
  Docs/source/install/dependencies.rst
Labels: component: documentation, install

#2861 Make rigid injected particles work with QED
  Source/Particles/RigidInjectedParticleContainer.cpp
Labels: component: QED

#2722 Relativistic ES - only add the E-field due to boundary potentials once
  Regression/WarpX-tests.ini
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/WarpX.H
Labels: component: electrostatic, component: boundary

#2864 Add Coulomb collision installation to picmi.py
  Examples/Tests/collision/PICMI_inputs_2d.py
  Examples/Tests/collision/analysis_collision_2d.py
  Python/pywarpx/picmi.py
  Regression/WarpX-tests.ini
Labels: component: PICMI, component: collisions

#2895 Correct field initialization in 2D/RZ
  Source/Initialization/WarpXInitData.cpp
Labels: bug, bug: affects latest release

#2893 Fix some bugprone-narrowing-conversions issues
  Source/BoundaryConditions/PML.cpp
  Source/Diagnostics/BackTransformedDiagnostic.cpp
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/MultiDiagnostics.cpp
  Source/Diagnostics/SliceDiagnostic.cpp
  Source/WarpX.cpp
Labels: cleaning
