Repository BLAST-WarpX/warpx, pull requests merged in 2022-03, with the labels that each got.

#2898 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
Labels: component: third party

#2904 openPMD: DumpToFile Validate Vectors
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: component: openPMD, cleaning

#2905 ionization_level -> ionizationLevel
  Docs/source/developers/particles.rst
  Examples/Modules/ionization/analysis_ionization.py
  Regression/Checksum/benchmarks_json/ionization_boost.json
  Regression/Checksum/benchmarks_json/ionization_lab.json
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
Labels: component: openPMD, cleaning, changes input scripts / defaults, component: core, component: diagnostics

#2903 openPMD: ED-PIC in Runtime Attributes
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: bug, component: openPMD, bug: affects latest release, component: diagnostics

#2894 Docs: Verbose CUDA PTX Builds
  Docs/source/install/cmake.rst
Labels: backend: cuda, component: documentation, install

#2910 Fix BTD: Flexible Digits in File Padding (Plotfiles)
  Source/Diagnostics/BTDiagnostics.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#2913 Rigid Injection: Serialize RNG
  Regression/WarpX-tests.ini
Labels: bug, component: tests, bug: affects latest release

#2916 Add Some Doxygen Strings
  Source/WarpX.H
Labels: component: documentation

#2915 add documentation for load_balance_costs_update_algo
  Source/WarpX.H
Labels: component: documentation

#2917 Bugfix for LB + MR + Filter
  Source/Parallelization/WarpXComm.cpp
Labels: bug, component: mesh refinement, bug: affects latest release, component: load balancing

#2909 pml_psatd_rz: w/o dynamic scheduling
  Examples/Tests/PML/inputs_rz
  Regression/Checksum/benchmarks_json/pml_psatd_rz.json
  Regression/WarpX-tests.ini
Labels: bug, component: tests, bug: affects latest release, component: boundary

#2920 CI: Cache for GitHub Actions
  .github/workflows/cuda.yml
  .github/workflows/dependencies/dpcpp.sh
  .github/workflows/dependencies/gcc.sh
  .github/workflows/dependencies/hip.sh
  .github/workflows/dependencies/icc.sh
  .github/workflows/dependencies/nvcc11.sh
  .github/workflows/dependencies/nvhpc.sh
  .github/workflows/hip.yml
  .github/workflows/intel.yml
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
Labels: component: tests

#2919 Python_restart_eb: Add CMake Options
  Regression/WarpX-tests.ini
Labels: bug, component: tests, bug: affects latest release, component: boundary

#2921 Add More Doxygen Strings
  Source/WarpX.H
Labels: component: documentation

#2907 Fix bug in setting weight with refine_plasma option.
  Regression/Checksum/benchmarks_json/RefinedInjection.json
  Source/Particles/PhysicalParticleContainer.cpp
Labels: bug, bug: affects latest release, component: core

#2385 file_min_digits: 5->6
  Docs/source/usage/parameters.rst
  Examples/Modules/ParticleBoundaryProcess/analysis_absorption.py
  Examples/Modules/ParticleBoundaryProcess/analysis_reflection.py
  Examples/Modules/ParticleBoundaryScrape/analysis_scrape.py
  Examples/Modules/laser_injection/analysis_1d.py
  Examples/Modules/laser_injection_from_file/analysis.py
  Examples/Physics_applications/capacitive_discharge/analysis.py
  Examples/Tests/ElectrostaticSphereEB/analysis.py
  Examples/Tests/Langmuir/analysis_langmuir_multi.py
  Examples/Tests/Langmuir/analysis_langmuir_multi_1d.py
  Examples/Tests/Langmuir/analysis_langmuir_multi_rz.py
  Examples/Tests/PML/analysis_pml_psatd.py
  Examples/Tests/collision/analysis_collision_2d.py
  Examples/Tests/collision/analysis_collision_3d.py
  Examples/Tests/divb_cleaning/analysis.py
  Examples/Tests/pass_mpi_communicator/analysis.py
  Examples/Tests/restart/PICMI_inputs_runtime_component_analyze.py
  Examples/Tests/restart_eb/PICMI_inputs_restart_eb.py
  Regression/WarpX-tests.ini
  Source/Diagnostics/Diagnostics.H
Labels: help wanted, component: diagnostics

#2912 Release 22.03
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#2899 Macroscopic Maxwell solver: do not update fields in EB (stair-case approximation)
  Examples/Modules/embedded_boundary_cube/analysis_fields.py
  Regression/Checksum/benchmarks_json/embedded_boundary_cube_macroscopic.json
  Regression/WarpX-tests.ini
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicEvolveE.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
Labels: component: boundary

#2885 Refactor Vay Deposition Functions
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmComoving.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmComoving.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmGalileanRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmGalileanRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmJLinearInTime.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmJLinearInTime.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPml.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPml.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPmlRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPmlRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralSolver.H
  Source/FieldSolver/SpectralSolver/SpectralSolver.cpp
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ.H
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: spectral

#2925 Rename `serialize_ics` as `serialize_initial_conditions`
  Docs/source/developers/warning_logger.rst
  Docs/source/usage/parameters.rst
  Examples/Modules/RigidInjection/inputs_2d_BoostedFrame
  Examples/Modules/RigidInjection/inputs_2d_LabFrame
  Examples/Modules/boosted_diags/inputs_3d_slice
  Examples/Modules/laser_injection/inputs_1d_rt
  Examples/Modules/laser_injection/inputs_2d_rt
  Examples/Modules/laser_injection/inputs_3d_rt
  Examples/Modules/laser_injection_from_file/inputs.2d_test_txye
  Examples/Modules/nci_corrector/inputs_2d
  Examples/Modules/qed/breit_wheeler/inputs_2d
  Examples/Modules/qed/breit_wheeler/inputs_3d
  Examples/Modules/qed/quantum_synchrotron/inputs_2d
  Examples/Modules/qed/quantum_synchrotron/inputs_3d
  Examples/Modules/qed/schwinger/inputs_3d_schwinger
  Examples/Physics_applications/laser_acceleration/PICMI_inputs_1d.py
  Examples/Physics_applications/laser_acceleration/PICMI_inputs_2d.py
  Examples/Physics_applications/laser_acceleration/PICMI_inputs_3d.py
  Examples/Physics_applications/laser_acceleration/inputs_1d
  Examples/Physics_applications/laser_acceleration/inputs_2d
  Examples/Physics_applications/laser_acceleration/inputs_2d_boost
  Examples/Physics_applications/laser_acceleration/inputs_3d
  Examples/Physics_applications/plasma_mirror/inputs_2d
  Examples/Physics_applications/uniform_plasma/inputs_2d
  Examples/Physics_applications/uniform_plasma/inputs_3d
  Examples/Tests/Langmuir/inputs_1d_multi_rt
  Examples/Tests/Langmuir/inputs_2d_multi_rt
  Examples/Tests/Langmuir/inputs_2d_multi_rz_rt
  Examples/Tests/Langmuir/inputs_3d_multi_rt
  Examples/Tests/PEC/inputs_field_PEC_3d
  Examples/Tests/PEC/inputs_field_PEC_mr_3d
  Examples/Tests/collision/PICMI_inputs_2d.py
  Examples/Tests/collision/inputs_2d
  Examples/Tests/collision/inputs_3d
  Examples/Tests/collision/inputs_rz
  Examples/Tests/comoving/inputs_2d_hybrid
  Examples/Tests/galilean/inputs_2d_hybrid
  Examples/Tests/radiation_reaction/test_const_B_analytical/analysis_classicalRR.py
  Examples/Tests/radiation_reaction/test_const_B_analytical/inputs_3d
  Python/pywarpx/picmi.py
  Regression/TestFillBoundary/inputs.2d
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  Source/Particles/PhysicalParticleContainer.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: changes input scripts / defaults

#2753 Print Fundamental PIC Parameters to Stdout
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
Labels: component: core

#2927 CI: Newer CCache for CUDA
  .github/workflows/cuda.yml
  .github/workflows/dependencies/icc.sh
  .github/workflows/dependencies/nvcc11.sh
  .github/workflows/dependencies/nvhpc.sh
  .github/workflows/dependencies/pyfull.sh
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
Labels: backend: cuda, component: tests

#2922 WarpX Static Attributes: Clean Up Types
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#2928 CI: Newer CCache for HIP
  .github/workflows/cuda.yml
  .github/workflows/dependencies/hip.sh
  .github/workflows/dependencies/nvcc11.sh
  .github/workflows/dependencies/nvhpc.sh
Labels: component: tests, backend: hip

#2929 Fix incorrect levels when reading raw data from a MR simulation
  Tools/PostProcessing/read_raw_data.py
Labels: bug, component: post-processing, bug: affects latest release

#2934 Properly handle MCC collision subcycling
  Examples/Physics_applications/capacitive_discharge/PICMI_inputs_1d.py
  Python/pywarpx/picmi.py
  Source/Particles/Collision/BackgroundMCCCollision.cpp
Labels: bug: affects latest release, component: collisions

#2935 More doxygen strings for WarpX static member variables
  Source/WarpX.H
Labels: component: documentation

#2884 Add background stopping
  Docs/source/usage/parameters.rst
  Examples/Tests/ion_stopping/analysis_ion_stopping.py
  Examples/Tests/ion_stopping/inputs_3d
  Regression/Checksum/benchmarks_json/ion_stopping.json
  Regression/WarpX-tests.ini
  Source/Particles/Collision/BackgroundStopping/BackgroundStopping.H
  Source/Particles/Collision/BackgroundStopping/BackgroundStopping.cpp
  Source/Particles/Collision/BackgroundStopping/CMakeLists.txt
  Source/Particles/Collision/BackgroundStopping/Make.package
  Source/Particles/Collision/CMakeLists.txt
  Source/Particles/Collision/CollisionHandler.cpp
  Source/Particles/Collision/Make.package
Labels: enhancement, component: collisions

#2945 Move MCC files to a new folder inside "Particles/Collision/"
  Source/Particles/Collision/BackgroundMCC/BackgroundMCCCollision.H
  Source/Particles/Collision/BackgroundMCC/BackgroundMCCCollision.cpp
  Source/Particles/Collision/BackgroundMCC/CMakeLists.txt
  Source/Particles/Collision/BackgroundMCC/MCCProcess.H
  Source/Particles/Collision/BackgroundMCC/MCCProcess.cpp
  Source/Particles/Collision/BackgroundMCC/MCCScattering.H
  Source/Particles/Collision/BackgroundMCC/Make.package
  Source/Particles/Collision/CMakeLists.txt
  Source/Particles/Collision/CollisionHandler.cpp
  Source/Particles/Collision/Make.package
Labels: cleaning, component: collisions

#2955 Fix ambiguity in reference to Parser
  Source/Particles/Gather/GetExternalFields.H
  Source/Particles/Gather/GetExternalFields.cpp
Labels: bug, bug: affects latest release, component: core

#2944 Clean up the use of ndt for collisions
  Source/Evolve/WarpXEvolve.cpp
  Source/Particles/Collision/BackgroundMCC/BackgroundMCCCollision.H
  Source/Particles/Collision/BackgroundMCC/BackgroundMCCCollision.cpp
  Source/Particles/Collision/BackgroundStopping/BackgroundStopping.H
  Source/Particles/Collision/BackgroundStopping/BackgroundStopping.cpp
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
  Source/Particles/Collision/CollisionBase.H
  Source/Particles/Collision/CollisionHandler.H
  Source/Particles/Collision/CollisionHandler.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
Labels: cleaning, component: collisions

#2954 Clean Pip Staging Directory
  Regression/WarpX-tests.ini
  setup.py
Labels: bug, install, bug: affects latest release, component: Python

#2950 CMake: pip_install w/o MPI
  CMakeLists.txt
Labels: bug, install, bug: affects latest release, component: parallelization

#2940 Default CFL to 0.999 instead of 0.7
  Docs/source/usage/parameters.rst
  Regression/WarpX-tests.ini
  Source/WarpX.H
Labels: component: documentation, changes input scripts / defaults, component: core

#2953 ABLASTR: Move TextMsg
  CMakeLists.txt
  Source/Utils/CMakeLists.txt
  Source/Utils/Make.package
  Source/Utils/TextMsg.H
  Source/Utils/TextMsg.cpp
  Source/Utils/WarnManager.cpp
  Source/ablastr/CMakeLists.txt
  Source/ablastr/Make.package
  Source/ablastr/particles/DepositCharge.H
  Source/ablastr/utils/CMakeLists.txt
  Source/ablastr/utils/Make.package
  Source/ablastr/utils/TextMsg.H
  Source/ablastr/utils/TextMsg.cpp
Labels: bug, component: ABLASTR

#2959 WarpX/PICSAR Version Define: File
  .github/workflows/cuda.yml
  CMakeLists.txt
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  Source/Make.WarpX
  Source/Utils/CMakeLists.txt
  Source/Utils/Make.package
  Source/Utils/WarpXVersion.H.in
  Source/Utils/WarpXVersion.cpp
  Source/WarpX.cpp
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: bug, install, bug: affects latest release

#2963 Load-balancing heuristic weights: not negative by default
  Source/WarpX.H
  Source/WarpX.cpp
Labels: bug, bug: affects latest release, component: load balancing

#2892 Add by-cell averages of particle properties
  Docs/source/usage/parameters.rst
  Examples/Tests/particle_fields_diags/analysis_particle_diags.py
  Examples/Tests/particle_fields_diags/analysis_particle_diags_impl.py
  Examples/Tests/particle_fields_diags/analysis_particle_diags_single.py
  Examples/Tests/particle_fields_diags/inputs
  Regression/Checksum/benchmarks_json/particle_fields_diags.json
  Regression/Checksum/benchmarks_json/particle_fields_diags_single_precision.json
  Regression/WarpX-tests.ini
  Source/Diagnostics/ComputeDiagFunctors/CMakeLists.txt
  Source/Diagnostics/ComputeDiagFunctors/Make.package
  Source/Diagnostics/ComputeDiagFunctors/ParticleReductionFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/ParticleReductionFunctor.cpp
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.cpp
Labels: component: diagnostics

#2956 QED: Add Space in Multiline Warnings
  Source/Particles/MultiParticleContainer.cpp
Labels: cleaning, component: QED

#2961 FFT of J: Use Spectral Index of Correct MR Level
  Source/FieldSolver/WarpXPushFieldsEM.cpp
Labels: component: spectral, component: mesh refinement

#2960 Langmuir 2D Tests: Better Analysis Plots
  Examples/Tests/Langmuir/analysis_langmuir_multi_2d.py
Labels: component: tests, cleaning

#2957 FAQ: Forward Declarations
  Docs/source/developers/faq.rst
  Docs/source/developers/repo_organization.rst
Labels: component: documentation

#2967 Bug Fix : BTD + MR, initialize output buffer only for the level in the output
  Source/Diagnostics/Diagnostics.cpp
Labels: bug, component: mesh refinement, bug: affects latest release, component: diagnostics

#2951 RZ: Use WarpX::ncomps more consistently
  Source/Diagnostics/ComputeDiagFunctors/DivEFunctor.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveF.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.H
  Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.cpp
Labels: cleaning, component: RZ

#2970 openPMD: Only Write up to Finest Level
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.H
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: enhancement, component: openPMD, component: mesh refinement

#2977 Update to be compatible with PICMI changes
  Python/pywarpx/picmi.py
Labels: component: PICMI

#2973 Minimum digits for plotfile cell and particle data is 5
  Source/Diagnostics/BTDiagnostics.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#2978 Doc: Major Cori Update
  Docs/source/install/hpc/cori.rst
  Tools/machines/cori-nersc/gpu_warpx.profile.example
  Tools/machines/cori-nersc/haswell_warpx.profile.example
  Tools/machines/cori-nersc/knl_warpx.profile.example
Labels: component: documentation, install, machine / system

#2982 LaserAccelection_1d: Use same build as other 1D tests
  Regression/WarpX-tests.ini
Labels: component: tests

#2971 Streamline profiling documentation
  Docs/source/developers/profiling.rst
  Docs/source/usage/workflows.rst
  Docs/source/usage/workflows/profiling.rst
Labels: Performance optimization, component: documentation

#2985 Measure time taken in the moving window
  Source/Utils/WarpXMovingWindow.cpp
Labels: component: core

#2987 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#2327 Hybrid Algorithms: Add FDTD Support for Centering
  Regression/Checksum/benchmarks_json/PlasmaAccelerationBoost3d_hybrid.json
  Regression/WarpX-tests.ini
  Source/FieldSolver/SpectralSolver/SpectralKSpace.H
  Source/FieldSolver/SpectralSolver/SpectralKSpace.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/Parallelization/WarpXComm_K.H
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: interpolation

#2965 Vay Deposition: Separate Arrays, Correct Index Types w/ FFTs
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldData.H
  Source/FieldSolver/SpectralSolver/SpectralFieldData.cpp
  Source/FieldSolver/SpectralSolver/SpectralSolver.H
  Source/FieldSolver/SpectralSolver/SpectralSolver.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: spectral, cleaning

#2980 openPMD: Handle Zero Particles Well
  Docs/source/usage/parameters.rst
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: bug, component: openPMD, bug: affects latest release, component: diagnostics, component: boosted frame

#2878 openPMD RZ modes dumped in thetaMode
  Docs/source/usage/parameters.rst
  Examples/Physics_applications/laser_acceleration/inputs_rz
  Examples/Tests/openpmd_rz/analysis_openpmd_rz.py
  Regression/WarpX-tests.ini
  Source/Diagnostics/ComputeDiagFunctors/DivBFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/DivBFunctor.cpp
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FieldIO.H
  Source/Diagnostics/FieldIO.cpp
  Source/Diagnostics/FullDiagnostics.H
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: component: openPMD, component: diagnostics, component: RZ

#2990 Perform mesh refinement taggin on GPU
  Source/Utils/WarpXTagging.cpp
  Source/WarpX.H
Labels: component: mesh refinement

#2975 add openPMD test for particle_fields_diags to CI
  Examples/Tests/particle_fields_diags/analysis_particle_diags_impl.py
  Examples/Tests/particle_fields_diags/inputs
  Regression/WarpX-tests.ini
Labels: component: openPMD, component: tests, component: diagnostics

#2998 Add Field Probe to Laser Ion Test
  Examples/Physics_applications/laser_ion/inputs
Labels: component: tests

#2993 Docs: Updates Profiling Perlmutter
  Docs/source/developers/profiling.rst
Labels: component: documentation, component: third party, machine / system

#3000 Use Utils::TextMsg::Err in MsgLogger
  Source/Utils/MsgLogger/MsgLogger.cpp
Labels: cleaning

#3009 Docs: Fix syntax issues in parameters.rst
  Docs/source/usage/parameters.rst
Labels: component: documentation

#3007 Change particle filter parser to check it as a boolean instead of comparing to 0.5
  Docs/source/usage/parameters.rst
  Source/Particles/Filter/FilterFunctors.H
Labels: cleaning

#2999 Langmuir 3D Tests: Better Analysis Plots
  Examples/Tests/Langmuir/analysis_langmuir_multi.py
Labels: component: tests, cleaning

#3008 Take into account the cost of 'shiftMF' in load-balancing
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.H
Labels: component: load balancing

#2992 Add propagation_direction to PICMI lasers
  Python/pywarpx/picmi.py
Labels: component: PICMI

#3005 Doc: Plotfile Serialization Parameters
  Docs/source/usage/parameters.rst
Labels: component: documentation, component: diagnostics, component: checkpoint/restart

#2986 BTD : Redistribute Particles in buffer to lab frame box array and copy with (local=true)
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: bug, component: third party, bug: affects latest release, component: diagnostics, component: boosted frame

#3003 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/Checksum/benchmarks_json/reduced_diags_single_precision.json
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: help wanted, component: third party

#3001 Add particle filter in ParticleReductionFunctor
  Docs/source/usage/parameters.rst
  Examples/Tests/particle_fields_diags/analysis_particle_diags_impl.py
  Examples/Tests/particle_fields_diags/inputs
  Regression/Checksum/benchmarks_json/particle_fields_diags.json
  Regression/Checksum/benchmarks_json/particle_fields_diags_single_precision.json
  Source/Diagnostics/ComputeDiagFunctors/ParticleReductionFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/ParticleReductionFunctor.cpp
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.cpp
Labels: enhancement, component: diagnostics

#3014 CI: NVHPC New Apt Repo
  .github/workflows/cuda.yml
  .github/workflows/dependencies/nvhpc.sh
Labels: backend: cuda, component: tests, component: third party
