Repository BLAST-WarpX/warpx, pull requests merged in 2022-07, with the labels that each got.

#3209 Use amrex::RandomNormal in Maxwell-Boltzmann momentum injection
  Examples/Physics_applications/capacitive_discharge/analysis_2d.py
  Regression/Checksum/benchmarks_json/Proton_Boron_Fusion_3D.json
  Regression/Checksum/benchmarks_json/background_mcc.json
  Regression/Checksum/benchmarks_json/background_mcc_dp_psp.json
  Regression/Checksum/benchmarks_json/initial_distribution.json
  Source/Initialization/InjectorMomentum.H
Labels: bug, bug: affects latest release

#3169 Merge `FillBoundary` and `NodalSync` (`OneStep_multiJ`)
  Regression/Checksum/benchmarks_json/multi_J_2d_psatd.json
  Regression/Checksum/benchmarks_json/multi_J_2d_psatd_pml.json
  Source/Evolve/WarpXEvolve.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/WarpX.H
Labels: Performance optimization, component: parallelization

#3194 Initialize multi-physics module (ionization, QED) when restarting a simulation from a checkpoint
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
Labels: bug, bug: affects latest release, component: checkpoint/restart

#3217 Parse the quantity `zmax_plasma_to_compute_max_step` in PICMI
  Python/pywarpx/picmi.py
Labels: component: PICMI

#3221 Improve Docs on max_grid_size/blocking_factor for RZ
  Docs/source/usage/workflows/parallelization.rst
Labels: component: documentation, component: RZ

#3211 Release 22.07
  .github/workflows/cuda.yml
  .github/workflows/insitu.yml
  CMakeLists.txt
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#3219 Cleanup how fields_to_plot = none is handled
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/FullDiagnostics.cpp
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: bug, bug: affects latest release, component: diagnostics

#2540 Add 2D tests for proton boron fusion
  Examples/Modules/nuclear_fusion/analysis_proton_boron_fusion.py
  Examples/Modules/nuclear_fusion/inputs_2d
  Regression/Checksum/benchmarks_json/Proton_Boron_Fusion_2D.json
  Regression/WarpX-tests.ini
Labels: component: tests, component: collisions

#3234 Fix: Write Used Inputs Once
  Source/Initialization/WarpXInitData.cpp
Labels: bug, Performance optimization, bug: affects latest release

#3229 Refactor code in fusion module to avoid machine-precision issues
  Examples/Modules/nuclear_fusion/analysis_proton_boron_fusion.py
  Source/Particles/Collision/BinaryCollision/NuclearFusion/SingleNuclearFusionEvent.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/TwoProductFusionUtil.H
Labels: component: collisions

#3196 CMake: 3.20+
  CMakeLists.txt
  Docs/source/install/dependencies.rst
  cmake/dependencies/AMReX.cmake
  pyproject.toml
  setup.py
Labels: install

#3237 Remove Unused Allocations of Averaged MultiFabs
  Source/WarpX.cpp
Labels: component: spectral, cleaning

#3244 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3243 ABLASTR: Update Poisson Solver API
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/ablastr/fields/PoissonSolver.H
Labels: component: electrostatic, component: ABLASTR

#3228 Docs: New OLCF Machine
  Docs/source/install/hpc.rst
  Docs/source/install/hpc/frontier.rst
  Tools/machines/frontier-olcf/frontier_warpx.profile.example
  Tools/machines/frontier-olcf/submit.sh
Labels: component: documentation, backend: hip, machine / system

#3153 D-T fusion
  Examples/Modules/nuclear_fusion/analysis_deuterium_tritium_fusion.py
  Examples/Modules/nuclear_fusion/inputs_deuterium_tritium_3d
  Examples/Modules/nuclear_fusion/inputs_proton_boron_2d
  Examples/Modules/nuclear_fusion/inputs_proton_boron_3d
  Regression/Checksum/benchmarks_json/Deuterium_Tritium_Fusion_3D.json
  Regression/WarpX-tests.ini
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
  Source/Particles/Collision/BinaryCollision/BinaryCollisionUtils.H
  Source/Particles/Collision/BinaryCollision/BinaryCollisionUtils.cpp
  Source/Particles/Collision/BinaryCollision/NuclearFusion/DeuteriumTritiumFusionCrossSection.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/NuclearFusionFunc.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/SingleNuclearFusionEvent.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/TwoProductFusionInitializeMomentum.H
  Source/Particles/Collision/BinaryCollision/ParticleCreationFunc.H
  Source/Particles/Collision/BinaryCollision/ParticleCreationFunc.cpp
Labels: component: collisions

#3249 Docs: gaussian beam q_tot is not optional
  Docs/source/usage/parameters.rst
Labels: component: documentation

#3253 Fix a bug in GPU version of Hankel Transform
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/HankelTransform.cpp
Labels: component: spectral, bug: affects latest release, component: RZ

#3251 Add Python callback call when a checkpointing signal is received
  Python/pywarpx/callbacks.py
  Source/Evolve/WarpXEvolve.cpp
  Source/Python/WarpX_py.H
Labels: component: Python

#3252 CI: Add Missing Regression Analysis (NCI corrector)
  Examples/Modules/nci_corrector/analysis_ncicorr.py
  Regression/Checksum/benchmarks_json/nci_corrector.json
  Regression/Checksum/benchmarks_json/nci_correctorMR.json
Labels: bug, component: tests, bug: affects latest release

#3239 Fixes to allow mixed precision, ParticleReal float, Real double
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineWrapper.H
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineWrapper.cpp
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineWrapper.H
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineWrapper.cpp
  Source/Particles/PhysicalParticleContainer.cpp
Labels: bug, component: QED, bug: affects latest release

#3247 Poisson Solver: Fix Bug w/ Semi-coarsening and EB
  Source/ablastr/fields/PoissonSolver.H
Labels: bug, component: electrostatic, bug: affects latest release, component: boundary

#3056 Bug fix for BTD - particle BA, and geom, same as field buffer
  Examples/Modules/RigidInjection/inputs_2d_BoostedFrame
  Examples/Modules/boosted_diags/inputs_3d_slice
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: bug, component: third party, bug: affects latest release, component: diagnostics, component: boosted frame

#3260 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3262 ParticleReal for external fields and collisions
  Source/Particles/Algorithms/KineticEnergy.H
  Source/Particles/Collision/BackgroundMCC/BackgroundMCCCollision.H
  Source/Particles/Collision/BackgroundMCC/BackgroundMCCCollision.cpp
  Source/Particles/Collision/BackgroundMCC/ImpactIonization.H
  Source/Particles/Collision/BackgroundMCC/MCCProcess.H
  Source/Particles/Collision/BackgroundMCC/MCCProcess.cpp
  Source/Particles/Collision/BackgroundStopping/BackgroundStopping.H
  Source/Particles/Collision/BackgroundStopping/BackgroundStopping.cpp
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
  Source/Particles/Collision/BinaryCollision/Coulomb/ElasticCollisionPerez.H
  Source/Particles/Collision/BinaryCollision/Coulomb/PairWiseCoulombCollisionFunc.H
  Source/Particles/Collision/BinaryCollision/Coulomb/UpdateMomentumPerezElastic.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/NuclearFusionFunc.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/SingleNuclearFusionEvent.H
  Source/Particles/Gather/GetExternalFields.H
  Source/Particles/Gather/GetExternalFields.cpp
  Source/Particles/MultiParticleContainer.H
Labels: cleaning

#3259 Starting with the pusher, consistently use ParticleReal
  Regression/Checksum/benchmarks_json/background_mcc_dp_psp.json
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/PushSelector.H
  Source/Particles/Pusher/UpdateMomentumBoris.H
  Source/Particles/Pusher/UpdateMomentumBorisWithRadiationReaction.H
  Source/Particles/Pusher/UpdateMomentumHigueraCary.H
  Source/Particles/Pusher/UpdateMomentumVay.H
  Source/Particles/Pusher/UpdatePosition.H
  Source/Particles/Pusher/UpdatePositionPhoton.H
  Source/Particles/RigidInjectedParticleContainer.H
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: cleaning

#3265 Fix: mpi4py requirement for `--target pip_install`
  CMakeLists.txt
  requirements_mpi.txt
Labels: install, component: parallelization, component: Python

#3271 Update background_mcc_dp_psp benchmark
  Regression/Checksum/benchmarks_json/background_mcc_dp_psp.json
Labels: component: tests, component: collisions

#3267 Frontier: Update Submission Scripts
  Tools/machines/frontier-olcf/submit.sh
Labels: component: documentation, machine / system

#3268 Remove duplicated parameter <species_name>.x/y/z_rms in parameters docs
  Docs/source/usage/parameters.rst
Labels: component: documentation, cleaning

#3273 Docs: Typos Frontier Section
  Docs/source/install/hpc/crusher.rst
  Docs/source/install/hpc/frontier.rst
Labels: component: documentation
