Repository BLAST-WarpX/warpx, pull requests merged in 2022-10, with the labels that each got.

#3435 Docs: BELLA MVA PoP & Ion PRAB Published
  Docs/source/highlights.rst
Labels: component: documentation

#3378 Lassen (LLNL): HDF5 1.12.2
  Tools/machines/lassen-llnl/lassen_warpx.profile.example
Labels: Performance optimization, component: documentation, component: openPMD, machine / system

#3361 Sphinx Extension: Sphinx-Design
  Docs/requirements.txt
  Docs/source/conf.py
  Docs/spack.yaml
Labels: component: documentation

#3329 Major update of the Python/picmi documentation
  Docs/requirements.txt
  Docs/source/conf.py
  Docs/source/developers/documentation.rst
  Docs/source/developers/particles.rst
  Docs/source/developers/profiling.rst
  Docs/source/developers/testing.rst
  Docs/source/highlights.rst
  Docs/source/usage/python.rst
  Python/pywarpx/__init__.py
  Python/pywarpx/picmi.py
  Python/setup.py
  Regression/Checksum/benchmark.py
  Regression/Checksum/checksum.py
  Regression/Checksum/checksumAPI.py
  requirements.txt
Labels: component: documentation, component: PICMI, component: Python

#2506 Use parser for input parameters of type long
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/LaserParticleContainer.cpp
  Source/Utils/WarpXUtil.H
  Source/Utils/WarpXUtil.cpp
Labels: changes input scripts / defaults

#3444 Release 22.10
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#3437 Doc: Dev FAQ Pinned Memory
  Docs/source/developers/faq.rst
Labels: backend: cuda, component: documentation, backend: hip, backend: dpc++

#3447 Docs: Fix PICMI Builds
  Docs/README.md
  Docs/requirements.txt
  Docs/source/developers/documentation.rst
Labels: bug, component: documentation, component: third party, bug: affects latest release

#3440 BTD: Improve Z-Slice Message
  Source/Diagnostics/BTDiagnostics.cpp
Labels: component: diagnostics, component: boosted frame

#3451 openPMD: Shape of Constant Particle Records
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: bug, component: openPMD, bug: affects latest release

#3449 Doc: BLAS++/LAPACK++ on GitHub
  .azure-pipelines.yml
  .github/workflows/dependencies/pyfull.sh
  Docs/source/developers/gnumake/rzgeometry.rst
  Docs/source/install/dependencies.rst
  Docs/source/install/hpc/cori.rst
  Docs/source/install/hpc/crusher.rst
  Docs/source/install/hpc/lassen.rst
  Docs/source/install/hpc/perlmutter.rst
  Docs/source/install/hpc/summit.rst
Labels: component: spectral, component: documentation, component: third party, machine / system, component: RZ

#3337 Spack Desktop: Simpler CUDA Visualization
  Tools/machines/desktop/spack-ubuntu-cuda.yaml
Labels: backend: cuda, component: documentation, install, machine / system

#3458 Updated 1D CI tests with particles because of update of yt
  Examples/Tests/collision/analysis_collision_3d.py
  Regression/Checksum/benchmarks_json/Langmuir_multi_1d.json
  Regression/Checksum/benchmarks_json/LaserAcceleration_1d.json
  Regression/Checksum/benchmarks_json/Python_LaserAcceleration_1d.json
  Regression/Checksum/benchmarks_json/Python_PlasmaAcceleration1d.json
  setup.py
Labels: component: tests

#3455 Fix synchronization of nodal points in subcycling
  Regression/Checksum/benchmarks_json/nci_correctorMR.json
  Source/Evolve/WarpXEvolve.cpp
Labels: bug, component: mesh refinement, bug: affects latest release, component: parallelization

#3457 Add functions for reading particle id and cpu numbers correctly
  Examples/Tests/restart/PICMI_inputs_id_cpu_read.py
  Python/pywarpx/_libwarpx.py
  Regression/WarpX-tests.ini
  Source/Python/WarpXWrappers.H
  Source/Python/WarpXWrappers.cpp
Labels: bug, bug: affects latest release, component: Python

#3459 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3461 Docs: Expand Debugging Workflow
  Docs/source/usage/workflows/debugging.rst
Labels: component: documentation

#3460 openPMD Engines: Allow Params w/o Type
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: bug, component: openPMD, bug: affects latest release

#3465 CI Fix: macOS OMP
  .github/workflows/macos.yml
  Docs/source/install/dependencies.rst
Labels: bug, component: tests, component: third party, machine / system

#3470 Update GCC Requirement
  Docs/source/install/dependencies.rst
Labels: component: documentation, install

#3469 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/Checksum/benchmarks_json/ElectrostaticSphereEB.json
  Regression/Checksum/benchmarks_json/ElectrostaticSphereEB_RZ.json
  Regression/Checksum/benchmarks_json/ElectrostaticSphereEB_RZ_MR.json
  Regression/Checksum/benchmarks_json/ElectrostaticSphereEB_mixedBCs.json
  Regression/Checksum/benchmarks_json/embedded_circle.json
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3471 OLCF Jupyter: Mamba is Pre-Installed
  Docs/source/install/hpc/summit.rst
Labels: component: documentation, component: post-processing, machine / system

#3462 User-Specified Used Inputs File
  Docs/source/usage/how_to_run.rst
  Docs/source/usage/parameters.rst
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
Labels: component: documentation, component: core

#3472 [mini] Fix unused import warnings in python analysis scripts
  Examples/Tests/ion_stopping/analysis_ion_stopping.py
  Examples/Tests/particle_fields_diags/analysis_particle_diags_impl.py
Labels: component: tests, cleaning

#3183 Do not query redundant `do_back_transformed_particles`
  Source/Diagnostics/BTDiagnostics.cpp
Labels: cleaning, component: diagnostics

#2942 Fix stair-case solver in 2D Cartesian
  Examples/Modules/embedded_boundary_cube/analysis_fields_2d.py
  Examples/Modules/embedded_boundary_cube/inputs_2d
  Regression/Checksum/benchmarks_json/embedded_boundary_cube_2d.json
  Source/FieldSolver/FiniteDifferenceSolver/EvolveE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicEvolveE.cpp
Labels: bug, bug: affects latest release, component: boundary, component: FDTD

#3479 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3475 Add reduced diagnostics to `picmi.py`
  Examples/Tests/reduced_diags/PICMI_inputs_loadbalancecosts.py
  Examples/Tests/reduced_diags/analysis_reduced_diags_loadbalancecosts.py
  Python/pywarpx/Diagnostics.py
  Python/pywarpx/WarpX.py
  Python/pywarpx/__init__.py
  Python/pywarpx/picmi.py
  Regression/WarpX-tests.ini
Labels: cleaning, component: PICMI

#3424 Diagnostics: print when writing openPMD, Ascent, Sensei and when writing BTD plotfile and openPMD
  Examples/Modules/RigidInjection/inputs_2d_BoostedFrame
  Examples/Modules/boosted_diags/inputs_3d_slice
  Examples/Physics_applications/laser_acceleration/inputs_2d_boost
  Regression/Checksum/benchmarks_json/BTD_ReducedSliceDiag.json
  Regression/Checksum/benchmarks_json/LaserAccelerationBoost.json
  Regression/WarpX-tests.ini
  Source/Diagnostics/BTD_Plotfile_Header_Impl.cpp
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/BoundaryScrapingDiagnostics.cpp
  Source/Diagnostics/FlushFormats/FlushFormat.H
  Source/Diagnostics/FlushFormats/FlushFormatAscent.H
  Source/Diagnostics/FlushFormats/FlushFormatAscent.cpp
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.H
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.H
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.H
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/FlushFormats/FlushFormatSensei.H
  Source/Diagnostics/FlushFormats/FlushFormatSensei.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/Utils/Parser/IntervalsParser.H
  Source/Utils/Parser/IntervalsParser.cpp
Labels: component: diagnostics, component: boosted frame

#3483 Replace "none" BC with Neumann for electrostatic
  Docs/source/usage/parameters.rst
  Examples/Tests/ElectrostaticSphereEB/inputs_3d_mixed_BCs
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/Utils/WarpXAlgorithmSelection.H
  Source/Utils/WarpXAlgorithmSelection.cpp
Labels: component: electrostatic, changes input scripts / defaults, component: boundary

#3323 Add warning to set zmin and zmax for ion-acc example
  Docs/source/usage/examples.rst
  Examples/Physics_applications/laser_ion/inputs
  Regression/Checksum/benchmarks_json/LaserIonAcc2d.json
Labels: component: documentation, changes input scripts / defaults

#3488 Docs: LUMI (CSC)
  Docs/source/install/hpc.rst
  Docs/source/install/hpc/frontier.rst
  Docs/source/install/hpc/lumi.rst
  Tools/machines/lumi-csc/lumi_warpx.profile.example
Labels: component: documentation, machine / system

#3489 Warn the user of possible instabilities if PML and PSATD are used together
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
Labels: component: spectral, warning, component: boundary

#3467 ABLASTR: Always Sync Option
  Docs/source/usage/parameters.rst
  Docs/source/usage/workflows/debugging.rst
  Regression/Checksum/benchmarks_json/pml_psatd_dive_divb_cleaning.json
  Regression/WarpX-tests.ini
  Source/Parallelization/WarpXComm.cpp
  Source/WarpX.H
  Source/ablastr/utils/Communication.H
  Source/ablastr/utils/Communication.cpp
Labels: component: documentation, component: ABLASTR

#3450 Fix Invalid Mem w/ Moving Window, LB & PMLs
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.H
Labels: bug, bug: affects latest release, component: load balancing, workaround, component: boundary

#3163 For background stopping, added error checks of the user input
  Source/Particles/Collision/BackgroundStopping/BackgroundStopping.cpp
Labels: component: collisions

#3490 Modify naming of species in CI fusion test
  Examples/Modules/nuclear_fusion/analysis_deuterium_tritium_fusion.py
  Examples/Modules/nuclear_fusion/inputs_deuterium_tritium_3d
  Examples/Modules/nuclear_fusion/inputs_deuterium_tritium_rz
  Regression/Checksum/benchmarks_json/Deuterium_Tritium_Fusion_3D.json
  Regression/Checksum/benchmarks_json/Deuterium_Tritium_Fusion_RZ.json
Labels: component: tests

#3350 BTD fields with RZ + openPMD - single mode only
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.cpp
Labels: enhancement, component: diagnostics, component: RZ, component: boosted frame

#3473 Add BTD notes to FAQ section
  Docs/source/usage/faq.rst
Labels: component: documentation, component: diagnostics, component: boosted frame

#3492 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3257 Implement D+D and D+He fusion
  Examples/Modules/nuclear_fusion/analysis_two_product_fusion.py
  Examples/Modules/nuclear_fusion/inputs_deuterium_deuterium_3d
  Regression/Checksum/benchmarks_json/Deuterium_Deuterium_Fusion_3D.json
  Regression/WarpX-tests.ini
  Source/Particles/Collision/BinaryCollision/BinaryCollisionUtils.H
  Source/Particles/Collision/BinaryCollision/BinaryCollisionUtils.cpp
  Source/Particles/Collision/BinaryCollision/NuclearFusion/BoschHaleFusionCrossSection.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/DeuteriumTritiumFusionCrossSection.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/NuclearFusionFunc.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/SingleNuclearFusionEvent.H
  Source/Particles/Collision/BinaryCollision/ParticleCreationFunc.H
  Source/Particles/Collision/BinaryCollision/ParticleCreationFunc.cpp
Labels: component: collisions
