Repository BLAST-WarpX/warpx, pull requests merged in 2023-12, with the labels that each got.

#4393 Set `amrex.omp_threads = "nosmt"`
  Docs/source/usage/parameters.rst
  Source/Initialization/WarpXAMReXInit.cpp
Labels: Performance optimization, changes input scripts / defaults, backend: openmp

#4456 New Cache Strategy
  .github/workflows/clang_tidy.yml
  .github/workflows/cleanup-cache-postpr.yml
  .github/workflows/cleanup-cache.yml
  .github/workflows/codeql.yml
  .github/workflows/cuda.yml
  .github/workflows/dependencies/ccache.sh
  .github/workflows/dependencies/clang14.sh
  .github/workflows/dependencies/dpcpp.sh
  .github/workflows/dependencies/gcc.sh
  .github/workflows/dependencies/gcc12.sh
  .github/workflows/dependencies/gcc12_blaspp_lapackpp.sh
  .github/workflows/dependencies/hip.sh
  .github/workflows/dependencies/icc.sh
  .github/workflows/dependencies/nvcc11-3.sh
  .github/workflows/dependencies/nvcc11-8.sh
  .github/workflows/dependencies/nvhpc.sh
  .github/workflows/dependencies/pyfull.sh
  .github/workflows/hip.yml
  .github/workflows/intel.yml
  .github/workflows/macos.yml
  .github/workflows/post-pr.yml
  .github/workflows/ubuntu.yml
Labels: Performance optimization, component: tests

#4459 Make geometry.dims abort message more user-friendly
  Source/Utils/WarpXUtil.cpp
Labels: cleaning

#4405 Add external current handling to Ohm's law solver
  Docs/source/theory/kinetic_fluid_hybrid_model.rst
  Docs/source/usage/parameters.rst
  Python/pywarpx/picmi.py
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICSolveE.cpp
  Source/FieldSolver/WarpXPushFieldsHybridPIC.cpp
  Source/WarpX.H
Labels: enhancement, component: fluid-ohm

#4469 Release 23.12
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#4470 Remove brew cache
  .github/workflows/macos.yml
Labels: component: tests

#4467 Doc: Restructure Examples
  .github/workflows/source/wrongFileNameInExamples
  Docs/source/dataanalysis/examples
  Docs/source/refs.bib
  Docs/source/usage/examples.rst
  Docs/source/usage/examples/capacitive_discharge
  Docs/source/usage/examples/gaussian_beam
  Docs/source/usage/examples/langmuir
  Docs/source/usage/examples/laser_ion
  Docs/source/usage/examples/lwfa
  Docs/source/usage/examples/ohm_solver_EM_modes
  Docs/source/usage/examples/ohm_solver_ion_Landau_damping
  Docs/source/usage/examples/ohm_solver_ion_beam_instability
  Docs/source/usage/examples/ohm_solver_magnetic_reconnection
  Docs/source/usage/examples/plasma_mirror
  Docs/source/usage/examples/pwfa
  Docs/source/usage/examples/uniform_plasma
  Docs/source/usage/python.rst
  Examples/Physics_applications/capacitive_discharge/README.md
  Examples/Physics_applications/capacitive_discharge/README.rst
  Examples/Physics_applications/laser_acceleration/README.md
  Examples/Physics_applications/laser_acceleration/README.rst
  Examples/Physics_applications/laser_acceleration/plot_3d.py
  Examples/Physics_applications/laser_ion/README.rst
  Examples/Physics_applications/laser_ion/inputs_2d
  Examples/Physics_applications/plasma_acceleration/README.rst
  Examples/Physics_applications/plasma_mirror/README.rst
  Examples/Physics_applications/uniform_plasma/README.rst
  Examples/Tests/gaussian_beam/README.rst
  Examples/Tests/langmuir/README.md
  Examples/Tests/langmuir/README.rst
  Examples/Tests/ohm_solver_EM_modes/README.rst
  Examples/Tests/ohm_solver_ion_Landau_damping/README.rst
  Examples/Tests/ohm_solver_ion_beam_instability/README.rst
  Examples/Tests/ohm_solver_magnetic_reconnection/README.rst
  Regression/WarpX-tests.ini
Labels: component: documentation, component: tests

#4472 Doc: Streamline Python Input
  Docs/source/index.rst
  Docs/source/usage/parameters.rst
  Docs/source/usage/pwfa.rst
  Docs/source/usage/python.rst
  Docs/source/usage/workflows.rst
  Docs/source/usage/workflows/domain_decomposition.rst
  Python/pywarpx/callbacks.py
  Python/pywarpx/particle_containers.py
  Python/pywarpx/picmi.py
Labels: component: documentation, component: Python

#4473 pybind11: v2.11.1+
  cmake/dependencies/pybind11.cmake
Labels: install, component: third party, component: Python

#4478 Set alpha mass directly from NIST data
  Source/Particles/SpeciesPhysicalProperties.cpp
Labels: help wanted

#4481 Add `latex_theory/allbibs.bib` to bibliography list and delete duplicates
  Docs/source/conf.py
  Docs/source/latex_theory/allbibs.bib
  Docs/source/refs.bib
  Docs/source/theory/intro.rst
  Examples/Physics_applications/laser_ion/README.rst
  Examples/Physics_applications/plasma_acceleration/README.rst
  Examples/Physics_applications/plasma_mirror/README.rst
Labels: component: documentation

#4490 sqrt -> std::sqrt
  Source/Initialization/InjectorMomentum.H
Labels: Performance optimization

#4441 Move external field parameters out of WarpX class
  Source/Initialization/CMakeLists.txt
  Source/Initialization/ExternalField.H
  Source/Initialization/ExternalField.cpp
  Source/Initialization/ExternalField_fwd.H
  Source/Initialization/Make.package
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/WarpXRegrid.cpp
  Source/Python/WarpX.cpp
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#4482 Custom class for bibliography style
  Docs/requirements.txt
  Docs/source/conf.py
  Docs/source/latex_theory/allbibs.bib
  Docs/source/refs.bib
  Docs/spack.yaml
Labels: component: documentation

#4489 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Python/pywarpx/fields.py
  Python/pywarpx/particle_containers.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  Source/Python/Particles/PinnedMemoryParticleContainer.cpp
  Source/Python/Particles/WarpXParticleContainer.cpp
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
Labels: component: third party, component: Python

#4496 Clang-tidy: enable readability-duplicate-include check in clang-tidy CI test
  .clang-tidy
  Source/ablastr/fields/PoissonSolver.H
  Source/ablastr/fields/VectorPoissonSolver.H
Labels: component: tests, cleaning

#4480 Use more consistent species types in fusion module
  Examples/Tests/nuclear_fusion/analysis_proton_boron_fusion.py
  Examples/Tests/nuclear_fusion/inputs_proton_boron_2d
  Examples/Tests/nuclear_fusion/inputs_proton_boron_3d
  Regression/Checksum/benchmarks_json/Proton_Boron_Fusion_2D.json
  Regression/Checksum/benchmarks_json/Proton_Boron_Fusion_3D.json
  Source/Particles/Collision/BinaryCollision/BinaryCollisionUtils.cpp
  Source/Particles/Collision/BinaryCollision/NuclearFusion/ProtonBoronFusionCrossSection.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/ProtonBoronFusionInitializeMomentum.H
Labels: changes input scripts / defaults, component: collisions

#4503 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
Labels: component: third party

#4499 workflow training neural network from warpx data
  Docs/source/refs.bib
  Docs/source/usage/workflows.rst
  Docs/source/usage/workflows/ml_dataset_training.rst
  Docs/source/usage/workflows/ml_materials/create_dataset.py
  Docs/source/usage/workflows/ml_materials/neural_network_classes.py
  Docs/source/usage/workflows/ml_materials/run_warpx_training.py
  Docs/source/usage/workflows/ml_materials/train.py
  Docs/source/usage/workflows/ml_materials/visualize.py
Labels: component: documentation

#4518 Clang-tidy: enable no-malloc check in clang-tidy CI test
  .clang-tidy
Labels: component: tests, cleaning

#4479 Update descriptions of hybrid-PIC examples
  Docs/source/usage/examples.rst
  Examples/Tests/ohm_solver_EM_modes/README.rst
  Examples/Tests/ohm_solver_ion_Landau_damping/README.rst
  Examples/Tests/ohm_solver_ion_beam_instability/README.rst
  Examples/Tests/ohm_solver_magnetic_reconnection/README.rst
Labels: component: documentation

#4513 Bibliography: improved citations
  Docs/source/latex_theory/Boosted_frame/Boosted_frame.tex
  Docs/source/latex_theory/allbibs.bib
  Docs/source/refs.bib
  Docs/source/theory/boosted_frame.rst
  Docs/source/theory/picsar_theory.rst
Labels: component: documentation

#4506 Bibliography: make author family names appear last
  Docs/source/conf.py
Labels: component: documentation

#4504 Clang-Tidy: performance-noexcept-move-constructor
  .clang-tidy
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
  Source/Particles/NamedComponentParticleContainer.H
Labels: Performance optimization, component: tests, cleaning

#4522 LatticeElementFinder: move function definition to cpp file
  Source/AcceleratorLattice/LatticeElementFinder.H
  Source/AcceleratorLattice/LatticeElementFinder.cpp
Labels: cleaning, component: core

#4525 Improve documentation for laser chirp
  Docs/source/usage/parameters.rst
Labels: component: documentation

#4524 Doc: Fix ChecksumAPI `autofunction`
  Docs/requirements.txt
  Docs/source/conf.py
  Docs/source/developers/checksum.rst
  Docs/spack.yaml
Labels: bug, component: documentation

#4521 WarpXSumGuardCells: move function definitions in cpp file
  Source/Parallelization/CMakeLists.txt
  Source/Parallelization/Make.package
  Source/Parallelization/WarpXSumGuardCells.H
  Source/Parallelization/WarpXSumGuardCells.cpp
Labels: cleaning, component: core

#4529 Spruce up amr.rst
  Docs/source/latex_theory/AMR/AMR.tex
  Docs/source/latex_theory/allbibs.bib
  Docs/source/theory/amr.rst
Labels: component: documentation

#4520 Doc: Extend a Simulation Workflow
  Docs/source/usage/python.rst
  Docs/source/usage/workflows.rst
  Docs/source/usage/workflows/python_extend.rst
  Python/pywarpx/callbacks.py
  Source/FieldSolver/ElectrostaticSolver.H
  Source/Python/WarpX.cpp
Labels: component: documentation, component: Python

#4533 Fix chirp documentation
  Docs/source/usage/parameters.rst
Labels: bug, component: documentation

#4532 Spruce up input_output.rst
  Docs/source/latex_theory/input_output/input_output.tex
  Docs/source/theory/input_output.rst
Labels: component: documentation

#4531 Spruce up cold_fluid_model.rst
  Docs/source/refs.bib
  Docs/source/theory/cold_fluid_model.rst
Labels: component: documentation

#4530 Spruce up boosted_frame.rst
  Docs/source/theory/boosted_frame.rst
Labels: component: documentation, component: boosted frame

#4528 Documentation: numbered reference formatting
  .gitignore
  Docs/source/_static/custom.css
  Docs/source/conf.py
  Docs/source/dataanalysis/sensei.rst
Labels: bug, component: documentation, component: third party, bug: affects latest release

#4527 Fix CI for ROCm 6.0
  .github/workflows/dependencies/hip.sh
Labels: component: tests, backend: hip

#4512 Spruce up ml_dataset_training.rst
  Docs/source/usage/workflows/ml_dataset_training.rst
Labels: component: documentation

#4536 Spruce up PIC theory section
  Docs/source/index.rst
  Docs/source/latex_theory/Makefile
  Docs/source/theory/pic.rst
  Docs/source/theory/picsar_theory.rst
  Docs/source/usage/pwfa.rst
Labels: component: documentation

#4537 Docs: rename and spruce up boundary conditions section
  Docs/source/index.rst
  Docs/source/theory/PML.rst
  Docs/source/theory/boundary_conditions.rst
Labels: component: documentation, component: boundary

#4534 Spruce up kinetic fluid hybrid model.rst
  Docs/source/refs.bib
  Docs/source/theory/kinetic_fluid_hybrid_model.rst
Labels: component: documentation

#4538 Doc: CUDA 11.7+
  Docs/source/install/dependencies.rst
  Tools/machines/summit-olcf/summit_warpx.profile.example
Labels: bug, backend: cuda, install, component: third party, bug: affects latest release, machine / system

#4477 Add updated instructions for WarpX on Karolina
  Docs/source/install/hpc/karolina.rst
  Tools/machines/karolina-it4i/cleanup.sh
  Tools/machines/karolina-it4i/install_cpu_dependencies.sh
  Tools/machines/karolina-it4i/install_dependencies.sh
  Tools/machines/karolina-it4i/install_gpu_dependencies.sh
  Tools/machines/karolina-it4i/karolina_cpu_warpx.profile.example
  Tools/machines/karolina-it4i/karolina_gpu.qsub
  Tools/machines/karolina-it4i/karolina_gpu.sbatch
  Tools/machines/karolina-it4i/karolina_gpu_warpx.profile.example
  Tools/machines/karolina-it4i/karolina_warpx.profile.example
  Tools/machines/karolina-it4i/spack-karolina-cuda.yaml
Labels: component: documentation, machine / system

#4541 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
Labels: component: third party

#4543 WarpXAMReXInit: move include directive from header to cpp file
  Source/Initialization/WarpXAMReXInit.H
  Source/Initialization/WarpXAMReXInit.cpp
Labels: cleaning

#4550 Adding user defined keywords in Hybrid PIC Python class to allow for …
  Python/pywarpx/picmi.py
Labels: enhancement, component: PICMI, component: Python

#4555 Clean up doc to improve readability
  Docs/source/usage/parameters.rst
Labels: component: documentation

#4551 Add hybrid-PIC PoP reference to docs
  Docs/source/highlights.rst
  Docs/source/refs.bib
  Docs/source/theory/kinetic_fluid_hybrid_model.rst
Labels: component: documentation

#4552 Fix perlmutter reference in documentation
  Docs/source/developers/profiling.rst
Labels: component: documentation, machine / system

#4559 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
Labels: component: third party

#4545 Add updated instructions for WarpX on Karolina
  Tools/machines/karolina-it4i/install_dependencies.sh
  Tools/machines/karolina-it4i/karolina_gpu.sbatch
  Tools/machines/karolina-it4i/karolina_warpx.profile.example
Labels: component: documentation, cleaning, machine / system

#4558 Fix: BeamRelevant 1D, 2D
  Source/Diagnostics/ReducedDiags/BeamRelevant.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#4071 Implicit electromagnetic solver using Picard iterations
  Docs/source/usage/parameters.rst
  Examples/Tests/Implicit/analysis_1d.py
  Examples/Tests/Implicit/inputs_1d
  Regression/Checksum/benchmarks_json/ImplicitPicard_1d.json
  Regression/WarpX-tests.ini
  Source/Evolve/CMakeLists.txt
  Source/Evolve/Make.package
  Source/Evolve/WarpXEvolve.cpp
  Source/Evolve/WarpXOneStepImplicitPicard.cpp
  Source/Evolve/WarpXPushType.H
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/Gather/FieldGather.H
  Source/Particles/LaserParticleContainer.H
  Source/Particles/LaserParticleContainer.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhotonParticleContainer.H
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/PushSelector.H
  Source/Particles/Pusher/UpdatePosition.H
  Source/Particles/RigidInjectedParticleContainer.H
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/ShapeFactors.H
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/Utils/WarpXAlgorithmSelection.H
  Source/Utils/WarpXAlgorithmSelection.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: enhancement

#4508 Fix default initialization of runtime attributes.
  Examples/Tests/ionization/analysis_ionization.py
  Examples/Tests/ionization/inputs_2d_rt
  Regression/Checksum/benchmarks_json/ionization_lab.json
  Source/Particles/Collision/BackgroundMCC/BackgroundMCCCollision.cpp
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
  Source/Particles/Collision/BinaryCollision/ParticleCreationFunc.H
  Source/Particles/LaserParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/ParticleCreation/DefaultInitialization.H
  Source/Particles/ParticleCreation/FilterCopyTransform.H
  Source/Particles/ParticleCreation/FilterCreateTransformFromFAB.H
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: bug, bug: affects latest release, component: core

#4544 Update explanation of why 2D simulations are not suitable for plasma-wakefield
  Examples/Physics_applications/laser_acceleration/README.rst
  Examples/Physics_applications/plasma_acceleration/README.rst
Labels: component: documentation
