Repository BLAST-WarpX/warpx, pull requests merged in 2023-03, with the labels that each got.

#3718 GB: Added DOI
  Docs/source/acknowledge_us.rst
  Docs/source/highlights.rst
Labels: component: documentation

#3719 Release 23.03
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#3725 Moving window: shift G MultiFab w/ div(B) cleaning
  Source/Utils/WarpXMovingWindow.cpp
Labels: bug, bug: affects latest release, component: core

#3726 RZ FDTD: fix bug w/ div(E) cleaning (extra c2)
  Source/FieldSolver/FiniteDifferenceSolver/EvolveF.cpp
Labels: bug, bug: affects latest release, component: RZ, component: FDTD

#3729 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3730 Docs: more structure in numerics input section
  Docs/source/usage/parameters.rst
Labels: component: documentation

#3732 fix zmax_plasma_... calculation upon restart
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: bug, bug: affects latest release, component: checkpoint/restart, component: boosted frame

#3660 Add test for DD fusion with intra-species collisions
  Examples/Tests/nuclear_fusion/analysis_deuterium_deuterium_3d_intraspecies.py
  Examples/Tests/nuclear_fusion/inputs_deuterium_deuterium_3d_intraspecies
  Regression/Checksum/benchmarks_json/Deuterium_Deuterium_Fusion_3D_intraspecies.json
  Regression/WarpX-tests.ini
Labels: component: tests, component: collisions

#3737 Doc: Fix Builds, Disable all but HTML
  .readthedocs.yml
  Docs/source/latex_theory/allbibs.bib
  Docs/source/theory/boosted_frame.rst
  Docs/source/theory/intro.rst
  Docs/source/usage/parameters.rst
  Docs/source/usage/pwfa.rst
Labels: bug, component: documentation, bug: affects latest release

#3735 Fix handling of name passed into SetTag
  Source/WarpX.H
  Source/WarpX.cpp
Labels: bug, cleaning

#3744 Spack: OpenMP w/o GPU
  Tools/machines/desktop/spack-macos-openmp.yaml
  Tools/machines/desktop/spack-ubuntu-openmp.yaml
Labels: install, component: third party, backend: openmp, machine / system

#3740 Implement PICMI flag for setting max_step from btd
  Python/pywarpx/picmi.py
Labels: component: PICMI, component: Python

#3747 Fix Bucket __getattr__
  Python/pywarpx/Bucket.py
Labels: bug, component: Python

#3743 PICMI: add missing flags for latest algorithms
  Python/pywarpx/picmi.py
Labels: component: PICMI, component: Python

#3738 Deposition: Fix LB Cost Segfault
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/Deposition/CurrentDeposition.H
Labels: bug, bug: affects latest release, component: load balancing

#3710 Docs: fix default of `warpx.n_field_gather_buffer`
  Docs/source/usage/parameters.rst
Labels: component: documentation

#3741 Fix figure reference in docs for input and output
  Docs/source/theory/input_output.rst
Labels: component: documentation

#3746 Sort `FieldProbe` output using probe particle ids
  Source/Diagnostics/ReducedDiags/FieldProbe.H
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
Labels: component: diagnostics

#3755 Correct typo in a comment in WarpX.H
  Source/WarpX.H
Labels: cleaning

#3708 Small fixes for Coulomb collisions
  Source/Particles/Collision/BinaryCollision/Coulomb/UpdateMomentumPerezElastic.H
Labels: cleaning, component: collisions

#3765 CI: fix bug in NVCC GNUMake yml file
  .github/workflows/cuda.yml
Labels: bug, component: tests, bug: affects latest release

#3763 Removed notes which were no longer restrictions on the allowed values
  Docs/source/usage/parameters.rst
Labels: component: documentation

#3761 Bug fixed: added missing CheckGuardCells() for G fields with divB_cle…
  Source/Initialization/WarpXInitData.cpp
Labels: component: parallelization

#3766 Add do_not_push and do_not_gather in PICMI.
  Python/pywarpx/picmi.py
Labels: component: PICMI

#3759 Crusher (OLCF): ADIOS 2.8.3
  Docs/source/install/hpc/crusher.rst
  Tools/machines/crusher-olcf/crusher_warpx.profile.example
Labels: component: documentation, component: third party, machine / system

#3753 [mini] Print full json file if checksum CI fails
  Regression/Checksum/benchmarks_json/Deuterium_Deuterium_Fusion_3D.json
  Regression/Checksum/checksum.py
Labels: component: tests

#3767 AMReX/PICSAR: Weekly Update
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#1613 Clean up for Langmuir tests
  Examples/Tests/langmuir/PICMI_inputs_2d.py
  Examples/Tests/langmuir/PICMI_inputs_3d.py
  Examples/Tests/langmuir/PICMI_inputs_rz.py
  Examples/Tests/langmuir/README.md
  Examples/Tests/langmuir/analysis_1d.py
  Examples/Tests/langmuir/analysis_2d.py
  Examples/Tests/langmuir/analysis_3d.py
  Examples/Tests/langmuir/analysis_rz.py
  Examples/Tests/langmuir/inputs_1d
  Examples/Tests/langmuir/inputs_2d
  Examples/Tests/langmuir/inputs_3d
  Examples/Tests/langmuir/inputs_rz
  Regression/WarpX-tests.ini
Labels: component: tests, cleaning

#3709 PICMI Boundary: Silver-Mueller
  Docs/requirements.txt
  Python/pywarpx/picmi.py
  Python/setup.py
  requirements.txt
Labels: component: Python, component: boundary

#3776 Fix add_particles to account for theta attribute with RZ
  Python/pywarpx/_libwarpx.py
  Source/Particles/WarpXParticleContainer.cpp
Labels: bug, bug: affects latest release, component: RZ, component: Python

#3770 Correct comments from #3708
  Source/Particles/Collision/BinaryCollision/Coulomb/UpdateMomentumPerezElastic.H
Labels: component: documentation

#3768 Allow 8-fold symmetry option
  Docs/source/usage/parameters.rst
  Examples/Tests/multi_j/inputs_rz
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
Labels: enhancement

#3774 Fix all the "modernize-loop-convert" issues found with clang-tidy
  Source/Diagnostics/BTD_Plotfile_Header_Impl.cpp
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/WarpXIO.cpp
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
Labels: cleaning

#3779 Add FieldEnergy diagnostic in RZ
  Source/Diagnostics/ReducedDiags/FieldEnergy.H
  Source/Diagnostics/ReducedDiags/FieldEnergy.cpp
Labels: enhancement, component: diagnostics, component: RZ

#3782 Workaround for nvcc
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.cpp
Labels: backend: cuda, Performance optimization, workaround

#3784 Refactoring of main.cpp to improve readability
  Source/Utils/CMakeLists.txt
  Source/Utils/MPIInitHelpers.H
  Source/Utils/MPIInitHelpers.cpp
  Source/Utils/Make.package
  Source/Utils/WarpXrocfftUtil.H
  Source/Utils/WarpXrocfftUtil.cpp
  Source/ablastr/utils/CMakeLists.txt
  Source/ablastr/utils/Make.package
  Source/ablastr/utils/timer/CMakeLists.txt
  Source/ablastr/utils/timer/Make.package
  Source/ablastr/utils/timer/Timer.H
  Source/ablastr/utils/timer/Timer.cpp
  Source/main.cpp
Labels: cleaning

#3786 include std::set, int template parameter
  Source/Initialization/PlasmaInjector.cpp
Labels: bug, cleaning

#3785 ParaView: Add More Docs
  Docs/source/dataanalysis/paraview.rst
Labels: component: documentation, component: openPMD, component: third party

#3772 Update `updateAMReX.py` to match new CUDA yml file
  Tools/Release/updateAMReX.py
Labels: bug, component: tests, component: third party, bug: affects latest release

#3787 Docs: start using BibTeX in theory section
  Docs/requirements.txt
  Docs/source/conf.py
  Docs/source/refs.bib
  Docs/source/theory/intro.rst
Labels: component: documentation

#3762 Enable calling SortParticlesForDeposition
  Docs/source/usage/parameters.rst
  Source/Particles/MultiParticleContainer.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: backend: cuda, Performance optimization

#3764 Fix bugs related to azimuthal modes for multi-J algo in RZ geometry
  Regression/Checksum/benchmarks_json/multi_J_rz_psatd.json
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.H
Labels: bug, component: spectral, bug: affects latest release, component: RZ

#3734 Fix restart btd
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/BoundaryScrapingDiagnostics.H
  Source/Diagnostics/BoundaryScrapingDiagnostics.cpp
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/FullDiagnostics.H
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/MultiDiagnostics.H
  Source/Diagnostics/WarpXIO.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
Labels: bug, bug: affects latest release, component: diagnostics, component: checkpoint/restart, component: boosted frame

#3783 Fix: openPMD Weighting Loading
  Docs/source/usage/parameters.rst
  Source/Particles/PhysicalParticleContainer.cpp
Labels: bug, component: openPMD, bug: affects latest release

#3790 Output enabled diagnostics (and checkpoint) on interrupt by default
  Source/Evolve/WarpXEvolve.cpp
Labels: component: diagnostics

#3793 [Mini-PR] Add random seed specification to `picmi`
  Python/pywarpx/picmi.py
Labels: component: PICMI

#3780 Docs: Frontier/Crusher ROCm 5.3/4 Perf
  Docs/source/install/hpc/crusher.rst
  Docs/source/install/hpc/frontier.rst
  Docs/source/install/hpc/lumi.rst
Labels: Performance optimization, component: documentation, machine / system
