Repository BLAST-WarpX/warpx, pull requests merged in 2023-08, with the labels that each got.

#4132 Remove WarpX::GetInstance call from ParserFilter functor
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.H
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Particles/Filter/FilterFunctors.H
Labels: cleaning, component: diagnostics

#4139 Move GotoNextLine helper function into ablastr
  Source/Diagnostics/BTD_Plotfile_Header_Impl.cpp
  Source/Diagnostics/ParticleIO.cpp
  Source/Diagnostics/WarpXIO.cpp
  Source/WarpX.H
  Source/ablastr/utils/text/CMakeLists.txt
  Source/ablastr/utils/text/Make.package
  Source/ablastr/utils/text/StreamUtils.H
  Source/ablastr/utils/text/StreamUtils.cpp
Labels: cleaning, component: ABLASTR

#4124 Clang tidy CI test: add several readability checks to clang tidy CI test
  .clang-tidy
  Source/BoundaryConditions/PML.cpp
  Source/BoundaryConditions/WarpX_PEC.H
  Source/BoundaryConditions/WarpX_PEC.cpp
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformParticleFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/DivBFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/DivEFunctor.cpp
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/MultiDiagnostics.cpp
  Source/Diagnostics/ReducedDiags/FieldEnergy.cpp
  Source/Diagnostics/ReducedDiags/FieldMomentum.cpp
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
  Source/Diagnostics/ReducedDiags/LoadBalanceCosts.cpp
  Source/Diagnostics/ReducedDiags/ParticleEnergy.cpp
  Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp
  Source/Diagnostics/ReducedDiags/ParticleMomentum.cpp
  Source/Diagnostics/SliceDiagnostic.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.cpp
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmFirstOrder.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldData.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/WarpXRegrid.cpp
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
  Source/Particles/LaserParticleContainer.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Resampling/Resampling.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.cpp
Labels: component: tests, cleaning

#4063 Clang tidy CI test: add almost all the cert-* checks to clang tidy CI test
  .clang-tidy
  Source/Diagnostics/BTDiagnostics.cpp
Labels: component: tests, cleaning

#4113 Clean up charge deposition code duplication
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: cleaning

#4155 WarpX: Rule-of-Five
  Source/WarpX.H
Labels: cleaning

#4160 Remove occurrences of WarpX::GetInstance from WarpX::InitFromCheckpoint ()
  Source/Diagnostics/WarpXIO.cpp
Labels: cleaning

#4143 Add a few abbreviations and terms to the glossary
  Docs/source/glossary.rst
Labels: component: documentation

#4165 Release 23.08
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#4166 Show compiler warnings with appleclang
  cmake/WarpXFunctions.cmake
Labels: warning, install

#4163 Clang tidy CI test: add 4 readability-* checks to clang-tidy CI test
  .clang-tidy
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/ParticleDiag/ParticleDiag.cpp
  Source/Diagnostics/ReducedDiags/ChargeOnEB.cpp
  Source/Diagnostics/ReducedDiags/FieldReduction.cpp
  Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp
  Source/Diagnostics/ReducedDiags/ParticleHistogram2D.H
  Source/Diagnostics/ReducedDiags/ReducedDiags.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/Initialization/PlasmaInjector.cpp
  Source/Initialization/TemperatureProperties.cpp
  Source/Utils/Parser/ParserUtils.cpp
  Source/WarpX.cpp
Labels: component: tests, cleaning

#4154 Fix printing of warning messages at the end of the simulation
  Source/main.cpp
Labels: bug, warning, bug: affects latest release

#4164 Clang tidy CI test: add 4 more readability-* checks to clang-tidy CI test
  .clang-tidy
  Source/Diagnostics/FlushFormats/FlushFormatSensei.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
Labels: component: tests, cleaning

#4158 Clang tidy CI test: add two performance-* checks to clang-tidy CI test
  .clang-tidy
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Particles/MultiParticleContainer.cpp
  Source/ablastr/utils/Serialization.H
Labels: component: tests, cleaning

#4152 Fix typo in parameters.rst
  Docs/source/usage/parameters.rst
Labels: component: documentation

#4151 Remove unused Timer function from WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.H
Labels: component: openPMD, cleaning

#4150 Clang tidy CI test: add some misc-* checks
  .clang-tidy
  Source/Initialization/WarpXAMReXInit.H
  Source/Initialization/WarpXAMReXInit.cpp
Labels: component: tests, cleaning

#4168 Doc: Gitter -> Discussions
  Docs/source/index.rst
  README.md
Labels: component: documentation

#4091 Add write_diagonstics_on_restart input option
  Docs/source/usage/parameters.rst
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: diagnostics

#4171 Doc: Update License Notice
  LICENSE.txt
  README.md
  Tools/Release/newVersion.sh
Labels: component: documentation

#4172 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#4177 Fix Python test due to recent openPMD-viewer update
  Examples/Tests/scraping/analysis_rz.py
Labels: component: tests

#4112 Fix continuous injection of lasers
  Source/Particles/LaserParticleContainer.H
  Source/Particles/LaserParticleContainer.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: bug, bug: affects latest release

#3748 Add Python wrapper to set the lens strength
  Python/pywarpx/_libwarpx.py
  Source/Python/WarpXWrappers.H
  Source/Python/WarpXWrappers.cpp
Labels: component: PICMI, component: Python

#4180 In picmi.py, add G to fields to plot check
  Python/pywarpx/picmi.py
Labels: component: PICMI, component: diagnostics

#4173 Python 3.8+
  Docs/source/developers/gnumake/python.rst
  Docs/source/install/dependencies.rst
  Docs/source/usage/python.rst
  Python/setup.py
  setup.py
Labels: install, component: third party, component: Python

#4153 t_lab optionally imposed for externally loaded species in the boosted frame
  Docs/source/usage/parameters.rst
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
Labels: component: openPMD

#4183 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#4182 Docs: HPC3 (UCI) with Only `-j 12`
  Docs/source/install/hpc/hpc3.rst
  Tools/machines/hpc3-uci/install_gpu_dependencies.sh
Labels: component: documentation, machine / system

#4190 Affiliation update in Zenodo file
  .zenodo.json
Labels: component: documentation

#4189 Update Python installation instructions on HPC
  Docs/source/install/cmake.rst
  Docs/source/install/hpc/adastra.rst
  Docs/source/install/hpc/frontier.rst
  Docs/source/install/hpc/hpc3.rst
  Docs/source/install/hpc/karolina.rst
  Docs/source/install/hpc/lawrencium.rst
  Docs/source/install/hpc/lumi.rst
  Docs/source/install/hpc/lxplus.rst
  Docs/source/install/hpc/perlmutter.rst
  Docs/source/install/hpc/summit.rst
Labels: component: documentation, component: Python

#4184 Fix time update in the boosted frame for externally loaded fields
  Source/Particles/LaserParticleContainer.cpp
Labels: bug, bug: affects latest release, component: boosted frame

#4191 Cleanup plasma injection
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/PhysicalParticleContainer.cpp
Labels: cleaning

#4198 Electrostatic sphere tests: add missing checksum analysis
  Examples/Tests/electrostatic_sphere/analysis_electrostatic_sphere.py
  Regression/Checksum/benchmarks_json/ElectrostaticSphere.json
  Regression/Checksum/benchmarks_json/ElectrostaticSphereLabFrame.json
  Regression/Checksum/benchmarks_json/ElectrostaticSphereRZ.json
Labels: component: tests

#3982 adds nodal electrostatic solver
  Examples/Tests/nodal_electrostatic/analysis_3d.py
  Examples/Tests/nodal_electrostatic/inputs_3d
  Regression/Checksum/benchmarks_json/ElectrostaticSphereRelNodal.json
  Regression/Checksum/benchmarks_json/NodalElectrostaticSolver.json
  Regression/WarpX-tests.ini
  Source/FieldSolver/ElectrostaticSolver.cpp
Labels: component: electrostatic

#4200 Fix: Remove Overly Exported Classes
  Source/FieldSolver/ElectrostaticSolver.H
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/Deposition/SharedDepositionUtils.H
  Source/Particles/NamedComponentParticleContainer.H
  Source/Particles/WarpXParticleContainer.H
Labels: bug, install, component: Python

#4116 Include `J` in diagnostic output when an electromagnetic solver is not used
  Examples/Tests/collision/inputs_2d
  Examples/Tests/collision/inputs_3d
  Examples/Tests/collision/inputs_rz
  Examples/Tests/particle_boundary_process/PICMI_inputs_reflection.py
  Regression/Checksum/benchmarks_json/Python_prev_positions.json
  Regression/Checksum/benchmarks_json/collisionRZ.json
  Regression/Checksum/benchmarks_json/collisionXYZ.json
  Regression/Checksum/benchmarks_json/collisionXZ.json
  Regression/Checksum/benchmarks_json/hard_edged_quadrupoles.json
  Regression/Checksum/benchmarks_json/hard_edged_quadrupoles_moving.json
  Source/Diagnostics/ComputeDiagFunctors/CMakeLists.txt
  Source/Diagnostics/ComputeDiagFunctors/CellCenterFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/ComputeDiagFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/JFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/JFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/Make.package
  Source/Diagnostics/ComputeDiagFunctors/RhoFunctor.cpp
  Source/Diagnostics/FullDiagnostics.H
  Source/Diagnostics/FullDiagnostics.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#4205 Add Low-noise Mode GPU-to-CPU mapping for Frontier
  Tools/machines/frontier-olcf/submit.sh
Labels: backend: cuda, component: documentation, machine / system

#4207 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#4206 pyWarpX.H: Add Include Guard
  Source/Python/pyWarpX.H
Labels: bug, component: Python

#4215 CI: Sphinx <7.2 for now
  Docs/requirements.txt
Labels: bug, component: documentation, component: third party, workaround

#4212 Hybrid grid type not implemented in RZ geometry
  Docs/source/usage/parameters.rst
  Source/WarpX.cpp
Labels: bug, bug: affects latest release, geometry: RZ

#4214 Fix mass and charge reading from an external openPMD file
  Source/Initialization/PlasmaInjector.cpp
Labels: bug, component: openPMD, bug: affects latest release

#4216 fix undefined behavior in btd intervals
  Source/Utils/Parser/IntervalsParser.cpp
Labels: bug, bug: affects latest release, component: diagnostics, component: boosted frame

#4211 CMake: Fix logic that triggers shared AMReX
  CMakeLists.txt
  cmake/dependencies/AMReX.cmake
Labels: bug, install, component: Python

#4208 BoxArray in BTD has single box
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/ComputeDiagFunctor.H
Labels: bug, bug: affects latest release, component: diagnostics, component: boosted frame

#4202 BTD RZ test: add missing checksum analysis
  Examples/Tests/btd_rz/analysis_BTD_laser_antenna.py
  Regression/Checksum/benchmarks_json/BTD_rz.json
Labels: component: tests

#4195 Use only 8 cores to compile on Summit
  Docs/source/install/hpc/summit.rst
Labels: component: documentation, machine / system

#4222 Add error check/message for Cuda 11.6 bug with Yee solver
  Source/Initialization/WarpXInitData.cpp
Labels: backend: cuda, warning

#4220 Fix Repeated Plasma Lens: Start
  Docs/source/usage/parameters.rst
  Source/Particles/Gather/GetExternalFields.H
Labels: bug, bug: affects latest release, component: core

#4228 Fix ParticleContainer for BTD plotfile
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
Labels: bug, bug: affects latest release, component: diagnostics, component: boosted frame

#4229 Fix Python wrapper to extract `theta`
  Python/pywarpx/particle_containers.py
Labels: bug, component: Python

#4224 CI: Shrink NVHPC Size
  .github/workflows/cuda.yml
  .github/workflows/dependencies/nvhpc.sh
Labels: backend: cuda, component: tests

#4218 Fix: WarpX Version
  CMakeLists.txt
  Python/pywarpx/__init__.py
  Python/pywarpx/_libwarpx.py
  Source/Python/pyWarpX.cpp
  setup.py
Labels: bug, bug: affects latest release, component: core, component: Python

#4227 Fix: openPMD 1D/2D3V Constant Positions
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: bug, component: openPMD, bug: affects latest release, component: diagnostics

#4231 Do not call pre-processing routine in Python initialization
  Python/pywarpx/_libwarpx.py
  Source/Python/pyWarpX.cpp
Labels: bug, bug: affects latest release, component: Python

#4226 Doc: HPC Python Separate (Static/Shared AMReX)
  Docs/source/install/hpc/adastra.rst
  Docs/source/install/hpc/frontier.rst
  Docs/source/install/hpc/hpc3.rst
  Docs/source/install/hpc/karolina.rst
  Docs/source/install/hpc/lawrencium.rst
  Docs/source/install/hpc/lumi.rst
  Docs/source/install/hpc/lxplus.rst
  Docs/source/install/hpc/perlmutter.rst
  Docs/source/install/hpc/summit.rst
  Tools/machines/adastra-cines/install_dependencies.sh
  Tools/machines/frontier-olcf/install_dependencies.sh
  Tools/machines/hpc3-uci/install_gpu_dependencies.sh
  Tools/machines/karolina-it4i/install_cpu_dependencies.sh
  Tools/machines/karolina-it4i/install_gpu_dependencies.sh
  Tools/machines/lumi-csc/install_dependencies.sh
  Tools/machines/perlmutter-nersc/install_cpu_dependencies.sh
  Tools/machines/perlmutter-nersc/install_gpu_dependencies.sh
  Tools/machines/summit-olcf/install_gpu_dependencies.sh
Labels: bug, component: documentation, install, component: third party, machine / system, component: Python, workaround

#4235 Frontier (OLCF): MPI_Waitall issues
  Docs/source/install/hpc/frontier.rst
  Tools/machines/frontier-olcf/submit.sh
  Tools/machines/lumi-csc/submit.sh
Labels: component: documentation, machine / system, component: parallelization, workaround

#4239 Remove some unnecessary static variables from WarpX.H
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#4242 Remove AddToMultiFabMap functions from WarpX class
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#4238 Cleaning: Explicit Capture in Copy Lambda
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: cleaning, component: diagnostics

#4237 Work-Around: Segfault in MPI_Init with HIP
  Source/ablastr/parallelization/MPIInitHelpers.cpp
  Source/main.cpp
Labels: bug, backend: hip, component: parallelization, workaround

#4243 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#4221 Docs: WarpX HOFI Start-to-End Paper
  Docs/source/highlights.rst
Labels: component: documentation

#4148 Add LabFrameParticleDiagnostic to picmi
  Python/pywarpx/picmi.py
Labels: component: PICMI, component: diagnostics

#4223 Docs: Perlmutter (NERSC) Update
  Tools/machines/perlmutter-nersc/perlmutter_gpu.sbatch
Labels: backend: cuda, component: documentation, machine / system

#4244 Add Python bindings to extract the timestep dt
  Source/Python/WarpX.cpp
  Source/WarpX.H
Labels: component: Python

#4248 Fix: PICMI BTD Diags
  Python/pywarpx/picmi.py
Labels: bug, component: diagnostics, component: Python

#4246 Update Crusher Docs and Scripts
  Docs/source/install/hpc/crusher.rst
  Tools/machines/crusher-olcf/crusher_warpx.profile.example
  Tools/machines/crusher-olcf/install_dependencies.sh
  Tools/machines/crusher-olcf/submit.sh
Labels: backend: hip, machine / system

#4240 Replace static function WarpX::CheckSignals() with direct call to SignalHandling::CheckSignals()
  Source/Evolve/WarpXEvolve.cpp
  Source/WarpX.H
Labels: cleaning

#4249 CMake: Verify WarpX_..._src paths exit
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  cmake/dependencies/openPMD.cmake
  cmake/dependencies/pyAMReX.cmake
  cmake/dependencies/pybind11.cmake
Labels: install

#4250 ChargeDeposition: Remove Global WarpX Variable
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: bug, backend: cuda, bug: affects latest release, backend: hip, component: ABLASTR

#4252 Doc: PM new E4S (Boost, CCache)
  Tools/machines/perlmutter-nersc/perlmutter_cpu_warpx.profile.example
  Tools/machines/perlmutter-nersc/perlmutter_gpu_warpx.profile.example
Labels: bug, component: documentation, install, component: QED, component: third party, machine / system
