Repository BLAST-WarpX/warpx, pull requests merged in 2023-11, with the labels that each got.

#4392 Python 3.12: Refactor out Distutils
  .github/workflows/cuda.yml
  .github/workflows/intel.yml
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
  CMakeLists.txt
  Docs/source/install/cmake.rst
  Docs/source/install/hpc/lawrencium.rst
  Docs/source/install/hpc/lxplus.rst
  Docs/source/install/users.rst
  Docs/source/maintenance/performance_tests.rst
  Tools/machines/adastra-cines/install_dependencies.sh
  Tools/machines/crusher-olcf/install_dependencies.sh
  Tools/machines/frontier-olcf/install_dependencies.sh
  Tools/machines/hpc3-uci/install_gpu_dependencies.sh
  Tools/machines/karolina-it4i/install_cpu_dependencies.sh
  Tools/machines/karolina-it4i/install_gpu_dependencies.sh
  Tools/machines/lassen-llnl/install_v100_dependencies.sh
  Tools/machines/lassen-llnl/install_v100_dependencies_toss3.sh
  Tools/machines/lassen-llnl/install_v100_ml.sh
  Tools/machines/leonardo-cineca/install_gpu_dependencies.sh
  Tools/machines/lumi-csc/install_dependencies.sh
  Tools/machines/perlmutter-nersc/install_cpu_dependencies.sh
  Tools/machines/perlmutter-nersc/install_gpu_dependencies.sh
  Tools/machines/quartz-llnl/install_dependencies.sh
  Tools/machines/summit-olcf/install_gpu_dependencies.sh
  pyproject.toml
  run_test.sh
  setup.py
Labels: install, component: Python

#4372 Properly flush metadata of incomplete BTD, at the end of simulation
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/BoundaryScrapingDiagnostics.H
  Source/Diagnostics/BoundaryScrapingDiagnostics.cpp
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.H
  Source/Diagnostics/FullDiagnostics.cpp
Labels: bug, bug: affects latest release, component: diagnostics, component: boosted frame

#4138 Remove call to WarpX::GetInstance from InitializeMacroMultiFabUsingParser
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.H
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.cpp
Labels: cleaning

#3939 Remove Cori from documentation
  Docs/source/dataanalysis/formats.rst
  Docs/source/install/hpc.rst
  Docs/source/install/hpc/cori.rst
  Docs/source/install/hpc/perlmutter.rst
Labels: component: documentation, machine / system

#4397 Allow negative mean velocity with NFluxPerCell
  Examples/Tests/flux_injection/analysis_flux_injection_3d.py
  Examples/Tests/flux_injection/inputs_3d
  Regression/Checksum/benchmarks_json/FluxInjection3D.json
  Source/Initialization/InjectorMomentum.H
Labels: component: initialization

#4094 Bug fix: the electric field for ionization in quasi-cylindrical geometry
  Source/Particles/ElementaryProcess/Ionization.H
Labels: bug, bug: affects latest release, geometry: RZ, component: interpolation

#4407 Add Nicks (2023) to science highlights
  Docs/source/highlights.rst
Labels: component: documentation

#4409 In doGatherShapeN, for RZ use temporaries for Er and Etheta
  Source/Particles/Gather/FieldGather.H
Labels: bug, bug: affects latest release, geometry: RZ

#4417 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
Labels: component: third party

#4427 CI: Unbreak macOS
  .github/workflows/macos.yml
Labels: bug, component: tests, component: third party, component: Python

#4423 Off schedule update of AMReX
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: backend: dpc++

#4422 Remove legacy references to EvolveEM which had been renamed Evolve
  Docs/source/developers/fields.rst
  Docs/source/developers/repo_organization.rst
  Docs/source/glossary.rst
  Source/WarpX.H
  Tools/PerformanceTests/functions_perftest.py
  Tools/PerformanceTests/performance_log.txt
  Tools/PerformanceTests/run_alltests.py
  Tools/PerformanceTests/run_alltests_1node.py
Labels: cleaning

#4414 Doc: Laser Pulse Manip. for LPI
  Docs/source/glossary.rst
Labels: component: documentation

#4421 Fix unused variables with OpenPMD=OFF
  Source/Initialization/PlasmaInjector.cpp
Labels: cleaning

#4431 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#4428 Add paper using WarpX for laser-driven fusion on liquid targets
  Docs/source/highlights.rst
Labels: component: documentation

#4406 Add python binding to `WarpXParticleContainer::sumParticleCharge`
  Python/pywarpx/particle_containers.py
  Source/Python/Particles/WarpXParticleContainer.cpp
Labels: component: Python

#4299 Refinement patch parser
  Docs/source/usage/parameters.rst
  Source/Utils/WarpXTagging.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: enhancement, component: mesh refinement

#4404 Make the static variable "authors" of the WarpX class a private member of the WarpX class
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#4400 Add gaussian_parse_momentum_function
  Docs/source/usage/parameters.rst
  Examples/Tests/initial_distribution/analysis_distribution.py
  Examples/Tests/initial_distribution/inputs
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/initial_distribution.json
  Source/Fluids/WarpXFluidContainer.H
  Source/Fluids/WarpXFluidContainer.cpp
  Source/Initialization/InjectorMomentum.H
  Source/Initialization/InjectorMomentum.cpp
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Utils/SpeciesUtils.H
  Source/Utils/SpeciesUtils.cpp
Labels: enhancement, component: initialization

#4440 Make whitespace alignment more consistent
  Examples/Tests/laser_injection_from_file/analysis_2d_binary.py
  Source/AcceleratorLattice/LatticeElements/HardEdged_K.H
  Source/BoundaryConditions/WarpX_PML_kernels.H
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/BoundaryScrapingDiagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/SliceDiagnostic.H
  Source/Diagnostics/SliceDiagnostic.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/FieldSolver/FiniteDifferenceSolver/ComputeDivE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveB.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveBPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveEPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveF.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveFPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICSolveE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicEvolveE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmComoving.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmGalileanRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralKSpace.cpp
  Source/FieldSolver/WarpX_QED_K.H
  Source/Fluids/WarpXFluidContainer.H
  Source/Fluids/WarpXFluidContainer.cpp
  Source/Initialization/InjectorMomentum.H
  Source/Initialization/WarpXInitData.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileFromFile.cpp
  Source/Make.WarpX
  Source/Parallelization/GuardCellManager.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/Particles/Collision/BinaryCollision/ParticleCreationFunc.H
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineWrapper.cpp
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineWrapper.cpp
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/ParticleCreation/SmartCreate.H
  Source/Particles/WarpXParticleContainer.H
  Source/Utils/Parser/ParserUtils.cpp
  Source/Utils/WarpXAlgorithmSelection.H
  Source/Utils/WarpXMovingWindow.cpp
  Source/Utils/check_interp_points_and_weights.py
  Source/WarpX.cpp
  Source/ablastr/coarsen/sample.cpp
  Source/ablastr/utils/SignalHandling.H
  Tools/PerformanceTests/functions_perftest.py
Labels: cleaning

#4442 Minor bug fix in picmi `ParticleDiagnostic`
  Python/pywarpx/picmi.py
Labels: bug, component: PICMI

#4339 Set the particle fields directly to the constant external fields
  Source/Diagnostics/ReducedDiags/ColliderRelevant.cpp
  Source/Diagnostics/ReducedDiags/ParticleExtrema.cpp
  Source/Particles/ElementaryProcess/Ionization.H
  Source/Particles/ElementaryProcess/Ionization.cpp
  Source/Particles/ElementaryProcess/QEDPairGeneration.H
  Source/Particles/ElementaryProcess/QEDPairGeneration.cpp
  Source/Particles/ElementaryProcess/QEDPhotonEmission.H
  Source/Particles/ElementaryProcess/QEDPhotonEmission.cpp
  Source/Particles/Gather/GetExternalFields.H
  Source/Particles/Gather/GetExternalFields.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: Performance optimization, changes input scripts / defaults

#4005 Move AnyFFT.H and FFT wrappers into ablastr
  CMakeLists.txt
  Source/FieldSolver/SpectralSolver/CMakeLists.txt
  Source/FieldSolver/SpectralSolver/Make.package
  Source/FieldSolver/SpectralSolver/SpectralFieldData.H
  Source/FieldSolver/SpectralSolver/SpectralFieldData.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.H
  Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.cpp
  Source/Make.WarpX
  Source/Utils/CMakeLists.txt
  Source/Utils/Make.package
  Source/Utils/WarpX_Complex.H
  Source/Utils/WarpXrocfftUtil.H
  Source/Utils/WarpXrocfftUtil.cpp
  Source/ablastr/CMakeLists.txt
  Source/ablastr/Make.package
  Source/ablastr/math/CMakeLists.txt
  Source/ablastr/math/Make.package
  Source/ablastr/math/fft/AnyFFT.H
  Source/ablastr/math/fft/CMakeLists.txt
  Source/ablastr/math/fft/Make.package
  Source/ablastr/math/fft/WrapCuFFT.cpp
  Source/ablastr/math/fft/WrapFFTW.cpp
  Source/ablastr/math/fft/WrapNoFFT.cpp
  Source/ablastr/math/fft/WrapRocFFT.cpp
  Source/main.cpp
  cmake/dependencies/FFT.cmake
Labels: component: spectral, cleaning, component: ABLASTR

#4450 CI: numprocs * numthreads <= 2
  Regression/WarpX-tests.ini
Labels: bug, component: tests, component: QED

#4449 Doc: Fix Typo `<probe>.integrate = true`
  Docs/source/usage/parameters.rst
Labels: component: documentation, component: diagnostics

#4326 Maxlevel user option for external field initialization
  Docs/source/usage/parameters.rst
  Docs/source/usage/python.rst
  Python/pywarpx/picmi.py
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: PICMI, component: mesh refinement, component: initialization

#4451 CPU CI: Always Serialize
  Regression/WarpX-tests.ini
  Regression/prepare_file_ci.py
Labels: component: tests

#4452 Contributing style and conventions additions
  CONTRIBUTING.rst
  Docs/source/developers/documentation.rst
Labels: component: documentation

#4437 add start/end moving step
  Python/pywarpx/picmi.py
Labels: component: Python

#4247 Frontier (OLCF): cupy
  Tools/machines/frontier-olcf/install_dependencies.sh
Labels: component: documentation, backend: hip, machine / system, component: Python

#4196 Allow multiple injection sources per species
  Docs/source/usage/parameters.rst
  Examples/Tests/nuclear_fusion/inputs_deuterium_tritium_3d
  Examples/Tests/plasma_lens/PICMI_inputs_3d.py
  Examples/Tests/plasma_lens/analysis.py
  Python/pywarpx/Bucket.py
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/Deuterium_Tritium_Fusion_3D.json
  Source/Fluids/WarpXFluidContainer.cpp
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Initialization/TemperatureProperties.H
  Source/Initialization/TemperatureProperties.cpp
  Source/Initialization/VelocityProperties.H
  Source/Initialization/VelocityProperties.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Utils/Parser/ParserUtils.H
  Source/Utils/Parser/ParserUtils.cpp
  Source/Utils/SpeciesUtils.H
  Source/Utils/SpeciesUtils.cpp
  Source/Utils/WarpXMovingWindow.cpp
Labels: enhancement, component: initialization

#4453 Clang-Tidy Cache
  .github/workflows/clang_tidy.yml
  .github/workflows/source/makeMakefileForClangTidy.py
Labels: Performance optimization, component: tests
