Repository BLAST-WarpX/warpx, pull requests merged in 2023-06, with the labels that each got.

#3956 Fix: PSATD+RZ in SP
  Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.H
  Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.cpp
Labels: bug, component: spectral, bug: affects latest release, geometry: RZ

#3961 revert #3928 calculation of b0 in binary collisions and add comment
  Source/Particles/Collision/BinaryCollision/Coulomb/UpdateMomentumPerezElastic.H
Labels: bug, component: collisions

#3960 Add max_background_density to MCCollision
  Python/pywarpx/picmi.py
Labels: component: PICMI, component: collisions

#3940 Correctly handle `do_pml_dive_cleaning` for RZ PSATD
  Docs/source/usage/parameters.rst
  Source/WarpX.cpp
Labels: bug, component: spectral, bug: affects latest release, geometry: RZ, component: boundary

#3883 Histogram 2D
  Docs/source/dataanalysis/reduced_diags.rst
  Docs/source/usage/parameters.rst
  Examples/Physics_applications/laser_ion/analysis_histogram_2D.py
  Examples/Physics_applications/laser_ion/inputs
  Source/Diagnostics/CMakeLists.txt
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
  Source/Diagnostics/Make.package
  Source/Diagnostics/OpenPMDHelpFunction.H
  Source/Diagnostics/OpenPMDHelpFunction.cpp
  Source/Diagnostics/ReducedDiags/CMakeLists.txt
  Source/Diagnostics/ReducedDiags/Make.package
  Source/Diagnostics/ReducedDiags/MultiReducedDiags.cpp
  Source/Diagnostics/ReducedDiags/ParticleHistogram2D.H
  Source/Diagnostics/ReducedDiags/ParticleHistogram2D.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: component: diagnostics

#3955 Add CI test in single precision
  .github/workflows/dependencies/gcc12_blaspp_lapackpp.sh
  .github/workflows/ubuntu.yml
Labels: component: tests

#3964 Fix wrong executable and missing Werror flag in CI test
  .github/workflows/ubuntu.yml
Labels: bug, component: tests, bug: affects latest release

#3962 Release 23.06
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#3698 Add waterbag generation in injector
  Docs/source/usage/parameters.rst
  Examples/Tests/initial_distribution/analysis_distribution.py
  Examples/Tests/initial_distribution/inputs
  Regression/Checksum/benchmarks_json/initial_distribution.json
  Source/Initialization/InjectorMomentum.H
  Source/Initialization/InjectorMomentum.cpp
  Source/Initialization/PlasmaInjector.cpp
Labels: component: core

#3969 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3917 Use clang-tidy in CI
  .clang-tidy
  .github/workflows/clang_tidy.yml
  .github/workflows/dependencies/clang14.sh
Labels: help wanted, component: tests

#3972 Docs: Make sbatch command consistent with the example file (Perlmutter)
  Docs/source/install/hpc/perlmutter.rst
Labels: component: documentation, machine / system

#3974 `geometry.is_periodic`: Only Warn
  Source/Utils/WarpXUtil.cpp
Labels: bug, changes input scripts / defaults, bug: affects latest release

#3777 Fix SyncCurrent and SyncRho for multi-levels
  Regression/Checksum/benchmarks_json/Langmuir_multi_2d_MR_psatd.json
  Source/Parallelization/WarpXComm.cpp
Labels: bug, component: mesh refinement, bug: affects latest release

#3981 precommit: make sure isort output is compatible with black
  .editorconfig
  Examples/Tests/laser_injection_from_file/analysis_from_RZ_file.py
  Tools/LibEnsemble/run_libensemble_on_warpx.py
  Tools/PerformanceTests/run_automated.py
Labels: component: tests

#3965 Replace amrex::Abort with WARPX_ABORT_WITH_MESSAGE
  Examples/Tests/nci_psatd_stability/analysis_galilean.py
  Source/BoundaryConditions/WarpX_PML_kernels.H
  Source/Diagnostics/BoundaryScrapingDiagnostics.cpp
  Source/Diagnostics/ReducedDiags/ParticleHistogram2D.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/EmbeddedBoundary/DistanceToEB.H
  Source/FieldSolver/FiniteDifferenceSolver/EvolveB.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveECTRho.cpp
  Source/Initialization/InjectorMomentum.H
  Source/Parallelization/WarpXComm.cpp
  Source/Parallelization/WarpXRegrid.cpp
  Source/Particles/Collision/BackgroundMCC/MCCProcess.cpp
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
  Source/Particles/Collision/BinaryCollision/BinaryCollisionUtils.cpp
  Source/Particles/Collision/BinaryCollision/NuclearFusion/NuclearFusionFunc.H
  Source/Particles/Collision/BinaryCollision/ParticleCreationFunc.cpp
  Source/Particles/Collision/CollisionHandler.cpp
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineWrapper.cpp
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineWrapper.cpp
  Source/Particles/ElementaryProcess/QEDSchwingerProcess.H
  Source/Particles/LaserParticleContainer.cpp
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Resampling/Resampling.cpp
  Source/Particles/ShapeFactors.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/Utils/Interpolate.cpp
  Source/Utils/WarpXAlgorithmSelection.cpp
  Source/ablastr/particles/NodalFieldGather.H
Labels: cleaning

#3665 Ohm's law solver (hybrid kinetic-fluid extension)
  Docs/source/index.rst
  Docs/source/refs.bib
  Docs/source/theory/kinetic_fluid_hybrid_model.rst
  Docs/source/theory/picsar_theory.rst
  Docs/source/usage/examples.rst
  Docs/source/usage/parameters.rst
  Examples/Tests/ohm_solver_EM_modes/PICMI_inputs.py
  Examples/Tests/ohm_solver_EM_modes/analysis.py
  Examples/Tests/ohm_solver_ion_Landau_damping/PICMI_inputs.py
  Examples/Tests/ohm_solver_ion_Landau_damping/analysis.py
  Examples/Tests/ohm_solver_ion_beam_instability/PICMI_inputs.py
  Examples/Tests/ohm_solver_ion_beam_instability/analysis.py
  Examples/Tests/ohm_solver_magnetic_reconnection/PICMI_inputs.py
  Examples/Tests/ohm_solver_magnetic_reconnection/analysis.py
  Python/pywarpx/HybridPICModel.py
  Python/pywarpx/WarpX.py
  Python/pywarpx/__init__.py
  Python/pywarpx/_libwarpx.py
  Python/pywarpx/fields.py
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/Python_ohms_law_solver_EM_modes_1d.json
  Regression/Checksum/benchmarks_json/Python_ohms_law_solver_ion_beam_1d.json
  Regression/Checksum/benchmarks_json/Python_ohms_law_solver_landau_damping_2d.json
  Regression/Checksum/benchmarks_json/Python_ohms_law_solver_magnetic_reconnection_2d.json
  Regression/WarpX-tests.ini
  Regression/requirements.txt
  Source/BoundaryConditions/WarpXFieldBoundaries.cpp
  Source/BoundaryConditions/WarpX_PEC.H
  Source/BoundaryConditions/WarpX_PEC.cpp
  Source/Evolve/WarpXComputeDt.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/CMakeLists.txt
  Source/FieldSolver/FiniteDifferenceSolver/CMakeLists.txt
  Source/FieldSolver/FiniteDifferenceSolver/EvolveB.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.cpp
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/CMakeLists.txt
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel_fwd.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/Make.package
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICSolveE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/Make.package
  Source/FieldSolver/Make.package
  Source/FieldSolver/WarpXPushFieldsHybridPIC.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/GuardCellManager.cpp
  Source/Python/WarpXWrappers.H
  Source/Python/WarpXWrappers.cpp
  Source/Utils/WarpXAlgorithmSelection.H
  Source/Utils/WarpXAlgorithmSelection.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: enhancement, component: core

#3971 Cleanup unused parts of WarpX Python interface
  Python/pywarpx/Langmuirwave.py
  Python/pywarpx/Particles.py
  Python/pywarpx/WarpX.py
  Python/pywarpx/__init__.py
Labels: cleaning, component: Python

#3977 Docs: TAE
  Docs/source/acknowledge_us.rst
Labels: component: documentation

#2355 Add python script to update benchmarks from Azure output
  Docs/source/developers/checksum.rst
  Tools/DevUtils/update_benchmarks_from_azure_output.py
Labels: component: tests

#3984 Add Frontier Checkpointing and IO Warning
  Docs/source/install/hpc/frontier.rst
Labels: component: documentation, machine / system, component: checkpoint/restart

#3983 Docs: Debian/Ubuntu no-MPI
  Docs/source/install/dependencies.rst
  Docs/source/install/hpc/fugaku.rst
  Docs/source/install/users.rst
Labels: component: documentation

#3990 Docs: Update OpenMP for macOS Pkg Mgs
  Docs/source/install/dependencies.rst
Labels: component: documentation, install, backend: openmp, machine / system

#3987 Fix: 1D Abort in Kernels
  Source/BoundaryConditions/WarpX_PML_kernels.H
  Source/Particles/ElementaryProcess/QEDSchwingerProcess.H
Labels: bug, backend: cuda, backend: hip, backend: dpc++

#3986 Doc: Frontier (OLCF) hipcc
  Docs/source/install/hpc/frontier.rst
  Docs/source/install/hpc/lumi.rst
  Tools/machines/frontier-olcf/frontier_warpx.profile.example
  Tools/machines/frontier-olcf/install_dependencies.sh
Labels: component: spectral, component: documentation, machine / system, geometry: RZ, component: Python

#3988 Fix: Unused Cost GPUClock
  Source/Particles/Deposition/CurrentDeposition.H
Labels: warning, backend: hip, component: load balancing

#3993 Add Twiss alpha to BeamRelevant and Docs
  Docs/source/usage/parameters.rst
  Source/Diagnostics/ReducedDiags/BeamRelevant.cpp
Labels: component: diagnostics

#3995 Generalize buffers for `SyncRho`, `SyncCurrent`, and related functions
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/FieldSolver/MagnetostaticSolver/MagnetostaticSolver.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/Python/WarpXWrappers.H
  Source/Python/WarpXWrappers.cpp
  Source/WarpX.H
Labels: enhancement, component: mesh refinement, component: parallelization

#3997 Doc: Summit (OLCF) Quick Install + Torch
  Docs/source/install/hpc/summit.rst
  Tools/machines/summit-olcf/install_gpu_dependencies.sh
  Tools/machines/summit-olcf/install_gpu_ml.sh
  Tools/machines/summit-olcf/summit_warpx.profile.example
Labels: backend: cuda, component: documentation, machine / system, component: Python

#3985 Doc: Perlmutter (NERSC) Install Helpers
  Docs/source/install/hpc/frontier.rst
  Docs/source/install/hpc/perlmutter.rst
  Tools/machines/frontier-olcf/frontier_warpx.profile.example
  Tools/machines/frontier-olcf/install_dependencies.sh
  Tools/machines/perlmutter-nersc/install_cpu_dependencies.sh
  Tools/machines/perlmutter-nersc/install_gpu_dependencies.sh
  Tools/machines/perlmutter-nersc/perlmutter_cpu_warpx.profile.example
  Tools/machines/perlmutter-nersc/perlmutter_gpu_warpx.profile.example
Labels: component: documentation, machine / system

#3998 Correct typo: seperate --> separate
  Examples/Physics_applications/plasma_acceleration/PICMI_inputs_plasma_acceleration_mr.py
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/HankelTransform.H
Labels: cleaning

#3999 Clang-tidy CI test: add readability-non-const-parameter check
  .clang-tidy
Labels: component: tests, cleaning

#4000 Clang-tidy CI test: add performance-for-range-copy check [🚀🚀 PR #4000 🚀🚀]
  .clang-tidy
Labels: component: tests, cleaning

#4002 Docs: Install Dep Scripts Build Dirs
  Docs/source/install/hpc/summit.rst
  Tools/machines/frontier-olcf/install_dependencies.sh
  Tools/machines/perlmutter-nersc/install_cpu_dependencies.sh
  Tools/machines/perlmutter-nersc/install_gpu_dependencies.sh
  Tools/machines/summit-olcf/install_gpu_dependencies.sh
  Tools/machines/summit-olcf/install_gpu_ml.sh
Labels: component: documentation, install, component: third party, machine / system

#4003 Clang-tidy CI test: add performance-faster-string-find check
  .clang-tidy
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: component: tests, cleaning

#4004 Doc: Button to Copy Code Blocks
  Docs/requirements.txt
  Docs/source/conf.py
  Docs/spack.yaml
Labels: component: documentation

#4010 Doc: HPC3 at UCI
  Docs/source/install/hpc.rst
  Docs/source/install/hpc/hpc3.rst
  Tools/machines/hpc3-uci/hpc3_gpu.sbatch
  Tools/machines/hpc3-uci/hpc3_gpu_warpx.profile.example
  Tools/machines/hpc3-uci/install_gpu_dependencies.sh
Labels: backend: cuda, component: documentation, install, machine / system

#4011 Doc: Batch System Cheat Sheets
  Docs/source/install/batch/lsf.rst
  Docs/source/install/batch/pbs.rst
  Docs/source/install/batch/pjm.rst
  Docs/source/install/batch/slurm.rst
  Docs/source/install/hpc.rst
Labels: component: documentation, machine / system

#4008 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3978 Add documentation describing handling of PICMI input
  Docs/source/developers/python.rst
Labels: component: documentation, component: PICMI, component: Python

#4013 Doc: HPC QED & Multi-Dim
  Docs/source/install/batch/pbs.rst
  Docs/source/install/hpc.rst
  Docs/source/install/hpc/adastra.rst
  Docs/source/install/hpc/crusher.rst
  Docs/source/install/hpc/frontier.rst
  Docs/source/install/hpc/fugaku.rst
  Docs/source/install/hpc/hpc3.rst
  Docs/source/install/hpc/juwels.rst
  Docs/source/install/hpc/lassen.rst
  Docs/source/install/hpc/lawrencium.rst
  Docs/source/install/hpc/lumi.rst
  Docs/source/install/hpc/lxplus.rst
  Docs/source/install/hpc/ookami.rst
  Docs/source/install/hpc/perlmutter.rst
  Docs/source/install/hpc/quartz.rst
  Docs/source/install/hpc/spock.rst
  Docs/source/install/hpc/summit.rst
  Docs/source/install/hpc/taurus.rst
Labels: component: documentation, install, component: QED, machine / system

#4015 Fixes to remove compilation warnings
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
  Source/Diagnostics/ReducedDiags/ParticleHistogram2D.cpp
Labels: cleaning, warning

#4022 For ReducedDiags, write header on restart if file does not exist
  Source/Diagnostics/ReducedDiags/BeamRelevant.cpp
  Source/Diagnostics/ReducedDiags/ChargeOnEB.cpp
  Source/Diagnostics/ReducedDiags/FieldEnergy.cpp
  Source/Diagnostics/ReducedDiags/FieldMaximum.cpp
  Source/Diagnostics/ReducedDiags/FieldMomentum.cpp
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
  Source/Diagnostics/ReducedDiags/FieldReduction.cpp
  Source/Diagnostics/ReducedDiags/LoadBalanceEfficiency.cpp
  Source/Diagnostics/ReducedDiags/ParticleEnergy.cpp
  Source/Diagnostics/ReducedDiags/ParticleExtrema.cpp
  Source/Diagnostics/ReducedDiags/ParticleHistogram.cpp
  Source/Diagnostics/ReducedDiags/ParticleMomentum.cpp
  Source/Diagnostics/ReducedDiags/ParticleNumber.cpp
  Source/Diagnostics/ReducedDiags/ReducedDiags.H
  Source/Diagnostics/ReducedDiags/ReducedDiags.cpp
  Source/Diagnostics/ReducedDiags/RhoMaximum.cpp
Labels: component: diagnostics

#4026 Move MPIInitHelpers into ablastr
  Source/Initialization/WarpXInitData.cpp
  Source/Utils/CMakeLists.txt
  Source/Utils/Make.package
  Source/ablastr/CMakeLists.txt
  Source/ablastr/parallelization/CMakeLists.txt
  Source/ablastr/parallelization/MPIInitHelpers.H
  Source/ablastr/parallelization/MPIInitHelpers.cpp
  Source/ablastr/parallelization/Make.package
  Source/main.cpp
Labels: cleaning, component: parallelization, component: ABLASTR

#4025 Clang-tidy CI test: add modernize-avoid-bind check
  .clang-tidy
Labels: component: tests, cleaning

#4017 Doc: IPAC23 Paper
  Docs/source/acknowledge_us.rst
  Docs/source/highlights.rst
Labels: component: documentation

#4028 Clean up GpuArray init in ABLASTR interp modules
  Source/ablastr/coarsen/average.cpp
  Source/ablastr/coarsen/sample.cpp
Labels: cleaning, component: interpolation

#4027 Doc: IPAC22 Tan et al. Dielectric
  Docs/source/highlights.rst
Labels: component: documentation

#4021 Doc: HPC3 (UCI) HDF5 & GPU Visibility
  Tools/machines/hpc3-uci/hpc3_gpu.sbatch
  Tools/machines/hpc3-uci/hpc3_gpu_warpx.profile.example
Labels: component: documentation, machine / system

#4029 Doc: HPC Machines Source Py Env
  Docs/source/install/hpc/frontier.rst
  Docs/source/install/hpc/hpc3.rst
  Docs/source/install/hpc/perlmutter.rst
  Docs/source/install/hpc/summit.rst
Labels: bug, component: documentation, install, component: Python

#4020 Prevent `E_ext_particle` and `B_ext_particle` use with hybrid-PIC solver
  Source/Initialization/WarpXInitData.cpp
Labels: component: hybrid-pic

#4033 Change default current deposition algorithm to `direct` with hybrid-PIC solver
  Docs/source/usage/parameters.rst
  Source/Utils/WarpXAlgorithmSelection.cpp
Labels: changes input scripts / defaults, component: hybrid-pic

#4034 Explicitly check field `IndexType` appropriateness when using hybrid-PIC solver
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICSolveE.cpp
Labels: component: hybrid-pic

#4023 Doc: Summit Scipy Install
  Tools/machines/summit-olcf/install_gpu_dependencies.sh
Labels: component: documentation, machine / system

#4044 Code clean-up: refactored `HybridPICModel::HybridPICSolveE` to more readable
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICSolveE.cpp
  Source/FieldSolver/WarpXPushFieldsHybridPIC.cpp
Labels: cleaning, component: hybrid-pic

#4030 Clang-tidy CI test: add bugprone-branch-clone check
  .clang-tidy
  Source/BoundaryConditions/PML.cpp
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/EmbeddedBoundary/WarpXFaceExtensions.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveB.cpp
  Source/Particles/Filter/FilterFunctors.H
  Source/WarpX.cpp
Labels: component: tests, cleaning, component: diagnostics

#3980 Adding current density to Field Reduction reduced diagnostic
  Docs/source/usage/parameters.rst
  Examples/Tests/reduced_diags/analysis_reduced_diags_impl.py
  Examples/Tests/reduced_diags/inputs
  Python/pywarpx/picmi.py
  Source/Diagnostics/ReducedDiags/FieldReduction.H
  Source/Diagnostics/ReducedDiags/FieldReduction.cpp
Labels: changes input scripts / defaults, component: diagnostics

#4045 Doc: Summit SciPy -j10
  Tools/machines/summit-olcf/install_gpu_dependencies.sh
Labels: component: documentation, install, machine / system, component: Python

#4056 Doc: Link All Tests in Examples
  Docs/source/usage/examples.rst
Labels: component: documentation, component: tests

#4054 Ablastr: remove dependency of VectorPoissonSolver.H on WarpX
  Source/ablastr/fields/VectorPoissonSolver.H
Labels: cleaning, component: ABLASTR

#4053 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#4039 Replace unsed WARPX_DIM_2D with AMREX_SPACEDIM==2
  Source/WarpX.cpp
Labels: bug, bug: affects latest release, geometry: 1D/2D

#4014 Clean up of MultiFab tagging
  Source/BoundaryConditions/PML.cpp
  Source/BoundaryConditions/PML_RZ.cpp
  Source/Diagnostics/BTDiagnostics.cpp
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/Parallelization/WarpXRegrid.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning, component: mesh refinement

#4058 mini-PR: fix typo in docs
  Docs/source/theory/kinetic_fluid_hybrid_model.rst
Labels: component: documentation

#4036 Allocate fewer `rho` components for ES, MS, hybrid-PIC solvers
  Examples/Physics_applications/capacitive_discharge/PICMI_inputs_1d.py
  Examples/Physics_applications/capacitive_discharge/PICMI_inputs_2d.py
  Source/WarpX.cpp
Labels: component: electrostatic, component: fluid-ohm

#4061 Doc: Update openPMD tutorials link
  Docs/source/dataanalysis/openpmdviewer.rst
Labels: component: documentation

#3949 Use GPU compatible kernel in `sumParticleCharge`
  Source/Particles/WarpXParticleContainer.cpp
Labels: backend: cuda, backend: hip, backend: dpc++, component: Python

#3958 Continuous injection of moving plasma
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/WarpXIO.cpp
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: core, component: boosted frame

#4057 Allow `FieldProbe` in RZ geometry
  Docs/source/usage/parameters.rst
  Source/Diagnostics/ReducedDiags/FieldProbe.H
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
  Source/Diagnostics/ReducedDiags/FieldProbeParticleContainer.H
  Source/Diagnostics/ReducedDiags/FieldProbeParticleContainer.cpp
Labels: component: diagnostics, geometry: RZ
