Repository BLAST-WarpX/warpx, pull requests merged in 2023-02, with the labels that each got.

#3661 updates classical radiation reaction entry in docs
  Docs/source/usage/parameters.rst
Labels: component: documentation, component: QED

#3659 Fix NUniformPerCell for 1D
  Examples/Physics_applications/capacitive_discharge/analysis_1d.py
  Regression/Checksum/benchmarks_json/Langmuir_multi_1d.json
  Regression/Checksum/benchmarks_json/LaserAcceleration_1d.json
  Regression/Checksum/benchmarks_json/Python_LaserAcceleration_1d.json
  Source/Particles/PhysicalParticleContainer.cpp
Labels: bug, bug: affects latest release

#3651 Perlmutter (NERSC): New Boost Module
  Tools/machines/perlmutter-nersc/perlmutter_warpx.profile.example
Labels: component: documentation, install, component: QED, machine / system

#3629 Docs: Summit Jupyter HDF5 Back
  Docs/source/install/hpc/summit.rst
Labels: component: documentation, machine / system

#3628 Docs: Spack Binary Caches
  Docs/source/developers/gnumake/spack.rst
  Docs/source/install/dependencies.rst
  Docs/source/install/users.rst
Labels: component: documentation, install, machine / system

#3650 Use a simpler expression for particle energy for reduced diagnostics
  Source/Particles/Algorithms/KineticEnergy.H
Labels: component: diagnostics

#3657 ADIOS2: Fix BTD Particle Resize w/ Empty Ranks
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: bug, component: openPMD, component: third party, bug: affects latest release, component: diagnostics, workaround, component: boosted frame

#3666 Add all the elements from Z=55 (Cs) to Z=85 (At) to the ionization table
  Source/Utils/Physics/IonizationEnergiesTable.H
  Source/Utils/Physics/atomic_data.txt
Labels: enhancement

#3647 Doc: Add ARTEMIS Publications
  Docs/source/highlights.rst
Labels: component: documentation

#3667 Release 23.02
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#3614 Doc: NAPAC22 DOI
  Docs/source/acknowledge_us.rst
Labels: component: documentation

#3601 Docs: Update Crusher (OLCF) Submission
  Tools/machines/crusher-olcf/submit.sh
Labels: component: documentation, backend: hip, machine / system

#3615 RZ: added abort message if warpx.numprocs[0] > 1 is set.
  Source/WarpX.cpp
Labels: bug, bug: affects latest release, component: RZ

#3671 Fix some issues in WarpX 1D in WarpXInitData, MacroscopicProperites, and FieldReduction
  Source/Diagnostics/ReducedDiags/FieldReduction.H
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.cpp
  Source/Initialization/WarpXInitData.cpp
Labels: bug, bug: affects latest release, component: core, component: diagnostics

#3669 Fix a bug in 1D PEC
  Regression/Checksum/benchmarks_json/LaserAcceleration_1d.json
  Regression/Checksum/benchmarks_json/LaserInjection_1d.json
  Source/BoundaryConditions/WarpX_PEC.H
Labels: bug, bug: affects latest release, component: boundary

#3670 Add all the elements from Z=87 (Fr) to Z=100 (Fm) to the ionization table
  Docs/source/usage/parameters.rst
  Source/Utils/Physics/IonizationEnergiesTable.H
  Source/Utils/Physics/atomic_data.txt
Labels: enhancement

#3656 Clean compilation warning on unused function
  Source/Particles/PhysicalParticleContainer.cpp
Labels: backend: cuda, warning

#3674 Bug fix : Coarse patch dx for external field init
  Regression/Checksum/benchmarks_json/PEC_field_mr.json
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
Labels: bug, component: mesh refinement, bug: affects latest release

#3677 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3678 Pre-Commit: Smaller Files & NB
  .pre-commit-config.yaml
  Tools/DevUtils/compare_wx_w_3d.ipynb
Labels: component: tests

#3681 Fix bug in mirror with F,G fields
  Source/Evolve/WarpXEvolve.cpp
Labels: bug, bug: affects latest release

#3680 CI & Bug Fixes: 1D & 2D Compile
  .github/workflows/dependencies/gcc12.sh
  .github/workflows/ubuntu.yml
  Source/Initialization/WarpXInitData.cpp
  Source/Particles/ParticleCreation/FilterCreateTransformFromFAB.H
Labels: bug, component: tests, bug: affects latest release, component: core

#3685 Updated gitignore with vscode-specific folder
  .gitignore
Labels: cleaning

#3682 Pass seed for gpu in ResetRandomSeed
  Source/WarpX.cpp
Labels: bug, backend: cuda, bug: affects latest release, backend: hip, backend: dpc++, component: core

#3688 Update Crusher Modules to cce/15.0.0 and others accordingly
  Docs/source/install/hpc/crusher.rst
  Tools/machines/crusher-olcf/crusher_warpx.profile.example
Labels: component: documentation, backend: hip, machine / system

#3699 Add `write_species` flag to picmi `FieldDiagnostic`
  Python/pywarpx/picmi.py
Labels: component: PICMI, component: diagnostics

#3697 Add FieldReduction and ParticleHistogram to PICMI
  Examples/Tests/reduced_diags/PICMI_inputs_loadbalancecosts.py
  Python/pywarpx/WarpX.py
  Python/pywarpx/picmi.py
Labels: component: PICMI, component: diagnostics

#3696 GetExternalEBField: Use AMReX's CompileTimeOption ParallelFor
  Source/Diagnostics/ReducedDiags/ParticleExtrema.cpp
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.cpp
Labels: backend: cuda, Performance optimization, backend: hip, backend: dpc++

#3655 Add warning message in RZ for < 2 azimuthal modes
  Source/WarpX.cpp
Labels: changes input scripts / defaults, component: RZ

#3675 Doc: HPC build/bin
  Docs/source/install/hpc/cori.rst
  Docs/source/install/hpc/crusher.rst
  Docs/source/install/hpc/frontier.rst
  Docs/source/install/hpc/juwels.rst
  Docs/source/install/hpc/lassen.rst
  Docs/source/install/hpc/lumi.rst
  Docs/source/install/hpc/lxplus.rst
  Docs/source/install/hpc/ookami.rst
  Docs/source/install/hpc/perlmutter.rst
  Docs/source/install/hpc/quartz.rst
  Docs/source/install/hpc/spock.rst
Labels: component: documentation, machine / system

#3703 Fix Silver-Mueller boundary condition in 1D
  Examples/Tests/silver_mueller/inputs_1d
  Regression/Checksum/benchmarks_json/silver_mueller_1d.json
  Regression/WarpX-tests.ini
  Source/FieldSolver/FiniteDifferenceSolver/ApplySilverMuellerBoundary.cpp
Labels: bug, bug: affects latest release, component: boundary

#3706 Doc: Perlmutter 80 GB GPUs
  Docs/source/install/hpc/perlmutter.rst
  Tools/machines/perlmutter-nersc/perlmutter.sbatch
Labels: duplicate, backend: cuda, component: documentation, machine / system

#3693 add option to increase max_step to fill BTD
  Docs/source/usage/parameters.rst
  Examples/Tests/btd_rz/inputs_rz_z_boosted_BTD
  Source/Diagnostics/BTDiagnostics.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: enhancement, changes input scripts / defaults, component: boosted frame

#3705 Fix getBulkMomentum for Maxwellian distributions
  Source/Initialization/InjectorMomentum.H
Labels: bug, bug: affects latest release, component: core

#3700 Doc: Lawrencium (LBNL) Machine
  Docs/source/install/hpc/lawrencium.rst
  Tools/machines/lawrencium-lbnl/lawrencium_v100.sbatch
  Tools/machines/lawrencium-lbnl/lawrencium_warpx.profile.example
Labels: backend: cuda, component: documentation, machine / system

#3648 Reduced diagnostics: charge on the embedded boundary
  Docs/source/usage/parameters.rst
  Examples/Tests/electrostatic_sphere_eb/PICMI_inputs_3d.py
  Examples/Tests/electrostatic_sphere_eb/analysis.py
  Examples/Tests/electrostatic_sphere_eb/inputs_3d
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/ElectrostaticSphereEB.json
  Regression/Checksum/benchmarks_json/Python_ElectrostaticSphereEB.json
  Regression/WarpX-tests.ini
  Source/Diagnostics/ReducedDiags/CMakeLists.txt
  Source/Diagnostics/ReducedDiags/ChargeOnEB.H
  Source/Diagnostics/ReducedDiags/ChargeOnEB.cpp
  Source/Diagnostics/ReducedDiags/Make.package
  Source/Diagnostics/ReducedDiags/MultiReducedDiags.cpp
  Source/WarpX.H
Labels: component: diagnostics

#3663 change plotfile RZ allowed diag to r,t from x,y
  .zenodo.json
  Docs/source/usage/parameters.rst
  Examples/Physics_applications/laser_acceleration/inputs_rz
  Examples/Tests/electrostatic_sphere/analysis_electrostatic_sphere.py
  Examples/Tests/electrostatic_sphere/inputs_rz
  Examples/Tests/electrostatic_sphere_eb/analysis_rz.py
  Examples/Tests/electrostatic_sphere_eb/inputs_rz
  Examples/Tests/electrostatic_sphere_eb/inputs_rz_mr
  Examples/Tests/langmuir/PICMI_inputs_langmuir_rz_multimode_analyze.py
  Examples/Tests/langmuir/analysis_langmuir_multi_rz.py
  Examples/Tests/langmuir/inputs_2d_multi_rz_rt
  Examples/Tests/magnetostatic_eb/PICMI_inputs_rz.py
  Examples/Tests/multi_j/inputs_rz
  Examples/Tests/nci_psatd_stability/analysis_galilean.py
  Examples/Tests/nci_psatd_stability/inputs_rz
  Examples/Tests/pml/analysis_pml_psatd_rz.py
  Examples/Tests/pml/inputs_rz
  Examples/Tests/scraping/inputs_rz
  Examples/Tests/silver_mueller/analysis_silver_mueller.py
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/ElectrostaticSphereEB_RZ.json
  Regression/Checksum/benchmarks_json/ElectrostaticSphereEB_RZ_MR.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_rz.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_rz_psatd.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_rz_psatd_current_correction.json
  Regression/Checksum/benchmarks_json/LaserAccelerationRZ.json
  Regression/Checksum/benchmarks_json/Python_Langmuir_rz_multimode.json
  Regression/Checksum/benchmarks_json/Python_LaserAccelerationRZ.json
  Regression/Checksum/benchmarks_json/Python_magnetostatic_eb_rz.json
  Regression/Checksum/benchmarks_json/collisionRZ.json
  Regression/Checksum/benchmarks_json/galilean_rz_psatd.json
  Regression/Checksum/benchmarks_json/galilean_rz_psatd_current_correction.json
  Regression/Checksum/benchmarks_json/galilean_rz_psatd_current_correction_psb.json
  Regression/Checksum/benchmarks_json/multi_J_rz_psatd.json
  Regression/Checksum/benchmarks_json/pml_psatd_rz.json
  Regression/Checksum/benchmarks_json/scraping.json
  Regression/Checksum/benchmarks_json/silver_mueller_rz_z.json
  Regression/WarpX-tests.ini
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.cpp
Labels: component: diagnostics, component: RZ

#3715 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party
