Repository BLAST-WarpX/warpx, pull requests merged in 2023-07, with the labels that each got.

#4012 Docs: Karolina (IT4I)
  Docs/source/install/hpc.rst
  Docs/source/install/hpc/karolina.rst
  Tools/machines/karolina-it4i/install_cpu_dependencies.sh
  Tools/machines/karolina-it4i/install_gpu_dependencies.sh
  Tools/machines/karolina-it4i/karolina_cpu_warpx.profile.example
  Tools/machines/karolina-it4i/karolina_gpu.qsub
  Tools/machines/karolina-it4i/karolina_gpu_warpx.profile.example
Labels: component: documentation, machine / system

#4072 Fix clang-tidy `bugprone-branch-clone` warning
  Source/Utils/WarpXMovingWindow.cpp
Labels: bug, component: tests

#4073 Fix max_grid_size for RZ PSATD
  Source/Utils/WarpXUtil.cpp
Labels: component: spectral, bug: affects latest release, geometry: RZ

#4067 update github actions ci test to use ascent 0.9.2
  .github/workflows/insitu.yml
Labels: component: tests, component: third party

#4060 Clang tidy CI test: exclude bugprone_easily_swappable_parameters check
  .clang-tidy
Labels: component: tests

#4055 main.cpp: change warpx_amrex_init into warpx::initialization::amrex_init
  Source/Initialization/WarpXAMReXInit.H
  Source/Initialization/WarpXAMReXInit.cpp
  Source/Python/WarpXWrappers.cpp
  Source/main.cpp
Labels: cleaning

#4046 Clang-tidy CI test: add few bugprone checks in clang-tidy CI
  .clang-tidy
Labels: component: tests, cleaning

#4047 Clang-tidy CI test: add few more bugprone checks in clang-tidy CI
  .clang-tidy
Labels: component: tests, cleaning

#4064 Clang-tidy CI test: add almost all the missing bugprone-* clang-tidy checks
  .clang-tidy
  Source/Utils/Parser/ParserUtils.cpp
Labels: component: tests, cleaning

#4075 Clang-tidy CI test: make bugprone checks list more compact
  .clang-tidy
Labels: component: tests, cleaning

#4081 Update Intel compiler installation
  .github/workflows/dependencies/dpcpp.sh
Labels: install, component: third party

#4079 Add reduced diag precision input parameter
  Docs/source/usage/parameters.rst
  Source/Diagnostics/ReducedDiags/ReducedDiags.H
  Source/Diagnostics/ReducedDiags/ReducedDiags.cpp
Labels: enhancement, component: diagnostics

#4080 ablastr: fix some missing or superfluous #include directives
  Source/ablastr/coarsen/average.H
  Source/ablastr/coarsen/average.cpp
  Source/ablastr/coarsen/sample.H
  Source/ablastr/coarsen/sample.cpp
  Source/ablastr/parallelization/MPIInitHelpers.cpp
  Source/ablastr/utils/Communication.H
  Source/ablastr/utils/Communication.cpp
  Source/ablastr/utils/Serialization.H
  Source/ablastr/utils/SignalHandling.cpp
  Source/ablastr/utils/TextMsg.H
  Source/ablastr/utils/TextMsg.cpp
  Source/ablastr/utils/UsedInputsFile.cpp
  Source/ablastr/utils/msg_logger/MsgLogger.H
  Source/ablastr/utils/msg_logger/MsgLogger.cpp
  Source/ablastr/utils/text/StringUtils.H
  Source/ablastr/warn_manager/WarnManager.H
  Source/ablastr/warn_manager/WarnManager.cpp
Labels: cleaning, component: ABLASTR

#4087 Update LUMI documentation
  Docs/source/install/hpc/lumi.rst
  Tools/machines/lumi-csc/install_dependencies.sh
  Tools/machines/lumi-csc/lumi_warpx.profile.example
Labels: component: documentation

#4077 Clang-tidy CI test: add some performance checks in clang-tidy CI test
  .clang-tidy
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp
  Source/ablastr/utils/SignalHandling.cpp
  Source/ablastr/utils/msg_logger/MsgLogger.cpp
Labels: component: tests, cleaning

#4088 Release 23.07
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#4074 Remove field probe raw_fields option
  Docs/source/usage/parameters.rst
  Source/Diagnostics/ReducedDiags/FieldProbe.H
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
Labels: cleaning, changes input scripts / defaults, component: diagnostics

#4048 Use default `nsys` on Perlmutter
  Docs/source/developers/profiling.rst
Labels: backend: cuda, component: documentation, component: third party, machine / system

#4092 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#4101 fix `chi_min` and `chi_max` in `ParticleExtrema` red diags
  Source/Diagnostics/ReducedDiags/ParticleExtrema.cpp
Labels: bug: affects latest release, component: diagnostics

#4111 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
Labels: component: third party

#4108 Clang tidy CI test: exclude some checks from clang tidy CI test
  .clang-tidy
Labels: component: tests, cleaning

#4100 Update perlmutter_gpu.sbatch
  Tools/machines/perlmutter-nersc/perlmutter_gpu.sbatch
Labels: component: documentation, machine / system

#4105 Docs: Fix timestep duration plot script download link
  Docs/source/usage/workflows/plot_timestep_duration.rst
Labels: component: documentation

#4107 Clang tidy CI test: add cppcoreguidelines-interfaces-global-init check to clang tidy CI test
  .clang-tidy
Labels: component: tests, cleaning

#4097 WarpX class: move a couple of function definitions from WarpX.H to WarpX.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#4098 Clang tidy CI test: add modernize-concat-nested-namespaces check to clang tidy CI test
  .clang-tidy
  Source/Utils/Logo/GetLogo.H
  Source/Utils/NCIGodfreyTables.H
  Source/ablastr/profiler/ProfilerWrapper.H
Labels: component: tests, cleaning

#4120 Tools: Update Copyright String
  Tools/DevUtils/update_copyright.sh
Labels: enhancement

#4123 Remove unused upper_bound algorithm
  Source/Laser/LaserProfilesImpl/LaserProfileFromFile.cpp
  Source/Utils/Algorithms/UpperBound.H
Labels: cleaning

#4118 Clang tidy CI test: exlcude cppcoreguidelines-init-variables check in clang tidy CI test
  .clang-tidy
Labels: component: tests, cleaning

#4126 AMReX: Update (Plotfile Write)
  .azure-pipelines.yml
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#4117 Initialize variables at declaration if it improves readability
  Source/AcceleratorLattice/LatticeElementFinder.H
  Source/BoundaryConditions/PML_RZ.cpp
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/ParticleReductionFunctor.cpp
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/ReducedDiags/ParticleEnergy.cpp
  Source/Diagnostics/ReducedDiags/ParticleMomentum.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CylindricalYeeAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmJConstantInTime.cpp
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/HankelTransform.cpp
  Source/FieldSolver/SpectralSolver/SpectralKSpace.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/WarpXComm_K.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/NuclearFusionFunc.H
  Source/Particles/Collision/BinaryCollision/ShuffleFisherYates.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/ablastr/coarsen/average.H
  Source/ablastr/coarsen/sample.H
Labels: cleaning

#4114 Fix the writing of raw rho_fp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
Labels: bug: affects latest release, component: diagnostics

#4089 fix BTD doc
  Docs/source/usage/parameters.rst
Labels: bug, component: documentation, bug: affects latest release, component: diagnostics

#4016 Improve script to compute PSATD stencil
  Tools/Algorithms/input_file_parser.py
  Tools/Algorithms/stencil.py
Labels: component: spectral, component: post-processing

#4078 Fix bug with MLMG solver, always pass ghost cells to `SumBoundary`
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/ablastr/utils/Communication.H
  Source/ablastr/utils/Communication.cpp
Labels: bug, bug: affects latest release, component: parallelization, component: ABLASTR

#4131 Remove superfluous #include from LatticeElements
  Source/AcceleratorLattice/LatticeElements/HardEdgedPlasmaLens.H
  Source/AcceleratorLattice/LatticeElements/HardEdgedPlasmaLens.cpp
  Source/AcceleratorLattice/LatticeElements/HardEdgedQuadrupole.H
  Source/AcceleratorLattice/LatticeElements/HardEdgedQuadrupole.cpp
  Source/AcceleratorLattice/LatticeElements/HardEdged_K.H
  Source/AcceleratorLattice/LatticeElements/LatticeElementBase.cpp
Labels: cleaning

#4142 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#4140 Clang tidy CI test: add misc-misleading-bidirectional checks to clang-tidy CI test
  .clang-tidy
Labels: component: tests, cleaning

#4130 [mini-PR] Remove WarpX::GetInstance() from PoissonBoundaryHandler::definePhiBCs
  Source/FieldSolver/ElectrostaticSolver.H
  Source/FieldSolver/ElectrostaticSolver.cpp
Labels: cleaning, component: electrostatic, component: boundary

#4133 Clang tidy CI test: add some modernize checks to clang-tidy CI test
  .clang-tidy
  Source/Diagnostics/BTD_Plotfile_Header_Impl.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformParticleFunctor.cpp
  Source/FieldSolver/ElectrostaticSolver.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianCKCAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianNodalAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianYeeAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CylindricalYeeAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmComoving.cpp
  Source/Initialization/InjectorMomentum.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/Collision/BinaryCollision/ParticleCreationFunc.H
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineWrapper.cpp
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineWrapper.cpp
  Source/Particles/NamedComponentParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Utils/ParticleUtils.cpp
  Source/Utils/WarpXVersion.cpp
  Source/ablastr/utils/SignalHandling.cpp
Labels: component: tests, cleaning

#4128 Clang tidy CI test: add a couple of performance checks to clang-tidy CI test
  .clang-tidy
Labels: component: tests, cleaning

#4135 Clang tidy CI test: add mpi-* checks to clang-tidy CI test
  .clang-tidy
Labels: component: tests, cleaning

#4141 Move CheckGuardCells(amrex::MultiFab const& mf) function into anonymous namespace in WarpXInitData
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
Labels: cleaning
