Repository BLAST-WarpX/warpx, pull requests merged in 2023-04, with the labels that each got.

#3795 Frontier: User Early Access Docs
  Docs/source/install/hpc/frontier.rst
Labels: component: documentation, machine / system

#3796 CI: CMake-Easyinstall New Link
  .azure-pipelines.yml
  .github/workflows/dependencies/hip.sh
  .github/workflows/dependencies/icc.sh
  .github/workflows/dependencies/nvcc11-0.sh
  .github/workflows/dependencies/nvcc11-8.sh
  .github/workflows/dependencies/nvhpc.sh
  .github/workflows/dependencies/pyfull.sh
  Docs/source/install/dependencies.rst
Labels: component: tests

#3799 Doc: Update Funding
  Docs/source/acknowledgements.rst
Labels: component: documentation

#3800 Release 23.04
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  LICENSE.txt
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#3801 CI: Retry Apt Repos
  .azure-pipelines.yml
  .github/workflows/dependencies/dpcpp.sh
  .github/workflows/dependencies/gcc.sh
  .github/workflows/dependencies/gcc12.sh
  .github/workflows/dependencies/hip.sh
  .github/workflows/dependencies/icc.sh
  .github/workflows/dependencies/nvcc11-0.sh
  .github/workflows/dependencies/nvcc11-8.sh
  .github/workflows/dependencies/nvhpc.sh
  .github/workflows/dependencies/pyfull.sh
Labels: component: tests, component: third party, backend: hip, backend: dpc++

#3802 Make verboncoeur correction optional
  Docs/source/usage/parameters.rst
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: RZ, component: boundary

#3590 Adding Amrex Bucket into WarpX Python interface.
  Python/pywarpx/Amrex.py
  Python/pywarpx/WarpX.py
  Python/pywarpx/__init__.py
  Python/pywarpx/picmi.py
Labels: component: Python

#3804 Implement thread-safe ChargeOnEB diagnostic
  Source/Diagnostics/ReducedDiags/ChargeOnEB.cpp
Labels: bug, backend: openmp, bug: affects latest release, component: diagnostics, component: boundary

#3808 Glossary, IO, LPI Again
  Docs/source/glossary.rst
Labels: component: documentation

#3771 openPMD-api 0.15.1
  .github/workflows/cuda.yml
  .github/workflows/dependencies/icc.sh
  .github/workflows/macos.yml
  CMakeLists.txt
  Docs/source/developers/gnumake/openpmd.rst
  Docs/source/install/cmake.rst
  Docs/source/install/dependencies.rst
  Docs/source/install/hpc/frontier.rst
  Docs/source/usage/parameters.rst
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Diagnostics/requirements.txt
  Source/Make.WarpX
  Tools/machines/summit-olcf/summit_warpx.profile.example
  cmake/dependencies/openPMD.cmake
  setup.py
Labels: component: openPMD, install, component: third party

#3807 Code cleanup: use `DepositCurrent()` in `AddSpaceChargeFieldLabFrame()`
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/Particles/MultiParticleContainer.cpp
Labels: cleaning, component: electrostatic

#3809 Charge on EB: Use `fp` field instead of `aux`
  Source/Diagnostics/ReducedDiags/ChargeOnEB.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#3812 CI: Retry Simplify
  .github/workflows/dependencies/dpcpp.sh
  .github/workflows/dependencies/icc.sh
Labels: component: tests

#3813 GitHub Actions: macOS has 3 Cores
  .github/workflows/macos.yml
Labels: component: tests

#3810 Fix loading particles from openPMD
  Source/Particles/PhysicalParticleContainer.cpp
Labels: bug, component: openPMD, bug: affects latest release

#3818 Glossary update
  Docs/source/glossary.rst
Labels: component: documentation

#3819 Contributing page update
  CONTRIBUTING.rst
Labels: component: documentation

#3815 Lattice: Line Docs & Rename
  Docs/source/usage/parameters.rst
  Examples/Tests/AcceleratorLattice/analysis.py
  Examples/Tests/AcceleratorLattice/inputs_quad_3d
  Source/AcceleratorLattice/AcceleratorLattice.cpp
Labels: enhancement

#3798 Diagnostics: Loop up to Finest Level
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.cpp
Labels: bug, component: mesh refinement, bug: affects latest release, component: diagnostics

#3720 PSATD: call FFT of rho with explicit spectral index
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/WarpX.cpp
Labels: component: spectral, cleaning

#3668 Improve Python script to plot PSATD stencils
  Tools/Algorithms/stencil.py
Labels: component: spectral, component: post-processing

#3612 CI: add RZ Langmuir test w/ multi-J PSATD
  Regression/Checksum/benchmarks_json/Langmuir_multi_rz_psatd_multiJ.json
  Regression/WarpX-tests.ini
Labels: component: spectral, component: tests

#3607 Clean up calls to FillBoundary in FDTD part of `OneStep_nosub`
  Source/Evolve/WarpXEvolve.cpp
Labels: component: parallelization

#3749 Add message if user sets old flag `warpx.do_nodal`
  Source/WarpX.cpp
Labels: changes input scripts / defaults, component: Python

#3832 Doc: Frontier Module Updates
  Docs/source/install/hpc/frontier.rst
  Tools/machines/frontier-olcf/frontier_warpx.profile.example
Labels: component: documentation, install, component: third party, machine / system, component: diagnostics

#3711 Reflect density from non-periodic boundaries during deposition
  Docs/source/theory/PML.rst
  Docs/source/usage/parameters.rst
  Examples/Physics_applications/capacitive_discharge/analysis_2d.py
  Regression/Checksum/benchmarks_json/LaserAcceleration.json
  Regression/Checksum/benchmarks_json/LaserAccelerationBoost.json
  Regression/Checksum/benchmarks_json/LaserAcceleration_1d.json
  Regression/Checksum/benchmarks_json/LaserAcceleration_BTD.json
  Regression/Checksum/benchmarks_json/LaserAcceleration_single_precision_comms.json
  Regression/Checksum/benchmarks_json/PEC_particle.json
  Regression/Checksum/benchmarks_json/Plasma_lens.json
  Regression/Checksum/benchmarks_json/Plasma_lens_boosted.json
  Regression/Checksum/benchmarks_json/Plasma_lens_short.json
  Regression/Checksum/benchmarks_json/Python_LaserAcceleration.json
  Regression/Checksum/benchmarks_json/Python_LaserAcceleration_1d.json
  Regression/Checksum/benchmarks_json/Python_magnetostatic_eb_3d.json
  Regression/Checksum/benchmarks_json/Python_plasma_lens.json
  Regression/Checksum/benchmarks_json/Python_prev_positions.json
  Regression/Checksum/benchmarks_json/RepellingParticles.json
  Regression/Checksum/benchmarks_json/background_mcc.json
  Regression/Checksum/benchmarks_json/background_mcc_dp_psp.json
  Regression/Checksum/benchmarks_json/hard_edged_plasma_lens.json
  Regression/Checksum/benchmarks_json/hard_edged_quadrupoles.json
  Regression/Checksum/benchmarks_json/magnetostatic_eb_3d.json
  Regression/Checksum/benchmarks_json/parabolic_channel_initialization_2d_single_precision.json
  Source/BoundaryConditions/WarpXFieldBoundaries.cpp
  Source/BoundaryConditions/WarpX_PEC.H
  Source/BoundaryConditions/WarpX_PEC.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/WarpX.H
Labels: component: boundary

#3835 Doc: Perlmutter CFS for SW & Optimas
  Docs/source/install/hpc/perlmutter.rst
  Tools/machines/perlmutter-nersc/perlmutter_cpu_warpx.profile.example
  Tools/machines/perlmutter-nersc/perlmutter_gpu_warpx.profile.example
  Tools/optimas/requirements.txt
Labels: backend: cuda, component: documentation, install, component: third party, machine / system

#3827 Docs: LPA Collision Papers
  Docs/source/highlights.rst
Labels: component: documentation

#3452 Add callback function before/after the initial Esolve
  Docs/source/usage/python.rst
  Python/pywarpx/callbacks.py
  Source/Initialization/WarpXInitData.cpp
  Source/Python/WarpX_py.H
Labels: component: electrostatic, component: Python

#3825 amrex.the_arena_is_managed=0
  Docs/source/usage/parameters.rst
  Source/Initialization/WarpXAMReXInit.cpp
Labels: backend: cuda, Performance optimization, changes input scripts / defaults, backend: hip, backend: dpc++

#3836 Doc: AAC22 Proceeding
  Docs/source/acknowledge_us.rst
Labels: component: documentation

#3840 Doc: HPSS Permissions
  Docs/source/usage/workflows/archiving.rst
Labels: component: documentation, machine / system

#3822 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/Checksum/benchmarks_json/background_mcc_dp_psp.json
  Regression/Checksum/benchmarks_json/hard_edged_quadrupoles.json
  Regression/Checksum/benchmarks_json/pml_psatd_dive_divb_cleaning.json
  Regression/Checksum/benchmarks_json/reduced_diags_single_precision.json
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3845 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3841 Doc: Tunneling Jupyter
  Docs/source/dataanalysis/workflows.rst
  Docs/source/dataanalysis/workflows/tunneling.rst
  Docs/source/index.rst
Labels: component: documentation

#3837 Fix particle reflecting boundaries in RZ
  Python/pywarpx/picmi.py
  Source/Particles/ParticleBoundaries_K.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: bug, component: PICMI, bug: affects latest release, geometry: RZ, component: boundary

#3848 AMReX/PICSAR: Update to New Particle APIs
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  Source/Diagnostics/ReducedDiags/FieldProbeParticleContainer.cpp
  Source/Particles/LaserParticleContainer.H
  Source/Particles/ParticleIO.H
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/Particles/WarpXParticleContainer_fwd.H
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3585 Adding additional check in addPlasma and addPlasmaFlux to respect the…
  Examples/Tests/nci_psatd_stability/analysis_galilean.py
  Regression/Checksum/benchmarks_json/Langmuir_multi_rz_psatd.json
  Regression/Checksum/benchmarks_json/Langmuir_multi_rz_psatd_current_correction.json
  Regression/Checksum/benchmarks_json/galilean_rz_psatd.json
  Regression/Checksum/benchmarks_json/galilean_rz_psatd_current_correction.json
  Regression/Checksum/benchmarks_json/galilean_rz_psatd_current_correction_psb.json
  Source/Particles/PhysicalParticleContainer.cpp
Labels: geometry: RZ

#3854 Doc: VisualPIC
  Docs/source/dataanalysis/visualpic.rst
Labels: component: documentation, component: third party

#3846 Use amrex::Math::powi<N>(x) in WarpX
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmComoving.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmJConstantInTime.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmJLinearInTime.cpp
  Source/Particles/Collision/BinaryCollision/NuclearFusion/ProtonBoronFusionCrossSection.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/SingleNuclearFusionEvent.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/TwoProductFusionUtil.H
Labels: Performance optimization, cleaning

#3859 Parameters doc: clean duplicated predefined density profile option
  Docs/source/usage/parameters.rst
Labels: component: documentation, cleaning

#3862 Remove unnecessary #include from ablastr/particles/DepositCharge.H
  Source/ablastr/particles/DepositCharge.H
Labels: cleaning, component: ABLASTR

#3863 Move KernelTimer.H to ablastr/parallelization
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/Deposition/CurrentDeposition.H
  Source/WarpX.cpp
  Source/ablastr/CMakeLists.txt
  Source/ablastr/Make.package
  Source/ablastr/parallelization/KernelTimer.H
  Source/ablastr/parallelization/Make.package
  Source/ablastr/particles/DepositCharge.H
Labels: cleaning, component: ABLASTR

#3864 Move StringUtils.H to ablastr
  Source/Utils/CMakeLists.txt
  Source/Utils/Make.package
  Source/Utils/Parser/IntervalsParser.cpp
  Source/Utils/Strings/Make.package
  Source/ablastr/utils/CMakeLists.txt
  Source/ablastr/utils/Make.package
  Source/ablastr/utils/TextMsg.H
  Source/ablastr/utils/TextMsg.cpp
  Source/ablastr/utils/text/CMakeLists.txt
  Source/ablastr/utils/text/Make.package
  Source/ablastr/utils/text/StringUtils.H
  Source/ablastr/utils/text/StringUtils.cpp
  Source/ablastr/warn_manager/WarnManager.cpp
Labels: cleaning, component: ABLASTR

#3856 Doc: add instructions to use the Fugaku supercomputer (Riken)
  Docs/source/install/hpc.rst
  Docs/source/install/hpc/fugaku.rst
  Tools/machines/fugaku-riken/submit.sh
Labels: component: documentation, machine / system

#3858 Doc: libmamba for Conda
  Docs/source/install/dependencies.rst
  Docs/source/install/users.rst
Labels: component: documentation, install

#3839 Doc: Update of the Perlmutter Filesystem Note
  Docs/source/install/hpc/perlmutter.rst
Labels: component: documentation

#3820 Fix FieldEnergy diagnostic for RZ
  Source/Diagnostics/ReducedDiags/FieldEnergy.cpp
Labels: component: diagnostics, geometry: RZ

#3849 Add python callback call when a break signal is recieved
  Python/pywarpx/callbacks.py
  Source/Evolve/WarpXEvolve.cpp
  Source/Python/WarpX_py.H
Labels: component: Python

#3584 Import external E/B fields from openPMD files
  Docs/source/usage/parameters.rst
  Examples/Tests/LoadExternalField/analysis_3d.py
  Examples/Tests/LoadExternalField/analysis_rz.py
  Examples/Tests/LoadExternalField/inputs_3d
  Examples/Tests/LoadExternalField/inputs_rz
  Regression/Checksum/benchmarks_json/LoadExternalField3D.json
  Regression/Checksum/benchmarks_json/LoadExternalFieldRZ.json
  Regression/WarpX-tests.ini
  Source/Evolve/WarpXEvolve.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/WarpXRegrid.cpp
  Source/WarpX.H
  Source/WarpX.cpp
  run_test.sh
Labels: component: openPMD

#3867 update ci to use ascent 0.9.1
  .github/workflows/insitu.yml
Labels: component: tests, component: third party, component: diagnostics

#3866 Documentation For Using NCU
  Docs/source/developers/profiling.rst
Labels: component: documentation

#3865 Docs: use bibtex citations in collisions theory section
  Docs/source/refs.bib
  Docs/source/theory/collisions.rst
Labels: component: documentation

#3868 AMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#3869 Docs: Suppress sphinx warning about duplicate bibliography labels
  Docs/source/conf.py
Labels: component: documentation, warning

#3874 Don't rely on managed memory in SmartUtils
  Source/Particles/ParticleCreation/SmartUtils.cpp
Labels: bug, backend: cuda, component: QED, backend: hip, backend: dpc++, component: core

#3368 Shared memory charge and current deposition
  Docs/source/usage/parameters.rst
  Examples/Tests/particle_fields_diags/analysis_particle_diags_impl.py
  Examples/Tests/reduced_diags/analysis_reduced_diags_impl.py
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/Deposition/SharedDepositionUtils.H
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: backend: cuda, Performance optimization, backend: hip, component: core

#3873 Fix missing GPU synchronization when QED lookup tables are loaded or generated
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineWrapper.H
  Source/Particles/ElementaryProcess/QEDInternals/BreitWheelerEngineWrapper.cpp
  Source/Particles/ElementaryProcess/QEDInternals/QedWrapperCommons.H
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineWrapper.H
  Source/Particles/ElementaryProcess/QEDInternals/QuantumSyncEngineWrapper.cpp
Labels: bug, backend: cuda, component: QED, backend: hip, backend: dpc++

#3884 Moving Window: Fix the logic to shift F and G fields when doing divE and divB cleaning in pml
  Source/Utils/WarpXMovingWindow.cpp
Labels: bug, component: mesh refinement, bug: affects latest release, component: boundary

#3880 Build buffer masks on GPU
  Source/WarpX.H
  Source/WarpX.cpp
Labels: bug, backend: cuda, Performance optimization, backend: hip, backend: dpc++

#3885 Doc: correct a formatting error in the Fugaku page
  Docs/source/install/hpc/fugaku.rst
Labels: bug, component: documentation, bug: affects latest release

#3882 Add new paper using WarpX
  Docs/source/highlights.rst
Labels: component: documentation

#3878 CI: macOS Cache Less
  .github/workflows/macos.yml
Labels: component: tests

#3877 Fix typo in parameters doc (period -> intervals)
  Docs/source/usage/parameters.rst
Labels: bug, component: documentation, bug: affects latest release
