Repository BLAST-WarpX/warpx, pull requests merged in 2024-10, with the labels that each got.

#5348 Doc: HPC no heFFTe yet
  Docs/source/install/hpc/lonestar6.rst
  Docs/source/install/hpc/perlmutter.rst
Labels: component: documentation, machine / system

#5345 Doc: NVTX in Nvidia Conda
  Docs/source/install/dependencies.rst
Labels: backend: cuda, component: documentation, install

#5273 Use only plasma current in `HybridPICSolveE`
  Examples/Tests/ohm_solver_magnetic_reconnection/inputs_test_2d_ohm_solver_magnetic_reconnection_picmi.py
  Python/pywarpx/fields.py
  Source/Diagnostics/ComputeDiagFunctors/JdispFunctor.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICSolveE.cpp
  Source/FieldSolver/WarpXPushFieldsHybridPIC.cpp
  Source/Fields.H
Labels: bug, bug: affects latest release, component: fluid-ohm

#5308 CI: avoid duplicate runs for secondary branches on main fork
  .azure-pipelines.yml
  .github/workflows/clang_sanitizers.yml
  .github/workflows/clang_tidy.yml
  .github/workflows/cuda.yml
  .github/workflows/hip.yml
  .github/workflows/insitu.yml
  .github/workflows/intel.yml
  .github/workflows/macos.yml
  .github/workflows/source.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
Labels: component: tests, cleaning

#5349 General parser function for external fields
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/FieldSolver/WarpXPushFieldsHybridPIC.cpp
  Source/Fluids/WarpXFluidContainer.cpp
  Source/Initialization/ExternalField.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Particles/Gather/GetExternalFields.cpp
  Source/WarpX.H
Labels: cleaning

#5357 Release 24.10
  .github/workflows/cuda.yml
  CMakeLists.txt
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
Labels: component: documentation, component: third party

#5358 Update ALCF Polaris profile
  Tools/machines/polaris-alcf/polaris_gpu_warpx.profile.example
Labels: component: documentation, machine / system

#5359 Fix: newVersion.sh Python
  Docs/source/conf.py
  Python/setup.py
  Tools/Release/newVersion.sh
  setup.py
Labels: bug, component: documentation, install, bug: affects latest release

#5360 Doc: Update Lawrencium (LBNL)
  Tools/machines/lawrencium-lbnl/lawrencium_warpx.profile.example
Labels: component: documentation, machine / system

#5362 CI: add base input file for convenience
  .github/workflows/clang_sanitizers.yml
  .github/workflows/ubuntu.yml
  Examples/Physics_applications/laser_acceleration/inputs_base_1d
  Examples/Physics_applications/laser_acceleration/inputs_test_1d_laser_acceleration
Labels: component: tests, cleaning

#5351 Remove multifab_map and associated functions
  Source/Python/WarpX.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#5365 Doc: Catalyst Verbatim Formatting
  Docs/source/dataanalysis/catalyst.rst
Labels: component: documentation

#5369 AMReX/pyAMReX/PICSAR: weekly update
  .github/workflows/cuda.yml
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
Labels: component: third party

#5374 Doc: Governance GitHub Team Links
  GOVERNANCE.rst
Labels: bug, component: documentation, bug: affects latest release, component: open governance

#5372 CI: update docs and reset tool for checksums
  Docs/source/developers/checksum.rst
  Docs/source/developers/testing.rst
  Docs/source/developers/workflows.rst
  Tools/DevUtils/update_benchmarks_from_azure_output.py
Labels: component: documentation, component: tests

#5376 Docs: fix checksums section cross-reference
  Docs/source/developers/testing.rst
Labels: component: documentation, cleaning

#5378 CMake: Fix List of Pip Options
  .github/workflows/macos.yml
  CMakeLists.txt
  Docs/source/install/cmake.rst
Labels: bug, install, bug: affects latest release, component: Python

#5364 Disable AMReX_LINEAR_SOLVER_INCFLO by default
  GNUmakefile
  Source/ablastr/Make.package
  Source/ablastr/fields/Make.package
  cmake/dependencies/AMReX.cmake
Labels: install, component: third party

#5382 Expose `MultiParticleContainer.GetChargeDensity` to Python
  Source/Python/Particles/MultiParticleContainer.cpp
Labels: component: Python

#5380 CMake: No FFTW Needed for SYCL anymore
  .github/workflows/intel.yml
  cmake/dependencies/FFT.cmake
Labels: bug, component: spectral, install, bug: affects latest release, backend: dpc++

#5385 Fix CI: CodeQL Setup
  .github/workflows/codeql.yml
Labels: bug, component: tests, component: third party

#5384 SYCL: 1D EB Compile
  Source/EmbeddedBoundary/DistanceToEB.H
Labels: bug, bug: affects latest release, backend: sycl

#5353 Move isAnyBoundaryPML to Warpx.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning, component: boundary

#5208 Implement injection of particles from the embedded boundary
  Docs/source/usage/parameters.rst
  Examples/Tests/flux_injection/CMakeLists.txt
  Examples/Tests/flux_injection/analysis_flux_injection_from_eb.py
  Examples/Tests/flux_injection/inputs_base_from_eb
  Examples/Tests/flux_injection/inputs_test_2d_flux_injection_from_eb
  Examples/Tests/flux_injection/inputs_test_3d_flux_injection_from_eb
  Examples/Tests/flux_injection/inputs_test_rz_flux_injection_from_eb
  Regression/Checksum/benchmarks_json/test_2d_flux_injection_from_eb.json
  Regression/Checksum/benchmarks_json/test_3d_flux_injection_from_eb.json
  Regression/Checksum/benchmarks_json/test_rz_flux_injection_from_eb.json
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/AddPlasmaUtilities.H
  Source/Particles/PhysicalParticleContainer.cpp
Labels: component: boundary

#5342 Avoid interpolating from guard cells in BTD
  Regression/Checksum/benchmarks_json/test_2d_rigid_injection_btd.json
  Source/Diagnostics/BTDiagnostics.cpp
Labels: component: diagnostics, component: boosted frame

#5341 Update BackTransformed diagnostics to take into account arbitrary moving window velocity
  Docs/source/usage/faq.rst
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BTDiagnostics.cpp
Labels: component: diagnostics, component: boosted frame

#5337 Add WarpX example for FEL simulation
  Docs/source/refs.bib
  Docs/source/usage/examples.rst
  Docs/source/usage/examples/free_electron_laser
  Docs/source/usage/parameters.rst
  Examples/Physics_applications/CMakeLists.txt
  Examples/Physics_applications/free_electron_laser/CMakeLists.txt
  Examples/Physics_applications/free_electron_laser/README.rst
  Examples/Physics_applications/free_electron_laser/analysis_fel.py
  Examples/Physics_applications/free_electron_laser/inputs_test_1d_fel
  Examples/Physics_applications/free_electron_laser/plot_sim.py
  Regression/Checksum/benchmarks_json/test_1d_fel.json
Labels: component: documentation

#5387 CI: skip build/test jobs if only `Docs/` is modified
  .azure-pipelines.yml
  .github/workflows/clang_sanitizers.yml
  .github/workflows/clang_tidy.yml
  .github/workflows/cuda.yml
  .github/workflows/hip.yml
  .github/workflows/insitu.yml
  .github/workflows/intel.yml
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
Labels: component: tests

#5390 `PYBIND11_FINDPYTHON=ON`
  CMakeLists.txt
  cmake/dependencies/pybind11.cmake
  setup.py
Labels: bug, install, bug: affects latest release, component: Python

#5340 HPC: `SRUN_CPUS_PER_TASK` to `SLURM_`
  Tools/machines/greatlakes-umich/greatlakes_v100.sbatch
  Tools/machines/karolina-it4i/karolina_gpu.sbatch
  Tools/machines/lonestar6-tacc/lonestar6_a100.sbatch
  Tools/machines/perlmutter-nersc/perlmutter_cpu.sbatch
  Tools/machines/perlmutter-nersc/perlmutter_gpu.sbatch
  Tools/machines/tioga-llnl/tioga_mi300a.sbatch
Labels: component: documentation, machine / system

#5394 CI: avoid duplicate runs for secondary branches on main repo
  .azure-pipelines.yml
Labels: component: tests

#5399 CI: fix `AppleClang` workflow
  .github/workflows/macos.yml
Labels: bug, component: tests

#5391 AMReX/pyAMReX/PICSAR: weekly update
  .github/workflows/cuda.yml
  Docs/source/developers/particles.rst
  Source/Diagnostics/ParticleIO.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Particles/NamedComponentParticleContainer.H
  Source/Particles/ParticleBoundaryBuffer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Python/Particles/WarpXParticleContainer.cpp
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
Labels: component: third party

#5405 Fix a typo in cmake option disabling amrex incflo solvers
  cmake/dependencies/AMReX.cmake
Labels: bug, install

#5406 Update picmistandard to 0.31.0
  Docs/requirements.txt
  Python/setup.py
  Tools/machines/karolina-it4i/install_dependencies.sh
  requirements.txt
Labels: component: PICMI

#5403 Docs: fix typo in documentation for Leonardo supercomputer (CINECA)
  Docs/source/install/hpc/leonardo.rst
Labels: component: documentation

#5285 Add Time-Averaged Field Diagnostics
  Docs/source/usage/parameters.rst
  Docs/source/usage/python.rst
  Examples/Physics_applications/laser_ion/CMakeLists.txt
  Examples/Physics_applications/laser_ion/README.rst
  Examples/Physics_applications/laser_ion/analysis_default_openpmd_regression.py
  Examples/Physics_applications/laser_ion/analysis_test_laser_ion.py
  Examples/Physics_applications/laser_ion/inputs_test_2d_laser_ion_acc
  Examples/Physics_applications/laser_ion/inputs_test_2d_laser_ion_acc_picmi.py
  Examples/Physics_applications/laser_ion/plot_2d.py
  Python/pywarpx/picmi.py
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/BoundaryScrapingDiagnostics.H
  Source/Diagnostics/BoundaryScrapingDiagnostics.cpp
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.H
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/MultiDiagnostics.H
  Source/Diagnostics/MultiDiagnostics.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: hackathon, component: diagnostics

#5416 Docs: how to generate QED tables in beam-beam example
  Examples/Physics_applications/beam_beam_collision/README.rst
  Examples/Physics_applications/beam_beam_collision/inputs_test_3d_beam_beam_collision
Labels: component: documentation

#5419 CI: fix IntelLLVM builds
  .github/workflows/dependencies/dpcpp.sh
  .github/workflows/intel.yml
Labels: bug, component: tests

#5421 CTest: fix bug with `WarpX_APP=OFF` and `WarpX_PYTHON=ON`
  Examples/CMakeLists.txt
Labels: bug, component: tests, bug: affects latest release

#5423 Docs: update documentation for Adastra supercomputer (CINES)
  Tools/machines/adastra-cines/adastra_warpx.profile.example
Labels: component: documentation

#5418 AMReX/pyAMReX/PICSAR: weekly update
  .github/workflows/cuda.yml
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
Labels: component: third party

#5430 Fix bug where tmax was ignored in flux injection
  Examples/Tests/flux_injection/analysis_flux_injection_from_eb.py
  Examples/Tests/flux_injection/inputs_base_from_eb
  Regression/Checksum/benchmarks_json/test_2d_flux_injection_from_eb.json
  Regression/Checksum/benchmarks_json/test_3d_flux_injection_from_eb.json
  Regression/Checksum/benchmarks_json/test_rz_flux_injection_from_eb.json
  Source/Initialization/PlasmaInjector.cpp
Labels: bug, bug: affects latest release, component: boundary
