Repository BLAST-WarpX/warpx, pull requests merged in 2024-01, with the labels that each got.

#4565 Add semi-implicit CI test
  Examples/Tests/Implicit/analysis_1d.py
  Examples/Tests/Implicit/inputs_1d_semiimplicit
  Regression/Checksum/benchmarks_json/SemiImplicitPicard_1d.json
  Regression/WarpX-tests.ini
Labels: component: tests, component: implicit solvers

#4371 Add filters for boundary scraping diagnostics
  Docs/source/usage/parameters.rst
  Examples/Tests/scraping/analysis_rz_filter.py
  Examples/Tests/scraping/inputs_rz_filter
  Regression/WarpX-tests.ini
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: component: diagnostics, component: boundary

#4564 Update the field probe diagnostic documentation
  Docs/source/usage/parameters.rst
Labels: component: documentation, component: diagnostics

#4570 Apply particle selection to BTDiagnostics
  Examples/Tests/boosted_diags/analysis.py
  Examples/Tests/boosted_diags/inputs_3d
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: bug, bug: affects latest release, component: diagnostics, component: boosted frame

#4572 Update dsmc and fusion binary collisions
  Examples/Physics_applications/capacitive_discharge/PICMI_inputs_1d.py
  Source/Particles/Collision/BinaryCollision/DSMC/CollisionFilterFunc.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/SingleNuclearFusionEvent.H
Labels: component: collisions

#4546 Beam-beam collision example
  Docs/source/refs.bib
  Docs/source/usage/examples.rst
  Docs/source/usage/examples/beam-beam_collision
  Examples/Physics_applications/beam-beam_collision/README.rst
  Examples/Physics_applications/beam-beam_collision/inputs
  Regression/Checksum/benchmarks_json/BeamBeamCollision.json
  Regression/WarpX-tests.ini
Labels: component: documentation

#4573 Perlmutter: Load `gpu` Module
  Tools/machines/perlmutter-nersc/perlmutter_gpu_warpx.profile.example
Labels: component: documentation, machine / system

#4578 Beam-beam collision example follow-up
  Examples/Physics_applications/beam-beam_collision/inputs
  Regression/Checksum/benchmarks_json/BeamBeamCollision.json
Labels: component: tests

#4576 Reduce tolerance for DSMC CI test
  Examples/Physics_applications/capacitive_discharge/analysis_dsmc.py
  Regression/Checksum/benchmarks_json/Python_dsmc_1d.json
Labels: component: tests

#4584 Doc: Clean Example TODOs
  Docs/source/usage/examples.rst
Labels: component: documentation

#4547 Read external fields from file in restarted simulation
  Docs/source/usage/parameters.rst
  Examples/Tests/LoadExternalField/inputs_rz
  Regression/WarpX-tests.ini
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
Labels: bug, bug: affects latest release, component: checkpoint/restart

#4586 Release 24.01
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#4510 Clang-tidy: enforce clang-tidy_readability_make_member_function_const check
  .clang-tidy
  Source/AcceleratorLattice/AcceleratorLattice.cpp
  Source/AcceleratorLattice/LatticeElementFinder.H
  Source/AcceleratorLattice/LatticeElementFinder.cpp
  Source/BoundaryConditions/WarpXFieldBoundaries.cpp
  Source/Diagnostics/BTD_Plotfile_Header_Impl.H
  Source/Diagnostics/BTD_Plotfile_Header_Impl.cpp
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/MultiDiagnostics.H
  Source/Diagnostics/ReducedDiags/ReducedDiags.H
  Source/Diagnostics/ReducedDiags/ReducedDiags.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/Initialization/InjectorMomentum.cpp
  Source/Particles/Collision/BackgroundMCC/BackgroundMCCCollision.H
  Source/Particles/Collision/BackgroundMCC/BackgroundMCCCollision.cpp
  Source/Particles/Collision/CollisionBase.H
  Source/Particles/ParticleBoundaries.H
  Source/Particles/ParticleBoundaries.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/WarpX.H
  Source/ablastr/utils/timer/Timer.H
  Source/ablastr/utils/timer/Timer.cpp
Labels: component: tests, cleaning

#4505 Implement correction to ADK for high fields
  Docs/source/usage/parameters.rst
  Source/Particles/ElementaryProcess/Ionization.H
  Source/Particles/ElementaryProcess/Ionization.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Utils/Physics/IonizationEnergiesTable.H
Labels: component: initialization, component: ionization

#4590 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
Labels: component: third party

#4597 Fix plasma injection from file for parallel runs
  Source/Initialization/PlasmaInjector.cpp
Labels: bug

#4607 Fix input of galerkin_scheme
  Source/WarpX.cpp
Labels: component: implicit solvers

#4554 Disambiguate the routine name initialize_inputs in picmi.py
  Python/pywarpx/picmi.py
Labels: cleaning, component: PICMI

#4620 Perlmutter (NERSC): January 2024 Update
  Tools/machines/perlmutter-nersc/perlmutter_cpu_warpx.profile.example
  Tools/machines/perlmutter-nersc/perlmutter_gpu_warpx.profile.example
Labels: component: documentation, machine / system

#4621 Update `CuPy` version in Perlmutter dependencies
  Tools/machines/perlmutter-nersc/install_gpu_dependencies.sh
Labels: component: documentation, machine / system

#4622 Update `picmi.ElectrostaticSolver` child class in external Poisson solver test
  Examples/Physics_applications/capacitive_discharge/PICMI_inputs_1d.py
  Examples/Physics_applications/capacitive_discharge/PICMI_inputs_2d.py
Labels: component: electrostatic, component: Python

#4615 Fix undefined behavior issue in WarpX initialization
  Source/WarpX.cpp
Labels: bug, bug: affects latest release, component: initialization

#4603 Doc: Fast, Local Compilation
  Docs/source/developers/local_compile.rst
  Docs/source/developers/workflows.rst
  Docs/source/install/cmake.rst
  Docs/source/install/dependencies.rst
Labels: component: documentation

#4630 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
Labels: component: third party

#4628 Temporary fix: disable hanging CI test (`Python_background_mcc_1d_tridiag`)
  .github/workflows/source/test_ci_matrix.sh
  Regression/WarpX-tests.ini
Labels: component: tests

#4633 Update pyAMReX
  cmake/dependencies/pyAMReX.cmake
Labels: component: third party, geometry: RZ, component: Python

#3850 Update Particle Container to Pure SoA
  Docs/source/usage/workflows/python_extend.rst
  Examples/Tests/particle_data_python/PICMI_inputs_2d.py
  Examples/Tests/particle_data_python/PICMI_inputs_prev_pos_2d.py
  Examples/Tests/restart/PICMI_inputs_runtime_component_analyze.py
  Python/pywarpx/particle_containers.py
  Source/Diagnostics/ComputeDiagFunctors/BackTransformParticleFunctor.H
  Source/Diagnostics/FlushFormats/FlushFormatAscent.cpp
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/ParticleIO.cpp
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
  Source/Diagnostics/ReducedDiags/FieldProbeParticleContainer.H
  Source/Diagnostics/ReducedDiags/FieldProbeParticleContainer.cpp
  Source/Diagnostics/ReducedDiags/LoadBalanceCosts.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/EmbeddedBoundary/ParticleBoundaryProcess.H
  Source/EmbeddedBoundary/ParticleScraper.H
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
  Source/Particles/Collision/BinaryCollision/Coulomb/PairWiseCoulombCollisionFunc.H
  Source/Particles/Collision/BinaryCollision/DSMC/DSMC.H
  Source/Particles/Collision/BinaryCollision/DSMC/SplitAndScatterFunc.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/NuclearFusionFunc.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/ProtonBoronFusionInitializeMomentum.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/TwoProductFusionInitializeMomentum.H
  Source/Particles/Collision/BinaryCollision/ParticleCreationFunc.H
  Source/Particles/Collision/BinaryCollision/ShuffleFisherYates.H
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/ElementaryProcess/QEDPairGeneration.H
  Source/Particles/ElementaryProcess/QEDPhotonEmission.H
  Source/Particles/LaserParticleContainer.H
  Source/Particles/NamedComponentParticleContainer.H
  Source/Particles/ParticleBoundaryBuffer.cpp
  Source/Particles/ParticleCreation/SmartCopy.H
  Source/Particles/ParticleCreation/SmartCreate.H
  Source/Particles/ParticleCreation/SmartUtils.H
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/GetAndSetPosition.H
  Source/Particles/Resampling/LevelingThinning.cpp
  Source/Particles/Sorting/Partition.cpp
  Source/Particles/Sorting/SortingUtils.H
  Source/Particles/Sorting/SortingUtils.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/Python/Particles/ParticleBoundaryBuffer.cpp
  Source/Python/Particles/PinnedMemoryParticleContainer.cpp
  Source/Python/Particles/WarpXParticleContainer.cpp
  Source/Utils/ParticleUtils.H
  Source/Utils/ParticleUtils.cpp
  Source/ablastr/particles/IndexHandling.H
  Source/ablastr/particles/ParticleMoments.H
Labels: Performance optimization, cleaning, component: core

#4585 Remove particles that are initialized in the EB
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/WarpX.H
Labels: bug, bug: affects latest release, component: boundary

#4646 Update DSMC picmi class initialization function
  Python/pywarpx/picmi.py
  Regression/WarpX-tests.ini
Labels: component: PICMI

#4647 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#4643 Fix neutral particle got pushed
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/PushSelector.H
Labels: bug, bug: affects latest release, component: ionization

#4650 Reactivate CI test (`Python_background_mcc_1d_tridiag`)
  Regression/WarpX-tests.ini
Labels: component: tests

#4617 Grammar Change in Theory Intro
  Docs/source/theory/intro.rst
Labels: component: documentation

#4652 Revert "Update Particle Container to Pure SoA (#3850)"
  Docs/source/usage/workflows/python_extend.rst
  Examples/Tests/particle_data_python/PICMI_inputs_2d.py
  Examples/Tests/particle_data_python/PICMI_inputs_prev_pos_2d.py
  Examples/Tests/restart/PICMI_inputs_runtime_component_analyze.py
  Python/pywarpx/particle_containers.py
  Source/Diagnostics/ComputeDiagFunctors/BackTransformParticleFunctor.H
  Source/Diagnostics/FlushFormats/FlushFormatAscent.cpp
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/ParticleIO.cpp
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
  Source/Diagnostics/ReducedDiags/FieldProbeParticleContainer.H
  Source/Diagnostics/ReducedDiags/FieldProbeParticleContainer.cpp
  Source/Diagnostics/ReducedDiags/LoadBalanceCosts.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/EmbeddedBoundary/ParticleBoundaryProcess.H
  Source/EmbeddedBoundary/ParticleScraper.H
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
  Source/Particles/Collision/BinaryCollision/Coulomb/PairWiseCoulombCollisionFunc.H
  Source/Particles/Collision/BinaryCollision/DSMC/DSMC.H
  Source/Particles/Collision/BinaryCollision/DSMC/SplitAndScatterFunc.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/NuclearFusionFunc.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/ProtonBoronFusionInitializeMomentum.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/TwoProductFusionInitializeMomentum.H
  Source/Particles/Collision/BinaryCollision/ParticleCreationFunc.H
  Source/Particles/Collision/BinaryCollision/ShuffleFisherYates.H
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/ElementaryProcess/QEDPairGeneration.H
  Source/Particles/ElementaryProcess/QEDPhotonEmission.H
  Source/Particles/LaserParticleContainer.H
  Source/Particles/NamedComponentParticleContainer.H
  Source/Particles/ParticleBoundaryBuffer.cpp
  Source/Particles/ParticleCreation/SmartCopy.H
  Source/Particles/ParticleCreation/SmartCreate.H
  Source/Particles/ParticleCreation/SmartUtils.H
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/GetAndSetPosition.H
  Source/Particles/Resampling/LevelingThinning.cpp
  Source/Particles/Sorting/Partition.cpp
  Source/Particles/Sorting/SortingUtils.H
  Source/Particles/Sorting/SortingUtils.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/Python/Particles/ParticleBoundaryBuffer.cpp
  Source/Python/Particles/PinnedMemoryParticleContainer.cpp
  Source/Python/Particles/WarpXParticleContainer.cpp
  Source/Utils/ParticleUtils.H
  Source/Utils/ParticleUtils.cpp
  Source/ablastr/particles/IndexHandling.H
  Source/ablastr/particles/ParticleMoments.H
Labels: bug, backend: cuda

#4654 AMReX: Latest `development`
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party
