Repository BLAST-WarpX/warpx, pull requests merged in 2024-04, with the labels that each got.

#4814 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
Labels: component: third party

#4684 Clang tidy CI test: add several clang-analyzer-* checks to clang tidy CI test
  .clang-tidy
  Source/BoundaryConditions/PML.cpp
  Source/BoundaryConditions/PML_RZ.cpp
  Source/BoundaryConditions/WarpXFieldBoundaries.cpp
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/CellCenterFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/JFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/JdispFunctor.cpp
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/ReducedDiags/ChargeOnEB.cpp
  Source/Diagnostics/ReducedDiags/ColliderRelevant.cpp
  Source/Diagnostics/ReducedDiags/FieldEnergy.cpp
  Source/Diagnostics/ReducedDiags/FieldMaximum.cpp
  Source/Diagnostics/ReducedDiags/FieldMomentum.cpp
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
  Source/Diagnostics/ReducedDiags/FieldReduction.H
  Source/Diagnostics/ReducedDiags/LoadBalanceCosts.cpp
  Source/Diagnostics/ReducedDiags/ParticleExtrema.cpp
  Source/Diagnostics/SliceDiagnostic.cpp
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.cpp
  Source/Parallelization/GuardCellManager.cpp
  Source/Parallelization/WarpXComm_K.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/WarpX.H
  Source/WarpX.cpp
  Source/ablastr/parallelization/MPIInitHelpers.H
  Source/ablastr/parallelization/MPIInitHelpers.cpp
Labels: component: tests, cleaning

#4809 Doc: Perlmutter Update
  Tools/machines/perlmutter-nersc/install_cpu_dependencies.sh
  Tools/machines/perlmutter-nersc/install_gpu_dependencies.sh
  Tools/machines/perlmutter-nersc/perlmutter_cpu_warpx.profile.example
  Tools/machines/perlmutter-nersc/perlmutter_gpu_warpx.profile.example
Labels: component: documentation, install, component: third party, machine / system

#4762 updated docs about focal distance
  Docs/source/refs.bib
  Docs/source/usage/parameters.rst
Labels: component: documentation

#4648 Implement Poisson solver based on integrated Green functions
  Docs/source/refs.bib
  Docs/source/usage/parameters.rst
  Examples/Tests/openbc_poisson_solver/analysis.py
  Examples/Tests/openbc_poisson_solver/inputs_3d
  Regression/Checksum/benchmarks_json/openbc_poisson_solver.json
  Regression/WarpX-tests.ini
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Utils/WarpXAlgorithmSelection.H
  Source/Utils/WarpXAlgorithmSelection.cpp
  Source/Utils/WarpXUtil.cpp
  Source/WarpX.H
  Source/WarpX.cpp
  Source/ablastr/CMakeLists.txt
  Source/ablastr/Make.package
  Source/ablastr/fields/CMakeLists.txt
  Source/ablastr/fields/IntegratedGreenFunctionSolver.H
  Source/ablastr/fields/IntegratedGreenFunctionSolver.cpp
  Source/ablastr/fields/Make.package
  Source/ablastr/fields/PoissonSolver.H
  Source/ablastr/math/fft/WrapCuFFT.cpp
Labels: component: electrostatic

#4821 Fix: ABLASTR FFT Poisson Solver
  Source/ablastr/fields/PoissonSolver.H
Labels: bug, component: electrostatic

#4827 Restart Bug fix for BTD
  Source/Diagnostics/BTDiagnostics.H
Labels: bug, bug: affects latest release, component: diagnostics, component: checkpoint/restart, component: boosted frame

#4824 Release 24.04
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#4829 Fix outdated element-wise comparison based assertions
  Source/Parallelization/WarpXComm.cpp
  Source/ablastr/coarsen/sample.cpp
  Source/ablastr/particles/DepositCharge.H
Labels: bug: affects latest release

#4830 Fix out of bounds memory access in `HybridPICModel::GetCurrentExternal`
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
Labels: bug, bug: affects latest release, component: fluid-ohm

#4834 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  Source/Utils/Parser/ParserUtils.cpp
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
Labels: component: third party

#4836 HPC3 (UCI): Fix ADIOS2 HDF5 Build
  Tools/machines/hpc3-uci/install_gpu_dependencies.sh
Labels: bug, install, component: third party, machine / system

#4599 Output the potential phi on the macroparticles
  Docs/source/usage/parameters.rst
  Examples/Tests/electrostatic_sphere/analysis_electrostatic_sphere.py
  Examples/Tests/electrostatic_sphere/inputs_3d
  Examples/Tests/electrostatic_sphere/inputs_rz
  Regression/WarpX-tests.ini
  Source/Diagnostics/ParticleDiag/ParticleDiag.H
  Source/Diagnostics/ParticleDiag/ParticleDiag.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Particles/ParticleIO.H
Labels: component: openPMD, component: diagnostics

#4771 Remove calls to WarpX::GetInstance() in PEC class and cleaning
  Source/BoundaryConditions/PML.H
  Source/BoundaryConditions/PML_RZ.H
  Source/BoundaryConditions/PML_fwd.H
  Source/BoundaryConditions/WarpXFieldBoundaries.cpp
  Source/BoundaryConditions/WarpX_PEC.H
  Source/BoundaryConditions/WarpX_PEC.cpp
  Source/FieldSolver/FiniteDifferenceSolver/ApplySilverMuellerBoundary.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.H
  Source/Utils/WarpXAlgorithmSelection.H
  Source/Utils/WarpXAlgorithmSelection.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#4839 Refactor output of phi on the particles
  Source/Diagnostics/ParticleIO.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Particles/ParticleIO.H
Labels: cleaning, component: diagnostics

#4823 Filter `rho`, when using relativistic electrostatic solver
  Examples/Tests/openbc_poisson_solver/inputs_3d
  Examples/Tests/relativistic_space_charge_initialization/inputs_3d
  Examples/Tests/space_charge_initialization/inputs_3d
  Regression/Checksum/benchmarks_json/BeamBeamCollision.json
  Regression/Checksum/benchmarks_json/ElectrostaticSphere.json
  Regression/Checksum/benchmarks_json/ElectrostaticSphereRelNodal.json
  Regression/Checksum/benchmarks_json/NodalElectrostaticSolver.json
  Regression/Checksum/benchmarks_json/openbc_poisson_solver.json
  Regression/Checksum/benchmarks_json/relativistic_space_charge_initialization.json
  Regression/Checksum/benchmarks_json/space_charge_initialization.json
  Regression/Checksum/benchmarks_json/space_charge_initialization_2d.json
  Source/FieldSolver/ElectrostaticSolver.cpp
Labels: bug, component: electrostatic, bug: affects latest release

#4831 Fix out of bounds access to `distance_to_eb`
  Source/Particles/WarpXParticleContainer.cpp
Labels: bug, bug: affects latest release, component: boundary

#4810 Doc: LUMI (CSC) Update
  Docs/source/install/hpc/lumi.rst
  Tools/machines/lumi-csc/install_dependencies.sh
  Tools/machines/lumi-csc/lumi.sbatch
  Tools/machines/lumi-csc/lumi_warpx.profile.example
Labels: component: documentation, machine / system

#4844 pybind11: v2.12.0
  cmake/dependencies/pybind11.cmake
Labels: component: third party, component: Python

#4848 Add ohms law hybrid multifab redistribution
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/WarpXRegrid.cpp
Labels: enhancement, component: parallelization, component: load balancing, component: fluid-ohm, component: initialization

#4857 Set OpenMP threads manually on Perlmutter nodes
  Tools/machines/perlmutter-nersc/perlmutter_cpu.sbatch
  Tools/machines/perlmutter-nersc/perlmutter_gpu.sbatch
Labels: component: documentation, machine / system

#4858 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
Labels: component: third party

#4577 Optimizing GPU acceleration of binary collision algorithms.
  Examples/Physics_applications/capacitive_discharge/analysis_dsmc.py
  Examples/Tests/nuclear_fusion/inputs_deuterium_tritium_3d
  Regression/Checksum/benchmarks_json/Deuterium_Deuterium_Fusion_3D.json
  Regression/Checksum/benchmarks_json/Deuterium_Deuterium_Fusion_3D_intraspecies.json
  Regression/Checksum/benchmarks_json/Deuterium_Tritium_Fusion_3D.json
  Regression/Checksum/benchmarks_json/Deuterium_Tritium_Fusion_RZ.json
  Regression/Checksum/benchmarks_json/Proton_Boron_Fusion_2D.json
  Regression/Checksum/benchmarks_json/Proton_Boron_Fusion_3D.json
  Regression/Checksum/benchmarks_json/Python_dsmc_1d.json
  Regression/Checksum/benchmarks_json/collisionISO.json
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
  Source/Particles/Collision/BinaryCollision/Coulomb/ElasticCollisionPerez.H
  Source/Particles/Collision/BinaryCollision/Coulomb/PairWiseCoulombCollisionFunc.H
  Source/Particles/Collision/BinaryCollision/DSMC/DSMCFunc.H
  Source/Particles/Collision/BinaryCollision/DSMC/SplitAndScatterFunc.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/NuclearFusionFunc.H
  Source/Particles/Collision/BinaryCollision/ParticleCreationFunc.H
Labels: Performance optimization, component: collisions

#4850 Add thermal boundary specification to picmi
  Python/pywarpx/picmi.py
Labels: component: PICMI

#4870 Update pyAMReX
  cmake/dependencies/pyAMReX.cmake
Labels: component: third party, component: Python

#4868 Add function to set value of `do_not_push`
  Source/Particles/WarpXParticleContainer.H
  Source/Python/Particles/WarpXParticleContainer.cpp
Labels: enhancement

#4882 Downgrade Reg Tests
  run_test.sh
Labels: bug, component: tests, component: third party

#4877 Remove unnecessary include of WarpX.H in "ParticleCreationFunc.H"
  Source/Particles/Collision/BinaryCollision/ParticleCreationFunc.H
Labels: cleaning

#4878 Ensure that only necessary headers are included in FieldAccessorFunctors.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/FieldAccessorFunctors.H
Labels: cleaning

#4879 Remove unnecessary include "WarpX.H" from FlushFormat.H
  Source/Diagnostics/FlushFormats/FlushFormat.H
Labels: cleaning

#4884 Further downgrade regression_testing
  run_test.sh
Labels: bug, component: tests, component: third party, bug: affects latest release

#4859 DepositCharge: Component 1 Allocated?
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#4881 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  run_test.sh
Labels: component: third party

#4852 Reorder particle boundary handling and call to `Redistribute`
  Source/EmbeddedBoundary/ParticleScraper.H
  Source/Evolve/WarpXEvolve.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/ParticleBoundaryBuffer.H
  Source/Particles/ParticleBoundaryBuffer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
Labels: component: parallelization, component: boundary

#4887 Fix macOS CI failure
  .github/workflows/macos.yml
Labels: bug, component: tests, component: third party

#4820 Implement grid based merging algorithm
  Docs/source/refs.bib
  Docs/source/usage/parameters.rst
  Examples/Tests/resampling/inputs_1d_velocity_coincidence_thinning
  Examples/Tests/resampling/inputs_leveling_thinning
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/resample_velocity_coincidence_thinning.json
  Regression/WarpX-tests.ini
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Resampling/CMakeLists.txt
  Source/Particles/Resampling/LevelingThinning.H
  Source/Particles/Resampling/LevelingThinning.cpp
  Source/Particles/Resampling/Make.package
  Source/Particles/Resampling/Resampling.cpp
  Source/Particles/Resampling/VelocityCoincidenceThinning.H
  Source/Particles/Resampling/VelocityCoincidenceThinning.cpp
Labels: enhancement, changes input scripts / defaults

#4874 Remove "friend class PML" from WarpX class
  Source/BoundaryConditions/PML.H
  Source/BoundaryConditions/PML.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#4875 Move FieldType enum from WarpX.H into a separate header
  Source/BoundaryConditions/PML.cpp
  Source/BoundaryConditions/PML_RZ.cpp
  Source/BoundaryConditions/WarpXFieldBoundaries.cpp
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/ComputeDiagFunctors/JFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/JdispFunctor.cpp
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/ParticleIO.cpp
  Source/Diagnostics/ReducedDiags/ChargeOnEB.cpp
  Source/Diagnostics/ReducedDiags/ColliderRelevant.cpp
  Source/Diagnostics/ReducedDiags/FieldEnergy.cpp
  Source/Diagnostics/ReducedDiags/FieldMaximum.cpp
  Source/Diagnostics/ReducedDiags/FieldMomentum.cpp
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
  Source/Diagnostics/ReducedDiags/FieldReduction.H
  Source/Diagnostics/ReducedDiags/LoadBalanceCosts.cpp
  Source/Diagnostics/ReducedDiags/ParticleExtrema.cpp
  Source/Diagnostics/SliceDiagnostic.cpp
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/FieldSolver/Fields.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.cpp
  Source/Particles/MultiParticleContainer.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#4873 Remove call to WarpX::GetInstance() from FilterCreateTransformFromFAB.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/ParticleCreation/FilterCreateTransformFromFAB.H
Labels: cleaning

#4872 Remove calls to WarpX::GetInstance() from MacroscopicProperties.cpp
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.H
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.cpp
  Source/Initialization/WarpXInitData.cpp
Labels: cleaning

#4885 TNSA Example: Link Domain Decomposition
  Docs/source/usage/workflows/domain_decomposition.rst
  Examples/Physics_applications/laser_ion/README.rst
Labels: component: documentation, component: tests

#4890 Fix failing `development` builds
  Source/Initialization/WarpXInitData.cpp
Labels: bug

#4869 Great Lakes Cluster (UMich)
  Docs/source/install/hpc.rst
  Docs/source/install/hpc/greatlakes.rst
  Tools/machines/greatlakes-umich/greatlakes_v100.sbatch
  Tools/machines/greatlakes-umich/greatlakes_v100_warpx.profile.example
  Tools/machines/greatlakes-umich/install_v100_dependencies.sh
Labels: component: documentation, machine / system

#4743 Open Governance Model
  Docs/source/governance.rst
  Docs/source/index.rst
  GOVERNANCE.rst
Labels: component: documentation

#4847 openPMD-api: 0.15.2
  .github/workflows/dependencies/icc.sh
  Docs/source/install/cmake.rst
  Docs/source/usage/parameters.rst
  cmake/dependencies/openPMD.cmake
Labels: component: openPMD, component: third party

#4895 Add two missing includes (found with iwyu)
  Source/Diagnostics/OpenPMDHelpFunction.cpp
  Source/Initialization/WarpXAMReXInit.cpp
Labels: cleaning

#4902 `isort`: First Party Modules
  Docs/source/usage/workflows/ml_materials/run_warpx_training.py
  Examples/Physics_applications/capacitive_discharge/PICMI_inputs_1d.py
  Examples/Physics_applications/capacitive_discharge/PICMI_inputs_2d.py
  Examples/Physics_applications/spacecraft_charging/PICMI_inputs_rz.py
  Examples/Tests/embedded_boundary_python_api/PICMI_inputs_EB_API.py
  Examples/Tests/langmuir/PICMI_inputs_rz.py
  Examples/Tests/magnetostatic_eb/PICMI_inputs_3d.py
  Examples/Tests/magnetostatic_eb/PICMI_inputs_rz.py
  Examples/Tests/ohm_solver_EM_modes/PICMI_inputs.py
  Examples/Tests/ohm_solver_EM_modes/PICMI_inputs_rz.py
  Examples/Tests/ohm_solver_EM_modes/analysis.py
  Examples/Tests/ohm_solver_EM_modes/analysis_rz.py
  Examples/Tests/ohm_solver_ion_Landau_damping/PICMI_inputs.py
  Examples/Tests/ohm_solver_ion_Landau_damping/analysis.py
  Examples/Tests/ohm_solver_ion_beam_instability/PICMI_inputs.py
  Examples/Tests/ohm_solver_ion_beam_instability/analysis.py
  Examples/Tests/ohm_solver_magnetic_reconnection/PICMI_inputs.py
  Examples/Tests/particle_boundary_interaction/PICMI_inputs_rz.py
  Examples/Tests/particle_boundary_scrape/PICMI_inputs_scrape.py
  Examples/Tests/particle_data_python/PICMI_inputs_2d.py
  Examples/Tests/particle_data_python/PICMI_inputs_prev_pos_2d.py
  Examples/Tests/pass_mpi_communicator/PICMI_inputs_2d.py
  Examples/Tests/python_wrappers/PICMI_inputs_2d.py
  Examples/Tests/restart/PICMI_inputs_id_cpu_read.py
  Examples/Tests/restart/PICMI_inputs_runtime_component_analyze.py
  Python/pywarpx/picmi.py
  pyproject.toml
Labels: bug, component: tests, component: Python

#4904 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
Labels: component: third party

#4905 Doc: Great Lakes ADIOS2 Update
  Tools/machines/greatlakes-umich/install_v100_dependencies.sh
Labels: component: documentation, machine / system
