Repository BLAST-WarpX/warpx, pull requests merged in 2024-05, with the labels that each got.

#4886 Add option for Cartesian velocity grid with `VelocityCoincidenceThinning`
  Python/pywarpx/picmi.py
  Source/Particles/Resampling/VelocityCoincidenceThinning.H
  Source/Particles/Resampling/VelocityCoincidenceThinning.cpp
Labels: enhancement

#4907 Fix Python installation instructions on Perlmutter
  Docs/source/install/hpc/perlmutter.rst
Labels: machine / system

#4901 Make do_current_centering a regular member variable of the WarpX class
  Source/Evolve/WarpXEvolve.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#4919 Add CI test for velocity coincidence thinning
  Examples/Tests/resampling/inputs_1d_velocity_coincidence_thinning_cartesian
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/resample_velocity_coincidence_thinning_cartesian.json
  Regression/WarpX-tests.ini
Labels: component: tests, component: PICMI

#4924 Amend Notices for Non-Endorsement
  NOTICE.txt
  README.md
Labels: component: documentation

#4914 Diagnostics: Fix Position Selection
  Docs/source/usage/parameters.rst
  Examples/Physics_applications/laser_acceleration/inputs_rz
  Examples/Physics_applications/uniform_plasma/inputs_3d
  Examples/Tests/Implicit/inputs_1d
  Examples/Tests/Implicit/inputs_1d_semiimplicit
  Examples/Tests/Implicit/inputs_vandb_2d
  Examples/Tests/electrostatic_sphere/inputs_rz
  Examples/Tests/langmuir/inputs_3d
  Examples/Tests/photon_pusher/inputs_3d
  Examples/Tests/plasma_lens/inputs_3d
  Examples/Tests/plasma_lens/inputs_boosted_3d
  Examples/Tests/plasma_lens/inputs_lattice_3d
  Examples/Tests/plasma_lens/inputs_short_3d
  Examples/Tests/qed/breit_wheeler/inputs_2d
  Examples/Tests/qed/breit_wheeler/inputs_3d
  Examples/Tests/qed/quantum_synchrotron/inputs_2d
  Examples/Tests/qed/quantum_synchrotron/inputs_3d
  Regression/WarpX-tests.ini
  Source/Diagnostics/ParticleDiag/ParticleDiag.cpp
  Source/Diagnostics/WarpXOpenPMD.H
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: bug, component: openPMD, bug: affects latest release, component: diagnostics

#4916 Resetting charge buffers to zero.
  Examples/Tests/electrostatic_sphere/analysis_electrostatic_sphere.py
  Regression/Checksum/benchmarks_json/ElectrostaticSphereLabFrame_MR_emass_10.json
  Regression/WarpX-tests.ini
  Source/FieldSolver/ElectrostaticSolver.cpp
Labels: bug, component: mesh refinement, component: electrostatic, bug: affects latest release

#4927 Update hip installation script for CI
  .github/workflows/dependencies/hip.sh
Labels: component: tests, backend: hip, workaround

#4930 `ElectrostaticSphereLabFrame_MR_emass_10`: +Positions
  Regression/WarpX-tests.ini
Labels: component: tests

#4846 ablastr::particles::compute_weights : implement 1D and use template parameter to specify if field is nodal
  Source/Diagnostics/ParticleIO.cpp
  Source/EmbeddedBoundary/ParticleScraper.H
  Source/Particles/ParticleBoundaryBuffer.cpp
  Source/ablastr/particles/NodalFieldGather.H
Labels: bug, cleaning, bug: affects latest release, component: ABLASTR

#4926 Small optimization in ParticleReductionFunctor
  Source/Diagnostics/ComputeDiagFunctors/ParticleReductionFunctor.cpp
Labels: Performance optimization, component: diagnostics

#4921 Code clean-up for binary collisions
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
  Source/Particles/Collision/BinaryCollision/BinaryCollisionUtils.H
  Source/Particles/Collision/BinaryCollision/DSMC/SplitAndScatterFunc.H
  Source/Particles/Collision/BinaryCollision/ParticleCreationFunc.H
Labels: cleaning, component: collisions

#4928 Release 24.05
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  Python/setup.py
  Regression/Checksum/benchmarks_json/Python_restart_eb.json
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#4929 LICENSE.txt: Wrap to 80 Characters
  LICENSE.txt
Labels: component: documentation

#4377 Updated proton-boron cross section
  Examples/Tests/nuclear_fusion/analysis_proton_boron_fusion.py
  Regression/Checksum/benchmarks_json/Proton_Boron_Fusion_2D.json
  Regression/Checksum/benchmarks_json/Proton_Boron_Fusion_3D.json
  Source/Particles/Collision/BinaryCollision/NuclearFusion/ProtonBoronFusionCrossSection.H
Labels: component: collisions

#4932 Fix two race conditions found with thread sanitizer
  Source/BoundaryConditions/WarpX_PEC.cpp
  Source/Particles/PhysicalParticleContainer.cpp
Labels: bug, backend: openmp, bug: affects latest release

#4938 Ensure compilation with double precision particles for DSMC collisions
  Source/Particles/Collision/BinaryCollision/DSMC/DSMCFunc.cpp
Labels: component: collisions

#4940 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
Labels: component: third party

#4941 Promote DSMC calculations to double precision to allow use with single-precision particles
  Source/Particles/Collision/BinaryCollision/BinaryCollisionUtils.H
  Source/Particles/Collision/BinaryCollision/DSMC/DSMCFunc.cpp
Labels: component: collisions

#4955 Make particle IDs valid in BoundaryScraping
  Examples/Tests/scraping/analysis_rz.py
  Source/Particles/ParticleBoundaryBuffer.cpp
Labels: bug, bug: affects latest release, component: boundary

#4889 Profiler: use amrex logic for device synchronization instead of custom solution
  Source/Diagnostics/ParticleIO.cpp
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/FieldSolver/SpectralSolver/SpectralSolver.cpp
  Source/Filter/Filter.cpp
  Source/Initialization/WarpXAMReXInit.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Particles/LaserParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/Utils/WarpXProfilerWrapper.H
  Source/WarpX.cpp
  Source/ablastr/fields/PoissonSolver.H
  Source/ablastr/math/fft/WrapCuFFT.cpp
  Source/ablastr/particles/DepositCharge.H
  Source/ablastr/profiler/ProfilerWrapper.H
Labels: cleaning, component: ABLASTR

#4947 Make RemakeMultiFab a lambda function inside WarpX::RemakeLevel
  Source/Parallelization/WarpXRegrid.cpp
Labels: cleaning

#4957 Fix: `MPIInitHelpers.cpp` Macro
  Source/ablastr/parallelization/MPIInitHelpers.cpp
Labels: bug, backend: openmp, bug: affects latest release

#4951 Picmi: allow different `random_fraction` for different species
  Python/pywarpx/picmi.py
Labels: component: PICMI, component: diagnostics

#4956 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
Labels: component: third party

#4962 Document PICMI function `LoadInitialField`
  Docs/source/usage/python.rst
Labels: component: documentation, component: Python
