Repository BLAST-WarpX/warpx, pull requests merged in 2024-08, with the labels that each got.

#5106 ABLASTR: Pass `GridType` instead of Global
  Source/BoundaryConditions/PML.H
  Source/BoundaryConditions/PML.cpp
  Source/FieldSolver/ElectrostaticSolver.cpp
  Source/FieldSolver/FiniteDifferenceSolver/ComputeDivE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveBPML.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmComoving.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmComoving.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmFirstOrder.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmFirstOrder.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmGalileanRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmGalileanRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmJConstantInTime.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmJConstantInTime.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmJLinearInTime.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmJLinearInTime.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPml.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPml.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPmlRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmPmlRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/PsatdAlgorithmRZ.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithm.H
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithm.cpp
  Source/FieldSolver/SpectralSolver/SpectralAlgorithms/SpectralBaseAlgorithmRZ.H
  Source/FieldSolver/SpectralSolver/SpectralKSpace.H
  Source/FieldSolver/SpectralSolver/SpectralKSpace.cpp
  Source/FieldSolver/SpectralSolver/SpectralSolver.H
  Source/FieldSolver/SpectralSolver/SpectralSolver.cpp
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ.H
  Source/FieldSolver/SpectralSolver/SpectralSolverRZ.cpp
  Source/Parallelization/GuardCellManager.H
  Source/Parallelization/GuardCellManager.cpp
  Source/Utils/WarpXAlgorithmSelection.H
  Source/Utils/WarpXAlgorithmSelection.cpp
  Source/WarpX.H
  Source/WarpX.cpp
  Source/ablastr/fields/PoissonSolver.H
  Source/ablastr/utils/Enums.H
Labels: bug, component: ABLASTR

#5101 PICMI interface for implicit solvers
  Docs/source/usage/python.rst
  Examples/Tests/Implicit/PICMI_inputs_vandb_jfnk_2d.py
  Python/pywarpx/WarpX.py
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/ThetaImplicitJFNK_VandB_2d_PICMI.json
  Regression/WarpX-tests.ini
Labels: component: PICMI, component: implicit solvers

#5104 Treat external field types consistently
  Source/Evolve/WarpXEvolve.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: bug, component: electrostatic

#5114 Fix bug in `PrintMainPICparameters` (uninitialized values)
  Source/WarpX.H
  Source/WarpX.cpp
Labels: bug, bug: affects latest release, component: core

#5117 Temporarily disable `openbc_poisson_solver`
  Examples/Tests/openbc_poisson_solver/README
  Regression/WarpX-tests.ini
Labels: component: tests, workaround

#5110 CI: Clean out Pip Caches
  Examples/Tests/openbc_poisson_solver/inputs_3d
  Regression/Checksum/benchmarks_json/collisionXYZ.json
  Regression/WarpX-tests.ini
  run_test.sh
Labels: component: tests, component: third party

#5119 Fix: `species_type` init memory
  Source/Particles/WarpXParticleContainer.H
Labels: bug, bug: affects latest release, component: core

#5112 AnyFFT: 1D Support
  Source/ablastr/math/fft/WrapCuFFT.cpp
  Source/ablastr/math/fft/WrapFFTW.cpp
Labels: component: spectral, component: ABLASTR

#5120 CI: clean test dirs, reset `collisionXZ` checksums
  .azure-pipelines.yml
  Regression/Checksum/benchmarks_json/collisionXZ.json
  run_test.sh
Labels: bug, component: tests

#5108 Add density min and max arguments to `picmi.AnalyticDistribution`
  Python/pywarpx/picmi.py
Labels: component: PICMI

#5105 Checksum Reset via Env Variable
  Docs/source/developers/checksum.rst
  Regression/Checksum/checksumAPI.py
Labels: component: tests

#5073 Make quantum_xi_c2 a non-static member variable of the WarpX class
  Source/FieldSolver/WarpX_QED_Field_Pushers.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#5125 Release 24.08
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#5121 CI: heFFTe for tests
  .azure-pipelines.yml
  .github/workflows/cuda.yml
  .github/workflows/dependencies/hip.sh
  .github/workflows/hip.yml
Labels: component: spectral, component: tests

#4893 Move PerformanceHints from WarpX class into anonymous namespace in WarpXInitData.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
Labels: cleaning

#5129 CI: update option name to clean test dirs
  run_test.sh
Labels: bug, component: tests, bug: affects latest release

#5134 Remove obsolete USE_WARPX_PSATD
  Source/FieldSolver/ImplicitSolvers/WarpXImplicitOps.cpp
Labels: cleaning

#5132 CI: fix fluctuations in `collisionXZ` checksums
  Examples/Tests/collision/analysis_collision_2d.py
  Examples/Tests/collision/analysis_collision_3d.py
Labels: bug, component: tests, bug: affects latest release, component: collisions

#5127 Add oneMKL FFT to AnyFFT wrapper for SYCL backend
  Source/Make.WarpX
  Source/ablastr/math/fft/AnyFFT.H
  Source/ablastr/math/fft/CMakeLists.txt
  Source/ablastr/math/fft/Make.package
  Source/ablastr/math/fft/WrapMklFFT.cpp
Labels: component: spectral, backend: dpc++

#5103 EB: Assert that its used
  .github/workflows/intel.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
  Regression/WarpX-tests.ini
  Source/EmbeddedBoundary/CMakeLists.txt
  Source/EmbeddedBoundary/Enabled.H
  Source/EmbeddedBoundary/Enabled.cpp
  Source/EmbeddedBoundary/Make.package
  Source/WarpX.cpp
Labels: bug, bug: affects latest release, component: boundary

#5130 `setup.py`: More Unique `build_base`
  setup.py
Labels: bug, install, bug: affects latest release, component: Python

#5138 Doc: `apt` w/ `python3-dev`
  Docs/source/install/dependencies.rst
Labels: component: documentation, machine / system

#5147 `collisionZ` tolerance bump
  Examples/Tests/collision/analysis_collision_1d.py
Labels: component: tests, component: collisions

#5126 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  Source/Parallelization/GuardCellManager.cpp
  Source/Particles/Resampling/VelocityCoincidenceThinning.H
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
Labels: component: third party

#5146 AnyFFT: `multiply`
  Source/ablastr/math/fft/AnyFFT.H
Labels: enhancement, component: spectral, component: ABLASTR

#5142 Tests: `useOMP = 1`
  Regression/WarpX-tests.ini
Labels: cleaning

#5148 potential fix to varying results for collisionXZ and collisionXYZ CI tests
  Examples/Tests/collision/analysis_collision_1d.py
  Examples/Tests/collision/analysis_collision_2d.py
  Examples/Tests/collision/analysis_collision_3d.py
  Examples/Tests/collision/analysis_collision_rz.py
  Regression/Checksum/benchmarks_json/collisionXYZ.json
  Regression/Checksum/benchmarks_json/collisionXZ.json
Labels: bug, component: tests, bug: affects latest release

#5133 Nuclear fusion algorithm modifications
  Regression/Checksum/benchmarks_json/Proton_Boron_Fusion_2D.json
  Regression/Checksum/benchmarks_json/Proton_Boron_Fusion_3D.json
  Source/Particles/Collision/BinaryCollision/NuclearFusion/NuclearFusionFunc.H
  Source/Particles/Collision/BinaryCollision/ParticleCreationFunc.H
Labels: component: collisions

#5124 Python: Errors & Linting
  Docs/source/conf.py
  Docs/source/index.rst
  Docs/source/maintenance/performance_tests.rst
  Docs/source/usage/workflows/ml_materials/train.py
  Docs/source/usage/workflows/ml_materials/visualize.py
  Examples/Tests/AcceleratorLattice/analysis.py
  Examples/Tests/btd_rz/analysis_BTD_laser_antenna.py
  Examples/Tests/collision/analysis_collision_1d.py
  Examples/Tests/electrostatic_sphere/analysis_electrostatic_sphere.py
  Examples/Tests/laser_injection_from_file/analysis_from_RZ_file.py
  Examples/Tests/nci_fdtd_stability/analysis_ncicorr.py
  Examples/Tests/nuclear_fusion/analysis_two_product_fusion.py
  Examples/Tests/ohm_solver_EM_modes/PICMI_inputs.py
  Examples/Tests/ohm_solver_EM_modes/PICMI_inputs_rz.py
  Examples/Tests/ohm_solver_EM_modes/analysis.py
  Examples/Tests/ohm_solver_EM_modes/analysis_rz.py
  Examples/Tests/ohm_solver_ion_Landau_damping/analysis.py
  Examples/Tests/ohm_solver_ion_beam_instability/analysis.py
  Examples/Tests/ohm_solver_magnetic_reconnection/PICMI_inputs.py
  Examples/Tests/ohm_solver_magnetic_reconnection/analysis.py
  Examples/Tests/photon_pusher/analysis_photon_pusher.py
  Examples/Tests/qed/breit_wheeler/analysis_core.py
  Examples/Tests/qed/quantum_synchrotron/analysis.py
  Examples/Tests/radiation_reaction/test_const_B_analytical/analysis_classicalRR.py
  Examples/Tests/restart/PICMI_inputs_id_cpu_read.py
  Examples/Tests/restart/PICMI_inputs_runtime_component_analyze.py
  Examples/Tests/restart_eb/PICMI_inputs_restart_eb.py
  Python/pywarpx/__init__.py
  Python/pywarpx/_libwarpx.py
  Python/pywarpx/fields.py
  Python/pywarpx/picmi.py
  Regression/WarpX-tests.ini
  Regression/prepare_file_ci.py
  Tools/Algorithms/psatd.ipynb
  Tools/Algorithms/psatd_pml.ipynb
  Tools/Ascent/ascent_replay_warpx.ipynb
  Tools/DevUtils/compare_wx_w_3d.ipynb
  Tools/DevUtils/update_benchmarks_from_azure_output.py
  Tools/PerformanceTests/automated_test_1_uniform_rest_32ppc
  Tools/PerformanceTests/automated_test_2_uniform_rest_1ppc
  Tools/PerformanceTests/automated_test_3_uniform_drift_4ppc
  Tools/PerformanceTests/automated_test_4_labdiags_2ppc
  Tools/PerformanceTests/automated_test_5_loadimbalance
  Tools/PerformanceTests/automated_test_6_output_2ppc
  Tools/PerformanceTests/cori.py
  Tools/PerformanceTests/functions_perftest.py
  Tools/PerformanceTests/performance_log.txt
  Tools/PerformanceTests/run_alltests.py
  Tools/PerformanceTests/run_alltests_1node.py
  Tools/PerformanceTests/run_automated.py
  Tools/PerformanceTests/summit.py
  Tools/PostProcessing/Visualization.ipynb
  Tools/PostProcessing/plot_distribution_mapping.py
  Tools/PostProcessing/plot_nci_growth_rate.ipynb
  Tools/PostProcessing/plot_parallel.py
  Tools/Release/updateAMReX.py
  Tools/Release/updatePICSAR.py
  Tools/Release/updatepyAMReX.py
Labels: cleaning, component: Python

#5152 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
Labels: component: third party

#5135 Update DSMC reaction weight calculation
  Examples/Physics_applications/capacitive_discharge/PICMI_inputs_1d.py
  Examples/Physics_applications/capacitive_discharge/analysis_dsmc.py
  Regression/Checksum/benchmarks_json/Python_dsmc_1d.json
  Source/Particles/Collision/BinaryCollision/DSMC/DSMCFunc.H
  Source/Particles/Collision/BinaryCollision/DSMC/DSMCFunc.cpp
  Source/Particles/Collision/BinaryCollision/DSMC/SplitAndScatterFunc.H
Labels: enhancement, component: collisions

#5157 Simplify Subtitle
  Docs/source/index.rst
Labels: component: documentation

#5154 Doc: Typos in LXPLUS (CERN)
  Docs/source/install/hpc/lxplus.rst
  Tools/machines/lxplus-cern/lxplus_warpx.profile.example
Labels: component: documentation, machine / system

#5118 Function to get particle cell index.
  Source/Diagnostics/ComputeDiagFunctors/ParticleReductionFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/TemperatureFunctor.cpp
Labels: component: core

#5162 Add callback to write values to external field multifabs
  Python/pywarpx/callbacks.py
  Source/Initialization/WarpXInitData.cpp
Labels: component: Python

#5160 Binary: Append `.HEFFTE`
  cmake/WarpXFunctions.cmake
Labels: component: spectral, install

#5047 Binary-pairing Coulomb collisions: improvements and optimization
  Regression/Checksum/benchmarks_json/collisionISO.json
  Regression/Checksum/benchmarks_json/collisionXZ.json
  Regression/Checksum/benchmarks_json/collisionZ.json
  Source/Particles/Collision/BinaryCollision/Coulomb/ElasticCollisionPerez.H
  Source/Particles/Collision/BinaryCollision/Coulomb/UpdateMomentumPerezElastic.H
Labels: Performance optimization, cleaning, component: collisions

#5167 Increase time limit for clang-tidy
  .github/workflows/clang_tidy.yml
Labels: component: tests

#5158 Fix: heFFTe on Perlmutter GPU
  Tools/machines/perlmutter-nersc/install_gpu_dependencies.sh
Labels: bug, backend: cuda, component: spectral, install, component: third party, machine / system, workaround

#5155 Catalyst2 support
  .github/workflows/insitu.yml
  .github/workflows/source/wrongFileNameInExamples
  CMakeLists.txt
  Docs/source/dataanalysis/catalyst.rst
  Docs/source/dataanalysis/formats.rst
  Docs/source/dataanalysis/paraview.rst
  Docs/source/install/cmake.rst
  Examples/Tests/electrostatic_sphere/catalyst_pipeline.py
  Examples/Tests/ionization/catalyst_pipeline.py
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FlushFormats/CMakeLists.txt
  Source/Diagnostics/FlushFormats/FlushFormatAscent.H
  Source/Diagnostics/FlushFormats/FlushFormatAscent.cpp
  Source/Diagnostics/FlushFormats/FlushFormatCatalyst.H
  Source/Diagnostics/FlushFormats/FlushFormatCatalyst.cpp
  Source/Diagnostics/FlushFormats/FlushFormatInSitu.H
  Source/Diagnostics/FlushFormats/FlushFormatInSitu.cpp
  Source/Diagnostics/FlushFormats/Make.package
  Source/Diagnostics/FullDiagnostics.cpp
  WarpXConfig.cmake
  cmake/WarpXFunctions.cmake
  cmake/dependencies/AMReX.cmake
Labels: component: diagnostics

#5172 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
Labels: component: third party

#5170 minor adjustments to comments in implicit solver classes
  Source/FieldSolver/ImplicitSolvers/SemiImplicitEM.cpp
  Source/FieldSolver/ImplicitSolvers/ThetaImplicitEM.cpp
Labels: cleaning, component: implicit solvers

#5174 Remove broken links from performance tests
  Examples/Tests/performance_tests/automated_test_1_uniform_rest_32ppc
  Examples/Tests/performance_tests/automated_test_2_uniform_rest_1ppc
  Examples/Tests/performance_tests/automated_test_3_uniform_drift_4ppc
  Examples/Tests/performance_tests/automated_test_4_labdiags_2ppc
  Examples/Tests/performance_tests/automated_test_5_loadimbalance
  Examples/Tests/performance_tests/automated_test_6_output_2ppc
Labels: bug, component: tests, cleaning

#5161 Add differential luminosity reduced diagnostic
  Docs/source/usage/parameters.rst
  Examples/Tests/diff_lumi_diag/analysis.py
  Examples/Tests/diff_lumi_diag/inputs
  Regression/Checksum/benchmarks_json/diff_lumi_diag.json
  Regression/WarpX-tests.ini
  Source/Diagnostics/ReducedDiags/CMakeLists.txt
  Source/Diagnostics/ReducedDiags/DifferentialLuminosity.H
  Source/Diagnostics/ReducedDiags/DifferentialLuminosity.cpp
  Source/Diagnostics/ReducedDiags/Make.package
  Source/Diagnostics/ReducedDiags/MultiReducedDiags.cpp
Labels: component: diagnostics

#5178 Clean up call to apply_boundary
  Source/Particles/ParticleBoundaries_K.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: cleaning

#4965 Simplify overwrite_amrex_parser_defaults WarpXAMReXInit.cpp
  Source/Initialization/WarpXAMReXInit.cpp
Labels: cleaning

#5177 remove multiplication of vcms/vcms in UpdateMomentumPerezElastic
  Regression/Checksum/benchmarks_json/collisionXZ.json
  Regression/Checksum/benchmarks_json/collisionZ.json
  Source/Particles/Collision/BinaryCollision/Coulomb/UpdateMomentumPerezElastic.H
Labels: cleaning, component: collisions

#5109 Add scraping boundary diagnostics with PICMI
  Docs/requirements.txt
  Examples/Physics_applications/spacecraft_charging/PICMI_inputs_rz.py
  Python/pywarpx/picmi.py
  Python/setup.py
  Tools/machines/karolina-it4i/install_dependencies.sh
  requirements.txt
Labels: component: PICMI, component: diagnostics

#5184 Modernize usage of type traits in WarpX
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/ParticleCreation/FilterCopyTransform.H
  Source/Particles/ParticleCreation/FilterCreateTransformFromFAB.H
  Source/Utils/Algorithms/IsIn.H
Labels: cleaning

#5181 UB sanitizer CI test: bump clang version from 15 to 17
  .github/workflows/clang_sanitizers.yml
Labels: component: tests

#4909 warpx.roundrobin_sfc: A runtime parameter to control distribution mapping
  Docs/source/usage/parameters.rst
  Python/pywarpx/picmi.py
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: load balancing, component: initialization

#5187 Doc: Remove Cori (NERSC) & Spock (OLCF)
  Docs/source/install/hpc.rst
  Docs/source/install/hpc/spock.rst
  Tools/machines/cori-nersc/cori_gpu.sbatch
  Tools/machines/cori-nersc/cori_haswell.sbatch
  Tools/machines/cori-nersc/cori_knl.sbatch
  Tools/machines/cori-nersc/gpu_warpx.profile.example
  Tools/machines/cori-nersc/haswell_warpx.profile.example
  Tools/machines/cori-nersc/knl_warpx.profile.example
  Tools/machines/spock-olcf/spock_mi100.sbatch
  Tools/machines/spock-olcf/spock_warpx.profile.example
Labels: component: documentation, cleaning, machine / system

#5185 Ablastr: make deposit_charge function non-static
  Source/ablastr/particles/DepositCharge.H
Labels: invalid, cleaning, component: ABLASTR

#4944 Add feature projection div cleaner
  .zenodo.json
  Docs/source/usage/parameters.rst
  Examples/Tests/projection_divb_cleaner/PICMI_inputs_3D_pyload.py
  Examples/Tests/projection_divb_cleaner/PICMI_inputs_3d.py
  Examples/Tests/projection_divb_cleaner/analysis_rz.py
  Examples/Tests/projection_divb_cleaner/inputs_rz
  Python/pywarpx/ProjectionDivBCleaner.py
  Python/pywarpx/WarpX.py
  Python/pywarpx/__init__.py
  Python/pywarpx/fields.py
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/Python_ohms_law_solver_magnetic_reconnection_2d.json
  Regression/Checksum/benchmarks_json/Python_projection_divb_cleaner_3d.json
  Regression/Checksum/benchmarks_json/Python_projection_divb_cleaner_callback_3d.json
  Regression/Checksum/benchmarks_json/embedded_boundary_cube.json
  Regression/Checksum/benchmarks_json/embedded_boundary_cube_macroscopic.json
  Regression/Checksum/benchmarks_json/projection_divb_cleaner_rz.json
  Regression/WarpX-tests.ini
  Source/FieldSolver/Fields.H
  Source/Initialization/CMakeLists.txt
  Source/Initialization/DivCleaner/CMakeLists.txt
  Source/Initialization/DivCleaner/Make.package
  Source/Initialization/DivCleaner/ProjectionDivCleaner.H
  Source/Initialization/DivCleaner/ProjectionDivCleaner.cpp
  Source/Initialization/ExternalField.H
  Source/Initialization/ExternalField.cpp
  Source/Initialization/Make.package
  Source/Initialization/WarpXInitData.cpp
  Source/Python/WarpX.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: enhancement, component: initialization

#5197 Express differential luminosity diagnostics in eV
  Docs/source/usage/parameters.rst
  Examples/Tests/diff_lumi_diag/analysis.py
  Examples/Tests/diff_lumi_diag/inputs
  Source/Diagnostics/ReducedDiags/DifferentialLuminosity.cpp
Labels: component: diagnostics

#5171 Generalization of WarpXSolverVec class used by implicit solvers
  Source/FieldSolver/Fields.H
  Source/FieldSolver/ImplicitSolvers/SemiImplicitEM.cpp
  Source/FieldSolver/ImplicitSolvers/ThetaImplicitEM.cpp
  Source/FieldSolver/ImplicitSolvers/WarpXImplicitOps.cpp
  Source/FieldSolver/ImplicitSolvers/WarpXSolverVec.H
  Source/FieldSolver/ImplicitSolvers/WarpXSolverVec.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning, component: implicit solvers
