Repository BLAST-WarpX/warpx, pull requests merged in 2024-06, with the labels that each got.

#4972 Add initialization of extra attribs to picmi
  Examples/Physics_applications/laser_acceleration/PICMI_inputs_3d.py
  Examples/Physics_applications/laser_acceleration/inputs_3d
  Examples/Physics_applications/laser_ion/PICMI_inputs_2d.py
  Examples/Tests/ionization/PICMI_inputs_2d.py
  Examples/Tests/ionization/analysis_ionization.py
  Examples/Tests/ionization/inputs_2d_bf_rt
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/Python_LaserAcceleration.json
  Regression/Checksum/benchmarks_json/Python_LaserIonAcc2d.json
  Regression/Checksum/benchmarks_json/Python_ionization.json
Labels: enhancement, component: tests, component: PICMI

#4942 Add temperature diagnostic
  Docs/source/usage/parameters.rst
  Examples/Tests/collision/inputs_3d
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/collisionXYZ.json
  Source/Diagnostics/ComputeDiagFunctors/CMakeLists.txt
  Source/Diagnostics/ComputeDiagFunctors/Make.package
  Source/Diagnostics/ComputeDiagFunctors/TemperatureFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/TemperatureFunctor.cpp
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.cpp
Labels: enhancement, component: diagnostics

#4973 Cleanup diagnostic dimension macros
  Source/Diagnostics/ReducedDiags/BeamRelevant.cpp
  Source/Diagnostics/ReducedDiags/FieldEnergy.cpp
  Source/Diagnostics/ReducedDiags/FieldMomentum.cpp
  Source/Diagnostics/ReducedDiags/ParticleExtrema.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
Labels: cleaning, component: diagnostics

#4968 Slightly increase tolerance for embedded_circle test
  Examples/Tests/embedded_circle/inputs_2d
Labels: component: tests

#4979 Remove unneeded macros from AllocLevelData
  Source/Parallelization/GuardCellManager.H
  Source/Parallelization/GuardCellManager.cpp
  Source/WarpX.cpp
Labels: cleaning

#4980 Release 24.06
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  Python/setup.py
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
  setup.py
Labels: component: documentation, component: third party

#4964 Simplify main file
  Source/Evolve/WarpXEvolve.cpp
  Source/Initialization/CMakeLists.txt
  Source/Initialization/Make.package
  Source/Initialization/WarpXInit.H
  Source/Initialization/WarpXInit.cpp
  Source/main.cpp
Labels: cleaning

#4983 Fix FieldProbe Check: Particle Shape
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#4986 CMake: heFFTe Support
  CMakeLists.txt
  Docs/source/install/cmake.rst
  Docs/source/install/dependencies.rst
  Docs/source/install/hpc/perlmutter.rst
  Tools/machines/desktop/spack-macos-openmp.yaml
  Tools/machines/desktop/spack-ubuntu-cuda.yaml
  Tools/machines/desktop/spack-ubuntu-openmp.yaml
  Tools/machines/desktop/spack-ubuntu-rocm.yaml
  Tools/machines/perlmutter-nersc/install_cpu_dependencies.sh
  Tools/machines/perlmutter-nersc/install_gpu_dependencies.sh
  Tools/machines/perlmutter-nersc/perlmutter_cpu_warpx.profile.example
  Tools/machines/perlmutter-nersc/perlmutter_gpu_warpx.profile.example
  cmake/WarpXFunctions.cmake
  setup.py
Labels: component: spectral, install

#4999 Resetting collisionXYY Temperature
  Regression/Checksum/benchmarks_json/collisionXYZ.json
Labels: component: tests, component: diagnostics

#4978 Cleanup deposition and gather routines
  Examples/Tests/repelling_particles/analysis_repelling.py
  Regression/Checksum/benchmarks_json/BTD_rz.json
  Regression/Checksum/benchmarks_json/PEC_particle.json
  Regression/Checksum/benchmarks_json/Python_ionization.json
  Regression/Checksum/benchmarks_json/RepellingParticles.json
  Regression/Checksum/benchmarks_json/ionization_boost.json
  Regression/Checksum/benchmarks_json/ionization_lab.json
  Source/AcceleratorLattice/LatticeElementFinder.cpp
  Source/BoundaryConditions/WarpXFieldBoundaries.cpp
  Source/Diagnostics/ReducedDiags/ColliderRelevant.cpp
  Source/Diagnostics/ReducedDiags/FieldEnergy.cpp
  Source/Diagnostics/ReducedDiags/FieldProbe.cpp
  Source/Diagnostics/ReducedDiags/ParticleExtrema.cpp
  Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/Particles/Deposition/ChargeDeposition.H
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/Deposition/SharedDepositionUtils.H
  Source/Particles/ElementaryProcess/Ionization.H
  Source/Particles/ElementaryProcess/Ionization.cpp
  Source/Particles/ElementaryProcess/QEDPairGeneration.H
  Source/Particles/ElementaryProcess/QEDPairGeneration.cpp
  Source/Particles/ElementaryProcess/QEDPhotonEmission.H
  Source/Particles/ElementaryProcess/QEDPhotonEmission.cpp
  Source/Particles/Gather/FieldGather.H
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.cpp
  Source/Utils/WarpXUtil.cpp
  Source/WarpX.H
  Source/WarpX.cpp
  Source/ablastr/particles/DepositCharge.H
Labels: cleaning

#5001 Documentation: fix a typo in parameters.rst
  Docs/source/usage/parameters.rst
Labels: component: documentation

#5004 Doc: Update WarpX Ack Text
  Docs/source/acknowledge_us.rst
Labels: component: documentation

#4998 Doc: Resonant excitation of plasma waves in a plasma channel
  Docs/source/acknowledge_us.rst
  Docs/source/highlights.rst
  Docs/source/refs.bib
Labels: component: documentation

#4991 Warning instead of error for Background MCC
  Source/Particles/Collision/BackgroundMCC/BackgroundMCCCollision.cpp
Labels: component: collisions

#4995 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
Labels: component: third party

#5006 Fix: Perlmutter heFFTe CPU
  Tools/machines/perlmutter-nersc/install_cpu_dependencies.sh
Labels: bug, component: documentation, install, component: third party, machine / system

#5007 Fix ccache for macos
  .github/workflows/macos.yml
Labels: component: tests

#5012 BLAS++: v2024.05.31+
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/HankelTransform.cpp
Labels: bug, backend: cuda, component: spectral, component: third party, bug: affects latest release, backend: hip, geometry: RZ

#5013 Doc: Latest Commit of BLAS++/LAPACK++
  Tools/machines/adastra-cines/adastra_warpx.profile.example
  Tools/machines/adastra-cines/install_dependencies.sh
  Tools/machines/cori-nersc/haswell_warpx.profile.example
  Tools/machines/cori-nersc/knl_warpx.profile.example
  Tools/machines/crusher-olcf/crusher_warpx.profile.example
  Tools/machines/crusher-olcf/install_dependencies.sh
  Tools/machines/frontier-olcf/frontier_warpx.profile.example
  Tools/machines/frontier-olcf/install_dependencies.sh
  Tools/machines/greatlakes-umich/greatlakes_v100_warpx.profile.example
  Tools/machines/greatlakes-umich/install_v100_dependencies.sh
  Tools/machines/hpc3-uci/hpc3_gpu_warpx.profile.example
  Tools/machines/hpc3-uci/install_gpu_dependencies.sh
  Tools/machines/lassen-llnl/install_v100_dependencies.sh
  Tools/machines/lassen-llnl/lassen_v100_warpx.profile.example
  Tools/machines/lassen-llnl/lassen_v100_warpx_toss3.profile.example
  Tools/machines/lawrencium-lbnl/lawrencium_warpx.profile.example
  Tools/machines/leonardo-cineca/install_gpu_dependencies.sh
  Tools/machines/leonardo-cineca/leonardo_gpu_warpx.profile.example
  Tools/machines/lumi-csc/install_dependencies.sh
  Tools/machines/lumi-csc/lumi_warpx.profile.example
  Tools/machines/perlmutter-nersc/install_cpu_dependencies.sh
  Tools/machines/perlmutter-nersc/install_gpu_dependencies.sh
  Tools/machines/perlmutter-nersc/perlmutter_cpu_warpx.profile.example
  Tools/machines/perlmutter-nersc/perlmutter_gpu_warpx.profile.example
  Tools/machines/polaris-alcf/install_gpu_dependencies.sh
  Tools/machines/polaris-alcf/polaris_gpu_warpx.profile.example
  Tools/machines/quartz-llnl/install_dependencies.sh
  Tools/machines/quartz-llnl/quartz_warpx.profile.example
  Tools/machines/summit-olcf/install_gpu_dependencies.sh
  Tools/machines/summit-olcf/summit_warpx.profile.example
Labels: component: documentation, component: third party, machine / system

#5014 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Regression/WarpX-GPU-tests.ini
  Regression/WarpX-tests.ini
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  run_test.sh
Labels: component: third party

#5021 obvious bug fix in ElasticCollisionPerez
  Regression/Checksum/benchmarks_json/collisionISO.json
  Regression/Checksum/benchmarks_json/collisionXYZ.json
  Source/Particles/Collision/BinaryCollision/Coulomb/ElasticCollisionPerez.H
Labels: bug, bug: affects latest release, component: collisions
