Repository BLAST-WarpX/warpx, pull requests merged in 2025-01, with the labels that each got.

#5532 Doc: Wave Attenuation Numerics
  Docs/source/highlights.rst
Labels: component: documentation

#5536 PEC: Fix Uninit Var Warning (GCC)
  Source/BoundaryConditions/PEC_Insulator.cpp
Labels: warning, component: boundary

#5535 Update CMake version for Perlmutter AY25
  Tools/machines/perlmutter-nersc/perlmutter_cpu_warpx.profile.example
  Tools/machines/perlmutter-nersc/perlmutter_gpu_warpx.profile.example
Labels: machine / system

#5540 Remove an unnecessary call to WarpX::GetInstance()
  Source/Parallelization/WarpXRegrid.cpp
Labels: cleaning

#5523 CI: ignore all `.rst` files in the repository
  .azure-pipelines.yml
  .github/workflows/clang_sanitizers.yml
  .github/workflows/clang_tidy.yml
  .github/workflows/cuda.yml
  .github/workflows/hip.yml
  .github/workflows/insitu.yml
  .github/workflows/intel.yml
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
Labels: component: tests

#5522 Docs: fix bugs (broken links, missing examples)
  Docs/source/developers/checksum.rst
  Docs/source/developers/fields.rst
  Docs/source/developers/particles.rst
  Docs/source/install/hpc/dane.rst
  Docs/source/install/hpc/lawrencium.rst
  Docs/source/refs.bib
  Docs/source/theory/multiphysics/collisions.rst
  Docs/source/usage/examples.rst
  Docs/source/usage/examples/thomson_parabola_spectrometer
  Examples/Physics_applications/thomson_parabola_spectrometer/README.rst
Labels: component: documentation

#5361 Python 3.13 Support, 3.8 EOL
  CMakeLists.txt
  Docs/source/developers/gnumake/python.rst
  Docs/source/install/dependencies.rst
  Python/setup.py
  cmake/dependencies/pybind11.cmake
  setup.py
Labels: install, component: third party, component: Python

#5544 Release 25.01
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  Docs/source/maintenance/release.rst
  Python/setup.py
  Tools/Release/releasePR.py
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  setup.py
Labels: component: documentation, component: third party

#5546 Make do_subcycling a private variable of the WarpX class
  Source/Evolve/WarpXComputeDt.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#5548 CMake: ABLASTR FFT AMReX
  cmake/dependencies/AMReX.cmake
Labels: bug, component: spectral, install, component: third party, bug: affects latest release

#5556 Add doxygen documentation regarding `is_igf_2d_slices`
  Source/FieldSolver/ElectrostaticSolvers/ElectrostaticSolver.H
  Source/ablastr/fields/IntegratedGreenFunctionSolver.H
  Source/ablastr/fields/PoissonSolver.H
Labels: component: documentation, component: ABLASTR

#5555 Update differential luminosity test
  Examples/Tests/diff_lumi_diag/inputs_test_3d_diff_lumi_diag_photons
  Regression/Checksum/benchmarks_json/test_3d_diff_lumi_diag_photons.json
Labels: component: tests

#5541 Pass gamma_boost as an argument to AcceleratorLattice and LatticeElementFinder
  Source/AcceleratorLattice/AcceleratorLattice.H
  Source/AcceleratorLattice/AcceleratorLattice.cpp
  Source/AcceleratorLattice/LatticeElementFinder.H
  Source/AcceleratorLattice/LatticeElementFinder.cpp
  Source/Parallelization/WarpXRegrid.cpp
  Source/WarpX.cpp
Labels: cleaning

#5557 Use `amrex::getParticleCell` More
  Source/Diagnostics/ComputeDiagFunctors/ParticleReductionFunctor.cpp
Labels: cleaning, component: diagnostics

#5141 Containerfile
  Tools/machines/perlmutter-nersc/Containerfile
Labels: install, machine / system

#5570 Doc: Update Frontier
  Tools/machines/frontier-olcf/frontier_warpx.profile.example
  Tools/machines/frontier-olcf/install_dependencies.sh
Labels: component: documentation, backend: hip, machine / system

#5489 Fix restart for implicit simulations
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp
  Source/Diagnostics/WarpXIO.cpp
  Source/FieldSolver/ImplicitSolvers/ImplicitSolver.H
  Source/FieldSolver/ImplicitSolvers/ImplicitSolver.cpp
  Source/Initialization/WarpXInitData.cpp
Labels: bug, bug: affects latest release

#5575 CI: install clang dependencies directly from LLVM
  .github/workflows/clang_sanitizers.yml
  .github/workflows/clang_tidy.yml
  .github/workflows/dependencies/clang.sh
  .github/workflows/dependencies/clang15.sh
Labels: component: tests

#5572 Remove unused code from WarpX class constructor
  Source/WarpX.cpp
Labels: cleaning

#5577 storePhiOnParticles: fix misplaced pragma omp parallel if
  Source/Diagnostics/ParticleIO.cpp
Labels: bug, component: electrostatic, bug: affects latest release

#5574 New embedded boundary data structures in preparation for #5534
  Examples/Tests/embedded_boundary_cube/inputs_base_3d
  Source/EmbeddedBoundary/WarpXInitEB.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicEvolveE.cpp
  Source/FieldSolver/ImplicitSolvers/WarpXImplicitOps.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/WarpXRegrid.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#5568 Doc: More Developer Packages
  Docs/source/install/dependencies.rst
Labels: bug, component: documentation, install, bug: affects latest release, component: Python

#5354 Move CheckDims and ParseGeometryInput out of WarpXUtil
  Source/Initialization/WarpXAMReXInit.cpp
  Source/Initialization/WarpXInit.H
  Source/Initialization/WarpXInit.cpp
  Source/Utils/WarpXUtil.H
  Source/Utils/WarpXUtil.cpp
  Source/WarpX.cpp
Labels: cleaning

#5583 WarpXUtil.H: remove unused function getCellCoordinates
  Source/Utils/WarpXUtil.H
Labels: cleaning

#5582 WarpX.cpp : move free function TagWithLevelSuffix inside WarpX::AllocInitMultiFab
  Source/WarpX.cpp
Labels: cleaning

#5534 Modify stair-case approximation to the EB
  Examples/Tests/embedded_boundary_cube/inputs_base_3d
  Examples/Tests/embedded_boundary_cube/inputs_test_2d_embedded_boundary_cube
  Regression/Checksum/benchmarks_json/test_2d_embedded_boundary_cube.json
  Regression/Checksum/benchmarks_json/test_2d_field_probe.json
  Regression/Checksum/benchmarks_json/test_3d_eb_picmi.json
  Regression/Checksum/benchmarks_json/test_3d_embedded_boundary_cube.json
  Regression/Checksum/benchmarks_json/test_3d_embedded_boundary_cube_macroscopic.json
  Regression/Checksum/benchmarks_json/test_3d_embedded_boundary_rotated_cube.json
  Regression/Checksum/benchmarks_json/test_3d_particle_absorption.json
  Regression/Checksum/benchmarks_json/test_3d_particle_scrape.json
  Regression/Checksum/benchmarks_json/test_3d_particle_scrape_picmi.json
  Regression/Checksum/benchmarks_json/test_rz_embedded_boundary_diffraction.json
  Source/EmbeddedBoundary/WarpXInitEB.cpp
  Source/Initialization/WarpXInitData.cpp
Labels: component: boundary, component: FDTD, component: initialization

#5560 Use `self_fields_verbosity` value for magnetostatic solver
  Source/FieldSolver/MagnetostaticSolver/MagnetostaticSolver.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: magnetostatic

#5586 Clean-up the analysis script
  Examples/Tests/particle_boundary_interaction/analysis.py
Labels: component: tests, cleaning

#5558 Use new stair-case approximation in hybrid solver
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICSolveE.cpp
  Source/FieldSolver/WarpXPushFieldsHybridPIC.cpp
  Source/Fields.H
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: boundary

#5591 WarpXInitEB: fix " int eb_update" shadowing "std::array< std::unique_ptr<amrex::iMultiFab>,3> & eb_update"
  Source/EmbeddedBoundary/WarpXInitEB.cpp
Labels: cleaning

#5589 WarpX header: remove unused GetDistanceToEB function
  Source/WarpX.H
Labels: cleaning

#5578 WarpX class: move ReorderFornbergCoefficients from WarpX.H to WarpX.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#5375 openPMD-api: 0.16.1+
  .github/workflows/clang_tidy.yml
  .github/workflows/cuda.yml
  .github/workflows/dependencies/icc.sh
  Docs/source/developers/gnumake/openpmd.rst
  Docs/source/install/cmake.rst
  Docs/source/install/dependencies.rst
  Docs/source/usage/parameters.rst
  Source/Diagnostics/requirements.txt
  Source/Make.WarpX
  Tools/machines/karolina-it4i/spack-karolina-cuda.yaml
  cmake/dependencies/openPMD.cmake
  setup.py
Labels: component: openPMD, install, component: third party, component: diagnostics

#5565 Maintainer: Weekly Update Script
  Tools/Release/updateAMReX.py
  Tools/Release/updatePICSAR.py
  Tools/Release/updatepyAMReX.py
  Tools/Release/weeklyUpdate.py
Labels: component: documentation

#5607 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  cmake/dependencies/pyAMReX.cmake
Labels: component: documentation, component: third party

#5602 WarpX class: make psatd_solution_type a private member variable
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#5605 WarpX class: make zmax_plasma_to_compute_max_step a private member variable and remove do_compute_max_step_from_zmax
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning, component: boosted frame

#5603 WarpX class: make dt_update_interval a private member variable
  Source/Evolve/WarpXComputeDt.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#5599 WarpX class: make safe_guard_cells a private member variable
  Source/Evolve/WarpXEvolve.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#5598 WarpX class: make do_divb_cleaning_external a private member variable
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#5596 WarpX class: make mirror-related variables private member variables
  Source/Evolve/WarpXEvolve.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#5573 Move checkEarlyUnusedParams from WarpX class to anonymous namespace
  Source/Evolve/WarpXEvolve.cpp
  Source/WarpX.H
Labels: cleaning

#5567 Catch warpx not being initialized in library loader
  Python/pywarpx/_libwarpx.py
  Python/pywarpx/particle_containers.py
Labels: component: Python

#5566 CI: CDash dashboard support
  .azure-pipelines.yml
  CMakeLists.txt
  CTestConfig.cmake
Labels: enhancement, component: tests

#5527 Docs and issue templates: clarify usage of issues and discussions
  .github/ISSUE_TEMPLATE/blank_issue.md
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.rst
Labels: component: documentation

#5608 Doc: Workflows -> How-To
  Docs/source/dataanalysis/workflows.rst
  Docs/source/developers/how_to_guides.rst
  Docs/source/usage/workflows.rst
Labels: component: documentation

#5604 WarpX class: make verboncoeur_axis_correction a private member variable
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#5611 CDash: fix variables in CTestConfig.cmake
  CTestConfig.cmake
Labels: component: tests

#5592 Clang-tidy CI test: bump version from 15 to 16
  .clang-tidy
  .github/workflows/clang_tidy.yml
  Source/BoundaryConditions/PML.H
  Source/BoundaryConditions/PML.cpp
  Source/BoundaryConditions/PML_RZ.H
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/ComputeDiagFunctors/BackTransformFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/CellCenterFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/DivBFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/DivEFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/JFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/PartPerCellFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/PartPerGridFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/ParticleReductionFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/RhoFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/TemperatureFunctor.H
  Source/Diagnostics/FlushFormats/FlushFormatInSitu.cpp
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/ReducedDiags/LoadBalanceCosts.H
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/FieldAccessorFunctors.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/Particles/AddPlasmaUtilities.H
  Source/Particles/ElementaryProcess/QEDPairGeneration.H
  Source/Particles/ElementaryProcess/QEDPhotonEmission.H
  Source/Particles/ElementaryProcess/QEDSchwingerProcess.H
  Source/Particles/Filter/FilterFunctors.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/ParticleBoundaryBuffer.cpp
  Source/Particles/ParticleCreation/SmartCreate.H
  Source/Particles/Sorting/SortingUtils.H
  Source/ablastr/fields/Interpolate.H
  Source/ablastr/utils/SignalHandling.cpp
  Source/ablastr/utils/msg_logger/MsgLogger.H
  Tools/Linter/runClangTidy.sh
Labels: component: tests, cleaning

#5616 WarpX class: evolve_scheme no longer a static variable
  Source/WarpX.H
Labels: cleaning

#5615 WarpX class: ProjectionCleanDivB no longer static
  Source/Python/WarpX.cpp
  Source/WarpX.H
Labels: cleaning, component: Python

#5617 Remove unused SliceDiagnostic.H/cpp
  Source/Diagnostics/CMakeLists.txt
  Source/Diagnostics/Make.package
  Source/Diagnostics/SliceDiagnostic.H
  Source/Diagnostics/SliceDiagnostic.cpp
Labels: cleaning, component: diagnostics

#5614 WarpX class: AllocInitMultiFab and imultifab_map no longer static
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#5550 CMake/CTest: Opt-in Disable Signal Handling
  .azure-pipelines.yml
  CMakeLists.txt
  Docs/source/install/cmake.rst
  Examples/CMakeLists.txt
Labels: component: documentation, component: tests, install

#5627 Add reference for new article using WarpX [Tyushev (2025)]
  Docs/source/highlights.rst
Labels: component: documentation

#5626 WarpX class: remove unused static variable
  Source/WarpX.H
Labels: cleaning

#5613 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  cmake/dependencies/pyAMReX.cmake
Labels: component: documentation, component: third party

#5576 Added CI to test secondary ion emission in RZ.
  Examples/Tests/CMakeLists.txt
  Examples/Tests/secondary_ion_emission/CMakeLists.txt
  Examples/Tests/secondary_ion_emission/analysis.py
  Examples/Tests/secondary_ion_emission/analysis_default_regression.py
  Examples/Tests/secondary_ion_emission/inputs_test_rz_secondary_ion_emission_picmi.py
  Regression/Checksum/benchmarks_json/test_rz_secondary_ion_emission_picmi.json
Labels: component: tests

#5625 Embedded Boundary: take some EB-related methods out of WarpX class
  Source/BoundaryConditions/PML.cpp
  Source/EmbeddedBoundary/CMakeLists.txt
  Source/EmbeddedBoundary/EmbeddedBoundary.H
  Source/EmbeddedBoundary/EmbeddedBoundary.cpp
  Source/EmbeddedBoundary/Make.package
  Source/EmbeddedBoundary/WarpXInitEB.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
Labels: cleaning, component: boundary

#5356 MultiFabRegister: `throw` in get
  Source/BoundaryConditions/PML.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/ElectrostaticSolvers/EffectivePotentialES.cpp
  Source/FieldSolver/ElectrostaticSolvers/LabFrameExplicitES.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/FieldSolver/WarpXPushFieldsHybridPIC.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/Utils/WarpXMovingWindow.cpp
  Source/ablastr/fields/MultiFabRegister.H
  Source/ablastr/fields/MultiFabRegister.cpp
Labels: help wanted, cleaning, component: ABLASTR
