Repository BLAST-WarpX/warpx, pull requests merged in 2025-09, with the labels that each got.

#6136 CI: workaround for macOS issue
  .github/workflows/macos.yml
Labels: bug, component: tests

#6130 FlushFormat int comp writing
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
Labels: bug, bug: affects latest release

#5969 Implement particle suborbits for the implicit solver
  Docs/source/usage/parameters.rst
  Source/FieldSolver/ImplicitSolvers/ImplicitOptions.H
  Source/FieldSolver/ImplicitSolvers/ImplicitSolver.H
  Source/FieldSolver/ImplicitSolvers/ImplicitSolver.cpp
  Source/FieldSolver/ImplicitSolvers/ThetaImplicitEM.cpp
  Source/FieldSolver/ImplicitSolvers/WarpXImplicitOps.cpp
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/Deposition/MassMatricesDeposition.H
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/ImplicitPushPX.cpp
  Source/Particles/WarpXParticleContainer.H
Labels: component: implicit solvers

#6137 Update picmi.py
  Python/pywarpx/picmi.py
Labels: component: Python

#6113 More readable code in PushPX, PushXPSingleStep
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/ImplicitPushPX.cpp
Labels: cleaning

#5712 Diagnostics: pass particle container by const ref to (slightly) reduce reliance on WarpX::GetInstance
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/BoundaryScrapingDiagnostics.H
  Source/Diagnostics/BoundaryScrapingDiagnostics.cpp
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.H
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/MultiDiagnostics.H
  Source/Diagnostics/MultiDiagnostics.cpp
  Source/Diagnostics/WarpXIO.cpp
  Source/Initialization/WarpXInitData.cpp
Labels: cleaning, component: diagnostics

#6155 Fix loading photons from openPMD file
  Source/Particles/ParticleCreation/AddParticles.cpp
Labels: component: openPMD, backend: openmp, component: initialization

#6167 PSATD: OMP Parallelize Data Packing and Unpacking
  Source/FieldSolver/SpectralSolver/SpectralFieldData.cpp
Labels: Performance optimization, component: spectral, backend: openmp

#6088 Suppress GCC -Warray-bounds warnings
  CMakeLists.txt
  cmake/WarpXFunctions.cmake
Labels: warning, install

#6150 Fix minor bugs in script to update dependencies
  Tools/Release/update_dependencies.py
Labels: bug, bug: affects latest release, automation

#6162 MF Register Direction: Descriptive Members
  Examples/Physics_applications/spacecraft_charging/inputs_test_rz_spacecraft_charging_picmi.py
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Python/MultiFabRegister.cpp
  Source/ablastr/fields/MultiFabRegister.H
  Source/ablastr/fields/MultiFabRegister.cpp
Labels: component: core, component: Python, component: ABLASTR

#6149 Add example of basic python input file
  Examples/Tests/plasma_lens/CMakeLists.txt
  Examples/Tests/plasma_lens/inputs_test_3d_plasma_lens_python.py
  Python/pywarpx/Bucket.py
  Python/pywarpx/Diagnostics.py
  Python/pywarpx/Particles.py
  Python/pywarpx/WarpX.py
  Python/pywarpx/__init__.py
  Python/pywarpx/_libwarpx.py
  Regression/Checksum/benchmarks_json/test_3d_plasma_lens_python.json
Labels: component: Python

#6122 CI: debug autoupdate workflows
  .github/workflows/monthly_release.yml
  .github/workflows/weekly_update.yml
Labels: automation

#6179 `MANIFEST.in`: `dependencies.json`
  MANIFEST.in
Labels: bug, install, bug: affects latest release, component: Python

#6180 Python: Remove Deprecated `multifab` Overload
  Source/Python/WarpX.cpp
Labels: changes input scripts / defaults, component: Python

#6169 add option to modify particle update on initial Newton step
  Docs/source/usage/parameters.rst
  Examples/Tests/implicit/inputs_test_1d_theta_implicit_planar_pinch
  Examples/Tests/implicit/inputs_test_2d_theta_implicit_planar_pinch
  Regression/Checksum/benchmarks_json/test_1d_semi_implicit_picard.json
  Source/FieldSolver/ImplicitSolvers/ImplicitOptions.H
  Source/FieldSolver/ImplicitSolvers/ImplicitSolver.H
  Source/FieldSolver/ImplicitSolvers/ImplicitSolver.cpp
  Source/Particles/Pusher/ImplicitPushPX.cpp
  Source/Particles/Pusher/UpdatePosition.H
Labels: component: implicit solvers

#6182 AMReX/pyAMReX/PICSAR: Weekly Update
  dependencies.json
Labels: component: documentation, component: third party

#6174 New SubcyclingHalf enum for subcycling algorithm
  Source/BoundaryConditions/WarpXFieldBoundaries.cpp
  Source/Evolve/WarpXDtType.H
  Source/Evolve/WarpXEvolve.cpp
  Source/FieldSolver/FiniteDifferenceSolver/EvolveF.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/FieldSolver/ImplicitSolvers/SemiImplicitEM.cpp
  Source/FieldSolver/ImplicitSolvers/WarpXImplicitOps.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/FieldSolver/WarpXPushFieldsHybridPIC.cpp
  Source/Fluids/MultiFluidContainer.H
  Source/Fluids/WarpXFluidContainer.H
  Source/Particles/LaserParticleContainer.H
  Source/Particles/LaserParticleContainer.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhotonParticleContainer.H
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/RigidInjectedParticleContainer.H
  Source/Particles/RigidInjectedParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Utils/WarpXAlgorithmSelection.H
  Source/WarpX.H
Labels: cleaning

#5872 Allow `phi` output with non-ES solvers
  Examples/Tests/ohm_solver_magnetic_reconnection/inputs_test_2d_ohm_solver_magnetic_reconnection_picmi.py
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/test_2d_ohm_solver_magnetic_reconnection_picmi.json
  Source/Diagnostics/ComputeDiagFunctors/CMakeLists.txt
  Source/Diagnostics/ComputeDiagFunctors/Make.package
  Source/Diagnostics/ComputeDiagFunctors/PhiFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/PhiFunctor.cpp
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.cpp
Labels: component: diagnostics

#6187 Move PushType enum to WarpXAlgorithmSelection.H
  Source/Evolve/WarpXPushType.H
  Source/FieldSolver/ImplicitSolvers/WarpXImplicitOps.cpp
  Source/Particles/LaserParticleContainer.H
  Source/Particles/LaserParticleContainer.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/PhotonParticleContainer.H
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/RigidInjectedParticleContainer.H
  Source/Particles/WarpXParticleContainer.H
  Source/Utils/WarpXAlgorithmSelection.H
  Source/WarpX.H
Labels: cleaning

#5937 Add CI test to read particles from openPMD
  Docs/source/usage/parameters.rst
  Examples/Tests/gaussian_beam/CMakeLists.txt
  Examples/Tests/gaussian_beam/inputs_test_3d_focusing_gaussian_beam_from_openpmd
  Examples/Tests/gaussian_beam/inputs_test_3d_focusing_gaussian_beam_from_openpmd_prepare.py
  Regression/Checksum/benchmarks_json/test_3d_focusing_gaussian_beam_from_openpmd.json
Labels: component: openPMD, component: tests

#6193 Fix Warning: GNU 11 + NVCC 11.7
  cmake/WarpXFunctions.cmake
Labels: backend: cuda, warning

#6177 Add option to have the process number of each box in the output
  Docs/source/usage/parameters.rst
  Source/Diagnostics/ComputeDiagFunctors/CMakeLists.txt
  Source/Diagnostics/ComputeDiagFunctors/Make.package
  Source/Diagnostics/ComputeDiagFunctors/ProcessNumberFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/ProcessNumberFunctor.cpp
  Source/Diagnostics/FullDiagnostics.cpp
Labels: component: diagnostics, component: load balancing

#6185 Update the "X" in ASCII art "WarpX" text to look more like our new logo
  Source/Utils/Logo/GetLogo.cpp
Labels: enhancement, component: documentation

#6209 Some cleaning of the #include directives
  Source/Diagnostics/FlushFormats/FlushFormatInSitu.cpp
  Source/Diagnostics/FlushFormats/FlushFormatSensei.cpp
  Source/Diagnostics/ParticleDiag/ParticleDiag.cpp
  Source/Diagnostics/ReducedDiags/FieldProbeParticleContainer.cpp
  Source/Particles/Collision/BinaryCollision/Bremsstrahlung/BremsstrahlungFunc.H
  Source/Particles/Collision/ScatteringProcess.H
  Source/Particles/Collision/ScatteringProcess.cpp
Labels: cleaning

#6159 Initial Box Splitting (Profile): NRandomPerCell
  Source/Initialization/WarpXInitData.cpp
Labels: component: load balancing, component: initialization

#6230 AddParticles.cpp : fix "maybe-uninitialized" issue for variable XDim3 r
  Source/Particles/ParticleCreation/AddParticles.cpp
Labels: cleaning
