Repository BLAST-WarpX/warpx, pull requests merged in 2025-07, with the labels that each got.

#5989 Add new paper using WarpX to highlights
  Docs/source/highlights.rst
Labels: component: documentation

#5993 CMake: Fix Superbuilds
  CMakeLists.txt
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  cmake/dependencies/pyAMReX.cmake
Labels: bug, install

#5986 Allow rigid free-drift in transverse coordinates
  Docs/source/usage/parameters.rst
  Source/Particles/RigidInjectedParticleContainer.H
  Source/Particles/RigidInjectedParticleContainer.cpp
Labels: changes input scripts / defaults, component: initialization

#5995 Add new paper using WarpX for Hall thruster simulations
  Docs/source/highlights.rst
Labels: component: documentation

#5929 Infrastructure for using full mass matrices in the implicit solvers
  Docs/source/usage/parameters.rst
  Examples/Tests/implicit/inputs_test_1d_planar_pinch_withPC
  Source/FieldSolver/ImplicitSolvers/ImplicitSolver.H
  Source/FieldSolver/ImplicitSolvers/ImplicitSolver.cpp
  Source/FieldSolver/ImplicitSolvers/SemiImplicitEM.cpp
  Source/FieldSolver/ImplicitSolvers/StrangImplicitSpectralEM.cpp
  Source/FieldSolver/ImplicitSolvers/ThetaImplicitEM.cpp
  Source/Fields.H
  Source/NonlinearSolvers/JacobianFunctionMF.H
  Source/NonlinearSolvers/NewtonSolver.H
  Source/NonlinearSolvers/NonlinearSolver.H
  Source/Particles/Deposition/MassMatricesDeposition.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: component: implicit solvers

#6000 FullDiagnostics.cpp : use WARPX_ABORT_WITH_MESSAGE instead of std::cout
  Source/Diagnostics/FullDiagnostics.cpp
Labels: cleaning

#5996 Release: 25.07
  dependencies.json
Labels: component: documentation

#5943 Add function to get total kinetic energy for a given species
  Python/pywarpx/particle_containers.py
  Source/Diagnostics/ReducedDiags/ParticleEnergy.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/Python/Particles/WarpXParticleContainer.cpp
Labels: component: diagnostics, component: Python

#6001 Fix temperature deposition thread safety
  Regression/Checksum/benchmarks_json/test_3d_ohm_solver_cylinder_compression_picmi.json
  Regression/Checksum/benchmarks_json/test_rz_ohm_solver_cylinder_compression_picmi.json
  Source/Particles/Deposition/TemperatureDeposition.H
  Source/Particles/Deposition/TemperatureDepositionTypes.H
  Source/Particles/Deposition/VarianceAccumulationBuffer.H
  Source/Particles/Deposition/VarianceAccumulationBuffer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
Labels: bug, component: fluid-ohm

#6009 Update dane scripts
  Docs/source/install/hpc/dane.rst
  Tools/machines/dane-llnl/dane_warpx.profile.example
  Tools/machines/dane-llnl/install_dependencies.sh
Labels: bug, component: documentation, machine / system

#5981 Further optimizations for the binary collision module
  Examples/Physics_applications/capacitive_discharge/analysis_dsmc.py
  Examples/Tests/ionization_dsmc/analysis_ionization_dsmc_3d.py
  Examples/Tests/nuclear_fusion/analysis_proton_boron_fusion.py
  Regression/Checksum/benchmarks_json/test_1d_charge_exchange_dsmc.json
  Regression/Checksum/benchmarks_json/test_1d_collision_z.json
  Regression/Checksum/benchmarks_json/test_1d_dsmc_picmi.json
  Regression/Checksum/benchmarks_json/test_1d_ionization_neutral_dsmc.json
  Regression/Checksum/benchmarks_json/test_1d_planar_pinch_withPC.json
  Regression/Checksum/benchmarks_json/test_2d_collision_xz.json
  Regression/Checksum/benchmarks_json/test_2d_collision_xz_global_debye.json
  Regression/Checksum/benchmarks_json/test_2d_collision_xz_picmi.json
  Regression/Checksum/benchmarks_json/test_2d_proton_boron_fusion.json
  Regression/Checksum/benchmarks_json/test_3d_collision_xyz.json
  Regression/Checksum/benchmarks_json/test_3d_deuterium_deuterium_fusion.json
  Regression/Checksum/benchmarks_json/test_3d_deuterium_tritium_fusion.json
  Regression/Checksum/benchmarks_json/test_3d_ionization_electron_dsmc.json
  Regression/Checksum/benchmarks_json/test_3d_ionization_ion_dsmc.json
  Regression/Checksum/benchmarks_json/test_3d_linear_breit_wheeler_many_photons.json
  Regression/Checksum/benchmarks_json/test_3d_proton_boron_fusion.json
  Regression/Checksum/benchmarks_json/test_rz_deuterium_tritium_fusion.json
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
Labels: Performance optimization, component: collisions

#6015 Remove unused file from binary collisions module
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
  Source/Particles/Collision/BinaryCollision/Coulomb/ComputeTemperature.H
Labels: cleaning

#5009 Enable general weight scaling for radial particle distributions
  Docs/source/usage/parameters.rst
  Examples/Tests/electrostatic_sphere/CMakeLists.txt
  Examples/Tests/electrostatic_sphere/analysis_electrostatic_sphere.py
  Examples/Tests/electrostatic_sphere/inputs_test_rz_electrostatic_sphere_uniform_weighting
  Examples/Tests/langmuir/inputs_test_rz_langmuir_multi_picmi.py
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/test_rsphere_langmuir_multi.json
  Regression/Checksum/benchmarks_json/test_rz_electrostatic_sphere_uniform_weighting.json
  Regression/Checksum/benchmarks_json/test_rz_langmuir_multi_psatd.json
  Regression/Checksum/benchmarks_json/test_rz_langmuir_multi_psatd_current_correction.json
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/ParticleCreation/AddParticles.cpp
Labels: geometry: RZ, component: initialization

#5407 fields.py relies on MultiFab global indexing
  Docs/source/developers/python.rst
  Docs/source/usage/workflows/python_extend.rst
  Examples/Physics_applications/capacitive_discharge/inputs_base_1d_picmi.py
  Examples/Physics_applications/capacitive_discharge/inputs_test_2d_background_mcc_picmi.py
  Examples/Physics_applications/spacecraft_charging/inputs_test_rz_spacecraft_charging_picmi.py
  Examples/Tests/ohm_solver_cylinder_compression/inputs_test_3d_ohm_solver_cylinder_compression_picmi.py
  Examples/Tests/ohm_solver_cylinder_compression/inputs_test_rz_ohm_solver_cylinder_compression_picmi.py
  Examples/Tests/ohm_solver_magnetic_reconnection/inputs_test_2d_ohm_solver_magnetic_reconnection_picmi.py
  Examples/Tests/projection_div_cleaner/inputs_test_3d_projection_div_cleaner_callback_picmi.py
  Examples/Tests/python_wrappers/inputs_test_2d_python_wrappers_picmi.py
  Python/pywarpx/fields.py
  Regression/Checksum/benchmarks_json/test_rz_spacecraft_charging_picmi.json
Labels: component: Python

#5990 Fix GCC 8: `stdc++fs`
  CMakeLists.txt
  cmake/has_filesystem.cpp
Labels: bug, install, bug: affects latest release, component: diagnostics

#5966 CMake: ABLASTR/WarpX/AMReX SIMD
  CMakeLists.txt
  cmake/WarpXFunctions.cmake
  cmake/dependencies/AMReX.cmake
Labels: install, backend: openmp

#6023 fixed index for gmres_iter in 1d planar pinch analysis script
  Examples/Tests/implicit/analysis_1d_pinch.py
Labels: bug, component: implicit solvers

#6022 ensure time solver-dependent alpha is set correctly in the curl-curl PC.
  Source/FieldSolver/ImplicitSolvers/ImplicitSolver.H
  Source/FieldSolver/ImplicitSolvers/SemiImplicitEM.H
  Source/FieldSolver/ImplicitSolvers/StrangImplicitSpectralEM.H
  Source/FieldSolver/ImplicitSolvers/ThetaImplicitEM.H
  Source/NonlinearSolvers/CurlCurlMLMGPC.H
Labels: bug, component: implicit solvers

#6027 permit CurlCurlMLMG with PEC and SilverMueller BCs.
  Source/FieldSolver/ImplicitSolvers/ImplicitSolver.cpp
Labels: component: implicit solvers

#6032 Weekly update of dependencies
  dependencies.json
Labels: component: third party

#6018 Update perlmutter.rst
  Docs/source/install/hpc/perlmutter.rst
Labels: component: documentation, machine / system

#6028 Bug fix: Mixed precision builds fail due to conflicting types
  .github/workflows/intel.yml
  Source/Diagnostics/ReducedDiags/ParticleHistogram2D.cpp
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
  Source/Particles/Collision/BinaryCollision/DSMC/SplitAndScatterFunc.H
Labels: bug, bug: affects latest release

#6016 `PlasmaInjector.H`: Hide `openPMD.hpp`
  Source/Initialization/PlasmaInjector.H
  Source/Initialization/PlasmaInjector.cpp
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/ParticleCreation/AddParticles.cpp
Labels: component: openPMD, cleaning

#6033 Add `--release` option to script for update of dependencies
  Docs/source/maintenance/release.rst
  Tools/Release/releasePR.py
  Tools/Release/update_dependencies.py
  Tools/Release/weeklyUpdate.py
Labels: component: documentation

#6044 Doc: openPMD Airplane Mode
  Docs/source/developers/how_to_compile_locally.rst
Labels: component: documentation

#3560 Doxygen CI: Warnings as Error
  .github/workflows/source.yml
  .github/workflows/source/doxygen
  Docs/Doxyfile
  Source/BoundaryConditions/PEC_Insulator.H
  Source/BoundaryConditions/WarpX_PEC.H
  Source/Diagnostics/BTDiagnostics.H
  Source/Diagnostics/BoundaryScrapingDiagnostics.H
  Source/Diagnostics/ComputeDiagFunctors/BackTransformParticleFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/RhoFunctor.H
  Source/Diagnostics/Diagnostics.H
  Source/Diagnostics/FullDiagnostics.H
  Source/Diagnostics/ReducedDiags/ChargeOnEB.H
  Source/Diagnostics/ReducedDiags/FieldPoyntingFlux.H
  Source/Diagnostics/WarpXOpenPMD.H
  Source/FieldSolver/ElectrostaticSolvers/EffectivePotentialES.H
  Source/FieldSolver/ElectrostaticSolvers/ElectrostaticSolver.H
  Source/FieldSolver/ElectrostaticSolvers/RelativisticExplicitES.H
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/FieldSolver/FiniteDifferenceSolver/MacroscopicProperties/MacroscopicProperties.H
  Source/FieldSolver/ImplicitSolvers/WarpXSolverVec.H
  Source/Fluids/WarpXFluidContainer.H
  Source/Initialization/WarpXAMReXInit.H
  Source/NonlinearSolvers/AMReXGMRES_Wrapper.H
  Source/NonlinearSolvers/LinearSolver.H
  Source/Parallelization/WarpXComm_K.H
  Source/Particles/Collision/BinaryCollision/Coulomb/PairWiseCoulombCollisionFunc.H
  Source/Particles/Collision/BinaryCollision/DSMC/CollisionFilterFunc.H
  Source/Particles/Collision/BinaryCollision/DSMC/DSMCFunc.H
  Source/Particles/Collision/BinaryCollision/LinearBreitWheeler/LinearBreitWheelerCollisionFunc.H
  Source/Particles/Collision/BinaryCollision/LinearBreitWheeler/SingleLinearBreitWheelerCollisionEvent.H
  Source/Particles/Collision/BinaryCollision/ParticleCreationFunc.H
  Source/Particles/Collision/CollisionHandler.cpp
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/Deposition/MassMatricesDeposition.H
  Source/Particles/Deposition/TemperatureDeposition.H
  Source/Particles/ElementaryProcess/QEDPairGeneration.H
  Source/Particles/ElementaryProcess/QEDPhotonEmission.H
  Source/Particles/Gather/FieldGather.H
  Source/Particles/ParticleCreation/DefaultInitialization.H
  Source/Particles/ParticleCreation/FilterCopyTransform.H
  Source/Particles/ParticleCreation/FilterCreateTransformFromFAB.H
  Source/Particles/PhysicalParticleContainer.H
  Source/Utils/ParticleUtils.H
  Source/Utils/ParticleUtils.cpp
  Source/Utils/WarpXUtil.H
  Source/WarpX.H
  Source/ablastr/fields/EffectivePotentialPoissonSolver.H
  Source/ablastr/fields/IntegratedGreenFunctionSolver.H
  Source/ablastr/fields/MultiFabRegister.H
  Source/ablastr/fields/PoissonSolver.H
  Source/ablastr/particles/NodalFieldGather.H
Labels: component: documentation, component: tests

#6050 Run test_2d_theta_implicit_strang_psatd test on one processor
  Examples/Tests/implicit/CMakeLists.txt
Labels: component: spectral, component: implicit solvers

#6052 Doxygen: No Python
  Docs/Doxyfile
Labels: bug, component: documentation
