Repository BLAST-WarpX/warpx, pull requests merged in 2025-02, with the labels that each got.

#5631 Doc: Frontier OpenMP Load
  Tools/machines/frontier-olcf/frontier_warpx.profile.example
Labels: component: documentation, install, machine / system, workaround

#5475 Add FieldPoyntingFlux reduced diagnostic
  Docs/source/usage/parameters.rst
  Examples/Tests/pec/CMakeLists.txt
  Examples/Tests/pec/analysis_pec_insulator_implicit.py
  Examples/Tests/pec/inputs_test_2d_pec_field_insulator_implicit
  Examples/Tests/pec/inputs_test_2d_pec_field_insulator_implicit_restart
  Examples/Tests/reduced_diags/inputs_test_3d_reduced_diags
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/test_2d_pec_field_insulator_implicit.json
  Regression/Checksum/benchmarks_json/test_2d_pec_field_insulator_implicit_restart.json
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.H
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp
  Source/Diagnostics/ReducedDiags/CMakeLists.txt
  Source/Diagnostics/ReducedDiags/FieldPoyntingFlux.H
  Source/Diagnostics/ReducedDiags/FieldPoyntingFlux.cpp
  Source/Diagnostics/ReducedDiags/Make.package
  Source/Diagnostics/ReducedDiags/MultiReducedDiags.H
  Source/Diagnostics/ReducedDiags/MultiReducedDiags.cpp
  Source/Diagnostics/ReducedDiags/ReducedDiags.H
  Source/Diagnostics/ReducedDiags/ReducedDiags.cpp
  Source/Diagnostics/WarpXIO.cpp
  Source/FieldSolver/ImplicitSolvers/SemiImplicitEM.cpp
  Source/FieldSolver/ImplicitSolvers/StrangImplicitSpectralEM.cpp
  Source/FieldSolver/ImplicitSolvers/ThetaImplicitEM.cpp
Labels: component: diagnostics

#5632 Doc Lassen: Pip Cache Disabled
  Tools/machines/lassen-llnl/install_v100_dependencies_toss3.sh
Labels: install, machine / system, component: Python

#5629 Add execution of `afterEpush` callback in hybrid solver
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
Labels: component: Python, component: fluid-ohm

#5622 Fix bug with DSMC collisions in RZ
  Source/Particles/Collision/BinaryCollision/DSMC/DSMCFunc.H
  Source/Particles/Collision/BinaryCollision/DSMC/SplitAndScatterFunc.H
Labels: bug, bug: affects latest release, geometry: RZ, component: collisions

#5635 Fix Dangling Ref in EB Init
  Source/EmbeddedBoundary/WarpXInitEB.cpp
Labels: bug, component: boundary, component: initialization

#5638 Fixing bug in hyper-resistivity calculation which had missing terms i…
  Examples/Tests/ohm_solver_em_modes/analysis_rz.py
  Regression/Checksum/benchmarks_json/test_rz_ohm_solver_em_modes_picmi.json
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICSolveE.cpp
Labels: bug, bug: affects latest release, component: fluid-ohm

#5639 Release 25.02
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  Python/setup.py
  Tools/Release/releasePR.py
  Tools/Release/weeklyUpdate.py
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  cmake/dependencies/pyAMReX.cmake
  setup.py
Labels: component: documentation, component: third party

#5643 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
Labels: component: documentation, component: third party

#5645 RTD: Fix GA Integration
  Docs/requirements.txt
  Docs/source/conf.py
Labels: bug, component: documentation, component: third party, bug: affects latest release

#5621 Add MCC forward scattering
  Docs/source/refs.bib
  Docs/source/theory/multiphysics/collisions.rst
  Docs/source/usage/parameters.rst
  Source/Particles/Collision/BackgroundMCC/BackgroundMCCCollision.cpp
  Source/Particles/Collision/BinaryCollision/DSMC/DSMCFunc.cpp
  Source/Particles/Collision/BinaryCollision/DSMC/SplitAndScatterFunc.H
  Source/Particles/Collision/ScatteringProcess.H
  Source/Particles/Collision/ScatteringProcess.cpp
Labels: component: collisions

#5628 Add PMC boundary conditions
  Docs/source/theory/boundary_conditions.rst
  Docs/source/usage/parameters.rst
  Examples/Tests/pec/CMakeLists.txt
  Examples/Tests/pec/inputs_test_3d_pmc_field
  Regression/Checksum/benchmarks_json/test_3d_magnetostatic_eb.json
  Regression/Checksum/benchmarks_json/test_3d_magnetostatic_eb_picmi.json
  Regression/Checksum/benchmarks_json/test_3d_pmc_field.json
  Source/BoundaryConditions/WarpXFieldBoundaries.cpp
  Source/BoundaryConditions/WarpX_PEC.H
  Source/BoundaryConditions/WarpX_PEC.cpp
  Source/FieldSolver/ImplicitSolvers/ImplicitSolver.cpp
  Source/Initialization/DivCleaner/ProjectionDivCleaner.cpp
  Source/Utils/WarpXAlgorithmSelection.H
  Source/Utils/WarpXUtil.cpp
  Source/WarpX.H
Labels: component: boundary

#5646 Doc: New APL on Magnetic Reconnection
  Docs/source/highlights.rst
Labels: component: documentation

#5651 Doc : MR paper highlight
  Docs/source/highlights.rst
Labels: component: documentation

#5619 Move Fornberg coefficients calculations from WarpX to ablastr
  Source/FieldSolver/SpectralSolver/SpectralKSpace.cpp
  Source/WarpX.H
  Source/WarpX.cpp
  Source/ablastr/math/CMakeLists.txt
  Source/ablastr/math/FiniteDifference.H
  Source/ablastr/math/FiniteDifference.cpp
  Source/ablastr/math/Make.package
Labels: cleaning, component: ABLASTR

#5642 WarpX class : em_solver_medium no longer a static variable
  Source/Evolve/WarpXEvolve.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#5600 Clang-tidy CI test: bump version from 16 to 17
  .clang-tidy
  .github/workflows/clang_tidy.yml
  Source/Diagnostics/FlushFormats/FlushFormatCatalyst.cpp
  Source/Diagnostics/FullDiagnostics.cpp
  Source/Diagnostics/ReducedDiags/Timestep.cpp
  Source/FieldSolver/MagnetostaticSolver/MagnetostaticSolver.cpp
  Source/FieldSolver/SpectralSolver/SpectralKSpace.H
  Source/FieldSolver/SpectralSolver/SpectralKSpace.cpp
  Source/FieldSolver/SpectralSolver/SpectralKSpace_fwd.H
  Source/Initialization/DivCleaner/ProjectionDivCleaner.cpp
  Source/NonlinearSolvers/NewtonSolver.H
  Source/NonlinearSolvers/PicardSolver.H
  Source/Particles/Resampling/VelocityCoincidenceThinning.H
  Source/Python/callbacks.cpp
  Source/Python/pyWarpX.cpp
  Source/ablastr/fields/EffectivePotentialPoissonSolver.H
  Source/ablastr/fields/Interpolate.H
  Source/ablastr/utils/msg_logger/MsgLogger.H
  Source/ablastr/utils/msg_logger/MsgLogger.cpp
  Tools/Linter/runClangTidy.sh
  Tools/QedTablesUtils/Source/QedTableCommons.H
Labels: component: tests, cleaning

#5579 WarpX class: moving initialization of warning manager to WarpXInit
  Source/Initialization/WarpXInit.H
  Source/Initialization/WarpXInit.cpp
  Source/WarpX.cpp
Labels: cleaning

#5609 WarpX class: move shiftMF to anonymous namespace in WarpXMovingWindow.cpp
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.H
Labels: cleaning

#5655 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Source/ablastr/fields/IntegratedGreenFunctionSolver.cpp
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
Labels: component: documentation, component: third party

#5630 Move several EB-related methods out of the WarpX class
  Source/BoundaryConditions/PML.cpp
  Source/EmbeddedBoundary/CMakeLists.txt
  Source/EmbeddedBoundary/EmbeddedBoundary.H
  Source/EmbeddedBoundary/EmbeddedBoundary.cpp
  Source/EmbeddedBoundary/EmbeddedBoundaryInit.H
  Source/EmbeddedBoundary/EmbeddedBoundaryInit.cpp
  Source/EmbeddedBoundary/Make.package
  Source/EmbeddedBoundary/WarpXInitEB.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
Labels: cleaning, component: boundary

#5656 WarpX class: simplify return type of get_spectral_solver_fp using `auto&`
  Source/WarpX.H
Labels: cleaning

#5545 Add reduced diagnostic: 2d differential luminosity
  Docs/source/usage/parameters.rst
  Examples/Tests/diff_lumi_diag/CMakeLists.txt
  Examples/Tests/diff_lumi_diag/analysis.py
  Examples/Tests/diff_lumi_diag/inputs_base_3d
  Source/Diagnostics/ReducedDiags/CMakeLists.txt
  Source/Diagnostics/ReducedDiags/DifferentialLuminosity2D.H
  Source/Diagnostics/ReducedDiags/DifferentialLuminosity2D.cpp
  Source/Diagnostics/ReducedDiags/Make.package
  Source/Diagnostics/ReducedDiags/MultiReducedDiags.cpp
Labels: component: diagnostics

#5644 WarpX class: move SetDotMask to anonymous namespace in WarpX.cpp
  Source/FieldSolver/ImplicitSolvers/WarpXSolverVec.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#5669 Update to latest AMReX version
  .github/workflows/cuda.yml
  cmake/dependencies/AMReX.cmake
Labels: component: third party

#5275 Add external particle fields ohms law hybrid
  Docs/source/refs.bib
  Docs/source/usage/parameters.rst
  Examples/Tests/CMakeLists.txt
  Examples/Tests/ohm_solver_cylinder_compression/CMakeLists.txt
  Examples/Tests/ohm_solver_cylinder_compression/analysis_default_regression.py
  Examples/Tests/ohm_solver_cylinder_compression/inputs_test_3d_ohm_solver_cylinder_compression_picmi.py
  Examples/Tests/ohm_solver_cylinder_compression/inputs_test_rz_ohm_solver_cylinder_compression_picmi.py
  Python/pywarpx/HybridPICModel.py
  Python/pywarpx/WarpX.py
  Python/pywarpx/__init__.py
  Python/pywarpx/fields.py
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/test_3d_ohm_solver_cylinder_compression_picmi.json
  Regression/Checksum/benchmarks_json/test_rz_ohm_solver_cylinder_compression_picmi.json
  Source/FieldSolver/FiniteDifferenceSolver/CMakeLists.txt
  Source/FieldSolver/FiniteDifferenceSolver/ComputeCurlA.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceSolver.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/CMakeLists.txt
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/ExternalVectorPotential.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/ExternalVectorPotential.cpp
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/Make.package
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICSolveE.cpp
  Source/FieldSolver/FiniteDifferenceSolver/Make.package
  Source/FieldSolver/WarpXPushFieldsHybridPIC.cpp
  Source/Fields.H
  Source/Initialization/WarpXInitData.cpp
  Source/Particles/Gather/GetExternalFields.H
  Source/Python/WarpX.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: enhancement, component: fluid-ohm

#5648 Perlmutter: SW Install Updates
  Docs/source/install/hpc/perlmutter.rst
  Tools/machines/perlmutter-nersc/install_cpu_dependencies.sh
  Tools/machines/perlmutter-nersc/install_gpu_dependencies.sh
  Tools/machines/perlmutter-nersc/perlmutter_cpu_warpx.profile.example
  Tools/machines/perlmutter-nersc/perlmutter_gpu_warpx.profile.example
Labels: component: documentation, machine / system

#5675 mini-PR: Cleanup in Ohm solver for readability
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICSolveE.cpp
Labels: cleaning, component: fluid-ohm

#5671 WarpX class: fuse together doFieldIonization with doFieldIonization(lev) and doQEDEvents with doQEDEvents(lev)
  Source/Evolve/WarpXEvolve.cpp
  Source/WarpX.H
Labels: cleaning, component: QED, component: ionization

#5670 WarpX class: remove declaration of two unimplemented functions
  Source/WarpX.H
Labels: cleaning, component: diagnostics

#5660 Fix plot_distribution_mapping.py for 2D
  Tools/PostProcessing/plot_distribution_mapping.py
Labels: component: parallelization

#5658 WarpX class: move PrintDtDxDyDz to an anonymous namespace in WarpXInitData.cpp
  Source/Evolve/WarpXComputeDt.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
Labels: cleaning, component: initialization

#5680 AMReX/pyAMReX/PICSAR: Weekly Update
  .azure-pipelines.yml
  .github/workflows/cuda.yml
  cmake/dependencies/AMReX.cmake
Labels: bug, component: documentation, component: third party

#5683 Small fix in Perlmutter GPU sbatch script
  Tools/machines/perlmutter-nersc/perlmutter_gpu.sbatch
Labels: Performance optimization, changes input scripts / defaults, machine / system

#5686 Doc: PoP on Ion-Acoustic Solitions
  Docs/source/highlights.rst
Labels: component: documentation

#5640 WarpX class: remove unused methods GetMacroscopicProperties and GetHybridPICModel
  Source/WarpX.H
Labels: cleaning

#5694 Fix: `AddPlasmaFlux` w/ RT Components
  Source/Particles/PhysicalParticleContainer.cpp
Labels: bug, component: core, component: initialization

#5688 Doc: Helion Credits
  Docs/source/acknowledge_us.rst
Labels: component: documentation

#5695 Doc: Frontier Update (Feb 18, 2025)
  Tools/machines/frontier-olcf/frontier_warpx.profile.example
  Tools/machines/frontier-olcf/install_dependencies.sh
Labels: component: documentation, install, machine / system

#5699 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  cmake/dependencies/AMReX.cmake
Labels: component: documentation, component: third party

#5689 PICMI Diagnostics settings: added handling method for ParticleHistogram2D in Reduced Diagnostics
  Python/pywarpx/picmi.py
Labels: component: PICMI, component: diagnostics

#5690 Fixing bug that only applied last field in the list of external field…
  Examples/Tests/ohm_solver_cylinder_compression/inputs_test_3d_ohm_solver_cylinder_compression_picmi.py
  Examples/Tests/ohm_solver_cylinder_compression/inputs_test_rz_ohm_solver_cylinder_compression_picmi.py
  Regression/Checksum/benchmarks_json/test_3d_ohm_solver_cylinder_compression_picmi.json
  Regression/Checksum/benchmarks_json/test_rz_ohm_solver_cylinder_compression_picmi.json
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/ExternalVectorPotential.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/ExternalVectorPotential.cpp
Labels: bug, bug: affects latest release, component: fluid-ohm

#5692 Adding hyper-resistivity expression, function of rho, B
  Python/pywarpx/picmi.py
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICSolveE.cpp
Labels: component: fluid-ohm

#5464 [WIP]Add diagnostic file output for the implicit solvers
  Docs/source/install/dependencies.rst
  Examples/Tests/implicit/inputs_test_2d_theta_implicit_jfnk_vandb
  Source/FieldSolver/ImplicitSolvers/SemiImplicitEM.cpp
  Source/FieldSolver/ImplicitSolvers/StrangImplicitSpectralEM.cpp
  Source/FieldSolver/ImplicitSolvers/ThetaImplicitEM.cpp
  Source/NonlinearSolvers/NewtonSolver.H
  Source/NonlinearSolvers/NonlinearSolver.H
  Source/NonlinearSolvers/PicardSolver.H
  Tools/machines/desktop/spack-ubuntu-cuda.yaml
  Tools/machines/desktop/spack-ubuntu-openmp.yaml
  Tools/machines/desktop/spack-ubuntu-rocm.yaml
Labels: component: implicit solvers

#5709 Documentation: update profile for Adastra supercomputer (CINES, France)
  Tools/machines/adastra-cines/adastra_warpx.profile.example
Labels: component: documentation, machine / system

#5706 Doc: ADIOS2 v2.10.2
  Tools/machines/adastra-cines/adastra_warpx.profile.example
  Tools/machines/adastra-cines/install_dependencies.sh
  Tools/machines/dane-llnl/dane_warpx.profile.example
  Tools/machines/dane-llnl/install_dependencies.sh
  Tools/machines/frontier-olcf/frontier_warpx.profile.example
  Tools/machines/fugaku-riken/fugaku_warpx.profile.example
  Tools/machines/fugaku-riken/install_dependencies.sh
  Tools/machines/greatlakes-umich/greatlakes_v100_warpx.profile.example
  Tools/machines/greatlakes-umich/install_v100_dependencies.sh
  Tools/machines/hpc3-uci/hpc3_gpu_warpx.profile.example
  Tools/machines/hpc3-uci/install_gpu_dependencies.sh
  Tools/machines/lassen-llnl/install_v100_dependencies_toss3.sh
  Tools/machines/lassen-llnl/lassen_v100_warpx_toss3.profile.example
  Tools/machines/lawrencium-lbnl/lawrencium_warpx.profile.example
  Tools/machines/leonardo-cineca/install_gpu_dependencies.sh
  Tools/machines/leonardo-cineca/leonardo_gpu_warpx.profile.example
  Tools/machines/lonestar6-tacc/install_a100_dependencies.sh
  Tools/machines/lonestar6-tacc/lonestar6_warpx_a100.profile.example
  Tools/machines/lumi-csc/install_dependencies.sh
  Tools/machines/lumi-csc/lumi_warpx.profile.example
  Tools/machines/perlmutter-nersc/install_cpu_dependencies.sh
  Tools/machines/perlmutter-nersc/install_gpu_dependencies.sh
  Tools/machines/perlmutter-nersc/perlmutter_cpu_warpx.profile.example
  Tools/machines/perlmutter-nersc/perlmutter_gpu_warpx.profile.example
  Tools/machines/pitzer-osc/install_cpu_dependencies.sh
  Tools/machines/pitzer-osc/install_v100_dependencies.sh
  Tools/machines/pitzer-osc/pitzer_cpu_warpx.profile.example
  Tools/machines/pitzer-osc/pitzer_v100_warpx.profile.example
  Tools/machines/polaris-alcf/install_gpu_dependencies.sh
  Tools/machines/polaris-alcf/polaris_gpu_warpx.profile.example
  Tools/machines/tioga-llnl/install_mi300a_dependencies.sh
  Tools/machines/tioga-llnl/tioga_mi300a_warpx.profile.example
Labels: component: documentation, component: openPMD, install, component: third party, machine / system

#5710 Ionization.H : remove duplicate call to `m_get_externalEB`
  Source/Particles/ElementaryProcess/Ionization.H
Labels: bug, bug: affects latest release, component: ionization

#5714 Move linear interpolation functions to ablastr
  Source/Initialization/WarpXInitData.cpp
  Source/Laser/LaserProfilesImpl/LaserProfileFromFile.cpp
  Source/ablastr/math/LinearInterpolation.H
Labels: cleaning, component: interpolation, component: ABLASTR
