Repository BLAST-WarpX/warpx, pull requests merged in 2025-03, with the labels that each got.

#5707 Fix HIP CI
  .github/workflows/dependencies/hip.sh
  .github/workflows/hip.yml
  Source/AcceleratorLattice/LatticeElementFinder.H
  Source/AcceleratorLattice/LatticeElementFinder.cpp
  Source/Particles/Gather/GetExternalFields.H
Labels: bug, component: tests, backend: hip

#5687 pre-commit: set up clang-format hook
  .clang-format
  .pre-commit-config.yaml
  Source/main.cpp
Labels: component: tests, cleaning

#5700 Add Villasenor and Buneman current deposition with explicit scheme
  Docs/source/usage/parameters.rst
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/WarpXParticleContainer.cpp
  Source/WarpX.cpp
Labels: enhancement

#1751 Synchronize velocity for diagnostics
  Docs/source/usage/parameters.rst
  Examples/Tests/single_particle/CMakeLists.txt
  Examples/Tests/single_particle/analysis_synchronize_velocity.py
  Examples/Tests/single_particle/inputs_test_1d_synchronize_velocity
  Python/pywarpx/picmi.py
  Source/Diagnostics/MultiDiagnostics.H
  Source/Diagnostics/MultiDiagnostics.cpp
  Source/Diagnostics/ReducedDiags/MultiReducedDiags.H
  Source/Diagnostics/ReducedDiags/MultiReducedDiags.cpp
  Source/Diagnostics/ReducedDiags/ReducedDiags.H
  Source/Evolve/WarpXEvolve.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: diagnostics

#5654 DSMC: Add impact ionization
  Docs/source/usage/parameters.rst
  Examples/Physics_applications/capacitive_discharge/analysis_dsmc.py
  Examples/Physics_applications/capacitive_discharge/inputs_base_1d_picmi.py
  Examples/Tests/CMakeLists.txt
  Examples/Tests/ionization_dsmc/CMakeLists.txt
  Examples/Tests/ionization_dsmc/analysis_default_regression.py
  Examples/Tests/ionization_dsmc/analysis_ionization_dsmc_3d.py
  Examples/Tests/ionization_dsmc/inputs_test_3d_ionization_dsmc
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/test_1d_dsmc_picmi.json
  Regression/Checksum/benchmarks_json/test_3d_ionization_dsmc.json
  Source/Particles/Collision/BackgroundMCC/BackgroundMCCCollision.cpp
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
  Source/Particles/Collision/BinaryCollision/DSMC/CollisionFilterFunc.H
  Source/Particles/Collision/BinaryCollision/DSMC/DSMCFunc.H
  Source/Particles/Collision/BinaryCollision/DSMC/DSMCFunc.cpp
  Source/Particles/Collision/BinaryCollision/DSMC/SplitAndScatterFunc.H
  Source/Particles/Collision/BinaryCollision/DSMC/SplitAndScatterFunc.cpp
Labels: component: collisions

#5723 Readme.md : correct typo in Governance section ("High Performance Computing Foundation" --> "High Performance Software Foundation" )
  README.md
Labels: component: documentation

#5726 Synchronize after copying in 2D reduced diagnostics
  Source/Diagnostics/ReducedDiags/DifferentialLuminosity2D.cpp
  Source/Diagnostics/ReducedDiags/ParticleHistogram2D.cpp
Labels: bug, component: diagnostics

#5724 acknowledgments.rst : corrected typo ("High Performance Computing Foundation" --> "High Performance Software Foundation" )
  Docs/source/acknowledgements.rst
Labels: component: documentation

#5735 openPMD: no BP5 Group Based
  Docs/source/usage/parameters.rst
  Docs/source/usage/workflows/ml_materials/run_warpx_training.py
  Source/Diagnostics/FlushFormats/FlushFormatOpenPMD.cpp
  Source/Diagnostics/OpenPMDHelpFunction.cpp
  Source/Diagnostics/WarpXOpenPMD.H
Labels: bug, component: openPMD, bug: affects latest release, component: diagnostics

#5736 Python: `setuptools[core]`
  .azure-pipelines.yml
  .github/workflows/cuda.yml
  .github/workflows/intel.yml
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
  Docs/source/install/cmake.rst
  Docs/source/install/hpc/lawrencium.rst
  Docs/source/install/hpc/lxplus.rst
  Docs/source/install/users.rst
  Tools/machines/adastra-cines/install_dependencies.sh
  Tools/machines/crusher-olcf/install_dependencies.sh
  Tools/machines/dane-llnl/install_dependencies.sh
  Tools/machines/frontier-olcf/install_dependencies.sh
  Tools/machines/greatlakes-umich/install_v100_dependencies.sh
  Tools/machines/hpc3-uci/install_gpu_dependencies.sh
  Tools/machines/lassen-llnl/install_v100_dependencies_toss3.sh
  Tools/machines/leonardo-cineca/install_gpu_dependencies.sh
  Tools/machines/lonestar6-tacc/install_a100_dependencies.sh
  Tools/machines/lumi-csc/install_dependencies.sh
  Tools/machines/perlmutter-nersc/Containerfile
  Tools/machines/perlmutter-nersc/install_cpu_dependencies.sh
  Tools/machines/perlmutter-nersc/install_gpu_dependencies.sh
  Tools/machines/pitzer-osc/install_cpu_dependencies.sh
  Tools/machines/pitzer-osc/install_v100_dependencies.sh
  Tools/machines/polaris-alcf/install_gpu_dependencies.sh
  Tools/machines/summit-olcf/install_gpu_dependencies.sh
  Tools/machines/tioga-llnl/install_mi300a_dependencies.sh
Labels: bug, install, bug: affects latest release, component: Python

#5684 WarpX class: move out PSATDCurrentCorrection and PSATDVayDeposition
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/WarpX.H
Labels: component: spectral, cleaning

#5734 Release 25.03
  .github/workflows/cuda.yml
  CMakeLists.txt
  Docs/source/conf.py
  Python/setup.py
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
  setup.py
Labels: component: documentation, install

#5672 WarpX class : move UpdateCurrentNodalToStag to anonymous namespace in WarpXComm.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/WarpX.H
Labels: cleaning

#5666 WarpX class: move AllocateCenteringCoefficients to anonymous namespace in WarpX.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#5740 Make labels with math text raw strings since they behave better
  Examples/Tests/ohm_solver_ion_beam_instability/analysis.py
Labels: cleaning

#5571 Remove temporary particle container
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformParticleFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/BackTransformParticleFunctor.cpp
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/ParticleBoundaryBuffer.cpp
  Source/Particles/PhotonParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/CopyParticleAttribs.H
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: cleaning

#5641 WarpX class : current_centering_* variables no longer static
  Source/Initialization/WarpXInitData.cpp
  Source/Parallelization/WarpXComm.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#5744 HybridPICModel : pass m_fields as an argument to InitData() to reduce reliance on WarpX::GetInstance()
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/Initialization/WarpXInitData.cpp
Labels: cleaning

#5745 WarpXInitData: eliminate WarpX::GetInstance from WarpX::ReadExternalFieldFromFile
  Source/Initialization/WarpXInitData.cpp
Labels: cleaning

#5746 AcceleratorLattice: avoid using WarpX::GetInstance()
  Source/AcceleratorLattice/AcceleratorLattice.H
  Source/AcceleratorLattice/AcceleratorLattice.cpp
  Source/AcceleratorLattice/LatticeElementFinder.H
  Source/AcceleratorLattice/LatticeElementFinder.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/Parallelization/WarpXRegrid.cpp
  Source/Particles/Gather/GetExternalFields.cpp
  Source/WarpX.cpp
Labels: cleaning, component: accelerator lattice

#5743 PML: pass m_fields as an argument to the constructor to rely less on WarpX::GetInstance()
  Source/BoundaryConditions/PML.H
  Source/BoundaryConditions/PML.cpp
  Source/Initialization/WarpXInitData.cpp
Labels: cleaning, component: boundary

#5679 WarpX and PML headers: remove unused fieldFactory() methods
  Source/BoundaryConditions/PML.H
  Source/WarpX.H
Labels: cleaning, component: boundary

#5756 [mini] Cleanup remaining mention of the tmp_particle_container
  Source/Diagnostics/BTDiagnostics.cpp
  Source/Diagnostics/ComputeDiagFunctors/BackTransformParticleFunctor.H
  Source/Particles/WarpXParticleContainer.H
Labels: cleaning

#5750 Check if implicit diagnostics file exist before writing the header
  Source/NonlinearSolvers/NewtonSolver.H
  Source/NonlinearSolvers/PicardSolver.H
Labels: bug, component: diagnostics, component: implicit solvers

#5718 WarpX class: sort_particles_for_deposition and sort_idx_type no longer static
  Source/Evolve/WarpXEvolve.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning

#5662 Interfacing 1D CurlCurl from AMReX
  Source/NonlinearSolvers/CurlCurlMLMGPC.H
Labels: enhancement, component: implicit solvers

#5748 added diagnostic_interval int for nonlinear solver diagnostic.
  Source/FieldSolver/ImplicitSolvers/ImplicitSolver.H
  Source/FieldSolver/ImplicitSolvers/SemiImplicitEM.H
  Source/FieldSolver/ImplicitSolvers/SemiImplicitEM.cpp
  Source/FieldSolver/ImplicitSolvers/StrangImplicitSpectralEM.H
  Source/FieldSolver/ImplicitSolvers/StrangImplicitSpectralEM.cpp
  Source/FieldSolver/ImplicitSolvers/ThetaImplicitEM.H
  Source/FieldSolver/ImplicitSolvers/ThetaImplicitEM.cpp
  Source/NonlinearSolvers/CurlCurlMLMGPC.H
  Source/NonlinearSolvers/NewtonSolver.H
  Source/NonlinearSolvers/NonlinearSolver.H
  Source/NonlinearSolvers/PicardSolver.H
Labels: component: diagnostics, component: implicit solvers

#5765 OpenPMDHelpFunction.H: remove superfluous #include
  Source/Diagnostics/OpenPMDHelpFunction.cpp
Labels: cleaning

#5716 Extending preconditioners to handle a diagonal operator for E-field
  Source/FieldSolver/ImplicitSolvers/ImplicitSolver.H
  Source/FieldSolver/ImplicitSolvers/ThetaImplicitEM.H
  Source/FieldSolver/ImplicitSolvers/ThetaImplicitEM.cpp
  Source/Fields.H
  Source/NonlinearSolvers/CurlCurlMLMGPC.H
  Source/NonlinearSolvers/JacobiPC.H
  Source/NonlinearSolvers/JacobianFunctionMF.H
  Source/NonlinearSolvers/Preconditioner.H
Labels: enhancement, component: implicit solvers

#5764 Doc: More Nsight Hints
  Docs/source/developers/how_to_profile.rst
Labels: backend: cuda, component: documentation, component: third party

#5759 Lassen: No MPI 4+ Support
  Docs/source/install/hpc/lassen.rst
  Tools/machines/lassen-llnl/install_v100_dependencies.sh
  Tools/machines/lassen-llnl/lassen_v100.bsub
  Tools/machines/lassen-llnl/lassen_v100_warpx.profile.example
Labels: bug, install, component: third party, bug: affects latest release, machine / system

#5758 For Python, wrap all input strings in double quotes.
  Python/pywarpx/Bucket.py
Labels: component: Python

#5769 Fix docstrings in WarpXEvolve and WarpXComm : /brief -> \brief
  Source/Evolve/WarpXEvolve.cpp
  Source/Parallelization/WarpXComm.cpp
Labels: bug, component: documentation, cleaning, bug: affects latest release

#5731 CI: Ubuntu 22.04/24.04 in GitHub Actions, CUDA 11.7+
  .github/workflows/clang_tidy.yml
  .github/workflows/cleanup-cache-postpr.yml
  .github/workflows/cleanup-cache.yml
  .github/workflows/codeql.yml
  .github/workflows/cuda.yml
  .github/workflows/dependencies/gcc12_blaspp_lapackpp.sh
  .github/workflows/dependencies/nvcc.sh
  .github/workflows/dependencies/nvcc11-3.sh
  .github/workflows/dependencies/nvcc11-8.sh
  .github/workflows/dependencies/nvhpc.sh
  .github/workflows/dependencies/pyfull.sh
  .github/workflows/insitu.yml
  .github/workflows/intel.yml
  .github/workflows/source.yml
  .github/workflows/ubuntu.yml
  .readthedocs.yml
Labels: backend: cuda, component: documentation, component: tests, install

#5753 Fix a runtime parameter issue in time-averaged diagnostics
  Source/Diagnostics/FullDiagnostics.cpp
Labels: bug, bug: affects latest release, component: diagnostics

#5766 Add more profiling instrumentation in the collision kernel
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
Labels: component: collisions

#5780 Fix FieldPoyntingFlux diagnostic for GPU
  Source/Diagnostics/ReducedDiags/FieldPoyntingFlux.cpp
Labels: bug: affects latest release, component: diagnostics

#5763 Calculate global debye length for Coulomb collisions
  Docs/source/usage/parameters.rst
  Examples/Tests/collision/CMakeLists.txt
  Examples/Tests/collision/inputs_test_2d_collision_xz_global_debye
  Regression/Checksum/benchmarks_json/test_2d_collision_xz_global_debye.json
  Source/Diagnostics/ComputeDiagFunctors/TemperatureFunctor.cpp
  Source/Fields.H
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
  Source/Particles/Collision/BinaryCollision/Coulomb/ElasticCollisionPerez.H
  Source/Particles/Collision/BinaryCollision/Coulomb/PairWiseCoulombCollisionFunc.H
  Source/Particles/Collision/BinaryCollision/DSMC/DSMCFunc.H
  Source/Particles/Collision/BinaryCollision/NuclearFusion/NuclearFusionFunc.H
  Source/Particles/Collision/CollisionBase.H
  Source/Particles/Collision/CollisionHandler.H
  Source/Particles/Collision/CollisionHandler.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: component: collisions

#5789 HankelTransform : remove unnecessary #include "WarpX.H"
  Source/FieldSolver/SpectralSolver/SpectralHankelTransform/HankelTransform.cpp
Labels: component: spectral, cleaning

#5791 change sign for imaginary part of xy in implicit gathers.
  Source/Particles/Gather/FieldGather.H
Labels: bug, bug: affects latest release, component: implicit solvers

#5781 WarpX class: move PSATDSubtractCurrentPartialSumsAvg to anonymous namespace in WarpXPushFieldEM.cpp
  Source/FieldSolver/WarpXPushFieldsEM.cpp
  Source/WarpX.H
Labels: cleaning

#5702 Add `WarpX_UNITY_BUILD`
  CMakeLists.txt
  Docs/source/install/cmake.rst
  Source/BoundaryConditions/PML_RZ.cpp
  Source/Diagnostics/FlushFormats/FlushFormatCheckpoint.cpp
  Source/Diagnostics/FlushFormats/FlushFormatPlotfile.cpp
  Source/Diagnostics/ReducedDiags/DifferentialLuminosity.cpp
  Source/Diagnostics/ReducedDiags/DifferentialLuminosity2D.cpp
  Source/Diagnostics/WarpXOpenPMD.cpp
  Source/EmbeddedBoundary/WarpXFaceExtensions.cpp
  cmake/WarpXFunctions.cmake
Labels: install

#5761 Add automated test for ion impact ionization
  Examples/Physics_applications/capacitive_discharge/analysis_dsmc.py
  Examples/Tests/ionization_dsmc/CMakeLists.txt
  Examples/Tests/ionization_dsmc/analysis_ionization_dsmc_3d.py
  Examples/Tests/ionization_dsmc/inputs_base_3d
  Examples/Tests/ionization_dsmc/inputs_test_3d_ionization_electron_dsmc
  Examples/Tests/ionization_dsmc/inputs_test_3d_ionization_ion_dsmc
  Regression/Checksum/benchmarks_json/test_1d_dsmc_picmi.json
  Regression/Checksum/benchmarks_json/test_3d_ionization_dsmc.json
  Regression/Checksum/benchmarks_json/test_3d_ionization_electron_dsmc.json
  Regression/Checksum/benchmarks_json/test_3d_ionization_ion_dsmc.json
  Source/Particles/Collision/BinaryCollision/DSMC/SplitAndScatterFunc.H
Labels: bug, component: collisions

#5786 Use KineticEnergy instead of getEnergy
  Source/Particles/Algorithms/KineticEnergy.H
  Source/Particles/Collision/BackgroundMCC/BackgroundMCCCollision.cpp
  Source/Particles/Collision/BackgroundMCC/ImpactIonization.H
  Source/Utils/ParticleUtils.H
Labels: cleaning, component: collisions

#5771 ParticleUtils.H: pass geometry as a parameter to findParticlesInEachCell instead on relying on WarpX::GetInstance()
  Source/Diagnostics/ReducedDiags/DifferentialLuminosity.cpp
  Source/Diagnostics/ReducedDiags/DifferentialLuminosity2D.cpp
  Source/Evolve/WarpXEvolve.cpp
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Resampling/LevelingThinning.H
  Source/Particles/Resampling/LevelingThinning.cpp
  Source/Particles/Resampling/Resampling.H
  Source/Particles/Resampling/Resampling.cpp
  Source/Particles/Resampling/VelocityCoincidenceThinning.H
  Source/Particles/Resampling/VelocityCoincidenceThinning.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Utils/ParticleUtils.H
  Source/Utils/ParticleUtils.cpp
Labels: cleaning

#5794 NuclearFusionFunc.H: remove superfluous include of the WarpX header
  Source/Particles/Collision/BinaryCollision/NuclearFusion/NuclearFusionFunc.H
Labels: cleaning

#5795 ElectrostaticSolver.H: remove superfluous include of the WarpX header
  Source/FieldSolver/ElectrostaticSolvers/ElectrostaticSolver.H
Labels: cleaning

#5796 WarpX.cpp: remove some superfluous preprocessor directives
  Source/WarpX.cpp
Labels: cleaning

#5776 direct gather routine for single vector field
  Source/Particles/Gather/FieldGather.H
Labels: cleaning, component: core, component: implicit solvers

#5799 ParticlesBoundaries.cpp: remove unnecessary #include "WarpX.H"
  Source/Particles/ParticleBoundaries.cpp
Labels: cleaning

#5663 Docs: add hint in how-to guide for checksum tool
  Docs/source/developers/how_to_test.rst
Labels: component: documentation

#5696 CI: Add Workflow to Run Jupyter Notebooks
  .github/workflows/jupyter.yml
  .gitignore
  Tools/Algorithms/psatd.ipynb
  Tools/Algorithms/psatd_pml.ipynb
Labels: component: tests

#5788 PartitionParticlesInBuffers : pass parameters as function arguments instead of using WarpX static variables
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Sorting/Partition.cpp
Labels: cleaning

#5801 Add Tyushev (2025) to highlights
  Docs/source/highlights.rst
Labels: component: documentation
