Repository BLAST-WarpX/warpx, pull requests merged in 2025-08, with the labels that each got.

#6047 Updating initialization of external vector potential based fields to …
  Regression/Checksum/benchmarks_json/test_3d_ohm_solver_cylinder_compression_picmi.json
  Regression/Checksum/benchmarks_json/test_rz_ohm_solver_cylinder_compression_picmi.json
  Source/FieldSolver/WarpXPushFieldsHybridPIC.cpp
Labels: bug, bug: affects latest release, component: initialization

#6059 AMReX/pyAMReX/PICSAR: Weekly Update
  Regression/Checksum/benchmarks_json/test_3d_eb_picmi.json
  Regression/Checksum/benchmarks_json/test_3d_particle_absorption.json
  Regression/Checksum/benchmarks_json/test_3d_particle_scrape.json
  Regression/Checksum/benchmarks_json/test_3d_particle_scrape_picmi.json
  dependencies.json
Labels: component: documentation, component: third party, component: boundary

#6065 Add tutorials section in documentation
  Docs/source/index.rst
  Docs/source/tutorials.rst
Labels: component: documentation

#5767 Refactor ReadBCParams
  Source/BoundaryConditions/CMakeLists.txt
  Source/BoundaryConditions/FieldBoundaries.H
  Source/BoundaryConditions/FieldBoundaries.cpp
  Source/BoundaryConditions/Make.package
  Source/Initialization/WarpXAMReXInit.cpp
  Source/Particles/ParticleBoundaries.H
  Source/Particles/ParticleBoundaries.cpp
  Source/Utils/WarpXUtil.H
  Source/Utils/WarpXUtil.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: cleaning, component: boundary

#6060 Update to use the correct stencils in FieldPoyntingFlux
  Source/Diagnostics/ReducedDiags/FieldPoyntingFlux.H
  Source/Diagnostics/ReducedDiags/FieldPoyntingFlux.cpp
Labels: component: diagnostics

#5888 CI: Remove Hard-Coded Path to Checksum Files
  Examples/Tests/laser_injection_from_file/inputs_test_2d_laser_injection_from_binary_file_prepare.py
  Examples/analysis_default_regression.py
Labels: bug, component: tests, bug: affects latest release

#6074 Dependencies: weekly update
  dependencies.json
Labels: component: third party

#6070 Docs: Hide tutorial chapter title from front page
  Docs/source/index.rst
Labels: component: documentation

#6093 Updated output for quadratic rho and J time dependencies
  Source/Initialization/WarpXInitData.cpp
Labels: component: spectral

#6100 Doc Tuo (LLNL): Small Typos
  Docs/source/install/hpc/tuolumne.rst
Labels: bug, component: documentation, bug: affects latest release, machine / system

#6079 Doxygen: remove obsolete macros from Doxyfile
  Docs/Doxyfile
Labels: component: documentation, cleaning

#6095 Refactor Implicit parameters in readthedocs
  Docs/source/usage/parameters.rst
  Source/FieldSolver/ImplicitSolvers/ImplicitSolver.cpp
Labels: component: documentation, component: implicit solvers

#5878 Add linear Compton scattering
  Docs/source/refs.bib
  Docs/source/usage/parameters.rst
  Examples/Tests/CMakeLists.txt
  Examples/Tests/linear_compton/CMakeLists.txt
  Examples/Tests/linear_compton/analysis_base.py
  Examples/Tests/linear_compton/analysis_bunch_laser.py
  Examples/Tests/linear_compton/analysis_default_regression.py
  Examples/Tests/linear_compton/analysis_two_particles.py
  Examples/Tests/linear_compton/inputs_test_3d_linear_compton_bunch_laser
  Examples/Tests/linear_compton/inputs_test_3d_linear_compton_two_particles
  Regression/Checksum/benchmarks_json/test_3d_linear_compton_bunch_laser.json
  Regression/Checksum/benchmarks_json/test_3d_linear_compton_two_particles.json
  Source/Particles/Collision/BinaryCollision/BinaryCollision.H
  Source/Particles/Collision/BinaryCollision/BinaryCollisionUtils.H
  Source/Particles/Collision/BinaryCollision/BinaryCollisionUtils.cpp
  Source/Particles/Collision/BinaryCollision/LinearCompton/LinearComptonCollisionFunc.H
  Source/Particles/Collision/BinaryCollision/LinearCompton/LinearComptonInitializeMomentum.H
  Source/Particles/Collision/BinaryCollision/LinearCompton/SingleLinearComptonCollisionEvent.H
  Source/Particles/Collision/BinaryCollision/ParticleCreationFunc.H
  Source/Particles/Collision/BinaryCollision/ParticleCreationFunc.cpp
  Source/Particles/Collision/CollisionHandler.cpp
Labels: enhancement, component: collisions

#6106 Added 1D & 2D CI test with loading density from .h5 file
  Examples/Tests/load_density/CMakeLists.txt
  Examples/Tests/load_density/analysis_1d.py
  Examples/Tests/load_density/analysis_2d.py
  Examples/Tests/load_density/inputs_test_1d_load_density
  Examples/Tests/load_density/inputs_test_1d_load_density_prepare.py
  Examples/Tests/load_density/inputs_test_2d_load_density
  Examples/Tests/load_density/inputs_test_2d_load_density_prepare.py
  Regression/Checksum/benchmarks_json/test_1d_load_density.json
  Regression/Checksum/benchmarks_json/test_2d_load_density.json
  Source/Initialization/InjectorDensity.H
Labels: bug, component: initialization

#6111 Add recent papers citing/using WarpX
  Docs/source/acknowledge_us.rst
  Docs/source/highlights.rst
Labels: component: documentation

#6103 Update WarpX's high-level description
  Docs/source/index.rst
Labels: component: documentation

#6112 CI: edit permissions for autoupdate workflows
  .github/workflows/monthly_release.yml
  .github/workflows/weekly_update.yml
Labels: bug, automation

#6108 Update the embedded documentation hyperlink for parallelization info to a working URL
  Source/Initialization/WarpXInitData.cpp
Labels: bug, component: documentation

#6110 Fix openPMD output of "eb_covered" in RZ geometry
  Regression/Checksum/benchmarks_json/test_rz_electrostatic_sphere_eb_mr.json
  Source/Diagnostics/FullDiagnostics.cpp
Labels: bug, component: openPMD, bug: affects latest release, component: diagnostics, geometry: RZ, component: boundary

#6092 Add verbosity flag for diagnostics
  Examples/Tests/ohm_solver_em_modes/inputs_test_1d_ohm_solver_em_modes_picmi.py
  Python/pywarpx/picmi.py
  Source/Diagnostics/Diagnostics.cpp
Labels: component: diagnostics

#6119 Linear Compton follow-up 1
  Regression/Checksum/benchmarks_json/test_3d_linear_compton_bunch_laser.json
  Regression/Checksum/benchmarks_json/test_3d_linear_compton_two_particles.json
  Source/Particles/Collision/BinaryCollision/LinearCompton/LinearComptonInitializeMomentum.H
Labels: bug, component: QED, component: collisions

#6104 Update acknowledgment slide
  Docs/source/acknowledge_us.rst
Labels: component: documentation
