Repository BLAST-WarpX/warpx, pull requests merged in 2025-10, with the labels that each got.

#6202 Implicit particle suborbits refactor.
  Source/FieldSolver/ImplicitSolvers/ImplicitOptions.H
  Source/FieldSolver/ImplicitSolvers/ImplicitSolver.H
  Source/FieldSolver/ImplicitSolvers/ImplicitSolver.cpp
  Source/Fields.H
  Source/Particles/Deposition/MassMatricesDeposition.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/Pusher/ImplicitPushPX.cpp
Labels: component: implicit solvers

#6235 Fix input file of photon pusher test
  Examples/Tests/photon_pusher/inputs_test_3d_photon_pusher
Labels: cleaning

#6238 WarpX class: move UpdateInjectionPosition method to anonymous namespace in WarpXMovingWindow.cpp
  Source/Utils/WarpXMovingWindow.cpp
  Source/WarpX.H
Labels: cleaning

#6246 Docs: fix two broken links
  Docs/source/usage/parameters.rst
Labels: component: documentation, cleaning

#6223 Fix potential recursive calls of WarpX constructor.
  Source/WarpX.cpp
Labels: bug
