Repository BLAST-WarpX/warpx, pull requests merged in 2025-06, with the labels that each got.

#5905 remove erroneous use of is_tangent_to_bndy in SetRhoOrJfieldFromPEC()
  Regression/Checksum/benchmarks_json/test_2d_particle_thermal_boundary.json
  Regression/Checksum/benchmarks_json/test_3d_magnetostatic_eb.json
  Source/BoundaryConditions/WarpX_PEC.cpp
Labels: bug: affects latest release, component: boundary

#5925 Add new field diagnostic that indicates whether a given cell is covered by the EB or not
  Docs/source/usage/parameters.rst
  Examples/Tests/electrostatic_sphere_eb/CMakeLists.txt
  Examples/Tests/electrostatic_sphere_eb/analysis.py
  Examples/Tests/electrostatic_sphere_eb/inputs_test_3d_electrostatic_sphere_eb
  Examples/Tests/electrostatic_sphere_eb/inputs_test_3d_electrostatic_sphere_eb_picmi.py
  Examples/Tests/electrostatic_sphere_eb/inputs_test_rz_electrostatic_sphere_eb
  Examples/Tests/electrostatic_sphere_eb/inputs_test_rz_electrostatic_sphere_eb_mr
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/test_3d_electrostatic_sphere_eb.json
  Regression/Checksum/benchmarks_json/test_3d_electrostatic_sphere_eb_picmi.json
  Regression/Checksum/benchmarks_json/test_rz_electrostatic_sphere_eb.json
  Regression/Checksum/benchmarks_json/test_rz_electrostatic_sphere_eb_mr.json
  Source/Diagnostics/ComputeDiagFunctors/CMakeLists.txt
  Source/Diagnostics/ComputeDiagFunctors/EBCoveredFunctor.H
  Source/Diagnostics/ComputeDiagFunctors/EBCoveredFunctor.cpp
  Source/Diagnostics/ComputeDiagFunctors/Make.package
  Source/Diagnostics/FullDiagnostics.cpp
Labels: component: boundary

#5934 Deactivate failing Windows CI workflow
  .github/workflows/windows.yml
Labels: component: tests

#5866 Implement particle_max_grid_crossings
  Docs/source/usage/parameters.rst
  Source/Evolve/WarpXEvolve.cpp
  Source/Parallelization/GuardCellManager.H
  Source/Parallelization/GuardCellManager.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: component: implicit solvers

#5939 Dependencies: Weekly Update
  .github/workflows/cuda.yml
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pyAMReX.cmake
Labels: component: third party

#5936 Run sanitizer test in double precision
  .github/workflows/clang_sanitizers.yml
Labels: component: tests

#5838 Enable Collocated grid Solve for Ohm's Law Hybrid solver
  Examples/Tests/load_external_field/inputs_test_3d_load_external_field_grid_picmi.py
  Examples/Tests/ohm_solver_cylinder_compression/CMakeLists.txt
  Examples/Tests/ohm_solver_cylinder_compression/inputs_test_3d_ohm_solver_cylinder_compression_picmi.py
  Examples/Tests/projection_divb_cleaner/inputs_test_3d_projection_divb_cleaner_callback_picmi.py
  Regression/Checksum/benchmarks_json/test_3d_ohm_solver_cylinder_compression_picmi.json
  Regression/Checksum/benchmarks_json/test_3d_projection_divb_cleaner_callback_picmi.json
  Source/FieldSolver/FiniteDifferenceSolver/ComputeCurlA.cpp
  Source/FieldSolver/FiniteDifferenceSolver/FiniteDifferenceAlgorithms/CartesianNodalAlgorithm.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/ExternalVectorPotential.H
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/ExternalVectorPotential.cpp
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICModel/HybridPICModel.cpp
  Source/FieldSolver/FiniteDifferenceSolver/HybridPICSolveE.cpp
  Source/FieldSolver/WarpX_FDTD.H
  Source/Initialization/DivCleaner/ProjectionDivCleaner.H
  Source/Initialization/DivCleaner/ProjectionDivCleaner.cpp
  Source/WarpX.cpp
Labels: enhancement, component: fluid-ohm

#5954 Updating documentation to clarify that certain callbacks are not exec…
  Python/pywarpx/callbacks.py
Labels: component: documentation

#5951 Mini-PR: Fix outdated line in documentation
  Docs/source/usage/parameters.rst
Labels: component: documentation

#5956 Adding flags to field initializer objects in PICMI to control project…
  Docs/source/usage/parameters.rst
  Examples/Tests/CMakeLists.txt
  Examples/Tests/load_external_field/inputs_test_3d_load_external_field_grid_picmi.py
  Examples/Tests/projection_div_cleaner/CMakeLists.txt
  Examples/Tests/projection_div_cleaner/analysis.py
  Examples/Tests/projection_div_cleaner/analysis_default_regression.py
  Examples/Tests/projection_div_cleaner/inputs_test_2d_projection_div_cleaner_initial_analytical_field_picmi.py
  Examples/Tests/projection_div_cleaner/inputs_test_3d_projection_div_cleaner_callback_picmi.py
  Examples/Tests/projection_div_cleaner/inputs_test_3d_projection_div_cleaner_picmi.py
  Examples/Tests/projection_div_cleaner/inputs_test_rz_projection_div_cleaner
  Examples/Tests/projection_divb_cleaner/CMakeLists.txt
  Python/pywarpx/ProjectionDivBCleaner.py
  Python/pywarpx/WarpX.py
  Python/pywarpx/__init__.py
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/test_2d_projection_div_cleaner_initial_analytical_field_picmi.json
  Regression/Checksum/benchmarks_json/test_3d_projection_div_cleaner_callback_picmi.json
  Regression/Checksum/benchmarks_json/test_3d_projection_div_cleaner_picmi.json
  Regression/Checksum/benchmarks_json/test_rz_projection_div_cleaner.json
  Source/Initialization/DivCleaner/ProjectionDivCleaner.cpp
  Source/Initialization/WarpXInitData.cpp
  Source/WarpX.H
  Source/WarpX.cpp
Labels: bug, changes input scripts / defaults, bug: affects latest release, component: Python, component: initialization

#5907 CI: Fix Skipped Required Workflows (again)
  .github/workflows/clang_tidy.yml
  .github/workflows/codeql.yml
Labels: component: tests

#5883 Update reference to new paper
  Docs/source/highlights.rst
Labels: component: documentation

#5897 Move WarpX::ErrorEst from Utils/WarpXTagging.cpp to WarpX.cpp
  Source/Utils/CMakeLists.txt
  Source/Utils/Make.package
  Source/Utils/WarpXTagging.cpp
  Source/WarpX.cpp
Labels: cleaning

#5972 CI: improve paths exclusion filters
  .azure-pipelines.yml
  .github/workflows/check_changes.yml
Labels: component: tests

#5971 Doc LLNL (LC) Tuolumne
  Docs/source/install/hpc.rst
  Docs/source/install/hpc/tioga.rst
  Docs/source/install/hpc/tuolumne.rst
  Tools/machines/tuolumne-llnl/install_mi300a_dependencies.sh
  Tools/machines/tuolumne-llnl/install_mi300a_ml.sh
  Tools/machines/tuolumne-llnl/tuolumne_mi300a.sbatch
  Tools/machines/tuolumne-llnl/tuolumne_mi300a_warpx.profile.example
Labels: component: documentation, machine / system

#5948 AMReX/pyAMReX/PICSAR: Weekly Update
  .github/workflows/cuda.yml
  Source/Initialization/DivCleaner/ProjectionDivCleaner.H
  Source/ablastr/fields/EffectivePotentialPoissonSolver.H
  Source/ablastr/fields/PoissonSolver.H
  Source/ablastr/fields/VectorPoissonSolver.H
  Tools/Release/releasePR.py
  Tools/Release/weeklyUpdate.py
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/PICSAR.cmake
  cmake/dependencies/pyAMReX.cmake
Labels: component: documentation, component: third party

#5974 RZ: GPU-Side Abort in FDTD
  Source/FieldSolver/WarpX_FDTD.H
Labels: bug, backend: cuda, bug: affects latest release, backend: hip, backend: sycl, geometry: RZ, geometry: cylinder/sphere

#5979 Aurora setup
  Docs/source/install/hpc.rst
  Docs/source/install/hpc/aurora.rst
  Tools/machines/aurora-alcf/aurora.pbs
  Tools/machines/aurora-alcf/aurora_warpx.profile.example
  Tools/machines/aurora-alcf/install_dependencies.sh
Labels: component: documentation, machine / system

#5811 Add feature running variance deposition
  Docs/source/usage/parameters.rst
  Examples/Tests/ohm_solver_cylinder_compression/CMakeLists.txt
  Examples/Tests/ohm_solver_cylinder_compression/inputs_test_3d_ohm_solver_cylinder_compression_picmi.py
  Examples/Tests/ohm_solver_cylinder_compression/inputs_test_rz_ohm_solver_cylinder_compression_picmi.py
  Python/pywarpx/picmi.py
  Regression/Checksum/benchmarks_json/test_3d_ohm_solver_cylinder_compression_picmi.json
  Regression/Checksum/benchmarks_json/test_rz_ohm_solver_cylinder_compression_picmi.json
  Source/Diagnostics/ComputeDiagFunctors/TemperatureFunctor.cpp
  Source/Diagnostics/Diagnostics.cpp
  Source/Diagnostics/FullDiagnostics.cpp
  Source/FieldSolver/WarpXPushFieldsHybridPIC.cpp
  Source/Particles/CMakeLists.txt
  Source/Particles/Deposition/CMakeLists.txt
  Source/Particles/Deposition/CurrentDeposition.H
  Source/Particles/Deposition/Make.package
  Source/Particles/Deposition/TemperatureDeposition.H
  Source/Particles/Deposition/VarianceAccumulationBuffer.H
  Source/Particles/Deposition/VarianceAccumulationBuffer.cpp
  Source/Particles/MultiParticleContainer.H
  Source/Particles/MultiParticleContainer.cpp
  Source/Particles/PhysicalParticleContainer.H
  Source/Particles/PhysicalParticleContainer.cpp
  Source/Particles/WarpXParticleContainer.H
  Source/Particles/WarpXParticleContainer.cpp
Labels: enhancement

#5597 Clang UB sanitizer CI test: increase coverage
  .github/workflows/clang_sanitizers.yml
  Source/Diagnostics/ReducedDiags/ParticleHistogram2D.H
  Source/Diagnostics/ReducedDiags/ParticleHistogram2D.cpp
  Source/Utils/Parser/IntervalsParser.cpp
  Source/ablastr/fields/PoissonSolver.H
Labels: component: tests

#5964 Adds emojis to issues template names
  .github/ISSUE_TEMPLATE/blank_issue.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/installation-issue.md
Labels: enhancement, cleaning
